### ISSUE TITLE
Team cannot be changed in the left sidebar

### ISSUE THREAD

**Issue by useitfortest** [mattermost/mattermost-server#8050] opened 2018-01-06 10:36 UTC
#### Summary
The user cannot change available teams

#### Steps to reproduce
1. Login to https://oss.mattermost.com/ (the user has some available teams)
2. Try to change active team in the left sidebar

#### Expected behavior
Team cannot be change

#### Observed behavior (that appears unintentional) 
After clicking another team icon nothing happens
![2018-01-06 13 29 42](https://user-images.githubusercontent.com/35164265/34638909-8276a4a4-f2e6-11e7-8010-c3340b0a3ee9.png)

#### Possible fixes
The following error occurs in the browser console (the issue cannot be fixed in accordance with error stack)
![2018-01-06 13 29 53](https://user-images.githubusercontent.com/35164265/34638906-7a4073aa-f2e6-11e7-97ec-cae1a6ff0796.png)

#### Environment
OS: Intel Mac OS X 10_11_5
Browser: Safari/9.1.1

**Comment by lindy65** [comment] 2018-01-08 10:43
Hi @useitfortest,

I'm not able to reproduce this on Windows so have asked for someone on the team to test on Mac.

**Comment by lfbrock** [comment] 2018-01-08 17:29
Hi @useitfortest - thanks for the report, we reproduced and filed a ticket here to fix the issue: https://mattermost.atlassian.net/browse/PLT-8510

**Comment by lindy65** [comment] 2018-01-09 19:50
I'll close this issue off for now and we can track via the ticket linked above.

**Closed by lindy65** 2018-01-09 19:50 UTC
