### ISSUE TITLE
Clicking on own username, an undefined chat window is opened.

### ISSUE THREAD

**Issue by kouratoras** [mattermost/mattermost-server#8003] opened 2017-12-23 20:55 UTC
#### Summary
Clicking on your own username in the members list, a chat window is opened with `undefined` title.

#### Steps to reproduce
1. Visit [Mattermost demo page](http://demo.mattermost.com/)
2. Go to a channel (i.e. `town-square`)
3. Click on the members icon to open the members list
4. Find your own username
5. Click on it

#### Expected behavior
Given that there is no chat icon next to your own username:
![Own username](https://s9.postimg.org/gpthl15gf/my-username.png)

as happening with all other usernames:
![Other username](https://s9.postimg.org/6fr2lsv0f/other-username.png)

it should not open the chat window with yourself.

#### Observed behavior (that appears unintentional) 
A chat with yourself is opened, displaying an `undefined` title in the browser tab:
![Tab title](https://s9.postimg.org/4ny3r0e9b/tab.png)

**Comment by lindy65** [comment] 2017-12-28 08:55
Hi @kouratoras,

Thanks for your feedback,

I am not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master.  oss.mattermost.com is on v4.4 but will be updated soon.

We recently included a feature where you are able to message yourself by clicking on your own username and this opens a direct message to yourself.

**Comment by lindy65** [comment] 2018-01-10 09:18
I'll close this issue off for now

**Closed by lindy65** 2018-01-10 09:18 UTC
