### ISSUE TITLE
Windows are not movable

### ISSUE THREAD

**Issue by egoldobin** [mattermost/mattermost-server#14168] opened 2020-03-26 20:30 UTC
#### Summary
Windows (message editing, Account settings) do not move by dragging the title bar with the mouse.

#### Steps to reproduce
Sandwich button|Account settings. Window "Account settings" opens. Try to click on the title bar and drag. 

#### Expected behavior
Window should move (follow the mouse)

#### Observed behavior (that appears unintentional) 
Window does not move.

#### Possible fixes
Use standard controls/windows etc. Do not invent a wheel. If you invent a wheel, make it BETTER than the standard wheel. Standard behavior was working for 20+ years in ALL applications. In Mttermost it doesnt :-((((

**Comment by amyblais** [comment] 2020-03-26 20:56
@egoldobin What Mattermost server version are you on?
Can you help elaborate on what windows are not moving and why you would like to see this change?

**Comment by egoldobin** [comment] 2020-03-27 19:27
> @egoldobin What Mattermost server version are you on?
> Can you help elaborate on what windows are not moving and why you would like to see this change?

Mattermost Version: 5.20.0
I guess NONE of the windows are moving. In addition to the two mentioned above, this is e.g. SandwitchButton|About Mattermost . 
Why? Because this is standard behavior of any window. The concept of a window includes a possibility to move it away at the position more convenient for me and see what is underneath. This works so since the times of Windows 3.1 in 1990s, but in Mattermost in 2020 it doesn't. Great regress back to 1980s!

**Comment by amyblais** [comment] 2020-03-27 19:32
@egoldobin Thank you for your feedback, would you be open to sharing this improvement idea on our feature proposals forum here: http://www.mattermost.org/feature-requests/?

**Comment by egoldobin** [comment] 2020-04-02 09:46
Amy, with all respect, but you are compelling me to spend too much time 
on this trivial issue. Windows should be movable even without saying 
anything. Instead I spend already 15min of my valuable time on this 
issue and do not want to spend any more (unless you pay 0.35EUR/minute) 
It takes probably much less time to fix the issue than you are going to 
spend for discussions.

Best Regards,
Edward -- disapponted user of mattermost

**Comment by amyblais** [comment] 2020-04-02 18:06
The Jira ticket was discussed and closed as this feature is a lot of work and should go through the feature request process.

Please help open a feature request issue for this and also let us know the use case for why you are looking for this feature.

**Comment by egoldobin** [comment] 2020-04-03 11:06
Amy, the answer is obvious: because I wanna see the content UNDER this 
window when I am editing the reply.

**Comment by amyblais** [comment] 2020-04-15 13:16
Closing as there hasn't been feedback on this for a while. I hope you will open a feature request for this,

**Closed by amyblais** 2020-04-15 13:16 UTC

**Comment by egoldobin** [comment] 2020-04-15 13:45
I am totally unsatisfied how you handle this trivial request -- just 
lost time without any result. Very inefficient.
Therefore, we decided that mattemost (as a product and as a company with 
all these extreme time consumption for trivial changes) is not suitable 
for our dynamic team. We will use another system for communication. Have 
a good time.
Edward

**Comment by JanHauerslev** [comment] 2025-06-18 07:02
I have had this exect issue before. Then it got fixed but as I got version 5.12.1 the issue is appearing again.
