### ISSUE TITLE
4.2.0 RC 1 completely breaks my mattermost

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-server#7395] opened 2017-09-07 07:46 UTC
After upgrading I see the login screen. When I enter credentials it goes to "logging in" and after that nothing. There are no errors in the log except for a succesful start of mattermost. I will try to revert to a backup now.

**Comment by Twilek-de** [comment] 2017-09-07 07:47
After some time the logs show "http2: server: error reading preface from client 176.199.x.x:60744: timeout waiting for client preface

**Comment by lindy65** [comment] 2017-09-07 08:36
Hi @Twilek-de 

Thanks for your feedback,

Could you tell me whether you're using the desktop app or browser?  If browser, which one?

I'll ask the devs for some troubleshooting help and get back to you...

**Comment by Twilek-de** [comment] 2017-09-07 09:44
I tried the latest Windows Desktop App, latest Chrome, latest Firefox and Edge. They all hung on the login screen. After going back to 4.1.0 things work again.

**Comment by lindy65** [comment] 2017-09-07 10:06
Hmmm... that's weird.  I'm currently testing 4.2 RC1 in the desktop app, Chrome as well as in browser, Win 7 Chrome and both are working fine for me.  It might have something to do with your set-up so perhaps one of the devs can help...  I'll post their feedback.

**Comment by maruTA-bis5** [comment] 2017-09-07 11:38
pre-release.mattermost.com seems to be broken as well.

I'm using latest Chrome and Desktop app(v3.7.0) on Windows 10.
Attach the Chrome console log. Many JavaScript errors occurred.
[pre-release.mattermost.com-1504783185671.txt](https://github.com/mattermost/mattermost-server/files/1284502/pre-release.mattermost.com-1504783185671.txt)

**Comment by lindy65** [comment] 2017-09-07 13:08
@maruTA-bis5 

Pre-release is fine for me using Desktop App (v3.7.1) on Win 7.  Could you try downloading the [latest version](https://about.mattermost.com/download/) of the Desktop to see if your issue still exists?

**Comment by hmhealey** [comment] 2017-09-07 13:20
What language are you both using Mattermost in? The issue appears to be a translated string not matching what's expected by the code

**Comment by hmhealey** [comment] 2017-09-07 13:39
Thanks for the stack trace @maruTA-bis5. We had some other users report it happening in French, so we tracked down the issue

**Comment by Twilek-de** [comment] 2017-09-07 14:04
I´m using the german translation.

**Comment by maruTA-bis5** [comment] 2017-09-07 14:15
You're welcome, @hmhealey. I'm using in Japanese.

**Comment by jasonblais** [comment] 2017-09-07 22:09
@Twilek-de @maruTA-bis5 RC2 is cut, can you see if the issue is fixed for you?

https://releases.mattermost.com/4.2.0-rc2/mattermost-4.2.0-rc2-linux-amd64.tar.gz

**Comment by maruTA-bis5** [comment] 2017-09-08 00:35
@jasonblais It works fine for me 👍

**Comment by Twilek-de** [comment] 2017-09-08 06:28
@jasonblais Just updated, seems to work. Thanks

**Comment by lindy65** [comment] 2017-09-08 06:46
Fantastic @Twilek-de and @maruTA-bis5 

Pleased the issue is resolved :)

Thanks to @hmhealey and @jasonblais for looking in to this so quickly!

I'll close this issue off for now then...

**Closed by lindy65** 2017-09-08 06:46 UTC
