### ISSUE TITLE
"Edited" indicator icon overlaps text on certain browsers

### ISSUE THREAD

**Issue by akhmerov** [mattermost/mattermost-server#19252] opened 2021-12-26 01:17 UTC
#### Summary
The unicode right-to-left character moves the sign of string being edited to the beginning of the line and breaks its formatting.

#### Steps to reproduce
- type "abc" in a new message
- Edit this message and insert a unicode character U+200F (right-to-left text) in the beginning of the line

#### Expected behavior
- The string renders as "abc"
- The "edited" sign appears on the right of the message

#### Observed behavior (that appears unintentional)
The "edited" sign moves to the beginning of the line.

![image](https://user-images.githubusercontent.com/2069677/147396450-008c190e-f392-4839-bbdb-dc7791414b5f.png)

**Comment by isacikgoz** [comment] 2021-12-27 13:37
Thanks for the feedback @akhmerov I could reproduce this as well. Created the ticket here: https://mattermost.atlassian.net/browse/MM-40770

**Comment by sinansonmez** [comment] 2022-02-03 08:24
Happy to work on that. Can you assign it to me?

**Comment by sinansonmez** [comment] 2022-02-05 00:42
While I was working on this, i realized that maybe current behaviour reported as issue is the  expected behavior. Why? 
- For ltr user, edited span is placed on the right side of the message (i.e. at the end of message)
- For rtl user, edited span is placed on the left side of the message which is the end of message for this use

To be consistent from this perspective maybe we would like to keep current behavior. Is there anyone to comment / decide on this? @amyblais

**Comment by amyblais** [comment] 2022-02-05 00:53
> While I was working on this, i realized that maybe current behaviour reported as issue is the expected behavior. Why?
> 
> * For ltr user, edited span is placed on the right side of the message (i.e. at the end of message)
> * For rtl user, edited span is placed on the left side of the message which is the end of message for this use
> 
> To be consistent from this perspective maybe we would like to keep current behavior. Is there anyone to comment / decide on this?

cc @hmhealey ^

**Comment by hmhealey** [comment] 2022-02-07 21:38
Now that you mention it, that does sound right to me. There's a weird overlap of the pencil icon with "Edited", but I think that's a Firefox bug since it happens for me regularly.

I'll check to see if any of our translators have any thoughts on that since I know we've had people with differing opinions in the past on how RTL support in Mattermost should work

**Comment by sinansonmez** [comment] 2022-02-07 21:41
Thanks. I will wait for your check to work on this. 

Related to pencil icon, you are right, it is a Firefox bug (I don't see it on Safari)

**Comment by akhmerov** [comment] 2022-02-07 21:42
> Related to pencil icon, you are right, it is a Firefox bug (I don't see it on Safari)

Also appears on chrome.

I agree that the pencil icon is likely the only problem.

**Comment by hmhealey** [comment] 2022-02-09 20:01
Okay, I think we've come to the conclusion that the positioning relative to RTL text is correct, but that the overlapping pencil icon is definitely something we want to fix. If you don't mind, I'm going to update the title of the ticket to reflect that

**Comment by sinansonmez** [comment] 2022-02-09 20:03
Please update the title. Then, I can work on to fix pencil icon issue

**Comment by hmhealey** [comment] 2022-02-09 21:00
@sinansonmez That's done. Want me to assign this to you then?

**Comment by sinansonmez** [comment] 2022-02-09 21:03
Sure @hmhealey happy to work on this

**Comment by michelengelen** [comment] 2022-02-10 08:05
Sorry to butt in on this so late, but the problem with the icon is that it was incorrectly stored on a Unicode character slot that normally is reserved for rtl characters (the unicode range used here is normally reserved for arabic ligatures).

To be precise `U+FC92` would normally be the arabic ligature "Yeh" with zain final form (https://www.compart.com/en/unicode/U+FC92). There have been a series of PRs to shift the icons to a private use area, prefix the "old" icons with `BRKN_` and finally remove the broken icons.

So the actual problem is already solved, the only thing that seems missing was to update the compass-icons package in the webapp.

@sinansonmez I am sorry that you spend time on this where it could have been prevented. 🙇🏼 

cc/ @hmhealey @amyblais @akhmerov

**Comment by sinansonmez** [comment] 2022-02-10 09:51
Thanks @michelengelen for clarification. Good to know for future PRs. 

No problem that i spent some time on this. I learned  a bit about ltr & rtl topic. It was also fun to play around css to fix this 😅

To solve this, I assume, one of core  committer should update package and you dont need PR from my side.

**Comment by hmhealey** [comment] 2022-02-11 16:59
@michelengelen Would you mind submitting a PR to update that library then? I know it's kind of outside of your area of responsibility now, but as far as I know, we don't have anyone really focused on it at the moment.

**Comment by michelengelen** [comment] 2022-02-14 07:52
@hmhealey PR is up! 👍🏼

**Comment by sinansonmez** [comment] 2022-02-17 22:57
Is it OK to close this issue as @michelengelen's PR is merged. cc: @hmhealey @amyblais

**Closed** 2022-02-21 07:47 UTC
Labels: Difficulty/1:Easy, Tech/ReactJS, Help Wanted
