### ISSUE TITLE
"Jump" from Pinned Posts list gives a blank page

### ISSUE THREAD

**Issue by GuybrushThreepwood22** [mattermost/mattermost-server#8158] opened 2018-01-26 07:24 UTC
#### Summary
Broken/empty link

#### Steps to reproduce
Version: 4.6.0
Public Channel = town-square1x3
Display pinned posts
Hit jump on post and left with blank screen
https://oss.mattermost.com/joomla/pl/noik4qwwk3yc7khmbs8cwjf1ye

#### Expected behavior
Expected to see the pinned post content

#### Observed behavior (that appears unintentional) 
Blank page (except for sidebar menu). See attached screenshot.
![mattermost-blank-page](https://user-images.githubusercontent.com/35830432/35428968-af789530-0226-11e8-81b1-a5a47f80be12.png)

#### Possible fixes
N/A. This issue might be an edge case scenario and difficult to reproduce.

**Comment by lindy65** [comment] 2018-01-26 08:59
Hi @GuybrushThreepwood22 

Thanks for your feedback,

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master so I believe the issue is fixed and will ship with the next release on February 16th.

**Comment by lindy65** [comment] 2018-02-14 10:27
I'll close this issue off for now and we can reopen if the issue reproduces after v4.7 is released on Feb 16th.

**Closed by lindy65** 2018-02-14 10:27 UTC
