### ISSUE TITLE
Elasticsearch is not used

### ISSUE THREAD

**Issue by Zsyh2619** [mattermost/mattermost-server#17866] opened 2021-07-06 08:02 UTC
I have tried v5.31.0 and v5.36.1
I configured elasticsearch, imported 5 million chat records, and returned 504 when querying. So I did a test:
1. Configure elasticsearch according to the document and close the database search
2. restart the service
3. send some message.
(I found that new message can be found in elasticsearch)
4. then I modified the message in elasticsearch
(Refresh the page and find that the message has not changed)
5. then I modified the message in mysql
(Refresh the page and find that the message becomes the content in MySQL)
So its query is still using MySQL instead of elasticsearch
I read some source code and found that the problem might be found in app/server.go line 360 370 385, this may cause the search to use sqlstore all the time

**Comment by amyblais** [comment] 2021-07-06 14:58
@Zsyh2619 Would you be open to posting this on our [troubleshooting forum here](https://forum.mattermost.org/) with relevant [details from here](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues), and someone on our community will likely be able to help troubleshoot this with you?

Since Elasticsearch is an [E20 feature](https://docs.mattermost.com/deployment/elasticsearch.html), you may also consider contacting our customer support team via https://mattermost.com/support/.

**Comment by Zsyh2619** [comment] 2021-07-07 01:22
> @Zsyh2619 Would you be open to posting this on our [troubleshooting forum here](https://forum.mattermost.org/) with relevant [details from here](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues), and someone on our community will likely be able to help troubleshoot this with you?
> 
> Since Elasticsearch is an [E20 feature](https://docs.mattermost.com/deployment/elasticsearch.html), you may also consider contacting our customer support team via https://mattermost.com/support/.

OK, I have posted this on  troubleshooting. I'm using the test license, so I won't trouble support team.

**Comment by amyblais** [comment] 2021-07-19 12:26
@BenCookie95 @mkraft Wondering if you'd have any further thoughts on this issue? ^

The support team did some troubleshooting in the [forum issue](https://forum.mattermost.org/t/elasticsearch-is-not-used/11894), but they couldn't figure out the cause.

**Comment by mkraft** [comment] 2021-07-19 16:07
> @BenCookie95 @mkraft Wondering if you'd have any further thoughts on this issue? ^
> 
> The support team did some troubleshooting in the [forum issue](https://forum.mattermost.org/t/elasticsearch-is-not-used/11894), but they couldn't figure out the cause.

Thanks @amyblais We'll take a look, maybe conscripting @streamer45's help as—I'm guessing—our team's SME on Elasticsearch.

**Comment by streamer45** [comment] 2021-07-20 09:30
@Zsyh2619
Can you provide the contents of the `ElasticsearchSettings` section from `config.json`? You can skip/blank any sensitive setting like ConnectionUrl, Username and Password.

Also it would be helpful if you could enable debug logs, reproduce the issue (try a few searches) and then share the produced server logs.

**Comment by Zsyh2619** [comment] 2021-07-21 03:01
@streamer45 
The ElasticsearchSettings section from config.json：
"ElasticsearchSettings": {
    "ConnectionUrl": "http://elasticsearch:9200",
    "Username": "",
    "Password": "",
    "EnableIndexing": true,
    "EnableSearching": true,
    "EnableAutocomplete": true,
    "Sniff": true,
    "PostIndexReplicas": 1,
    "PostIndexShards": 1,
    "ChannelIndexReplicas": 1,
    "ChannelIndexShards": 1,
    "UserIndexReplicas": 1,
    "UserIndexShards": 1,
    "AggregatePostsAfterDays": 365,
    "PostsAggregatorJobStartTime": "03:00",
    "IndexPrefix": "",
    "LiveIndexingBatchSize": 1,
    "BulkIndexingTimeWindowSeconds": 3600,
    "RequestTimeoutSeconds": 30,
    "SkipTLSVerification": false,
    "Trace": ""
  },


The logs:
{"level":"debug","ts":1626835642.2806273,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/users/n4kfhd41e3nbxxgf7478x6kneh/channels/nqu83hzentgqjxiwbnz891gz8h/posts/unread","request_id":"unzcy6sm3jb19kr4m37swouezh"}
{"level":"debug","ts":1626835642.295469,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/channels/nqu83hzentgqjxiwbnz891gz8h/member_counts_by_group","request_id":"uj1ctd3aa7ghidthtygwhtoncw"}
{"level":"debug","ts":1626835642.5564988,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"qw4ffd4rq7yquejbm4a6rxcome"}
{"level":"debug","ts":1626835642.766157,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"rxbmrw8is7n5przysrwucyjycc"}
{"level":"debug","ts":1626835644.0686061,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/websocket","request_id":"mwm1473mibfytew86b87dha7ar"}
{"level":"debug","ts":1626835645.6077137,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"kitpri6xsj8iprio9fox83w1yr"}
{"level":"debug","ts":1626835659.0756752,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"9ekxfmroutyr8mwu3inua544sr"}
{"level":"debug","ts":1626835659.1033235,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/users/me/teams/7io1wpbnqbgg3fg1xxf3pmptnc/channels","request_id":"k3oignhe3tdntxis5nyunuffyr"}
{"level":"debug","ts":1626835659.1035223,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"GET","url":"/api/v4/users/me/teams/7io1wpbnqbgg3fg1xxf3pmptnc/channels/members","request_id":"fh3twkjb4fbdmq17x86bxzyd3a"}
{"level":"debug","ts":1626835666.5195117,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/teams/7io1wpbnqbgg3fg1xxf3pmptnc/posts/search","request_id":"r4s1dupshjnyi8ewi1n8qdd8fr"}
{"level":"debug","ts":1626835669.1756034,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"japxinwmatrrukkew54gia9wxo"}
{"level":"debug","ts":1626835680.949099,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"k5zk85rkijbatj8ao34gtxyq8c"}
{"level":"debug","ts":1626835687.8669586,"caller":"wsapi/websocket_handler.go:25","msg":"Websocket request","action":"user_update_active_status"}
{"level":"debug","ts":1626835690.6881433,"caller":"web/handlers.go:89","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"mf47t8ky53dmzx946m454yxk5e"}
{"level":"error","ts":1626835696.7287385,"caller":"sqlstore/post_store.go:1475","msg":"Query error getting posts.","error":"context deadline exceeded"}
{"level":"error","ts":1626835696.7292395,"caller":"searchlayer/post_layer.go:117","msg":"Encountered error on SearchPostsInTeamForUser.","search_engine":"elasticsearch","error":"SqlPostStore.GetPostsByIds: Unable to get the posts., "}
{"level":"debug","ts":1626835696.7292967,"caller":"searchlayer/post_layer.go:126","msg":"Returning empty results for post SearchPostsInTeam as the database search is disabled"}


These are from v5.25.7. The v5.25.7 could load history posts but can't search posts.

**Comment by streamer45** [comment] 2021-07-21 08:36
Looking at the logs the search seems to be working fine but that only returns ids. The problem appears to be the final fetching from the database which is timing out. That could be a sign of a performance issue with the database. Assuming you are running MySQL, could you share results of the following:

```sql
SHOW FULL COLUMNS FROM Posts;
SHOW INDEX FROM Posts;
```

**Comment by Zsyh2619** [comment] 2021-07-22 02:01
This is the result:
mysql> SHOW FULL COLUMNS FROM Posts;
+--------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Field        | Type         | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
+--------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Id           | varchar(26)  | utf8mb4_general_ci | NO   | PRI | NULL    |       | select,insert,update,references |         |
| CreateAt     | bigint(20)   | NULL               | YES  | MUL | NULL    |       | select,insert,update,references |         |
| UpdateAt     | bigint(20)   | NULL               | YES  | MUL | NULL    |       | select,insert,update,references |         |
| EditAt       | bigint(20)   | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| DeleteAt     | bigint(20)   | NULL               | YES  | MUL | NULL    |       | select,insert,update,references |         |
| IsPinned     | tinyint(1)   | NULL               | YES  | MUL | NULL    |       | select,insert,update,references |         |
| UserId       | varchar(26)  | utf8mb4_general_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| ChannelId    | varchar(26)  | utf8mb4_general_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| RootId       | varchar(26)  | utf8mb4_general_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| ParentId     | varchar(26)  | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| OriginalId   | varchar(26)  | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| Message      | text         | utf8mb4_general_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| Type         | varchar(26)  | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| Props        | text         | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| Hashtags     | text         | utf8mb4_general_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| Filenames    | text         | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| FileIds      | varchar(150) | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| HasReactions | tinyint(1)   | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
+--------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
18 rows in set (0.00 sec)

mysql> SHOW INDEX FROM Posts;
+-------+------------+------------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table | Non_unique | Key_name                                 | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-------+------------+------------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Posts |          0 | PRIMARY                                  |            1 | Id          | A         |     5715621 |     NULL | NULL   |      | BTREE      |         |               |
| Posts |          1 | idx_posts_update_at                      |            1 | UpdateAt    | A         |     4469225 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_create_at                      |            1 | CreateAt    | A         |     4968075 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_delete_at                      |            1 | DeleteAt    | A         |           1 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_channel_id                     |            1 | ChannelId   | A         |       50929 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_root_id                        |            1 | RootId      | A         |           1 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_user_id                        |            1 | UserId      | A         |       16278 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_is_pinned                      |            1 | IsPinned    | A         |           1 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_channel_id_update_at           |            1 | ChannelId   | A         |       42251 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_channel_id_update_at           |            2 | UpdateAt    | A         |     4091206 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_channel_id_delete_at_create_at |            1 | ChannelId   | A         |       51540 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_channel_id_delete_at_create_at |            2 | DeleteAt    | A         |       34789 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_channel_id_delete_at_create_at |            3 | CreateAt    | A         |     4636879 |     NULL | NULL   | YES  | BTREE      |         |               |
| Posts |          1 | idx_posts_message_txt                    |            1 | Message     | NULL      |     5715621 |     NULL | NULL   | YES  | FULLTEXT   |         |               |
| Posts |          1 | idx_posts_hashtags_txt                   |            1 | Hashtags    | NULL      |     5715621 |     NULL | NULL   | YES  | FULLTEXT   |         |               |
+-------+------------+------------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
15 rows in set (0.00 sec)

But I'm using elasticsearch, and disabled databsae search

**Comment by streamer45** [comment] 2021-07-22 06:18
Thanks, everything looks good schema wise.

> But I'm using elasticsearch, and disabled databsae search

Yes, the search is happening on ES but that does return post ids. The application needs to fetch the full posts (from DB) before returning them to the client. This last bit seems to be taking a long time, most probably due to poor DB performance.

- What's the value of `SqlSettings.QueryTimeout`? It may help to increase that a bit but otherwise everything points to a db issue.
- What are the specifications for the instance running MySQL (memory/cpu)? Also, is it running alongside Mattermost server or in a separate box?

**Comment by Zsyh2619** [comment] 2021-07-22 06:45
SqlSettings.QueryTimeout is 30.
MySQL running in docker without resource limitation.
I notice that elasticsearch stores the complete content of the message. Why return the ID instead of the message content. Our data volume is 5 million, so MySQL performance will definitely decline.

**Comment by streamer45** [comment] 2021-07-22 07:08
> SqlSettings.QueryTimeout is 30.
> MySQL running in docker without resource limitation.
> I notice that elasticsearch stores the complete content of the message. Why return the ID instead of the message content. Our data volume is 5 million, so MySQL performance will definitely decline.

Well, ES may store the message content but all the metadata is only in the DB and needs fetching in order for the client to properly display it. Also, the query that's timing out is rather trivial and shouldn't be taking that long even on large datasets because it means anything else post related (e.g. loading channels) could eventually suffer the same way. My recommendation would be to look into DB specs and possibly consider upgrading them and/or having a dedicated instance for running the db.

**Comment by amyblais** [comment] 2021-09-03 19:41
Closing for now, but feel free to re-open if you need further assistance here,

**Closed by amyblais** 2021-09-03 19:41 UTC
