### ISSUE TITLE
rejoining left channel unwillingily

### ISSUE THREAD

**Issue by sbulka** [mattermost/mattermost-server#8986] opened 2018-06-25 09:23 UTC
#### Summary
I left a public channel on May 28, and since joined the channel twice unwillingly (without user action).

#### Steps to reproduce
Join a channel with User A.
Leave the channel with User A.
Add User A by User B.
Remove User A by User B.
Write many messages in the channel (frequent daily usage).

Mattermost Version: 4.10.1
Database Schema Version: 4.10.0
Database: mysql
Client: Firefox 52.6.0 (64-Bit)

#### Expected behavior
Stay out of channel that was left until: willingly joining or being added by another user again.

#### Observed behavior (that appears unintentional) 
I left the channel on May 28, 2018.
Got added back once that day by an admin for a last message, and immediatly removed again.
The message in channel was 'sbulka added to the channel by {username}'.
On June 7, there was a message in channel 'sbulka joined channel', and I was in the channel again.
I left the channel on June 8.
On June 25, the channel was again joined with the same message, without my user action.
Both times it happened while mattermost client was running in browser.
I only happen to notice the rejoin when something new is written in the channel.
I am not immediatly taken to the channel.

#### Possible fixes
Make sure channel is not joined without User intent.
Add a confirm dialog for joining a channel which was left before, to prevent accidental joining?

**Comment by amyblais** [comment] 2018-06-25 14:40
Hi @sbulka! Thank you for reporting this.

I'll be testing this throughout the week and I'll let you know if I'm able to repro!

**Comment by amyblais** [comment] 2018-06-29 16:53
Hi @sbulka! Giving you an update that I haven't been able to repro this so far, so I will test it for another week or two as this seems to be a longer-term issue.

**Comment by sbulka** [comment] 2018-07-03 08:10
Hi @amyblais, thank you for looking into this.
Happened again today.

I wanted to check a channel which had new messages, clicked on it, and afterwards joined the unwanted channel.
side note: my computer had a noticeable delay (1-2s, mouse stuttering), so may be a kind of "misclick" originating from the system.

**Comment by amyblais** [comment] 2018-07-03 17:57
Hi @sbulka, would you be able to gather any errors in logs / Console errors that you might see around the time the issue occurs again? Also, do you have "Group unread channels" setting at "None" or "At the top of the channel sidebar"?

This did once happen to me a while ago on one of my test accounts, but I haven't seen it since and didn't investigate it further since I wasn't able to repro at the time.

**Comment by sbulka** [comment] 2018-07-04 06:10
I will watch out for Browser Console errors.
Don't know about other helpful logs (which/where to find them).

For the setting "Group unread channels", I can't find it (Account settings/display).
I assume "None", because my channels are not grouped when new messages appear.

**Comment by amyblais** [comment] 2018-07-04 22:52
Thank you! 

Regarding the "Group unread channels" setting, it might be disabled in the System Console and it would be found in "Sidebar" section in the Account Settings. No need to worry about it, I just tried to think about all possible situations for testing this case.

**Comment by sbulka** [comment] 2018-07-11 09:01
Happened again.

Browser console gave these two warnings, but I'm not sure if everything was logged before i opened it.
Had no timestamps activated unfortunately (activated afterwards, but message was gone after going back to console. next time there should be time stamps).
The warning is about possible issues with Panning and ScrollLinkedEffects (its in german).
"mittagessen" is the name of the channel which gets rejoined.

    websocket connecting to wss://mattermost.le-tex.de:443/api/v4/websocket  0.b9189eb3c1ad1e8e16c1.js:1:1873052
    
    Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil! mittagessen

**Comment by amyblais** [comment] 2018-07-11 23:43
Thank you @sbulka!

Just to confirm, do you only see this issue in one channel (mittagessen)?

I will ask our team about whether anyone has experienced something similar in the past and if there is any other specific information we could help gather to investigate this.

I could not find information on ScrollLinkedEffects (related to Mattermost) so I have a feeling that it might not be the cause of the issue, but we will continue to investigate this.

**Comment by amyblais** [comment] 2018-07-19 13:20
Hi @sbulka! Just to confirm, is this happening with multiple channels or one channel?

**Comment by amyblais** [comment] 2018-07-19 14:45
I checked with the team and here are some possible causes:

1. You are clicking on a link/bookmark.
2. You have the browser autocomplete the URL to that channel's address.
3. You are clicking a permalink to a message in the channel.

Based on these, a "Join this channel?" confirmation prompt was suggested (which you also proposed) as well as having a preview shown when viewing a permalink.

If one of the above options sounds possible, I can create Improvement tickets for the suggestions.

**Comment by sbulka** [comment] 2018-07-19 14:58
It's number 1.
So obvious...

It's confusing to me that if I click a link I automatically join the channel.
Some kind of information/warning before joining would definitely be helpful.

Out of curiosity I just checked: when clicking the link to a private channel, I am forwarded to a general channel without further notice.
If there was a "Join this channel?" message, there could be info provided like "You can't join this channel since it's private. Ask channel admin."

Anyways, thank you very much for your efforts!

**Comment by amyblais** [comment] 2018-07-20 18:11
Hi @sbulka! Glad to hear that the immediate issue is resolved (figuring out the reason why you are rejoining a channel you've left).

I've created an Improvement ticket to investigate adding the "Join this channel?" message, but we cannot yet give any confirmation when or if this feature will be added since we need to explore different designs / scenarios, etc. for this case (I checked with our product managers about this). However, you can follow the progress of the ticket here: https://mattermost.atlassian.net/browse/MM-11435.

I'll close this Issue for now as the main problem is resolved.

**Closed by amyblais** 2018-07-20 18:11 UTC
