### ISSUE TITLE
When using compact display mode the actions popup overlaps the message

### ISSUE THREAD

**Issue by ansgarwiechers** [mattermost/mattermost-server#20218] opened 2022-05-17 07:05 UTC
#### Summary
When using compact display mode the actions popup (where you can select "reply", "edit", etc.) overlaps the message.

#### Steps to reproduce
In _Settings > Display_ change "Message Display" from "Standard" to "Compact", then hover the mouse cursor over a message.

Versions tested: v6.4.2, v6.6.1

#### Expected behavior
The message should always be accessible via mouse, so that for example links can be clicked.

#### Observed behavior (that appears unintentional) 
In compact mode the actions popup overlaps the message text when you hover the mouse cursor over the message. This makes part of the message inaccessible (e.g. you can't click links that are covered up by the popup). You have to resize the window to get around this.

![Screenshot of the actions popup overlapping a message.](https://user-images.githubusercontent.com/37694823/168747830-21552bb4-4587-4e7e-97cf-ecf5e9ebcb81.png)

#### Possible fixes
Display the popup above the message in compact mode or allow for suppressing/hiding the actions popup (e.g. by pressing a key).

**Comment by amyblais** [comment] 2022-05-17 13:21
Closing as duplicate of https://github.com/mattermost/mattermost-server/issues/20187.

**Closed by amyblais** 2022-05-17 13:21 UTC
