### ISSUE TITLE
Prevent dragging images (e.g. close button) 

### ISSUE THREAD

**Issue by infacto** [mattermost/mattermost-server#20255] opened 2022-05-20 08:31 UTC
You can drag things like images from the UI. Like the minimize, maximize and close button. But also the profile avatar on the left side, etc.

![demo](https://user-images.githubusercontent.com/60390085/169485471-9d1b26ac-2bf0-42e3-960f-dfc68f95a34f.gif)

Some possible solutions: 

- Set `pointer-events: none` to img. Not on the button. Be sure that you have no images with interactions. You could use class names to enable pointer-events only for that cases again (.interactive {pointer-events: auto}).

- Add the attribute `draggable` to the `img` element.

- Use the `dragstart` event in JS to `preventDefault()`.

- Search the web for more solutions.

Mattermost Desktop Client Version: `Version 5.1.0-nightly.20220428 commit: c6bf661e` (all versions have this issue as far as I can remember)

**Comment by JtheBAB** [comment] 2022-05-20 13:46
@devinbinnie 

I don't think it is just server. You can drag the close button which is the Desktop App itself and not the webapp.

**Comment by devinbinnie** [comment] 2022-05-20 13:47
@JtheBAB I see my comment didn't make it over :P

I created a ticket seperately for the Desktop issues: https://mattermost.atlassian.net/browse/MM-44466
But you can do this with static webapp images as well.

**Comment by JtheBAB** [comment] 2022-05-20 13:47
Ah i see :D

**Comment by stackkrocket** [comment] 2022-05-27 21:57
Correct me if I am wrong. But from what I can see there, isn't that the close button of your browser tab being draggable there?

**Comment by hmhealey** [comment] 2022-07-26 14:24
This looks like it was fixed by the Desktop App change. I can't repro this within the web app. Feel free to reopen if it's still happening

**Closed by hmhealey** 2022-07-26 14:24 UTC
Labels: Bug Report/Open

**Comment by devinbinnie** [comment] 2024-07-15 16:50
@fudom I can't reproduce this at all, can you take a video of what you're seeing? What OS are you using as well?
