### ISSUE TITLE
Clicking Help hyperlink inside the “Set a Header” modal window does not actually load or display the Help page

### ISSUE THREAD

**Issue by billybrown1** [mattermost/mattermost-server#8269] opened 2018-02-13 15:39 UTC
#### Summary
Clicking Help hyperlink inside the “Set a Header” modal window does not actually load or display the Help page

#### Config:
Web browser:
• Google Chrome - MacOS X - Version 63.0.3239.132 (Official Build) (64-bit)

#### Steps to reproduce
1)  Login to https://demo.mattermost.com and go to the Joomla channel
2)  Under PUBLIC CHANNELS in the blue sidebar (on the left) select “Channel for bugfinding”
3)  Scroll all the way up to the top of the channel text until you see “Beginning of Channel for bugfinding”
4)  Click on the Pencil/“Set a Header”  link:
![click on set a header](https://user-images.githubusercontent.com/25070389/36157891-1eb2c5d6-1098-11e8-9f57-bd96501e554c.jpg)
5)  Next, in this new modal window being displayed, attempt to click on the blue hyperlinked word “Help”, immediately to the right of >quote
![click on help2](https://user-images.githubusercontent.com/25070389/36158345-5947fa58-1099-11e8-8c4c-c5e07d8982be.jpg)

*** NOTHING HAPPENS

#### Expected behavior
A new browser tab should open with the html URL, similar to the way clicking "Help" link down below in the lower-right corner of the Channel window opens a new tab displaying https://demo.mattermost.com/help/messaging
![clicking help works](https://user-images.githubusercontent.com/25070389/36158047-930e6930-1098-11e8-9b97-1d405f4e78e1.jpg)

#### Observed behavior (that appears unintentional) 
Nothing happens (at the end of step 5 above), when you attempt to click on the hyperlinked 'Help' in the modal window.
Work-around:  If you control-(or right) Click the link and choose Open in new Tab, then the user can still access the help page url.

#### Possible fixes
It might have something to do with the fact that the click is originating from within a modal "Edit Header for Channel for _______" window, and it is somehow preventing the click from opening the help in a new tab.

**Comment by lindy65** [comment] 2018-02-14 09:34
Hi @billybrown1 

Thanks for the report,

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) so I believe it is fixed and will ship with v4.7 on Feb 16th.

Please try on the above server to see if it still reproduces for you?

**Comment by lindy65** [comment] 2018-02-23 07:58
I believe this is fixed now so I'll close this issue off for now @billybrown1

**Closed by lindy65** 2018-02-23 07:58 UTC
