### ISSUE TITLE
model.NewAppError allows invalid AppError.StatusCode

### ISSUE THREAD

**Issue by SmartHoneybee** [mattermost/mattermost-server#9282] opened 2018-08-22 12:33 UTC
#### Summary
`model.NewAppError` allows setting invalid `AppError.StatusCode` values.

#### Steps to reproduce
Mattermost uses `AppError.StatusCode` as parameter `code` for `net/http`'s `WriteHeader` (e.g. in `web/handlers.go` line 163). This panics if `code < 100 || code > 999`.

(Mattermost version: 5.2.0)

#### Expected behavior
No `panic`. (`NewAppError` rejects invalid arguments and uses a sane default instead.)

#### Observed behavior (that appears unintentional) 
Lovely stack traces and errors mentioning "*invalid WriteHeader code 0*".

#### Possible fixes
* check `model.NewAppError`'s arguments
* use constants provided by `net/http` (files to check: `api4/oauth_test.go`, `utils/config.go`, `model/client4.go`)

**Comment by amyblais** [comment] 2018-08-22 13:04
@cpanato Are you familiar with this error or let me know if I can help ping other devs to look at this as well?

**Comment by amyblais** [comment] 2018-08-22 13:53
Thank you @SmartHoneybee! Ticket here: https://mattermost.atlassian.net/browse/MM-11800.

**Comment by amyblais** [comment] 2018-08-28 18:00
Hi @SmartHoneybee, the Jira ticket was closed as "Won't Fix" because this is caused by a developer error, where panic isn't an unreasonable result.

Thank you for originally reporting this!

I'll close this Issue for now,

**Closed by amyblais** 2018-08-28 18:00 UTC
