### ISSUE TITLE
Quote in Channel Header Semi-hidden

### ISSUE THREAD

**Issue by jeshuawoon** [mattermost/mattermost-server#8036] opened 2018-01-04 18:44 UTC
#### Summary
When using a quote as the channel header in the browser version, bottom part of the quote is hidden/blocked from view by the bar restraining it.

#### Steps to reproduce
1. Use quotation as a channel header

Mattermost Version: 4.4.0  (4.4.2)
Database: mysql

Browser: Chrome
B. Version: 63+

#### Expected behavior
If, for any reason, a user were to set a quote as a channel header, it should be able to be seen fully and not be obscured from view.

#### Observed behavior (that appears unintentional) 
![capture](https://user-images.githubusercontent.com/35112783/34578997-1eb145ac-f1c2-11e7-9097-0ba8b920f21b.PNG)

The "channel header bug" quote is semi-hidden.

#### Possible fixes
Perhaps make the quotes shrink to fit the bar when used as channel header, or have the bar resize (scale up) to fit the normal/regular size of quotes.

**Comment by lindy65** [comment] 2018-01-05 09:11
Hello @jeshuawoon,

Thanks for your feedback,

I believe this is by design...  Only 1 line is displayed in the UI.  To view the full channel header, click on the line of text in the header and the other lines will be displayed.

![image](https://user-images.githubusercontent.com/13020833/34602548-dc27f752-f208-11e7-8255-7b54c0c747e7.png)

![image](https://user-images.githubusercontent.com/13020833/34602573-f04dd9e0-f208-11e7-8038-8c825169677c.png)


Links in the channel header are clickable and will open in a new browser tab.

It might be a good idea to upgrade to the [latest version](https://about.mattermost.com/download/) of Mattermost.  Version 4.6 will be shipping on January 16th if you'd prefer to wait until then.

**Comment by lindy65** [comment] 2018-01-09 09:54
Hi @jeshuawoon 

We've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8514) to improve the layout.

**Comment by lindy65** [comment] 2018-01-09 19:52
I'll close this issue off for now and we can track via the ticket linked above.

**Closed by lindy65** 2018-01-09 19:52 UTC
