### ISSUE TITLE
Channel Header Formatting: Code Blocks Aren't Readable

### ISSUE THREAD

**Issue by Merlin2001** [mattermost/mattermost-server#7861] opened 2017-11-20 10:05 UTC
#### Summary
When using emojis in the channel header text, their bottom part is truncated. When formatting the text as code block, it is not readable at all because it is truncated.

#### Version/Client Info
**Mattermost Team Edition** Version 4.2.0 on postgres DB - build hash a5ce36d0882ae1b4b409a7b68233bf89591a5f95
**Windows Client** v3.7.1 as well as  
**Chrome** (Version 62.0.3202.94 (official build) (64-bit))

#### Steps to reproduce
For the emoji bug, set the channel header text using emoji characters, e. g. `:smile:` or `:red_circle:` (effect is most visible with round/face emojis).

The illegible code text can be reproduced by starting the channel header text with four space characters (i. e. "code block"), e. g. "&nbsp;&nbsp;&nbsp;&nbsp;Code Block Text"
(note: in-line code blocks using back ticks work fine)

#### Expected behavior
Emojis should be shown correctly by either resizing the emojis or increasing line height. Code blocks in the first row of the channel header should be converted to in-line code or displayed as text only (i. e. render them as code block only when hovering over the channel header).

#### Observed behavior (that appears unintentional) 
Emojis show up like this:
![2017-11-17_12h30_17](https://user-images.githubusercontent.com/13134791/33012511-73285940-cde1-11e7-865e-55ba636cc44c.png)

Code block text looks like this:
![2017-11-17_12h31_51](https://user-images.githubusercontent.com/13134791/33012523-7b1ea8b6-cde1-11e7-8af3-8ba1b70ff3cd.png)

**Comment by lindy65** [comment] 2017-11-21 08:37
Hi @Merlin2001,

Thanks for your report!

I've reproduced the code block issue on our nightly build server that builds off master but am not able to reproduce the emoji issue.

Could we have your help updating to the [latest version](https://about.mattermost.com/download/) of Mattermost to see whether the emoji issue still reproduces for you?

In the meantime, I've created [this ticket](https://mattermost.atlassian.net/browse/PLT-8206) for the team to investigate the code block issue.

**Comment by Merlin2001** [comment] 2017-11-21 09:06
Hi @lindy65,

thank you very much for your lightning-fast response and creating the ticket!

Unfortunately, I'm not in control of the server version here, since it's a deployment in a rather large corporation. Maybe somebody else can('t) reproduce this and chime in here. I'll report back, of course, should we update anytime soon :)

Thanks again!

**Comment by lindy65** [comment] 2017-11-21 09:19
Thanks @Merlin2001 :)

We'll wait to see whether someone else can reproduce the emoji issue and work on the ticket in the meantime.  Let us know how it goes once your company has updated the server!

**Comment by Merlin2001** [comment] 2017-11-27 08:21
Hi @lindy65,

our admins just installed **v4.4.2** today and emojis are now **displaying correctly** in channel headers! :tada:

Should I update the issue in some way to reflect this?

**Comment by lindy65** [comment] 2017-11-27 09:10
Good to hear @Merlin2001 :)

No need to make any update to this issue.  The [ticket](https://mattermost.atlassian.net/browse/PLT-8206) I created is for the code block issue only and I've edited the title of this issue to reflect only the code block issue...

**Comment by lindy65** [comment] 2017-11-29 09:32
Hi @Merlin2001,

Just an update that the [bug](https://mattermost.atlassian.net/browse/PLT-8170) with editing channel headers has been fixed :)

I'll close this issue off for now and we can track the code block issue via the ticket linked above.

**Closed by lindy65** 2017-11-29 09:32 UTC
