### ISSUE TITLE
Not able to paste Custom Theme

### ISSUE THREAD

**Issue by fosBHY** [mattermost/mattermost-server#10125] opened 2019-01-20 22:48 UTC
#### Summary
Can not paste theme into field.

#### Steps to reproduce
Like described in closed issue #6184 ( https://github.com/mattermost/mattermost-server/issues/6184 ) it is not possible for me write into the field. But it is also not possible to PASTE into the field, so I can not use the themes provided at https://docs.mattermost.com/help/settings/theme-colors.html#custom-theme-examples for example.

Mattermost-Version: 5.5.0
Database: postgres

#### Expected behavior
Pastable theme

#### Observed behavior (that appears unintentional) 
Nothing happens

#### Possible fixes
I have no clue

**Comment by amyblais** [comment] 2019-01-22 19:42
Hi @fosBHY,

Can you help upgrade to v5.7 server version? I tested this just now on the latest version and wasn't able to repro. If you want to, you can first do some testing on our community instance here: https//community.mattermost.com

**Comment by fosBHY** [comment] 2019-01-29 21:56
I can not upgrade sadly as I am not the admin. Also I dont want to register to yet another service. I am sorry. I might come back to this issue once we got to version 5.7 though..

**Comment by lfbrock** [comment] 2019-01-29 23:14
@fosBHY - would you also be able to share what browser and computer OS you were using, so we can try reproducing it with a similar environment?

**Comment by fosBHY** [comment] 2019-01-29 23:37
firefox 64.0 
ubuntu 18.04

**Comment by amyblais** [comment] 2019-01-30 18:53
@crspeller / @grundleborg can you help test this on a Linux environment?

**Comment by DSchalla** [comment] 2019-01-30 20:21
@fosBHY Can you try to paste the entire theme into the box at once?

1. Click in the custom theme text box
2. Paste the theme
3. Theme should be applied directly for testing

I think the way it's currently implemented doesn't allow you to manually write one in there, since it's instantly validated, so to say. Using the steps above I could change the theme successful on:

- Fedora 29
- Firefox 64.0.1 and Desktop App v4.1.2

**Comment by fosBHY** [comment] 2019-02-01 19:11
I did paste the whole theme, I am aware of this.

**Comment by amyblais** [comment] 2019-02-19 17:55
Hi @fosBHY, I'll close this Issue for now as there haven't been updates on this for a while. If the issue persists, please re-open this with relevant additional details for additional troubleshooting.

**Closed by amyblais** 2019-02-19 17:55 UTC

**Comment by Bilb** [comment] 2020-02-21 03:50
Just got the same issue.
Can we reopen it?
Here are logs from both consoles:

```
websocket_client.jsx:156 websocket closed
2react-dom.production.min.js:198 TypeError: Cannot read property 'toUpperCase' of undefined
    at X.setHex (color_input.tsx:56)
    at X.componentDidUpdate (color_input.tsx:43)
    at ji (react-dom.production.min.js:216)
    at Yi (react-dom.production.min.js:220)
    at react-dom.production.min.js:250
    at Object.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Is (react-dom.production.min.js:250)
    at Ds (react-dom.production.min.js:249)
    at Ls (react-dom.production.min.js:248)
    at qs (react-dom.production.min.js:251)
fi @ react-dom.production.min.js:198
Mi.n.callback @ react-dom.production.min.js:210
ai @ react-dom.production.min.js:193
ri @ react-dom.production.min.js:193
ji @ react-dom.production.min.js:217
Yi @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Is @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ls @ react-dom.production.min.js:248
qs @ react-dom.production.min.js:251
On @ react-dom.production.min.js:85
react-dom.production.min.js:248 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at X.setHex (color_input.tsx:56)
    at X.componentDidUpdate (color_input.tsx:43)
    at ji (react-dom.production.min.js:216)
    at Yi (react-dom.production.min.js:220)
    at react-dom.production.min.js:250
    at Object.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Is (react-dom.production.min.js:250)
    at Ds (react-dom.production.min.js:249)
    at Ls (react-dom.production.min.js:248)
    at qs (react-dom.production.min.js:251)
setHex @ color_input.tsx:56
componentDidUpdate @ color_input.tsx:43
ji @ react-dom.production.min.js:216
Yi @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Is @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ls @ react-dom.production.min.js:248
qs @ react-dom.production.min.js:251
On @ react-dom.production.min.js:85
root.jsx:36 POST https://mattermost.xxxx/api/v4/logs 401 (Unauthorized)
window.onerror @ root.jsx:36
```

**Comment by amyblais** [comment] 2020-02-25 21:55
@Bilb would you also be able to share what browser and computer OS you were using, so we can try reproducing it with a similar environment?

**Comment by Bilb** [comment] 2020-02-25 22:14
Linux Ubuntu 19.10
Firefox 73.0 (64-bit)

Tried using the monokai theme from https://docs.mattermost.com/help/settings/theme-colors.html#custom-theme-examples

**Comment by UpriseNate** [comment] 2020-04-20 18:16
I am also seeing this on 5.20.1

Tested using edge on macos 81.0.416.53, chrome on macos 81.0.4044.113, and safari on macos 13.0.5 running on MacOS Catalina 10.15.3
