### ISSUE TITLE
File extentions are omitted in MatterMost Windows Client

### ISSUE THREAD

**Issue by MMetze** [mattermost/mattermost-server#7599] opened 2017-10-10 07:49 UTC
#### Summary
Downloading a posted file within the Mattermost Windows x64 3.7.1 omits the file extention.

#### Steps to reproduce
Mattermost Windows x64 Client 3.7.1 on Windows 10

#### Expected behavior
I posted a file to a channel. If I login via the webfrontend, using Chrome, and klick on the file,
it get's downloading and filename and extention are correct. I assume this should be the same
for the windows client.

#### Observed behavior (that appears unintentional) 
Clicking the file opens a preview window:
![image](https://user-images.githubusercontent.com/7137535/31374888-08265d9c-ada0-11e7-8629-6f489b074433.png)

Clicking the window, or the download button, open a save as dialog:
![image](https://user-images.githubusercontent.com/7137535/31374913-202a3076-ada0-11e7-836e-8671da068f55.png)
Filename is correct, but extention is omitted.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment] 2017-10-10 18:39
Hi @MMetze,

Thanks for your feedback,

We're not able to reproduce your issue.  Could you share which version of Mattermost server is running?   You can see this by clicking "Main Menu' > "About Mattermost" (from within your team).  

v4.2 is the latest released version and you can download it [here](https://about.mattermost.com/download/).  v4.3 will be released on October 16th if you'd prefer to wait until then.

**Comment by MMetze** [comment] 2017-10-12 06:35
Hi lindy, 

sure. I'm running 4.2.0 with mysql backend. Let me know if you need anything else.
We can put this issue on hold and check again when I upgraded to 4.3.

**Comment by lindy65** [comment] 2017-10-12 07:11
Thanks @MMetze 

Let us know how it goes once you've upgraded to v4.3

**Comment by lindy65** [comment] 2017-10-18 09:12
Hi @MMetze,

How did the upgrade to v4.3 go?  Is your issue resolved?

**Comment by MMetze** [comment] 2017-10-18 12:34
The Update worked like a charm.
And now the file extentions are properly forwarded to the mattermost windows client.
This case is resolved :)

Thank you very much!

**Comment by lindy65** [comment] 2017-10-18 17:52
Good to hear @MMetze :)

I'll close this issue off then.

**Closed by lindy65** 2017-10-18 17:52 UTC
