### ISSUE TITLE
After upgrade to gitlab 14.6.3 bundle New Features notification  in browser renders system unusable

### ISSUE THREAD

**Issue by cxrider** [mattermost/mattermost-server#19397] opened 2022-01-21 22:07 UTC
#### Summary
Bug report in one concise sentence

After upgrading gitlab bundle to version 14.6.3, the "New Features" feature of Mattermost consumes enough CPU resources to render a machine unusable.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Upgrade to gitlab-14.6.3; I do not know from whence we came.
Login to desktop, start shell, start top in shell
Start browser - I am using Firefox 91.2.0esr (64-bit) on Centos 8.4, kernel 4.18.0-305.19.1
Login to Mattermost in a browser. 
Wait ~ 30s while watching cpu load as measured by top go from ~ 0.5 to 6+
* Note - memory resources were virtually still free; ~ 75% mem free as reported by top
* 
#### Expected behavior
Describe your issue in detail
I expect to be able to use Mattermost without it rendering my system inoperable.   After *two* power cycles to recover the system I keyed in on the 'pulsing green orb of death' which when clicked brought up the "New Features".   I managed to 'opt out' before the load was so high that I could not manage my system.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
See expected behaviour above.   There were no known error messages and since the system effectively froze, no screenshots can be provided.  I do note that top continued to update w/ system load information, input focus from the mouse was virtually lost making it impossible to kill the browser or type anything in the shell.  That being said, I did manage to one time kill the browser as I had anticipated the run-away event and clicked the 'kill' button for the browser before all input focus was lost.  It still took nearly a minute for the browser to exit and I observed system load as measured by top immediately drop, returning to normal levels after a few minutes.
#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment] 2022-01-26 00:04
Does this still reproduce when the "New Features" banner is dismissed?

**Comment by cxrider** [comment] 2022-01-26 00:35
I wouldn't say that there is a banner to dismiss, at least not at first.   When I launched mattermost after the upgrade it looked like it always does, taking me to my various chat areas.   Had I not been paying attention I would have never noticed the pulsing orb; a banner never appeared anywhere.   I had to power cycle my machine (I guess I could have considered a remote ssh to potentially kill the process but then I didn't immediately know what was causing the system to thrash) as the only thing that 'worked' was the mouse pointer; clicking on the shells or the browser did nothing; the input focus never shifted.  

When I finally suspected the code behind the pulsing orb to be the most likely candidate for the problem (I'd powered up, started a single shell running top, and the browser with the only tab being mattermost), I was able to see sys load start to skyrocket.  I killed the browser before I lost all control and tried again, this time clicking on the orb asap.   That action brought up the "New Features" and I opted out of previewing the rest asap.   The sys load dropped back to normal and hasn't been a problem since.   I have no idea what the new features are and I won't go looking b/c I don't want to have to deal with that problem again. 

I guess the best answer to your question is the problem was 100% reproducible; 2 times => power cycle, 1 time monitoring and a quick kill, no reboot/logout, 1 time on its way to buried until I clicked on the orb and opted out of seeing more.   If that is considered a dismiss then the answer would be no or unknown; I've not tried seeing what the new features are.

**Comment by amyblais** [comment] 2022-01-26 00:59
@hmhealey @streamer45 Let me know if you have thoughts on which team may be the best to take a look at this.

**Comment by hmhealey** [comment] 2022-01-31 19:47
That's odd. I'm not aware of anything in the web app that could bring down the browser, let alone the whole computer. We used to have issues with regexes going out of control in the message formatting code, but that was triggered by users sending messages with specific text, and its been a while since we've had any issues like that.

---

@cxrider What version of Mattermost/GitLab were you on before the upgrade? That might change which features are shown in the New Features window, so maybe there's an issue with a specific notification.

Also, are you otherwise seeing any issues with your Mattermost instance since you upgraded? Perhaps this is a side effect of another issue. I'm seeing some code that looks like it could get stuck in a loop repeatedly requesting stuff from the server if your websocket connection was unstable (which cause a spam of messages in the browser's console), so maybe that could be related.

---

@amyblais Growth team are the ones who have been working on the tutorial and onboarding recently, but I don't have any idea if that is actually what's causing this issue since I think they only changed things that.

If I understand right, the New Features popup would be one of the in-product notices, so perhaps Eric might have an idea which notifications could show up on an upgrade to 6.1 since that's what comes with that version of GitLab.

**Comment by amyblais** [comment] 2022-03-15 16:50
I'll close this for now, but feel free to re-open this issue if the problem comes back.

**Closed by amyblais** 2022-03-15 16:50 UTC
