### ISSUE TITLE
Cannot update the post type using PluginAPI

### ISSUE THREAD

**Issue by chetanyakan** [mattermost/mattermost-server#9897] opened 2018-11-28 07:18 UTC
#### Summary
The `UpdatePost` method in `PluginAPI` cannot update the post type.

#### Steps to reproduce
In a server plugin,
1. Get a post using `GetPost`.
2. Update the `Message` and `Type` fields.
3. Update the post by calling `UpdatePost`.

#### Expected behavior
Expected both post type and message fields to be updated.

#### Observed behavior (that appears unintentional) 
Only post message is updated. Post type is not updated.

#### Possible fixes
https://github.com/mattermost/mattermost-server/blob/master/app/post.go#L351
Post type could be updated here, if it is changed.

**Comment by amyblais** [comment] 2018-11-28 23:49
Hi @chetanyakan, I've asked our team to help test this out.

**Comment by amyblais** [comment] 2018-11-29 12:57
Hi @chetanyakan Looks like one of our developers replied to your question in the Developers channel - "Is made that way by design, at the App layer (not only for plugins) you can't modify the post Type after the creation." I'll close this Issue for now as this seems to be expected.

**Closed by amyblais** 2018-11-29 12:57 UTC
