### ISSUE TITLE
5.0.2 Memory leak on OSX?

### ISSUE THREAD

**Issue by variable** [mattermost/mattermost-server#19549] opened 2022-02-07 21:14 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Running MM for a few days, with opening different channels etc result excessive memory consumption

**Environment**
- Operating System: Mac OSX 11.6
- Mattermost Desktop App version: 5.0.2
- Mattermost Server version: X.X.X 

**Steps to reproduce**
Run MM for a few days and browse different channels

**Expected behavior**
Runs smooth and doesn't consume a lot of memory

**Observed behavior**
Excessive memory usage

![image](https://user-images.githubusercontent.com/558175/152872970-a38f8a2d-768b-46d0-b54d-8a1dfc415506.png)

**Comment by amyblais** [comment] 2022-02-14 15:54
Opened a ticket: https://mattermost.atlassian.net/browse/MM-41812.

**Comment by hmhealey** [comment] 2022-02-23 15:54
I think we've finally nailed down the cause of this issue as being caused by instances of the post textbox component (CreatePost) being leaked when its removed from the DOM (like on team switch). We've submitted fixes for that to master and backported them to 6.3.x and 6.2.x. A similar fix is in the works for 6.4.x.

We're going to close this for the time being, but we can reopen this if it's still a problem.

**Closed by hmhealey** 2022-02-23 15:54 UTC
Labels: Bug Report/Open
