### ISSUE TITLE
SMTP test emails & password reset emails are not sent when email notifications are off

### ISSUE THREAD

**Issue by aidenmitchell** [mattermost/mattermost-server#14977] opened 2020-07-07 00:57 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
SMTP test emails & password reset emails are not sent when email notifications are off.

#### Steps to reproduce
1. Setup SMTP
2. Disable email notifications
3. Test SMTP using the Test Connection button
4. Enable email notifications
4. Test SMTP using the Test Connection button

OR

1. Setup SMTP
2. Disable email notifications
3. Request a password reset email.
4. Enable email notifications
5. Request a password reset email.

#### Expected behavior
I receive a test email. Users receive a password reset email.

#### Observed behavior (that appears unintentional) 
I do not receive a test email. Users do not receive a password reset email when requested.

**Comment by amyblais** [comment] 2020-07-07 11:57
@aidenmitchell What server version are you on?

**Comment by agnivade** [comment] 2020-07-07 12:08
This is likely a duplicate of https://mattermost.atlassian.net/browse/MM-26033.

**Comment by aidenmitchell** [comment] 2020-07-07 18:18
@amyblais Version 5.24.2

**Comment by aidenmitchell** [comment] 2020-07-24 16:22
@amyblais I don't believe PR #15022 solves the password reset email part of this issue.

**Comment by agnivade** [comment] 2020-07-24 17:19
@isacikgoz - Did you get a chance to chat with @thefactremains about this? :point_up:

**Comment by isacikgoz** [comment] 2020-07-27 19:34
> @amyblais I don't believe PR #15022 solves the password reset email part of this issue.

Just got the chance to review this. So, yes that PR is for SMTP testing part of the issue. The remaining part, however, doesn't seem to be related with the `SendEmailNotifications` setting.

**Comment by amyblais** [comment] 2020-07-28 16:14
Ok, I created a ticket for the other case: https://mattermost.atlassian.net/browse/MM-27349.

**Comment by agnivade** [comment] 2020-07-29 06:53
Hi @aidenmitchell - the test email does seem to be part of the `SendEmailNotifications`, but the password reset is not. I just tested it with the setting being off and I can see password reset mails being sent properly.

Would you be able to provide additional logs that can help us debug this issue further?

**Comment by agnivade** [comment] 2020-09-23 07:57
Both the tickets are resolved now. @aidenmitchell - would you be able to clarify my comment above?

**Closed** 2021-09-03 14:50 UTC
Labels: PR Exists
