### ISSUE TITLE
High disk I/O reads after upgrading to 4.9

### ISSUE THREAD

**Issue by nagotti** [mattermost/mattermost-server#8658] opened 2018-04-23 14:20 UTC
#### Summary
After updating Mattermost from 4.8 to 4.9 the amount of disk I/O read activity went extremely high. This causes channels to load very slowly.

#### Steps to reproduce
Install or upgrade to Mattermost 4.9 and monitor disk I/O read activity when loading large channels. 

#### Expected behavior
Channels load fast(er) with "normal" amount of disk I/O read activity. This issue is probably related to these changes done in Mattermost 4.9:
- Decreased channel load time by optimizing database queries used to fetch threads and parent posts in a channel.
- Decreased load time of large channels with 5,000+ messages by up to 90% by optimizing many client functions related to rendering posts and threads.

#### Observed behavior (that appears unintentional) 
This screenshot displays the AWS EC2 volume Read IOPS from the last two weeks. The increased disk load is after upgrading to Mattermost 4.9

![mm](https://user-images.githubusercontent.com/38661652/39132315-420f1cba-471a-11e8-88cb-246810ebfcc1.png)

**Comment by lieut-data** [comment] 2018-04-24 14:31
@nagotti, are you noticing the increased `IOPS` on your Mattermost server instance or your database instance? We are in the process of releasing 4.9.1 that reverts some performance changes that negatively impact large installations that use threads infrequently: does this describe your situation?

**Comment by nagotti** [comment] 2018-04-24 14:40
@lieut-data We are running both Mattermost server and the database server (PostgreSQL 9.6.7) on the same instance. The I/O load is caused by PostgreSQL processes. We have quite small deployment with 20+ users.

Here's some stats from iotop when trying to open a channel that contains large amount of messages:

> Total DISK READ :      61.00 M/s | Total DISK WRITE :      31.38 K/s
Actual DISK READ:      61.01 M/s | Actual DISK WRITE:      62.76 K/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
11958 be/4 postgres   23.03 M/s    0.00 B/s  0.00 % 34.16 % postgres: mmuser mattermost 192.168.x.x (37228) SELECT
12271 be/4 postgres   18.90 M/s    0.00 B/s  0.00 % 27.84 % postgres: mmuser mattermost 192.168.x.x (41172) SELECT
11965 be/4 postgres   18.87 M/s    0.00 B/s  0.00 % 27.37 % postgres: mmuser mattermost 192.168.x.x (37406) SELECT

**Comment by lieut-data** [comment] 2018-04-24 15:01
Would you be comfortable running a SQL query to see if your instance is negatively impacted by the performance change I mentioned above?
```
EXPLAIN ANALYZE SELECT * FROM Posts WHERE Id IN (SELECT * FROM ( (SELECT * FROM ( SELECT CASE RootId WHEN '' THEN NULL ELSE RootId END FROM Posts WHERE ChannelId = (SELECT ChannelId FROM Channels ORDER BY CreateAt ASC LIMIT 1) AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT 60 OFFSET 0) x ) UNION ( SELECT Id FROM Posts WHERE RootId IN (SELECT * FROM ( SELECT CASE RootId WHEN '' THEN Id ELSE RootId END FROM Posts WHERE ChannelId = (SELECT ChannelId FROM Channels ORDER BY CreateAt ASC LIMIT 1) AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT 60 OFFSET 0) x ))) x ) AND DeleteAt = 0;
```

This should spit out a multi-line query plan that might help pinpoint the issue, if it's related to the query I suspect in 4.9.

**Comment by nagotti** [comment] 2018-04-25 13:30
@lieut-data Alright, I'll test 4.9.1 as soon as it is released and I'll let you know then if it helped. Thanks for the help!

**Comment by nagotti** [comment] 2018-04-29 17:02
@lieut-data I just upgraded to 4.9.1 and I can confirm that it fixed the issue. Channels are loading very fast again.

**Comment by lieut-data** [comment] 2018-04-29 21:36
Thanks, @nagotti! This is a useful data point for our continued investigation :)

**Comment by lindy65** [comment] 2018-05-02 08:40
Thanks @nagotti @lieut-data 

Glad the issue is resolved.

I'll close this issue off here for now...

**Closed by lindy65** 2018-05-02 08:40 UTC
