### ISSUE TITLE
Sending email to an OWA enabled account

### ISSUE THREAD

**Issue by andyinno** [mattermost/mattermost-server#7578] opened 2017-10-05 09:52 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Unable to send email notification with an OWA enabled account.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?) 

version: 4.2.0
I have installed mattermost side by side with gitlab. I am able to send emails from gitlab. I tried to copy the email settings into mattermost also using the web interface but I don't have a way for setting the authentication type.

1) Create a user able to send the email on the SMTP server
2) Set the authentication to "login"
3) configure mattermost with the correct parameters (I don't see an authentication type setting while I can set it in other programs / webapps / email clients)

#### Expected behavior
Describe your issue in detail

I would expect to receive an email from the mattermost application, instead in the logs while testing the connection I receive:

    Failed to authenticate on SMTP server [details: 504 5.7.4 Unrecognized authentication type]

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by lindy65** [comment] 2017-10-06 06:47
Hi @andyinno,

Thanks for your feedback,

Does this documentation for [SMTP settings](https://docs.mattermost.com/install/smtp-email-setup.html) help?

**Comment by lindy65** [comment] 2017-10-11 07:52
Hi @andyinno,

Is your issue resolved?

**Comment by hanyihong0324** [comment] 2017-10-16 12:57
I'm working on installation of version 4.3.0 on a Ubuntu 16.04 VPS with the official doc. I met the same problem when I tried to set up a SMTP server with my hotmail.
Here is the log:

> [2017/10/16 21:41:51 JST] [EROR] /api/v4/email/test:SendMail code=500 rid=e4kf3jyssfgkurettk44urxaqa uid=u1xbbtt4qbgujk4pahbcpprgba ip=36.3.83.5 Failed to authenticate on SMTP server [details: 504 5.7.4 Unrecognized authentication type [OS2PR01CA0102.jpnprd01.prod.outlook.com]]


I think Microsoft Outlook uses OWA, too(Look the browser's address bar when log in to outlook)

**Comment by andyinno** [comment] 2017-10-16 17:06
Hi. Sorry! I completely forgot to reply. In my opinion in the documentation
is missing a way for change the authentication type.
The same setting is present in other programs. Without it it is impossible
to connect. For example in gitlab
https://docs.gitlab.com/omnibus/settings/smtp.html it is present

Il lun 16 ott 2017, 19:00 lindy65 <notifications@github.com> ha scritto:

**Comment by hanyihong0324** [comment] 2017-10-17 03:41
@lindy65 Thank you for your reply. In fact the doc I read is exactly [that document](https://docs.mattermost.com/install/smtp-email-setup.html) you mentioned and I tried two of my hotmail account with the same error received.

**Comment by lindy65** [comment] 2017-10-17 06:58
Thanks @andyinno @hanyihong0324 

I'll ask the team whether they can help troubleshoot further and post back here...

**Comment by jasonblais** [comment] 2017-10-25 13:10
@andyinno @hanyihong0324 Can you share the `EmailSettings` from your GitLab config file? Attached are the recommended settings for GitLab Mattermost when TLS isn't enabled. https://docs.gitlab.com/omnibus/gitlab-mattermost/#setting-up-smtp-for-gitlab-mattermost

```
mattermost['email_enable_sign_in_with_email'] = false
mattermost['email_enable_sign_up_with_email'] = false
mattermost['email_send_email_notifications'] = true
mattermost['email_smtp_auth'] = true
mattermost['email_smtp_username'] = "username"
mattermost['email_smtp_password'] = "password"
mattermost['email_smtp_server'] = "smtp.example.com"
mattermost['email_smtp_port'] = "465"
mattermost['email_connection_security'] = nil
mattermost['email_feedback_name'] = "GitLab Mattermost"
mattermost['email_feedback_email'] = "email@example.com"
mattermost['email_skip_server_certificate_verification'] = false
```

You can of course obfuscate all confidential information. Just want to see how the SMTP settings are configured.

**Comment by hmhealey** [comment] 2017-10-25 13:47
I think the issue is that [we only support PLAIN authentication](https://github.com/mattermost/mattermost-server/blob/master/utils/mail.go#L89), and the Outlook Web App doesn't appear to support that. We'll need to add handling for one of the other login methods like LOGIN.  It won't be trivial since Go doesn't support it by default, but someone posted a [Gist](https://gist.github.com/andelf/5118732) of how to implement it fairly easily. I think it would make a good help wanted ticket if we don't have time to look at it ourselves.

Link about the different authentication types: http://www.samlogic.net/articles/smtp-commands-reference-auth.htm

**Comment by lindy65** [comment] 2017-11-08 17:18
I'll close this issue off here for now and we can track via the ticket linked above.

**Closed by lindy65** 2017-11-08 17:18 UTC
