### ISSUE TITLE
Uploading a text file as an attachment to a channel displays an extra blank trailing line in the preview

### ISSUE THREAD

**Issue by billybrown1** [mattermost/mattermost-server#8266] opened 2018-02-13 13:37 UTC
#### Summary
Uploading a text file as an attachment to a channel displays an extra blank trailing line in the preview

#### Config:
Web browser:
• Google Chrome - MacOS X - Version 63.0.3239.132 (Official Build) (64-bit)

#### Steps to reproduce
1)  Login to https://demo.mattermost.com and go to the Joomla channel, and enter the main public channel, “Channel for bug finding”
2)  Created a simple text file that contains exactly 4 lines, with the filename: test4lines.txt
abcdefg
hijklmn
opqrstu
vwxyz

3)  Upload the file "test4lines.txt" into the Channel for Bugfinding, and Press ENTER key to submit the uploaded text
4)  Now click on the textfile thumbnail graphic to see a preview rendered:
￼<img width="378" alt="screen shot 2018-02-12 at 7 28 30 pm" src="https://user-images.githubusercontent.com/25070389/36152176-4eccb594-1087-11e8-8532-b1bd0e5c12c3.png">
**NOTICE that the test4lines.txt file preview has 5 displayed lines.**
5)  In the preview area click on Download link in order to verify whether or not the file was indeed uploaded correctly (by downloading it back again for comparison)
6)  In Unix (Terminal on MacOS X), use /usr/bin/wc  (word count) utility to display how many lines, words, and characters are in the file
$ wc test4lines.txt
      4       4      30 test4lines.txt
*** PERFECT.  This looks good!  4 lines, 4 ‘words’, and exactly 30 characters.

#### Expected behavior
The PREVIEW image of the text file should not contain any additional blank lines at the end of the file.

#### Observed behavior (that appears unintentional) 
**NOTICE that the test4lines.txt file preview has 5 displayed lines.**
<img width="378" alt="screen shot 2018-02-12 at 7 28 30 pm" src="https://user-images.githubusercontent.com/25070389/36152176-4eccb594-1087-11e8-8532-b1bd0e5c12c3.png">

#### Possible fixes
Don't display the extra 'phantom' carriage return at the end of simple text files during preview

**Comment by lindy65** [comment] 2018-02-14 09:52
Hi @billybrown1 

Thanks for the report :)

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) so I believe it is fixed and ship with v4.7 on Feb 16th.

![image](https://user-images.githubusercontent.com/13020833/36197785-72bd749c-117d-11e8-8c1e-0b7d1ef2acba.png)

**Comment by lindy65** [comment] 2018-02-23 07:59
I'll close this off here for now @billybrown1 as this is fixed in 4.7.2

**Closed by lindy65** 2018-02-23 07:59 UTC
