### ISSUE TITLE
Unable to type Japanese word to search textbox in IE11

### ISSUE THREAD

**Issue by dupont-kedama** [mattermost/mattermost-server#8206] opened 2018-02-06 11:38 UTC
#### Summary
Unable to type Japanese word to search textbox in IE11.

#### Steps to reproduce
1. Open channel, (for example [demo](https://demo.mattermost.com/space-motors/channels/town-square))
2. Input word into search textbox with Microsoft IME HIRAGANA mode.

#### Expected behavior
+ Inputted word is incompletely.
  + ![matter-ie](https://user-images.githubusercontent.com/5292063/35857088-6401799c-0b7b-11e8-8099-e257b5f97fa9.gif)

#### Other detail
+ In GoogleChrome, not reproduce.
  + ![matter-chrome](https://user-images.githubusercontent.com/5292063/35857096-6bbc7e48-0b7b-11e8-929b-40cf4cc6fc31.gif)
+ In IE11 + Microsoft IME ascii mode, not reproduce.
+ Not reproduce in other textbox ( for example Message, Comment, ..)

##### Environment
Windows10 pro
IE11 / chrome63

**Comment by yuya-oc** [comment] 2018-02-06 13:12
Reproduced on the desktop app. I finally got `ｎいｈおｎｇお` when typing `nihongo`.

- Windows 10 Pro
- Mattermost Desktop 4.0.0 (equivalent of Chrome 58)
- pre-release.mattermost.com 4.7.0 (3268)

In recent webapp, I think that `<SuggestionBox>` of search textbox stores its value into Redux store unlike other textboxes. 
When using IME, strings would have "unsettled" state until it's determined. Possibly an unsettled string is stored each time to press keys.

**Comment by CometKim** [comment] 2018-02-06 14:04
@yuya-oc I got `ㅎ` when I typed `한글` in the demo with IE11

![hangul-search-test](https://user-images.githubusercontent.com/9696352/35863462-11397f40-0b92-11e8-9dd5-4cc1256c9792.gif)

**Comment by yuya-oc** [comment] 2018-02-06 15:04
@CometKim It's the first time I saw Korean keyboard though, please let me confirm my understanding. When you want to input `한글`, do you press <kbd>ㅎ</kbd><kbd>ㅏ</kbd><kbd>ㄴ</kbd><kbd>ㄱ</kbd><kbd>ㅡ</kbd><kbd>ㄹ</kbd>, then press <kbd>Enter</kbd> to determine the string?

**Comment by CometKim** [comment] 2018-02-06 15:19
@yuya-oc You exactly understand the basic of Korean characters 👍 
Would it be more helpful if I record once again with the visual keyboard together?

**Comment by yuya-oc** [comment] 2018-02-06 15:53
@CometKim Not needed. Japanese input method is almost same. Pressed alphabets are automatically converted to Hiragana, then press space bar to choose Kanji, finally press Enter to determine it.

I tested IE11 on pre-release. I could input `日本語` as expected.

**Comment by jasonblais** [comment] 2018-02-07 15:54
@lindy65 Maybe we can get Harrison's thoughts tomorrow via the Peer-to-peer channel?

**Comment by hmhealey** [comment] 2018-02-08 17:13
@dupont-kedama @CometKim For IE11, are you still able to reproduce the issue on Mattermost 4.7.0-rc1? pre-release.mattermost.com and demo.mattermost.com have recently been updated to that version, and I'm able to type correctly in both languages on those servers.

@yuya-oc For the desktop app, I am seeing that issue in both the channel switcher and search boxes for both Korean and Japanese. Is there anywhere else in the app that you're seeing it? I can file a ticket for those

**Comment by CometKim** [comment] 2018-02-09 12:17
@hmhealey Looks good to me

**Comment by dupont-kedama** [comment] 2018-02-09 13:00
Thank you all.
@hmhealey Looks good to me, too.

**Comment by yuya-oc** [comment] 2018-02-09 13:24
@hmhealey As long as I tested, search box for View Members of menu has same issue.

I also tested below, but these worked as expected.

- LHS
  - Search box for More Channels
  - Search box for Direct Messages
- Menu
  - Account Settings -> General
  - Send Email Invite
- Search box for Emoji Picker
- Input field to write a new message
- Input field of RHS

**Comment by hmhealey** [comment] 2018-02-14 14:40
Thanks everyone for confirming those.

@yuya-oc I've filed a ticket for those [here](https://mattermost.atlassian.net/browse/MM-9586). It's very strange that it works fine in other browser since usually IE11 has been the one to cause problems here

**Comment by hmhealey** [comment] 2018-02-14 14:40
I'm closing this issue since the reported IE11 problem is fixed

**Closed by hmhealey** 2018-02-14 14:40 UTC
