### ISSUE TITLE
Set SessionId correctly for use with UserHasLoggedIn plugin hook

### ISSUE THREAD

**Issue by freerider7777** [mattermost/mattermost-server#12369] opened 2019-09-25 15:55 UTC
Just a simple plugin like this:

```go
func (p *SamplePlugin) UserHasLoggedIn(c *plugin.Context, user *model.User) {
    fmt.Println("User has logged in, sessionId: ", c.SessionId)
}
```

SessionId is always logged empty so we don't know the device inside the plugin.

**Comment by amyblais** [comment] 2019-09-25 16:12
@freerider7777 Can you help fill in reproduction steps, expected behaviour, and your environment details?

**Comment by freerider7777** [comment] 2019-09-25 16:45
I just make a simple plugin with UserHasLoggedIn hook and I see c.SessionId is empty.
Plugin is like this:
https://github.com/mattermost/mattermost-plugin-demo/blob/9bf345f96788ce93976b4fa16b5113e3cdf6c85b/server/login_hooks.go

In any anvironment (I'm running on Windows but it does not matter)

I would expect that it is filled so that I can get details of the session.

**Comment by amyblais** [comment] 2019-09-25 18:39
What Mattermost server version are you on? Do you see any errors?

**Comment by freerider7777** [comment] 2019-09-25 19:10
Latest from github :) I build it from source. In code it's obviously not filled. But the question is - is it by design or is it a bug?

**Comment by lieut-data** [comment] 2019-09-25 19:20
@freerider7777, yes, this is a bug -- the `session` object isn't set on the `App` instance until after this hook returns.

Thanks for the report!

**Comment by amyblais** [comment] 2019-09-25 20:34
Ticket: https://mattermost.atlassian.net/browse/MM-18871.

**Comment by amyblais** [comment] 2019-09-30 13:28
Closing this as a duplicate of the Help Wanted issue that was opened here: https://github.com/mattermost/mattermost-server/issues/12389.

**Closed by amyblais** 2019-09-30 13:28 UTC
Labels: Bug Report/Open, Difficulty/2:Medium, Hacktoberfest, Help Wanted, Tech/Go, Up For Grabs
