### ISSUE TITLE
mattermost markdown autolinking inconsistencies

### ISSUE THREAD

**Issue by ryantm** [mattermost/mattermost-server#7407] opened 2017-09-07 20:54 UTC
#### Summary
A complete message of `company-uri:invoice/5` auto links correctly. A complete message of `company-uri:invoice/5 blah` auto links correctly. However, a complete message of `blah company-uri:invoice/5` does not auto-link the uri.

#### Steps to reproduce

1. Use Markdown
2. Type in "blah company-uri:invoice/5"
3. click Preview or send the message and look at how it renders

#### Expected behavior
I expect it to turn company-uri:invoice/5 into a link with "company-uri:invoice/5" as the href attribute like it does when "company-uri:invoice/5" is by itself in a message.

#### Observed behavior (that appears unintentional) 
<img width="266" alt="mattermost autolinking" src="https://user-images.githubusercontent.com/4804/30184748-ea672c90-93d3-11e7-8b22-f02963e79ed7.png">

**Comment by lindy65** [comment] 2017-09-08 08:00
Hi @ryantm 

Thank you for your feedback,

Could you share which server version of Mattermost you are using?

There have been some recent improvements to markdown so perhaps upgrading to the [latest version](https://about.mattermost.com/download/) will solve the issue for you.

**Comment by ryantm** [comment] 2017-09-08 14:43
@lindy65 Sure, I am using version 4.1.0, which appears to be the latest version at this time.

**Comment by prixone** [comment] 2017-09-08 16:13
That is reproducible on pre-release as well, it seems to be related to a 3rd party library used for autolinker.

**Comment by hmhealey** [comment] 2017-09-08 16:38
It's reproing on pre-release for me as well, but it doesn't happen on the mobile app, so I'll add it to the list of things the new markdown renderer does that the old one fails at. I'm very much looking forward to replacing it.

I've filed a ticket for the issue [here](https://mattermost.atlassian.net/browse/PLT-7592) if you'd like to track it further. In the mean time, you'll have to use `[this style of link](company-uri:invoice/5)`

**Comment by prixone** [comment] 2017-09-08 16:41
@hmhealey that fails if you have numbers in the first part, I've covered it here https://github.com/mattermost/mattermost-webapp/pull/16 but its not related to the rest of this issue.

**Comment by lindy65** [comment] 2017-09-20 17:31
Thanks @ryantm @hmhealey 

I'll close this issue off for now and we can track via the ticket linked above.

**Closed by lindy65** 2017-09-20 17:31 UTC
