### ISSUE TITLE
"You can add 20 more people" is always showing, never changes even though details are changed in admin console

### ISSUE THREAD

**Issue by ra-uk** [mattermost/mattermost-server#8321] opened 2018-02-18 21:32 UTC
#### Summary
"You can add 20 more people" is always showing, never changes even though details are changed in admin console.

#### Steps to reproduce
Cloudron (can't report issues on Cloudron Github) - 1.8.1

#### Expected behavior
should display number of users allowed corresponding to the set number in admin console

#### Observed behavior (that appears unintentional) 
"You can add 20 more people" goes to 19 after adding new user and clicking 'Add', then going to add another user in a new pop-up, the number returns to 20.

**Comment by lindy65** [comment] 2018-02-19 08:35
Hi @ra-uk,

Thanks for your feedback,

Could you help share which server version of Mattermost is installed and also which modal you're seeing the issue in?

I think it's the "Add members to a team" modal (where I also see the total as 20) but I am not able to reproduce the issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=ekjar11peig45b4t9ufqx7ep7e) running off the latest master.

Could you try to reproduce your issue on the above server and let us know if it reproduces for you?

**Comment by lindy65** [comment] 2018-02-23 07:45
Hi @ra-uk,

Has your issue been resolved by testing on the nightly build server?

[v4.7.2](https://about.mattermost.com/download/) has been released so perhaps you can upgrade and let us know if it still persists once you've tested?

**Comment by lindy65** [comment] 2018-03-06 09:55
Hi @ra-uk,

As we haven't had any feedback from you, I'm assuming your issue is fixed or is no longer a problem so I'll close off this issue for now...

**Closed by lindy65** 2018-03-06 09:55 UTC
