### ISSUE TITLE
Privacy and ToS Links in the about modal ignore the customization settings

### ISSUE THREAD

**Issue by RouL** [mattermost/mattermost-server#16043] opened 2020-10-20 12:09 UTC
#### Summary
Privacy and ToS Links in the about modal ignore the customization settings.

#### Steps to reproduce
Set yout own privacy and tos links in the settings. Reload the page (just to be sure). Open the about modal. Check the links.

#### Expected behavior
The links in the about modal should respect the customization settings.

#### Observed behavior (that appears unintentional) 
Privacy and ToS Links in the about modal ignore the customization settings.

**Comment by amyblais** [comment] 2020-10-20 13:34
Thanks, I'll close this as a duplicate of https://github.com/mattermost/mattermost-server/issues/14531.

A Jira ticket exists here: https://mattermost.atlassian.net/browse/MM-26294.

**Closed by amyblais** 2020-10-20 13:34 UTC
