### ISSUE TITLE
Not all messages show up on all devices

### ISSUE THREAD

**Issue by shochdoerfer** [mattermost/mattermost-server#11603] opened 2019-07-10 09:08 UTC
We upgraded a few days ago to 5.12.2 and have a problem now that sometimes messages do not appear properly on different devices. E.g. messages show up on Mattermost on my mobile phone but not on the Desktop client. Refreshing the Desktop client does not help. For different user different channels are affected and some users also have the problem with alternative clients (e.g. Rambox).

**Comment by amyblais** [comment] 2019-07-10 13:21
Hi @shochdoerfer, would you be open to sharing reproduction steps, environment details, and server log errors?

**Comment by collegenetjacob** [comment] 2019-07-10 16:55
We have this(?) issue all over the place.  Lots of reports of "mattermoist is exploding".  I see it on the web client right now; all the messages in one or more channels since last time I used the web client are missing.  I can see new messages since I came back.  And everything is still there on my phone.  So if you really do need more info, we can probably provide it (but I hear through backchannels the MM team can already reproduce).

**Comment by shochdoerfer** [comment] 2019-07-10 17:07
We have upgraded to 5.12.3 this afternoon and the problem still persists. For me personally things are working fine on mobile (standard Mattermost app, nothing custom), on the web but fails von Rambox. So far just one specific channel is the problem, other channels seem to work fine. Rambox has two options "Clear Cache" & "Clear Local Storage". After using both and logging out & in again, things are working again.

Maybe this is some frontend caching problem and not something on server side?

**Comment by collegenetjacob** [comment] 2019-07-10 17:12
Users report they can refresh by force quitting the phone app or restarting the desktop app, but forced refresh doesn't seem to do it for the web app.  Perhaps it's stored on the server with the user's session.

**Comment by shochdoerfer** [comment] 2019-07-10 17:15
Good catch, yes forcing a refresh did also not work in the web app & in Rambox for me.

**Comment by amyblais** [comment] 2019-07-10 17:42
@shochdoerfer @collegenetjacob Does this describe your issue:

A channels gets marked unread, you switch to that channel, but there are no new messages. After refresh or clearing cache, the new messages in that channel appear.

**Comment by collegenetjacob** [comment] 2019-07-10 17:55
I haven't seen it when a channel is unread (but from reports we've received that's probably true).  I resumed an existing web client session that had not been loaded for some days and all the messages from that time were missing from the channel I had up when I closed the browser.

Shift refreshing the browser window didn't fix it.  Closing and restarting the browser didn't fix it.  Logging out and back in again did (so far).  I think a fresh session has to be created to get back the missing messages.

We've also had other odd reports like notifications not getting sent, but they may just be outliers.  People are more sensitive to everything when they know there's a problem.

**Comment by amyblais** [comment] 2019-07-10 18:00
We are currently investigating this report and it might be related: https://github.com/mattermost/mattermost-server/issues/11079.

**Comment by shochdoerfer** [comment] 2019-07-10 18:14
#11079 is not an issue in our case, the channel is newly created and contains maybe 100 - 200 messages.

The channel also does not get marked unread in my case. It looks like I have read all messages in the channel. Click on it and I can see the messages I read last but not the newer ones. I can't recall if I was just missing the last message or multiple ones.

**Comment by tarabanton** [comment] 2019-07-10 18:25
> @shochdoerfer @collegenetjacob Does this describe your issue:
> 
> A channels gets marked unread, you switch to that channel, but there are no new messages. After refresh or clearing cache, the new messages in that channel appear.

In my case this description also correct. Appears even in PM.

**Comment by collegenetjacob** [comment] 2019-07-10 18:27
We had a user report if you know about a missing message and can find it in search, then jumping to it in the channel via the search results will force the channel to refresh and gain back the missing messages.

**Comment by amyblais** [comment] 2019-07-10 18:39
Are there any log error messages that any of you are seeing?

**Comment by collegenetjacob** [comment] 2019-07-10 18:41
> Are there any log error messages that any of you are seeing?

Nothing at all in ours.  Well, there's tons of the usual stuff but nothing new/unusual.

**Comment by shochdoerfer** [comment] 2019-07-10 18:46
No log error messages here that would point to the source of the problem. That's why I am thinking it might be a frontend issue, maybe some caching problem.

**Comment by collegenetjacob** [comment] 2019-07-10 19:27
I can't say for certain but it seems like having multiple clients logged in at one time might be involved in the problem.  I asked our userbase and nobody who always uses just a single client reported the problem (but the majority case is probably at least two clients).

**Comment by trustedsec** [comment] 2019-07-11 17:36
I've been running into the same thing at our organization.

**Comment by amyblais** [comment] 2019-07-11 17:39
FYI that our devs are currently on top of investigating issues around missing messages.

**Comment by furkanmustafa** [comment] 2019-07-12 02:04
Experiencing same issue. It started happening after upgrading to 5.12.x (we're currently on 5.12.3).

**Comment by shochdoerfer** [comment] 2019-07-12 11:42
@amyblais any progress? Any help needed? Is it possible to downgrade to 5.12.1 from 5.12.3 easily or where there changes made to the database?

**Comment by amyblais** [comment] 2019-07-12 12:36
Our devs are currently on top of investigating issues around missing messages and I have more updates in the next few days. Here are instructions for downgrading: https://docs.mattermost.com/administration/downgrade.html#downgrading-mattermost-server. There were no database changes between 5.12.1 and 5.12.3.

**Comment by amyblais** [comment] 2019-07-12 22:06
Can people help with more information about their environment?

 - OS and version, device, browser
 - Any notable Mattermost configurations (such as HA, Elasticsearch, image proxy, SSO)

**Comment by collegenetjacob** [comment] 2019-07-12 22:20
Reports here are so broad I'm pretty sure it's roughly any client.  I've personally seen it on the web client in Firefox 60.7.0esr on Linux (Debian 9).
Our Mattermost server is not HA, Elasticsearch, image proxy, or SSO.

**Comment by amyblais** [comment] 2019-07-12 22:47
Fixes submitted for v5.13 and master:

 - https://github.com/mattermost/mattermost-server/pull/11618
 - https://github.com/mattermost/mattermost-server/pull/11619

**Comment by shochdoerfer** [comment] 2019-07-13 07:51
Will there also be a fix for the 5.12.x series or will 5.13 come out soonish?

**Comment by arjitc** [comment] 2019-07-13 16:42
@shochdoerfer if I recall correctly a new release comes out on 16th of every month (~3 days)

**Comment by amyblais** [comment] 2019-07-15 17:37
We are also aiming to cut a v5.12.4 dot release for this today (or by tomorrow latest).

**Comment by amyblais** [comment] 2019-07-15 22:58
v5.12.4 is now released and available to download.

**Comment by shochdoerfer** [comment] 2019-07-16 07:08
@amyblais thx! Updating our instance now. Will let you know if the problem still persists. Should I leave the issue open for now?

**Comment by amyblais** [comment] 2019-07-16 22:36
Thank you, we can leave this issue open for now,

**Comment by shochdoerfer** [comment] 2019-07-17 06:35
No issues so far. Seems the problem is solved.

**Comment by amyblais** [comment] 2019-07-17 13:09
Good to hear it, I'll close this issue for now but if anyone still sees the issue after upgrading, please post here and re-open this.

**Closed by amyblais** 2019-07-17 13:09 UTC
Labels: Bug report
