### ISSUE TITLE
"Thumbs up" emoji does not get added to "Recently Used"

### ISSUE THREAD

**Issue by Aninstance** [mattermost/mattermost-server#12368] opened 2019-09-25 12:47 UTC
#### Summary

The "thumbs up" emoji - `:+1:` - does not get added to the 'Recently Used' field, on the web app.

Issue presents on Firefox and Google Chrome browsers (others not tested), on an Kubuntu 18.04 system (other OS's not tested).

**Comment by amyblais** [comment] 2019-09-25 12:57
Hi @Aninstance, what Mattermost server version and desktop app version are you on?

**Comment by Aninstance** [comment] 2019-09-25 13:06
> Hi @Aninstance, what Mattermost server version and desktop app version are you on?

@amyblais Sorry, I meant to write web app, not desktop app. The server is version 5.12.1 (docker).

**Comment by amyblais** [comment] 2019-09-25 18:48
@Aninstance I'm not able to reproduce this, would you be open to testing this on our [community server](https://community.mattermost.com/private-core/channels/alerts) to see if you experience the same issue there. 

Does this only happen with the thumbs up emoji? Are all users on your server seeing this issue?

Upgrading your server to the latest might help fix the issue.

**Comment by Aninstance** [comment] 2019-09-25 20:33
> @Aninstance I'm not able to reproduce this, would you be open to testing this on our [community server](https://community.mattermost.com/private-core/channels/alerts) to see if you experience the same issue there.
> Does this only happen with the thumbs up emoji? Are all users on your server seeing this issue?

@amyblais Hi, yes, no problem; I've just tested on your community server and indeed the same issue does occur there. I've only noticed the issue with the 'thumbs up' emoji. I've tested with a range of others - including 'thumbs down' - and they're all added to the 'Recently Used' list as expected.

**Comment by amyblais** [comment] 2019-09-26 13:16
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18885.

**Comment by Aninstance** [comment] 2019-09-26 13:58
> Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18885.
Thank you.

**Comment by Aninstance** [comment] 2019-09-28 09:38
@amyblais Further to this, I note the 'thumbs up' emoji is not added to the `recent_emojis` array in the browser's Local Storage, so it's an issue with the _adding_ rather than subsequent read. Being that the thumbs up emoji is denoted in the array by `+1`, I wonder if this could be some kind of code type issue (i.e. the 1 is typed as an integer rather than a string at the point at which it's supposed to be added to the array). Only speculation, as haven't yet had chance to dig into the code myself.

**Comment by lieut-data** [comment] 2019-09-30 13:47
Thanks, @Aninstance! I've got a PR up to address this on webapp: https://github.com/mattermost/mattermost-webapp/pull/3798.

**Comment by amyblais** [comment] 2019-09-30 18:08
Closing as this is fixed for v5.16 release which will be released on October 16th,

**Closed by amyblais** 2019-09-30 18:08 UTC
Labels: Bug Report/Open
