### ISSUE TITLE
React Native: Add an expand button to truncated markdown tables to improve discoverability

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11948] opened 2019-08-23 19:44 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14199)

In v5.8 / 1.16, support was added to better support horizontal scroll for wide tables. The right-side of the truncated table is shaded slightly grey but there is no indication that you can open a full-screen view of the table by tapping on it.

This leads to poor discoverability for the end-user as it's not obvious you can tap on the truncated table within a post to view it full-screen.

This ticket is for adding an expand button to truncated tables to improve discoverability, see design: https://projects.invisionapp.com/share/Q6S9HX5R5TJ#/screens/366043352

See Android and iOS screenshot examples in the JIRA ticket of what the table looks like in a post today.

**Comment by avasconcelos114** [comment] 2019-09-09 06:09
Hey!  

I thought I'd give this issue a shot and added the buttons following the design, but ran into a bit of a predicament

![image](https://user-images.githubusercontent.com/29700158/64506780-c1c0fb00-d313-11e9-90fa-3003afe4921d.png)

The button renders and works fine on tables as long as they don't extend to the full width of the channel, where it then gets clipped out (aside from the `moreRight` indicator also extending past the height of the table itself).

It seems like the fix to that would be either:
1. Place the button in the `markdown.js` component instead of `markdown_table.js`. This would hopefully fix issues with styling, but the problem is that the button wouldn't have easy access to the methods that send the user to the full-screen table view

2. Use [design option 2](https://projects.invisionapp.com/share/Q6S9HX5R5TJ#/screens/366043351) where the button would just need to be absolutely positioned inside of the markdown table (although I personally did like design option 1 better)

Let me know what you think the best way forward would be (or if there's anything else you'd like to explore) and I'll do my best to test things out! :)

**Comment by esethna** [comment] 2019-09-16 20:46
@avasconcelos114 we can probably add slightly larger margins on the right of the table so the button doesn't get cut off, if that works? Feel free to submit a PR and we can iterate there if necessary.

**Comment by avasconcelos114** [comment] 2019-09-17 06:06
The margin idea sounds like it could work (or perhaps a padding on the `ScrollView` that wraps the table), but as you mentioned both this PR and the [table responsiveness](https://github.com/mattermost/mattermost-mobile/pull/3249) one involve a few changes to the styling of the same component, which will likely result in a merge conflict.

As far as whether to combine the two PRs or keep them separate, for my perspective it'll take a similar amount of effort to either cherry-pick this commit into that branch, or to rebase whichever PR gets approved last (and then resolve conflicts after doing either thing), so I'll leave it up to you guys to decide what's the best way to manage these two changes moving forward :)

**Comment by avasconcelos114** [comment] 2019-09-19 13:49
I went ahead and submitted a PR just to get some feedback in regarding the implementation of the expand button, after that starts looking merge-ready we can see whether to cherry-pick the commit, or rebase after the other PR gets merged

**Closed** 2019-10-09 01:55 UTC
Labels: Area/End User Feature, Difficulty/2:Medium, Hacktoberfest, Help Wanted, PR Exists, Tech/React Native
