### ISSUE TITLE
Markdown preview in message attachments

### ISSUE THREAD

**Issue by jtama** [mattermost/mattermost-server#7399] opened 2017-09-07 13:31 UTC
#### Summary
Markdown is sometimes displayed as plain text for long attachments preview using chrome ( server version 3.8.2).

#### Steps to reproduce
Post a message with long attachment : 

`curl -i -X POST -d 'payload={"attachments":[{
    "color": "#009edc",
    "text": "## Starting release JOB 1074 \nBuild started by j.tama.\n\n| Module | version  | target env |\n| -------- | -------- | ------------------- |\n| Core  | v2.3.0_27 | recette4|\n| Batch  | v2.3.0_16 | recette4|\n"
}]}' https://domain/hooks/token`

#### Expected behavior
The header table should be correctly displayed.

#### Observed behavior (that appears unintentional) 
Markdown is shown as plain text

![mattermost_diplay_failure](https://user-images.githubusercontent.com/7072126/30165442-60975b90-93e0-11e7-999f-1db4bde382f6.jpeg)

The full attachment is displayed as followed : 

![mattermost_correct_diplay](https://user-images.githubusercontent.com/7072126/30165775-842b098e-93e1-11e7-9ab5-7c7b5992425e.jpeg)

**Comment by lindy65** [comment] 2017-09-08 07:38
Hi @jtama 

Thank you for your feedback,

There have been numerous improvements to markdown in recent releases.  Could you try upgrading to the [latest version](https://about.mattermost.com/download/) to see if the issue is resolved?

**Comment by jtama** [comment] 2017-09-08 08:17
Hi,
The bug can be reproduced using the mattermost/mattermost-preview:latest docker image.

**Comment by prixone** [comment] 2017-09-12 08:59
@jtama have you tried sending it without being as an attachment? it will lose the color bar, but I just wanted to know if the behavior would be the same.

**Comment by jtama** [comment] 2017-09-18 08:48
Hello,
The bug doesn't happen with plain message.

I think it's related to the "Show more\Show less" feature.

**Comment by hmhealey** [comment] 2017-10-04 13:34
Hi @jtama,

Thanks for the report. We talked about it a bit, and we decided that we should change the collapsed version of the attachment text to be cut off using CSS instead of by cutting off the text after 300 characters. There's a Jira ticket for this issue [here](https://mattermost.atlassian.net/browse/PLT-7805) if you'd like to help fix the issue or just track its progress.

**Comment by lindy65** [comment] 2017-10-11 07:46
I'll close this issue off here for now and we can track via the Jira ticket linked above.

**Closed by lindy65** 2017-10-11 07:46 UTC
