### ISSUE TITLE
On page load, username and profile picture for bot accounts aren't initially loaded

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10822] opened 2019-05-10 18:44 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15433)

Repro:

1. Download the latest version of the reminder plugin here (the tar.gz version): https://github.com/scottleedavis/mattermost-plugin-remind/releases
2. Install the binary via System Console > Plugins (Beta)
3. After the plugin has been uploaded, enable the plugin on the same page
4. Switch to a Mattermost team and post "/remind me 5 sec" twice
5. Refresh the page

Observed: Messages posted by a bot account do not display the username and profile picture immediately after a page refresh or channel load. Instead, a blank profile picture and "Someone" username is displayed.
![image](https://user-images.githubusercontent.com/13119842/57550397-408d3380-7334-11e9-8434-d2ef5a9ea83f.png)

Expected: Messages posted by a bot account display username and profile picture immediately, like for user posts.
![image](https://user-images.githubusercontent.com/13119842/57550402-4420ba80-7334-11e9-81d6-53f2ffa15949.png)

Potential fixes: Looking at `imageURLForUser(userIdOrObject) `
On page load for users and webhook bots, a user object object is passed, and is immediately translated into an image route.

For bots, a userId is passed, which at first pass is not found in the store and `Constants.TRANSPARENT_PIXEL` is loaded until which time the store has the bot user, and the image is rendered. (i.e. the dot -> image transition)

For user & webhook username 'Someone' is displayed for one render cycle before switching to the correct username. For bots it is two, which produces the noticeable shift.

**Comment by sapnasivakumar** [comment] 2019-05-13 12:26
@jasonblais I would like to work on this ticket, Can you please assign the same to me

**Comment by jasonblais** [comment] 2019-05-13 12:28
Thank you @sapnasivakumar! Removed `up for grabs` label. If any questions, don't hesitate to ask

**Comment by jasonblais** [comment] 2019-05-19 23:16
Hey @sapnasivakumar, just touching base to see if you have any questions so far :)

**Comment by sapnasivakumar** [comment] 2019-05-20 20:25
@jasonblais I'll get in touch in a couple of days with any questions I have on this

**Comment by jasonblais** [comment] 2019-06-09 02:38
Hey @sapnasivakumar, just touching base to hear how things are going :)

**Comment by sapnasivakumar** [comment] 2019-06-10 22:41
@jasonblais I'm working on it and will let you know soon

**Comment by sapnasivakumar** [comment] 2019-06-12 20:30
Waiting on https://github.com/scottleedavis/mattermost-plugin-remind/issues/115 to resume working on this issue

**Comment by jasonblais** [comment] 2019-06-12 23:05
@hanzei wondering if we have a binary for the Demo Plugin with bot accounts we can share with @sapnasivakumar so that she can continue on this ticket?

**Comment by hanzei** [comment] 2019-06-13 10:31
Surely @jasonblais

@sapnasivakumar Send you a DM. It's the latest build from `master`.

**Comment by jasonblais** [comment] 2019-07-16 13:25
Hey @sapnasivakumar, let us know if you have any questions, and whether the Demo plugin helped you to move forward on this issue :)

**Comment by hanzei** [comment] 2019-09-11 11:43
Making this one available for the public again due to inactivity.

**Comment by larkox** [comment] 2019-11-29 13:54
May I take this one?

**Comment by jasonblais** [comment] 2019-11-29 14:05
Certainly, thanks @larkox!

**Comment by larkox** [comment] 2019-11-29 14:23
Thanks @jasonblais . Is there any chance this is already solved? I am not able to reproduce the error by following the steps.

**Comment by jasonblais** [comment] 2019-11-29 14:38
@larkox It does seem fixed. I'll close the issue and ask QA to verify while closing the related Jira ticket. Thanks for looking into it!

**Closed by jasonblais** 2019-11-29 14:38 UTC
Labels: Area/Bot Accounts, Difficulty/2:Medium, Help Wanted, Tech/ReactJS
