### ISSUE TITLE
Account Settings: Responsiveness of Account Settings popup is broken when expanding browser window from Narrow view

### ISSUE THREAD

**Issue by mattrampolla** [mattermost/mattermost-server#8285] opened 2018-02-13 22:04 UTC
#### Summary
When expanding a browser window, with the Account Settings popup menu in the compacted/responsive state, the display of the window is broken.  It only breaks after selecting a main tab/group, and then going back to the main Account Settings page, then expanding the browser size. (See attached gifs)

#### Steps to reproduce

1. Login to Mattermost Version: 4.7.0 (4.7.0-rc2)
2. Select Main Menu (hamburger menu)
3. Select Account Settings
5. Shrink browser window (horizontally) until Account Settings popup menu becomes responsive and compacts to only the main Account Settings list items (General, Security, Notifications, Display, Sidebar, Advanced)
4. Select General
5. Select back arrow (top left of popup menu), to return to Account Settings list
6. Expand browser window (manually dragging, double clicking window to expand, or expanding to full screen)

#### Expected behavior
Expanding a browser should return the Account Settings popup menu to the two column view, with everything just as visible as if the window had been large enough for the two column display the entire time.

#### Observed behavior
Expanding a browser, after navigating to General and then back to the main Account Settings list breaks the popup menu's display, until menu item (tab/group) is selected.

![2018-02-13_17-02-18](https://user-images.githubusercontent.com/17954664/36176198-d1ce0e68-10df-11e8-9aaa-289be355beb7.gif)

**Comment by lindy65** [comment] 2018-02-23 07:56
Hi @mattrampolla 

I believe this issue has been fixed in [v4.7.2](https://about.mattermost.com/download/) which shipped yesterday.  Perhaps you can check if it still reproduces for you on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676)?

**Comment by mattrampolla** [comment] 2018-02-23 17:03
@lindy65 I just tested and still am able to reproduce on https://pre-release.mattermost.com in both Chrome (Version 63.0.3239.132) and Firefox (52.0).

**Comment by lindy65** [comment] 2018-02-23 18:34
Hey @mattrampolla 

Sorry, I believe the nightly build server will be updated to the latest version today.

**Comment by mattrampolla** [comment] 2018-02-24 19:01
@lindy65 I'll check back when the build is updated.  I'm still seeing 4.7.1

**Comment by lindalumitchell** [comment] 2018-03-06 01:40
@mattrampolla @lindy65 I'm still seeing this on pre-release, which is now on 4.8.0-rc1, so I filed a ticket for it: https://mattermost.atlassian.net/browse/MM-9732. I'll close this issue and we can track the issue in JIRA. Because of our compressed schedule for the 4.8 release (due to Mattermost team traveling for the Meetup last week), a fix may need to wait for 4.9 at this point, but we'll assess and note it on the ticket. Thanks for the issue report!

**Closed by lindalumitchell** 2018-03-06 01:40 UTC

**Comment by lindy65** [comment] 2018-03-06 06:31
Hey @mattrampolla @lindalumitchell 

Thanks for the issue report and for filing a ticket.  Agree we can track via Jira 👍
