### ISSUE TITLE
Emoji in link URL

### ISSUE THREAD

**Issue by adamalexandru4** [mattermost/mattermost-server#23346] opened 2023-05-08 20:40 UTC
#### Summary
URL link can't be escaped to avoid emojis

#### Steps to reproduce
`[URL](https://link/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-08T12:06:38.609846Z',to:now))&_a=(columns:!(appName,'@timestamp',traceId,METHOD,PATH,USERNAME,message,stack_trace),filters:!(),grid:(columns:('@timestamp':(width:125),IP:(width:178),METHOD:(width:88),PATH:(width:184),USERNAME:(width:282),appName:(width:168),traceId:(width:88))),index:'1d3b7fdf-2f03-4545-9f5f-b76cba0207cc',interval:auto,query:(language:lucene,query:'6458e5ce5868d05a69c29b2eb688ffb2'),rowHeight:7,sort:!(!('@timestamp',desc))))`

#### Expected behavior
I tried to escape the entire link to avoid emojis but I couldn't find any pattern for this issue.

**Comment by amyblais** [comment] 2023-05-08 22:20
Closing as a duplicate of https://github.com/mattermost/mattermost-server/issues/20543, which includes details on workarounds.

**Closed by amyblais** 2023-05-08 22:20 UTC
