### ISSUE TITLE
Using Amazon S3 consistently leads to server crash

### ISSUE THREAD

**Issue by thieraufc** [mattermost/mattermost-server#9078] opened 2018-07-09 19:00 UTC
#### Summary
Using Amazon S3 Buckets, authenticated using the "Access Key ID" and "Secret Access Key", consistently crashes the server whenever files are uploaded.

#### Steps to reproduce
Running Mattermost version 5.0 on Red Hat Enterprise Linux. The Amazon S3 Access Key ID and Secret Access Key were filled out using the appropriate keys for the bucket. When accessing the server from the web client\*, the team view loads the basic javascript before the server crashes while loading the actual content.

Changing the file storage type to local and restarting allows the server to be started normally. The storage type can then be changed back to `amazons3`. When this is done, the server behaves normally, but attempting to upload any file (either using the file uploader or by changing profile image, custom emoji, etc) crashes the server. 

_\* Tested with Firefox on Debian GNU/Linux and Chrome on Windows, and the desktop client for each._

#### Expected behavior
To upload a file and have it be stored with Amazon S3.

#### Observed behavior (that appears unintentional) 
SSH'ing into the server and running `systemctl status mattermost` shows that the server is running and behaving properly before attempting to upload an image, but is not after file upload. Running the server directly from the command line (by running `./mattermost`) and observing the output with debug level logging shows everything behaving normally, then crashing when a file is uploaded. The error  `fatal error: runtime: out of memory` appears.

There is plenty of file space available, and `top` from the command line showed that %CPU and %MEM were reasonable even when many messages were being passed, as well as when the file was being uploaded. The "Test Connection" button also shows that the bucket can be reached.

To test further, I intentionally inserted incorrect values for my access keys. In this situation, everything behaves normally except files. No images load and attempting to upload files gives the message "Encountered an error writing to S3" to the user. The server does not crash. 

#### Possible fixes
From playing with this issue it looks like the issue is with how Mattermost is interacting with S3. It's possible to run Mattermost without a connection to S3, so error handling instead of a crash seems more desirable. Loading from local memory before attempting to reach out to other services might also be worth considering for robustness. In addition, the "Test Connection" button checks that the bucket exists, but it could be made more useful by checking to see that it can read/write to the S3 bucket.

**Comment by amyblais** [comment] 2018-07-09 23:45
Hi @thieraufc! Thank you for reporting this 👍 

Can you help check if this Jira ticket describes the issue you are seeing: https://mattermost.atlassian.net/browse/MM-10677?

**Comment by thieraufc** [comment] 2018-07-10 14:31
Happy to help out!

Looking into that link, I'm not sure it's the same error. I have enough memory that I think a 512MiB buffer should be fine (1GB available, it's idling at about a percent usage with mattermost running) and I didn't notice a memory spike in `top`. The linked error also aims for an optimization, while I'm experiencing total server failure. 

That said, it could be the same error if the uploading of files actually consumes closer to double that amount very quickly (leading to a crash too quick for `top` to notice), and/or if the word "optimization" is more of an understatement.

**Comment by amyblais** [comment] 2018-07-11 23:00
Hi @thieraufc! I'll ask our engineers about this. Would you also be able to share any debug logs from around the time the issue occurs?

**Comment by amyblais** [comment] 2018-07-12 16:45
Hi @thieraufc - I checked with the team and the issue is most likely related to running out of memory space when initiating a file upload. Some users have had success in mitigating this by adding a swap file. This will slow file uploads considerably, but will prevent the system from running out of memory when too many files are uploaded.

These are next steps to improve this:
https://github.com/mattermost/mattermost-server/issues/8838
https://github.com/mattermost/mattermost-server/issues/8641
https://github.com/mattermost/mattermost-server/issues/8718

**Comment by amyblais** [comment] 2018-07-26 18:59
Hi @thieraufc, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by admiralobvious** [comment] 2018-07-26 19:19
@amyblais Why would this be fixed or no longer valid when the three issues you linked are not closed? Specifically this [one](https://github.com/mattermost/mattermost-server/issues/8838) and the JIRA [issue](https://mattermost.atlassian.net/browse/MM-10677) which is still unresolved as well.

I confirm this is still happening on 5.1.0.

**Comment by zetaab** [comment] 2018-09-10 17:41
#9373 merged, so this is solved

**Comment by amyblais** [comment] 2018-09-12 13:06
https://mattermost.atlassian.net/browse/MM-10677 has been resolved and tested internally and the fix will be available in v5.3 (which will be released on Sept 14th). It should provide a fix for this issue - please let us know if you still experience the issue after upgrading.

**Closed by amyblais** 2018-09-12 13:06 UTC
