### ISSUE TITLE
[Desktop] time interpreted as emoji

### ISSUE THREAD

**Issue by jacksga** [mattermost/mattermost-server#8383] opened 2018-02-28 13:38 UTC
#### Summary
Since upgrading from 4.6.0 to 4.7.2 time values in fields of incoming webhooks are interpreted as emojis, therefor not displayed correctly on WebUI. Not an issue on my mobile (android, react app).

mattermost version: 4.7.1 (4.7.2)
build date: Fri Feb 23 01:08:46 UTC 2018
database: mysql

#### Steps to reproduce

1. Send the following json to an incoming webhook
``` json
{
   "attachments":[
      {
         "color":"Gut",
         "fields":[
            {
               "title":"Angefordert von",
               "value":"SomeUser",
               "short":true
            },
            {
               "title":"Dauer",
               "value":"00:19:10",
               "short":true
            },
            {
               "title":"Builddefinition",
               "value":"Main",
               "short":true
            }
         ],
         "pretext":"Build \"<https://tfs.someuri.com|Main123456789>\" war erfolgreich",
         "mrkdwn_in":[
            "pretext"
         ],
         "fallback":"Build \"Main123456789\" war erfolgreich"
      }
   ]
}
```
2. Check the channel the message was send to.

#### Expected behavior
00:19:10 is shown as 00:19:10
![webhookresult_expected](https://user-images.githubusercontent.com/7153221/36790245-7a3882ee-1c94-11e8-94d8-83ae34a0ef13.png)

#### Observed behavior (that appears unintentional) 
The `:19:` of 00:19:10 is interpreted as an emoji
![webhookresult](https://user-images.githubusercontent.com/7153221/36790192-55a05da8-1c94-11e8-8cea-feeb35013387.png)

**Comment by koxen** [comment] 2018-03-01 01:45
this is caused by one of the patches that makes emoji loading async

**Comment by lindy65** [comment] 2018-03-05 09:24
Thanks @jacksga @koxen 

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9722) to investigate the issue...

**Comment by lindy65** [comment] 2018-03-07 08:31
I'll close this issue off here for now and we can track via the ticket linked above :)

**Closed by lindy65** 2018-03-07 08:31 UTC
