### ISSUE TITLE
[Help Wanted] [PLT-6519] Invalid prop type warning from RHS date separator

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6386] opened 2017-05-10 17:40 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6519)

Repro steps:
1) Run a developer build (ie using the Makefile)
2) Click the reply button next to a post

![image](https://cloud.githubusercontent.com/assets/13119842/25915833/b4d9c548-3590-11e7-85a8-3a2043bc6802.png)

**Comment by cpanato** [comment] 2017-05-11 11:40
I tried that in the current master and was not able to reproduce the issue.

Test cases:
1:
 - make a post with user A
 - reply that post with user A

2: 
 - Reply the post from user A but with user B

none in those cases I got that warning.

**Comment by jasonblais** [comment] 2017-05-11 12:05
@hmhealey Is the step for running a developer build necessary to reproduce the issue?

**Comment by hmhealey** [comment] 2017-05-11 12:44
Yes, it is. The warning isn't displayed if you're using a compiled version like on pre-release.

**Comment by cpanato** [comment] 2017-05-11 12:45
but need to be a reply in a post from other day? Or can I create a post and reply that ?

**Comment by hmhealey** [comment] 2017-05-11 13:15
You may need to make a post on one day and then reply to it on another (or even change your server clock to fake that). I'm not sure which DateSeparator causes it to appear. Even if you can't repro it, the problem DateSeparator is probably in the RhsThread component or its children.

Alternatively, you could just change the prop type that's being reported in the warning. It seems to work fine anyway

**Comment by cpanato** [comment] 2017-05-15 09:45
I was not able to reproduce that.

**Comment by jasonblais** [comment] 2017-12-13 13:19
Cannot reproduce anymore, closing

**Closed by jasonblais** 2017-12-13 13:19 UTC
Labels: Difficulty: Introductory, ReactJS
