### ISSUE TITLE
Using Tab in Autocomplete posts as e.g. `@n@aanick` then breaks and is fixed only after refresh

### ISSUE THREAD

**Issue by RalfJung** [mattermost/mattermost-server#7936] opened 2017-12-04 14:32 UTC
#### Summary
Mattermost's tab completion for @something frequently breaks and is only fixed by hitting F5.

#### Steps to reproduce

We are using the mattermost integrated with GitLab; the version information says `Version: 4.2.0  (4.2.1)` which I cannot interpret (4.2.0 or 4.2.1, what now?).

Steps to trigger:
* Say you want to type @nickname, so start by typing `@` `n` and then quickly hit Tab while/before the menu showing the available nicknames opens.

#### Expected behavior
If there is just one nickname starting with `n`, it should auto-complete. Otherwise it should either do nothing (and keep the menu open), or autocomplete to one of the nicknames starting with `n` (and keep the menu open), or only fill in the common prefix of all nicknames starting with `n` (and keep the menu open).

#### Observed behavior (that appears unintentional) 

It inserts the alphabetically first nickname into the text field. So I end up with `@n@aanick`. Moreover, tab-completion is now broken: Hitting `@` again does not open any menu. I have to hit F5 to get it to work again.

This is not 100% reproducible, there seems to be a race condition. But I am hitting this several times a day.

I am using Firefox 58b8.

**Comment by arjitc** [comment] 2017-12-04 20:35
We're having a lot of this as well, especially when trying to quickly @ mention/tag a user and the auto-complete just breaks until a reload of the application/F5 in browser.

**Comment by lindy65** [comment] 2017-12-05 10:47
Hi @RalfJung @arjitc 

Thanks for your feedback,

There have been many improvements and fixes with autocomplete since v4.2 and we suggest upgrading to the [latest version](https://about.mattermost.com/download/) 

Let us know if this resolves the issue for you.

**Comment by arjitc** [comment] 2017-12-05 10:56
@lindy65 I'm running Version: 4.4.0 (4.4.1) here and still have this issue :(

![image](https://user-images.githubusercontent.com/363587/33603603-1049bea0-d9d9-11e7-891e-0c9cc68846ee.png)

**Comment by RalfJung** [comment] 2017-12-05 11:31
> There have been many improvements and fixes with autocomplete since v4.2 and we suggest upgrading to the latest version

Unfortunately we have to wait until GitLab ships that update. :/

**Comment by lalmeras** [comment] 2017-12-05 12:35
Same here with a post 4.2 (Version: 4.3.0  (4.3.2) shipped with gitlab).

If I use Firefox developer tool, I can see that requests are done (/api/v4/users/autocomplete?in_team=pedkjhdi8pyajb41r6u1sws6ky&in_channel=hm1x5855kidtt8q37tdqrpzrzw&name=jben) and seem correct.
Response code is 200, and there is a correct JSON content: a field users, with a list with expected results.

```json
{"users":[{"id":"xxx","create_at":1510399359233,"update_at":1510439231301,"delete_at":0,"username":"xxx","auth_data":"","auth_service":"gitlab","email":"xxx@xxx.xxx","nickname":"","first_name":"xxx","last_name":"xxx","position":"","roles":"system_user","locale":"en"}]}
```
Private data replaced by xxx.

Domain name used for request is consistent with mattermost domain, and there is no warning in console view, so this is not a problem related to cross-domain.

So this is a front-end failure.

If I reload my mattermost page, complete works again for some time.

If there is a way to activate verbose logging in Firefox console, I can provide more logs.

Thanks.

**Comment by lindy65** [comment] 2017-12-06 06:06
Hi @RalfJung @arjitc @lalmeras 

Testing this on our nightly build server, I see the autocomplete appears only after typing the second character e.g. `@na`.  I'm not sure whether this is by design but I'll ask our team and post their feedback here.

**Comment by lindy65** [comment] 2017-12-11 06:17
Hi @RalfJung @arjitc @lalmeras 

I've created a [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8306) to track the issue.

**Comment by lindy65** [comment] 2017-12-13 08:16
I'll close this issue off here and we can track via the Jira ticket linked above.

**Closed by lindy65** 2017-12-13 08:16 UTC
