### ISSUE TITLE
[Help Wanted] [PLT-7459] Users restricted from inviting other users to private channel should not see invite link in-channel

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7316] opened 2017-08-29 16:23 UTC
@If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7459)

If a user isn't allowed to invite other users to a private channel, they can still scroll to the top of the channel and click the link "Invite others to this private channel." Then they can select a user to invite, but end up just seeing an error saying they don't have permission. The link should be hidden.

1. Set System Console > General > Policy > Enable managing of private channel members for: to System Admins
2. Log in as non-admin and scroll to the top of a private channel (or create a new one)

Observed: "Invite others to this private channel" link appears above the first message in the channel, and non-admin can go through invite process until error displays

Expected: In private channels, "Invite others to this private channel" link is hidden on any account restricted from managing members of a private channel

**Comment by jboxman** [comment] 2017-08-30 04:33
I'd like to try tackling this.

**Comment by jasonblais** [comment] 2017-08-30 12:48
Thank you @jboxman! Please let us know if you have any questions.

**Comment by jasonblais** [comment] 2017-11-01 18:35
@jboxman Let us know if you have any questions on this one?

**Comment by jboxman** [comment] 2017-11-03 21:57
Hi! I actually started a new job recently. This got lost in the shuffle.

**Comment by jasonblais** [comment] 2017-11-03 23:15
Ah, no worries @jboxman. If you're interested and have time to work on this or another ticket, don't hesitate to reach out :)

**Comment by jasonblais** [comment] 2017-11-03 23:15
And congrats on your new job @jboxman!

**Comment by maarsej** [comment] 2018-04-20 16:25
I just followed up to look at this Jira ticket and it says the issue is closed, am I correct? Perhaps this wasnt updated here. If this is correct I am looking for other introductory ReactJS issues to solve

**Comment by jasonblais** [comment] 2018-04-20 16:30
Sorry about that, it's indeed resolved. I'll close this issue.

[List of other open introductory ReactJS tickets here](https://github.com/mattermost/mattermost-server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22Difficulty%3A+Introductory%22++label%3AReactJS++label%3A%22Up+For+Grabs%22). If nothing catches your attention, let me know as we might have other ones not yet posted in GitHub.

**Comment by jasonblais** [comment] 2018-04-20 16:31
Really appreciate your interest contributing :)

**Closed by jasonblais** 2018-04-20 16:31 UTC
Labels: Difficulty: Introductory, ReactJS
