### ISSUE TITLE
New channel cannot be created without js error (blank page is displayed)

### ISSUE THREAD

**Issue by useitfortest** [mattermost/mattermost-server#8052] opened 2018-01-06 15:03 UTC
#### Summary
After creating a new channel blank page is displayed

#### Steps to reproduce
1. Login to https://oss.mattermost.com
2. Add a new public/private channel (fill out all fields in the 'New Channel' modal)
3. Click 'Create New Channel' in the modal

#### Expected behavior
New channel will be created & opened

#### Observed behavior (that appears unintentional) 
Blank page is displayed, after refreshing the page correct channel is displayed. 

#### Possible fixes
Browser console contains the following errors (fix should be done in accordance with error stack):
![2018-01-06 17 54 47](https://user-images.githubusercontent.com/35164265/34640829-64d63674-f30b-11e7-8518-f3f07da1424c.png)

#### Environment
OS: Intel Mac OS X 10_11_5
Browser: Safari/9.1.1

**Comment by lindy65** [comment] 2018-01-08 10:39
Hi @useitfortest,

Thanks for your feedback,

I'm not able to reproduce your issue on Windows but will check with someone on the team who has a Mac with Safari.

**Comment by lfbrock** [comment] 2018-01-08 17:30
Thanks @useitfortest, we reproduced the issue and have a ticket filed here to fix it: https://mattermost.atlassian.net/browse/PLT-8510

**Comment by lindy65** [comment] 2018-01-09 19:50
I'll close this issue off for now and we can track via the ticket linked above.

**Closed by lindy65** 2018-01-09 19:50 UTC
