### ISSUE TITLE
Image Proxy configuration does not save to config.json.

### ISSUE THREAD

**Issue by dschaper** [mattermost/mattermost-server#9014] opened 2018-06-27 04:42 UTC
#### Summary
Unable to save image proxy configuration.

#### Steps to reproduce
Mattermost Server version 5.0. Using S3 Storage back end.

Open System Console, under Files select Atmos/Camo for proxy. Configure URL and secret HMAC key. Click save. Configuration immediately reverts back to unselected. Checking config.json shows 3 empty lines added to ServiceSettings. No changes made to  FileSettings. 

Attempted to set up proxy with Local Storage and issue is replicated. The Atmos/Camo instance is running and returns `hwhat` response as expected for ping.

#### Expected behavior
Following the Image Proxy configuration as per documentation should enable the proxy.

#### Observed behavior (that appears unintentional) 
Configuration was not able to be saved. Immediately reverts to unconfigured state upon saving.

**Comment by amyblais** [comment] 2018-06-27 15:31
Hi @dschaper! Thank you for reporting this!

As a first step, can you help confirm if you have followed all steps and links in our image proxy docs: https://docs.mattermost.com/administration/image-proxy.html?

Can you also help check logs and Console if you see any errors while you reproduce the issue?

**Comment by dschaper** [comment] 2018-06-27 16:02
Yes, I've followed the steps in the linked guide on two installations, one with S3 backing, and one without. I've tail'd the logfiles while making the changes and nothing has come up. I've also tried to manually populate the key/value pairs in the empty 'ImageProxy' config lines and that does not solve the problem either.

**Comment by amyblais** [comment] 2018-06-27 17:30
Hi @dschaper! I tested this and was able to repro. I opened a ticket here for our engineers to address: https://mattermost.atlassian.net/browse/MM-11081.

I don't know if there are known issues around this or known reasons why it doesn't work, but I'll know more details tomorrow.

**Comment by ThiefMaster** [comment] 2018-06-27 21:11
I fixed this in mattermost/mattermost-webapp#1349 a few days ago

**Comment by amyblais** [comment] 2018-06-27 21:44
Awesome @ThiefMaster! 👍 

@dschaper Looks like this will be fixed in v5.1!

**Comment by amyblais** [comment] 2018-07-04 13:34
Hi @dschaper! Since the PR to fix this issue has been merged and it will be available in 5.1, I'll close this Issue for now.

5.1 will be released in July 16.

If you encounter the bug after upgrading to 5.1, please reopen this Issue.

**Closed by amyblais** 2018-07-04 13:34 UTC
