### ISSUE TITLE
[Help Wanted] [MM-12396] Option to add user to a channel from the profile pop-over

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9501] opened 2018-09-28 21:45 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12396)

This is an added option to the profile pop-over to add another user to a different channel.

Invision screens: https://invis.io/DYNZR9J64A9

Notes: 

- Only the users who have permissions to manage channel members will be able to see this option.

    - If the user has manage channel member permissions for public OR private channels, show the option in the profile pop-over
    - If the user has only manage channel member permissions for public channels, then show the option in the profile pop-over and only show public channels in the channel dropdown.
    - If the user has only manage channel member permissions for private channels, then show the option in the profile pop-over and only show private channels in the channel dropdown.

- Users can only add other users to channels they already belong to. (The list shows only the channels the user is in).
- If a user tries to add a person to a channel he is already in, there is an error as soon as he selects that channel from the list.
- After a user adds someone to a channel, a system message of the user being added to that channel is posted in the channel in which he was added in.
- The user who is doing the adding is returned to his previous state after clicking “Add” and the modal closes.

**Comment by mickmister** [comment] 2018-10-08 15:29
I'd like to work on this. I couldn't find a modal that already does this action, so I've taken some time looking at how modals are spawned and how their state is maintained, as well as how some modals may be re-used for slightly different purposes. I'll be asking questions on some of these details on the dev chat as I continue to work on the feature.

As far as the feature is concerned, is this something that will be included in the mobile app as well?

**Comment by mickmister** [comment] 2018-10-08 16:40
In the Invision design included above, the channel picker is a drop down select box. All channel pickers I've seen in the app have been standard text boxes that show results below in a drop down fashion as the user types. I think that same functionality would be re-used in this case, but I wanted to clarify since the design shows a different component being used for the selection.

**Comment by jasonblais** [comment] 2018-10-09 11:50
Thanks @mickmister! Good questions. @esethna / @asaadmahmood would you be able to help with the above?

**Comment by esethna** [comment] 2018-10-09 17:53
Yes thanks @mickmister, makes sense, we can use a similar component as used in the channel switcher. However the difference being the user doing the adding should have to click "Add" in the modal. Where as the channel switcher disappears as soon as you select a channel from the list.

**Comment by hanzei** [comment] 2018-12-17 07:39
Fixed with https://github.com/mattermost/mattermost-webapp/pull/1918

**Comment by hanzei** [comment] 2019-02-14 12:30
Reopened, as https://github.com/mattermost/mattermost-webapp/pull/1918 got reverted. @mickmister is still on a new PR.

**Comment by mickmister** [comment] 2019-02-19 15:35
@hanzei I am unable to reproduce the issues laid out in the [Jira ticket](https://mattermost.atlassian.net/browse/MM-12396) comments. I've followed up on the ticket accordingly, asking for further explanation of how to reproduce.

**Comment by hanzei** [comment] 2019-02-20 07:19
Hey @mickmister, thanks for keeping track of this! 

@lindy65 could you please share some details on what exactly the permission issue is and how to repo it?

**Comment by lindy65** [comment] 2019-02-20 07:28
Thanks @hanzei @mickmister 

I am going to retest this feature on `master` and will comment in the Jira ticket in response to `@mickmister's` questions/comments.

**Comment by jespino** [comment] 2019-04-25 08:56
Fixed by #2435 and #806

**Closed by jespino** 2019-04-25 08:56 UTC
Labels: Difficulty: Intermediate, Go, ReactJS
