### ISSUE TITLE
Italic style markdown should not be applied to text with *asterisks* before and after them

### ISSUE THREAD

**Issue by billybrown1** [mattermost/mattermost-server#8264] opened 2018-02-13 13:16 UTC
#### Summary
As per the Help document - Italic style markdown should not be applied to text with *asterisks* before and after them

#### Config:
Web browser:
• Google Chrome - MacOS X - Version 63.0.3239.132 (Official Build) (64-bit)

#### Steps to reproduce
1)  Login to https://demo.mattermost.com.  Then go to the Joomla channel.  
2)  Enter the main public channel, “Channel for bug finding”
3)  Enter the following line of text exactly as shown into the "Write a message..." field
This _italic_ and this is an *example* of markdown with just a single asterisk before and after example.

4)  Press the RETURN (or ENTER) key to submit the line of text
5)  The formatted text is then displayed:  Both the word "italic" and the word "example" are shown in italics.

#### Expected behavior
Any word(s) having an asterisk both before and after it should not invoke any stylistic markdown.

#### Observed behavior (that appears unintentional) 
When a line of text in a channel is submitted, if word(s) have an asterisk both before and after it (such as *asterisk*) it should not trigger a markdown but rather simply be passed-through and displayed as *asterisk*, with no style parsing applied to the word "asterisk".

https://demo.mattermost.com/help/messaging
![messagestable1](https://user-images.githubusercontent.com/25070389/36151985-a3854fb6-1086-11e8-8751-50fff2ebb3b5.png)

**EXAMPLE**
![assterisks before and after a word behaves same as italic markdown](https://user-images.githubusercontent.com/25070389/36151653-5515e526-1085-11e8-8ca8-fba4232e37da.jpg)

#### Possible fixes
The markdown formatting in the channel should simply ignore and not also display in italics word(s) with asterisks before and after them.

**Comment by hmhealey** [comment] 2018-02-13 14:14
Hi @billybrown1,

Perhaps our documentation could be clearer, but it's intended that you can italicize text by surrounding it with either a single asterisk or underscore and that you can bold text with two of either of those. For example, we use the same Markdown version as GitHub and here
```
*apple* **banana** _orange_ __pineapple__
```
renders as 

*apple* **banana** _orange_ __pineapple__

If you're wanting to show the asterisks in your text you could escape them with a backslash like `\*this\*` which renders as \*this\*.

**Comment by billybrown1** [comment] 2018-02-13 14:20
Thanks Harrison, so good to get your feedback.

Yes… I too noticed while writing up the bug, that GitHub itself follows the same paradigm of *asterisk* and _italic_ both result in italics.

However, as you noticed and I agree, perhaps the documentation could be clearer.  I was going strictly on the examples provided by the HELP link for the mattermost-server ( https://demo.mattermost.com/help/messaging <https://demo.mattermost.com/help/messaging> ).

Thanks again for your thoughts and input.

—
Billy Brown

**Comment by billybrown1** [comment] 2018-02-13 16:05
Upon reflection, this bug could be actually be re-titled that the Help documentation could be improved with an example showing examples of how both _ and * around word(s) could be used for italics.

**Comment by lindy65** [comment] 2018-02-14 09:54
Thanks @billybrown1 

Would you be interested in submitting a pull request to update the documentation?

**Comment by billybrown1** [comment] 2018-02-14 10:44
Hi lindy65,
Sure, how do I initiate that?  I only just recently discovered mattermost (while submitting my resume for the QA Engineering position) and would want to do it right.  
--
BillyB

**Comment by lindy65** [comment] 2018-02-14 10:55
Hi @billybrown1,

If you go to the document that needs updating in docs.mattermost.com you'll see an "edit" button at the top right of the page and you can edit and submit a pull request to the docs report directly from there.

You'll also need to sign the CLA form in order for your pull request to be considered. (all contributors need to sign this form).

I'm on my phone at the moment so can't link you to the form but you should find it on the "Contribute" page of about.mattermost.com

Hope this helps and good luck with your application! Your issue reports are detailed and contain everything we need to try to reproduce on our end so that's a great start! 😀

**Comment by lindy65** [comment] 2018-02-15 08:49
Hi @billybrown1 

Here is the [CLA form](https://www.mattermost.org/mattermost-contributor-agreement/) you'll need to complete in order to submit a PR :)

**Comment by billybrown1** [comment] 2018-02-15 09:18
Hi Lindy65, OK great.  I’ll jump in and do it!

—
BillyB

**Comment by lindy65** [comment] 2018-02-15 19:53
Sounds good! Thanks @billybrown1 😀

**Comment by billybrown1** [comment] 2018-02-15 19:56
@lindy65 
So take a look and see if I did this right...  I wanted to close the Pull Request, but it appeared there was still a Travis CI build in progress, and "Some checks haven’t completed yet.  1 pending check"

**Comment by lindy65** [comment] 2018-02-16 06:51
Hi @billybrown1,

Thanks for the pull request!

I've added comments to it so take a look and see which you think should be amended :)

I'm going to close this issue here and we can follow on the pull request so we don't have two conversations going :)

**Closed by lindy65** 2018-02-16 06:51 UTC
