### ISSUE TITLE
direct message myself

### ISSUE THREAD

**Issue by str255** [mattermost/mattermost-server#10008] opened 2018-12-16 22:14 UTC
#### Summary
Yes, got a white screen of death when I direct message myself. So there is a self-referential bug there. 

#### Steps to reproduce
I am running version 4.2.0 
And linux gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I've just tested it on the windows client and it has the same problem
Version 4.1.2 on Windows 10

#### Expected behavior
Try opening a Direct Channel with yourself

#### Observed behavior (that appears unintentional) 
White Screen of Death

#### Possible fixes
Delete .config and it is o.k.
OK I resolved it with "History" menu and then "Back" (alt+left arrow) and then CTRL-R to refresh

**Comment by jasonblais** [comment] 2018-12-17 03:30
Thanks @str255! Can you help go to the Main Menu shown below, then select About Mattermost, and help take a screenshot of the modal?

![image](https://user-images.githubusercontent.com/13119842/50064995-2afb4f80-0182-11e9-9bc9-90d5fa012621.png)

That will display the Mattermost server version and help us try reproduce the issue.

**Comment by jjellinek** [comment] 2018-12-23 12:50
Upgraded server and tested again. Problem still exists on this version:-

Mattermost Enterprise Edition

Mattermost Version: 5.6.1
Database Schema Version: 5.6.0
Database: mysql

**Comment by jasonblais** [comment] 2018-12-23 18:04
Thanks @jjellinek for sharing!

@str255 @jjellinek Would you be open to sharing the contents of your JavaScript Developer Console at the time this error occurs? [Here is how to do so](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers).

I was unable to reproduce, so errors in the console can help pinpoint the cause.

**Comment by jjellinek** [comment] 2018-12-23 18:34
This happens in the clients, not in the web browser.

**Comment by jasonblais** [comment] 2018-12-23 18:38
Thanks @jjellinek, got it. Here is how you can share contents on the Desktop App https://docs.mattermost.com/install/desktop.html#reporting-issues

**Comment by jjellinek** [comment] 2018-12-23 18:49
[-1545590798860.log](https://github.com/mattermost/mattermost-server/files/2706213/-1545590798860.log)

**Comment by amyblais** [comment] 2019-01-08 18:02
Hi all, the Jira ticket was closed because we cannot reproduce this. Can you help share specific reproduction steps to help us diagnose this issue?

**Comment by jjellinek** [comment] 2019-01-08 19:16
When you click on your own username in the Direct Message list the screen blanks out. This is latest versions both Linux and Windows and all users.
![mattermost-bug](https://user-images.githubusercontent.com/8393056/50853362-e0808380-1379-11e9-8348-b1a6f380bfc8.gif)

**Comment by amyblais** [comment] 2019-01-09 00:55
Do you see any errors in the Server logs when this issue occurs?

**Comment by jjellinek** [comment] 2019-01-17 00:03
OK I think the problem was something to do with a github plugin I had installed and tested, and then disabled. The plugin had root only permissions. I did a recursive permissions change on the plugins directory to the mattermost user, and didn't think much more of it. I tried the direct message to myself later and realised it was now working. I can't for sure say if this was related or not!

**Comment by amyblais** [comment] 2019-01-18 21:08
The issue sounds to be fixed so I'll close this for now. If the issue comes back, please re-open this Github Issue with detail repro steps and Mattermost log errors.

**Closed by amyblais** 2019-01-18 21:08 UTC
