### ISSUE TITLE
Direct message problem after adding new User to conversation

### ISSUE THREAD

**Issue by ddavid9755** [mattermost/mattermost-server#8503] opened 2018-03-24 15:09 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
After adding a User to a Direct message, the conversation will duplicating

#### Steps to reproduce
1. Log in to Mattermost
2. Select a channel
3. Create a new direct message (or use an existing one) 
4. Add a header to your direct message
5. Add a member to your direct message

#### Expected behavior
New user is added, there is no new conversation

#### Observed behavior (that appears unintentional) 
Please see the uploaded video: 
https://www.screencast.com/t/uFmURF3N

#### Possible fixes
I think this issue is because of the database layer (maybe microservices?), because I've checked the consol in the browser and there were no error message.

**Comment by lindy65** [comment] 2018-03-26 09:09
Hi @ddavid9755,

Thanks for your report!

This is expected behavior when adding users to an already existing group direct message.

![image](https://user-images.githubusercontent.com/13020833/37897241-0eaf8084-30e6-11e8-9f50-bd079e8da7e3.png)

**Comment by ddavid9755** [comment] 2018-03-26 09:47
Hi @lindy65,

Sorry for the misunderstanding, but I would have a question about this.
That's clear I need to create a new direct message if I want to add more people. But what if I want to remove a single user? I think this is a different case, so in my opinion, a new conversation should't be created if only a single user is deleted for a conversation. This would be more user friendly, if you could remove users without creating new conversations. 
Or if it's not possible, maybe it would be great if: 
after you add/delete a user from a conversation, after saving your modification, you should be navigated to the new conversation instead of the old one.

**Comment by lindy65** [comment] 2018-03-26 18:35
Hi @ddavid9755,

Thanks for your feedback and you make a good point about removing users and navigation to the new conversation instead of the old one...

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9960) for our product team to take a look at improving the experience. 👍

**Comment by jasonblais** [comment] 2018-03-28 12:48
Thanks @ddavid9755, great feedback!

1) Adding users: When I tried to add a user to an existing direct/group message conversation, I navigated to the new conversation. Steps:

 - Create a new group direct message with at least two other people
 - Add a member to the channel
 - Observed: New conversation created, and I'm navigated to the channel.

Do I have the correct steps above that describes your issue?

2) Removing users: You raise a good point, but what if we have this scenario:
 - group message channel with: user1, user 2. Call this "GROUP 1-2"
 - group message channel with: user1. Call this "GROUP 1"

Then, suppose I remove user 2 from "GROUP 1-2"? Will the conversation get merged with "GROUP 1"?

**Comment by ddavid9755** [comment] 2018-03-29 05:41
Hi @jasonblais,
1. I checked this, it's working as expected, feels smooth :) (I checked both adding and deleting users from a group) 

2. I checked this, the result of this case is a nice 400 "Bad request" :)
IMO, that would make sense if the same groups (case 2) would get merged.

**Comment by jasonblais** [comment] 2018-03-29 10:43
Hi @ddavid9755,

2. We could probably improve the error message in that case. If we merged the two conversations, I worry it might make the channel confusing (since there might have been two separate discussions going on at the same time, in those two groups - and if merged, those conversations would be mixed)

**Comment by lindy65** [comment] 2018-04-25 08:49
I'll close this issue off for now (see above-linked ticket for resolution).

**Closed by lindy65** 2018-04-25 08:49 UTC
