### ISSUE TITLE
Mattermost Server restarts when trying to upload an image (S3 Storage)

### ISSUE THREAD

**Issue by catacraciun** [mattermost/mattermost-server#8489] opened 2018-03-21 12:46 UTC
#### Summary
I am trying to configure mattermost on an Amazon Lightsail machine. I have installed it on Ubuntu 16.04 LTS, and also on Amazon Linux. Everything works smoothly, excepting one case:
If I am enabling S3 Storage, and I'm trying to upload a PNG image (small images, screenshots, for example), the server seems to restart, causing a 'connection refused' (looking in Chrome devTools). 
The image gets uploaded into the bucket, but there is something wrong happening on the server. I didn't see any error in logs, just the fact that the server is starting again.

I have tried with and without nginx proxy, the result is the same. 

I am using version: 4.8.0 (4.8.0/Thu Mar 15 23:11:12 UTC 2018/d1ed79a66c7930020b7fda046a11050f5890c84e/6f563c1fa497d123134fd499eb37674eb2511325).

Uploading other files (not images) using S3 storage works fine, too...

If I change to local storage, everything works fine. 

Am I missing some configuration, or is it from some Lightsail VM limitation?

I have used the following client apps: web, mac, and IOS. Same results.

**Comment by catacraciun** [comment] 2018-03-21 12:53
On IOS, I just managed to upload a ~7 MB photo after retrying 2-3 times.

**Comment by jespino** [comment] 2018-03-22 14:02
Hi @catacraciun,

It may be a problem of "Out of memory" during the image resizing. Could you try with a bigger Lightsail VM instance, at least to verify if the problem is related to that?

**Comment by lindy65** [comment] 2018-04-25 08:48
Hi @catacraciun,

As there hasn't been any feedback, I'll close this issue off for now.  If you're still experiencing issues, please try `jespino's` suggestion above and open a new issue if that doesn't work for you.

Thanks!

**Closed by lindy65** 2018-04-25 08:48 UTC
