### ISSUE TITLE
Post texts disappear

### ISSUE THREAD

**Issue by avas27JTG** [mattermost/mattermost-server#22516] opened 2023-03-15 14:56 UTC
#### Summary
Post texts disappear when typed as `[<text>]: <any-url>`

#### Steps to reproduce
1. Type a message in the below format
`[<text>]: <any-url>`
example: `[abc]: https://www.google.com/`

2. Message will be posted but texts will not be visible in the post

#### Expected behavior
The post should show the texts

**Comment by amyblais** [comment] 2023-03-15 16:14
Opened https://mattermost.atlassian.net/browse/MM-51433.

**Comment by hmhealey** [comment] 2023-03-23 14:19
Thanks for the report, @avas27JTG. This is actually working as "intended" since that's actually some advanced Markdown syntax. It's a way of defining links that are reused without having to repeat the URL. For example,

```markdown
[some link][example]

[example]: https://example.com
```

renders as 

---
[some link][example]

[example]: https://example.com

---

Is this stopping you from doing something or is it just something you happened to notice? It's definitely a bit of unexpected behaviour, but it's something we need to support because it's part of the Markdown spec

**Comment by avas27JTG** [comment] 2023-04-03 07:11
Not exactly stopping me from doing anything but I was trying to write a post when I noticed it. I thought to mention this as I was not able to see this behavior on Slack or Discord.

**Comment by hmhealey** [comment] 2023-04-04 16:56
Okay, cool. I just wanted to make sure there wasn't anything here that we couldn't work around. We found an edge case recently with the autolinker that couldn't be worked around so I wanted to make sure it wasn't completely breaking a use case like that one was.

I'm going to close this, but I do appreciate the report. Hopefully this is something we can address when we get around to revisiting the post input to give an alternative to using raw Markdown. As it is, we're kind of stuck with Markdown and all its quirks for better or for worse.

**Closed** 2023-04-04 16:57 UTC
Labels: Bug Report/Open
