### ISSUE TITLE
Add bool (boolean) type for Interactive Dialogs

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10464] opened 2019-03-18 09:26 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14273)

Interactive Dialogs allow integrations to receive some form-styled input from users and have that input submitted back to the integration. An Interactive Dialog consists of a list of elements. These elements have a defined type such as `text` or `select`.

This ticket is about adding a `bool` type element for Dialog elements. Setting this type for an element should render a checkbox like:

```
[X] The meeting was helpful.
```

For an example UI style containing a checkbox, see Account Settings > Notifications > Words that trigger mentions

The default value is `false`. The integration might change this by setting `default' to `true`.

This ticket requires changes in both the web app and the mobile app.

For more information about Interactive Dialog, see https://docs.mattermost.com/developer/interactive-dialogs.html

If you have any questions or would like feedback, feel free to ask in the [Developer Toolkit channel](https://community.mattermost.com/core/channels/developer-toolkit) on our Mattermost community instance.

**Comment by hvhallmann** [comment] 2019-06-30 21:32
working on it

**Comment by hanzei** [comment] 2019-06-30 21:58
Thanks @hvhallmann. Let me know, if you have questions.

**Comment by hanzei** [comment] 2019-08-05 13:10
Webapp is merged. Now only mobile is missing.

**Comment by hanzei** [comment] 2019-09-04 08:45
Hey @hvhallmann,

Just want to sync up with you: Are you still interested in adding this feature for the mobile app?

**Comment by hvhallmann** [comment] 2019-09-04 12:53
Hey @hanzei,
I'm sorry, but I don't think I will have time in the next couple of weeks

**Comment by hanzei** [comment] 2019-09-04 13:04
All fine! Thanks for the heads up and all you spend on the awesome feature :+1:

**Comment by marianacapelo** [comment] 2019-10-01 12:30
Hi @hanzei,
Can you confirm if the issue is Up For Grabs? I noticed a merged PR to address it -https://github.com/mattermost/mattermost-mobile/pull/3239.

**Comment by hanzei** [comment] 2019-10-02 09:14
Good catch @marianacapelo :+1:. This was competed with https://github.com/mattermost/mattermost-mobile/pull/3239. Closing

**Closed by hanzei** 2019-10-02 09:14 UTC
Labels: Area/Extension, Difficulty/2:Medium, Good First Issue, Hacktoberfest, Help Wanted, PR Exists, Tech/React Native, Tech/ReactJS
