### ISSUE TITLE
Let's Encrypt TLS problems,  handshake error, etc

### ISSUE THREAD

**Issue by polyzium** [mattermost/mattermost-server#8149] opened 2018-01-24 20:58 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
TLS problems when using Let's Encrypt certificate, Mattermost server giving out handshake&no solvers errors.

#### Steps to reproduce
Tried to google the solution, someone said to update my mattermost server install but it didn't work.
Attempt number 1:
1. Get a Let's Encrypt certificate by running `certbot certonly` and selecting the first (standalone) option
2. Change the config file to use Let's Encrypt cert:
```
        "ListenAddress": ":443",
        "ConnectionSecurity": "TLS",
        "TLSCertFile": "/etc/letsencrypt/live/yourhostnamehere/cert.pem",
        "TLSKeyFile": "/etc/letsencrypt/live/yourhostnamehere/privkey.pem",
        "UseLetsEncrypt": true,
        "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
```
3. Run the server.
4. Try to connect.
Attempt number 2:
Do the same as above, but `"UseLetsEncrypt": false` despite you're using a LE cert.

#### Expected behavior
Attempt 1: Expected everything to be working.
Attempt 2: Expected something worse but that didn't happen.

#### Observed behavior (that appears unintentional) 
Attempt 1:
When i connect no matter how, this gets spit out into server's terminal:
```
2018/01/24 15:04:07 [INFO] acme: Registering account for 
2018/01/24 15:04:08 [INFO][polyzium.tk] acme: Obtaining bundled SAN certificate
2018/01/24 15:04:08 [INFO][polyzium.tk] AuthURL: https://*redacted*
2018/01/24 15:04:08 [INFO][polyzium.tk] acme: Could not find solver for: http-01
2018/01/24 15:04:08 [INFO][polyzium.tk] acme: Could not find solver for: dns-01
2018/01/24 15:04:09 http: TLS handshake error from *redacted*:54518: map[yourhostnamehere:[yourhostnamehere] acme: Could not determine solvers]
2018/01/24 15:04:09 http: TLS handshake error from *redacted*:54522: map[yourhostnamehere:[yourhostnamehere] acme: Could not determine solvers]
```
Attempt 2:
The website works on both PC and phone, but the mobile app refuses to connect:
```
2018/01/24 15:20:41 http: TLS handshake error from *redacted*:56064: remote error: tls: unknown certificate
```
Also the electron-based PC client app and 3rd party clients such as purple-mattermost work just fine.
#### Possible fixes
Not a link to the code files but you might find this useful https://community.letsencrypt.org/t/tls-handshake-error-map-acme-could-not-determine-solvers-could-not-find-solver-for-dns-01-could-not-find-solver-for-http-01/51177

**Comment by polyzium** [comment] 2018-01-24 20:59
Whoops. I pressed an enter key by accident. Don't repond to this yet

**Comment by joernheissler** [comment] 2018-01-26 13:33
If polyzium.tk is your domain (Please don't redact those!) then for whatever reason you don't have an intermediate cert loaded.

**Comment by polyzium** [comment] 2018-01-26 14:22
>If polyzium.tk is your domain
I am turning on whitelisting right now (jk)

Anyways, how do i load an intermediate certificae? There's no entry for it in config.json...

**Comment by jasonblais** [comment] 2018-01-29 22:41
Let's Encrypt certificates are broken on Mattermost servers. We're working on a fix https://mattermost.atlassian.net/browse/ABC-198

@polyzium @joernheissler A workaround is to terminate SSL at the proxy, or set up let's encrypt manually directly on the Mattermost server.

**Comment by lindy65** [comment] 2018-02-14 10:27
I'll close this issue off for now and we can reopen if the issue still reproduces after v4.7 releases on Feb 16th.

**Comment by polyzium** [comment] 2018-03-06 18:33
I just updated Mattermost to v4.7.2. The problem still persists. I tried attempt 1:
```
2018/03/06 13:28:29 http: TLS handshake error from *redacted*:44446: acme/autocert: unable to authorize "polyzium.tk"; tried ["tls-sni-02" "tls-sni-01"]
```
And it can also occasionally switch to `missing certificate` even when logging in from PC

**Comment by SmartHoneybee** [comment] 2018-03-07 08:55
@polyzium, did you enable `Forward80To443`?

**Comment by polyzium** [comment] 2018-03-07 13:44
That worked, thanks.
I never thought it would even work.

**Comment by hmhealey** [comment] 2018-03-07 14:16
Thanks for the help, @SmartHoneybee.

So the problem that you were seeing in 4.7.2 is resolved, @polyzium?

**Comment by SmartHoneybee** [comment] 2018-03-07 14:40
@polyzium, great.

Without [`Forward80To443`][1] enabled [`m.HTTPHandler(...)`][2] is not called. As a consequence `m.tryHTTP01` remains `false` and `"http-01"` is not considered as challenge type. Since TLS-SNI challenges are disabled this implies that `acme/autocert` will fail to create (or update) a certificate unless `Forward80To443` is enabled.

[1]: https://github.com/mattermost/mattermost-server/blob/838295f82c4bad22bd83a30a5b157dd717f8ceb6/app/server.go#L173
[2]: https://github.com/mattermost/mattermost-server/blob/09713ff4eadd3d706df45cb69f096b66c5b283fd/vendor/golang.org/x/crypto/acme/autocert/autocert.go#L257
[3]: https://github.com/mattermost/mattermost-server/blob/09713ff4eadd3d706df45cb69f096b66c5b283fd/vendor/golang.org/x/crypto/acme/autocert/autocert.go#L550

**Comment by hmhealey** [comment] 2018-03-07 15:30
Okay, that sounds like there's still a bug then. I'll file a Jira ticket to track this better

**Comment by polyzium** [comment] 2018-03-07 16:09
Well, i guess with Forward80To443 enabled it works but what if you have Apache2 running on port 80?

**Comment by SmartHoneybee** [comment] 2018-03-07 17:36
@polyzium, e.g. something like this: https://github.com/mattermost/mattermost-server/issues/8291

**Comment by lindy65** [comment] 2018-03-08 08:11
Thanks @SmartHoneybee @hmhealey 

I'll close this issue off here for now and we can track via the ticket `hmhealey` linked above 👍

**Closed by lindy65** 2018-03-08 08:11 UTC
