### ISSUE TITLE
More than 24 hours per day?

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-server#14102] opened 2020-03-18 00:01 UTC
#### Summary
It seems, the Mattermost web client is a time machine and has more than 24 Hours per day.

![image](https://user-images.githubusercontent.com/5354356/76912314-bbf43580-68b3-11ea-8bdd-5b4ef6ecc48b.png)

#### Steps to reproduce
Write anything after 0:45 / No idea.

#### Expected behavior
The posting time to be 0:57 and not 24:57.

#### Observed behavior (that appears unintentional) 
The posting time to be 24:57.

**Comment by amyblais** [comment] 2020-03-18 12:16
We have a ticket to investigate this: https://mattermost.atlassian.net/browse/MM-22595.

I'll close this as a duplicate of https://github.com/mattermost/mattermost-server/issues/14063.

**Closed by amyblais** 2020-03-18 12:16 UTC
