### ISSUE TITLE
invalid json text while deleting a post

### ISSUE THREAD

**Issue by PommereningMartin** [mattermost/mattermost-server#18983] opened 2021-11-11 07:19 UTC
#### Summary
- writing a post and deleting the same post raise an error and the post is still existing 

#### Steps to reproduce
- write a post and delete

#### Expected behavior
- the post should get deleted without an error

#### Observed behavior (that appears unintentional) 
`{"timestamp":"2021-11-11 08:05:34.332 +01:00","level":"error","msg":"Unable to delete the post.","caller":"web/context.go:105","path":"/api/v4/posts/ya7timne338bdekm5hcbx8nuiw","request_id":"qtxxupkatj8hikwb7dktyphkby","ip_addr":"XXX.X.XXX.XX","user_id":"XXXXXXXXXXXXXXX","method":"DELETE","err_where":"DeletePost","http_code":500,"err_details":"failed to update Posts: Error 3141: Invalid JSON text in argument 1 to function cast_as_json: \"Invalid value.\" at position 0."}`

#### Possible fixes
no time to investigate the code at this point

#### Mattermost Version
6.0.2

#### Database Schema Version
6.0.2

#### MYSQL Version
8.0.22

**Comment by amyblais** [comment] 2021-11-11 14:10
@agnivade @isacikgoz Is this a bug?

**Comment by agnivade** [comment] 2021-11-11 14:33
Sounds like it.

@PommereningMartin - When did this issue start? Was it after upgrading to 6.0.2? Does it happen for all posts? Or only for particular posts? If it's only for particular posts, would you be able to share the text?

**Comment by PommereningMartin** [comment] 2021-11-11 14:47
@agnivade the issue comes up yesterday.
We upgraded on Monday to version 6.0.2.
This happens to all posts also for simple ones like `test` and for each channel and for each user.

**Comment by agnivade** [comment] 2021-11-11 14:48
Thanks, it looks like a problem with MySQL 8.

@amyblais - would you mind creating a SET ticket for this?

**Comment by amyblais** [comment] 2021-11-11 15:44
Opened https://mattermost.atlassian.net/browse/MM-40041.

**Comment by streamer45** [comment] 2021-11-11 16:20
@PommereningMartin Would you be able to run the following query to confirm if the issue may be triggered by possibly NULL Props values?

```sql
SELECT COUNT(*) FROM Posts WHERE Props IS NULL;
```

**Comment by PommereningMartin** [comment] 2021-11-12 06:38
i ran the quey and this is the result

```
mysql> SELECT COUNT(*) FROM Posts WHERE Props IS NULL;
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.84 sec)

```

**Comment by PommereningMartin** [comment] 2021-11-15 08:58
@streamer45 I figured out that our production system runs with MySQL version 8.0.22 instead of 8.0.25 like our test system

* I will update the version in the ticket description
* on the test system with Mysql version 8.0.25 the delete of posts works fine

**Comment by agnivade** [comment] 2021-11-15 09:06
Thanks @PommereningMartin, that's interesting to know. I happened to test this while doing something else, and I observed that with 8.0.21, post deletion is working fine. I am guessing there happened to be some regression with 8.0.22 which got fixed in a later version.

**Comment by lieut-data** [comment] 2021-11-16 15:00
Thank you for the extra notes, @PommereningMartin, and for the early investigation @agnivade & @streamer45. Looking at the release notes for 8.0.23 and 8.0.24, there are a handful of JSON-specific changes, including one specifically addressing work done in 8.0.22. 

I'll consider this closed for now, and encourage anyone else arriving at this issue to upgrade to at least MySQL 8.0.25.

**Closed by lieut-data** 2021-11-16 15:00 UTC
Labels: Bug Report/Open
