### ISSUE TITLE
Fix For Duplicated messages

### ISSUE THREAD

**Issue by rbdevr** [mattermost/mattermost-server#8471] opened 2018-03-16 14:27 UTC
Messages sent by mobile are getting duplicated. Probably because not 100% stable connection.
The server requires a mechanism to make sure the same message is not saved in the server multiple times.
If there is already a mechanism in place then it needs to be reviewed.

I suggest to have the clients to generate a message id(GUID probably) and send the message and the id together. The server will then check if the id already exists. if not add new message or else ignore it.
This change means the clients also need to be updated.

**Comment by lindy65** [comment] 2018-03-19 07:03
Hi @rbdevr,

Thanks for your feedback,

We have [this ticket](https://mattermost.atlassian.net/browse/MM-8528) open to investigate but haven't found concrete reproduction steps and the issue is intermittent.

**Comment by rbdevr** [comment] 2018-03-19 12:32
Interesting. they could be related.

**Comment by lindy65** [comment] 2018-03-20 06:40
Hi @rbdevr,

Thanks for your feedback,

Yes, agree, the Jira ticket is on browser...

Could you help with reproduction steps for your mobile issue so we can try to replicate on our side?  If you can let us know which version of Mattermost server you have installed as well as which version of the mobile app you are running with steps on what occurs leading up to messages being duplicated, that would be very helpful for us to investigate.

Thanks!

**Comment by lindy65** [comment] 2018-04-25 08:45
Hi @rbdevr 

Just checking whether you've had time to reproduce the issue and send us further information.  If you are using the mobile classic app, the above-linked ticket should fix the issue when it's released with v4.10 on May 16th.

If you're using the RN app, we'll need to investigate further.  Please also let us know which server version of Mattermost you have installed.

Thanks!

**Comment by lindy65** [comment] 2018-05-02 08:53
I'll close this issue off here for now due to inactivity.  Please feel free to open a new issue if you're still experiencing problems.

**Closed by lindy65** 2018-05-02 08:53 UTC

**Comment by lfbrock** [comment] 2018-05-03 22:00
@rbdevr - filed another ticket specific to mobile to investigate this: https://mattermost.atlassian.net/browse/MM-10460
