### ISSUE TITLE
E-mail notifications dropped when messages received during status timeout window

### ISSUE THREAD

**Issue by kyonifer** [mattermost/mattermost-server#7372] opened 2017-09-04 22:33 UTC
#### Steps to reproduce
Close the mm client and then have someone message you within the next few minutes, while your status is still "online".

#### Expected behavior
Notification of messages to be delivered according to the users preferences (instant, delay batch, etc.)

#### Observed behavior (that appears unintentional) 
No notifications are ever delivered for those messages. A user can therefore log out of MM, receive messages, and never be notified that someone is trying to contact them.

#### Possible fixes
The notification code [drops all messages](https://github.com/mattermost/platform/blob/master/app/notification.go#L173) when the user has `STATUS_ONLINE`. 

The easiest fix would be to generate e-mail notifications when the user switches from ONLINE to AWAY (except if status was set manually). Code could be added [here](https://github.com/mattermost/platform/blob/master/app/status.go#L277) which finds all unread messages sent after the user's last activity and sends them to [sendNotificationEmail](https://github.com/mattermost/platform/blob/master/app/notification.go#L300). This would respect the user's email-batching preferences and only generate these notifications when the user has gone away and the messages were delivered after they were last active.

Another possible fix is to modify the [email notification code](https://github.com/mattermost/platform/blob/master/app/notification.go#L173) to batch-queue messages when `status.Status == model.STATUS_ONLINE`.

**Comment by lindy65** [comment] 2017-09-05 08:23
Hi @kyonifer,

Thanks for your feedback,

It's by design that email notifications aren't sent while a user is online.  They are sent for mentions and direct messages when you are offline or away from Mattermost for more than 5 minutes.

Push notifications to your phone would cover this short period as you can set them to trigger while you are online (as well as away and offline).  

I'll post your issue to our team and ask them for feedback.

**Comment by saturninoabril** [comment] 2017-09-05 13:11
@kyonifer, if MM client is closed, the user's `offline` status propagation into its server will take some time; in effect, the user is still `online` for quite sometime. During that period, no notification will be delivered as it is blocked by `online` status.
It's different when the user logged out or set status (`away` / `offline`) manually, where the user immediately update it's status. Hence, the notification is expected per their preference.

**Comment by kyonifer** [comment] 2017-09-05 14:00
I see. In my case, that means I have to continuously open mattermost to see if I've missed a message, because every time I close the client I might have missed a notification in the 5 minute window right after the client closed, with no way to discover a message is waiting for me.

> Push notifications to your phone would cover this short period

This doesn't work for me, since I'm not using mobile and I do not have a device that works with either of the supported push services (GCM and iOS notifications).

To clarify, I do not propose that emails should be sent while the user is online, but that unread messages should be queued so that they're included in the e-mail sent when the server finally notices the MM client has closed.

**Comment by esethna** [comment] 2017-09-06 17:08
@kyonifer do you have batching enabled on the server? Which email preferences are you using to reproduce this? 

I just tested on a server with batching disabled, and the email preference set to immediate, and I was able to receive an email within a few seconds of closing my browser window.

**Comment by kyonifer** [comment] 2017-09-06 18:44
Batching is enabled, user preferences set to "Immediately". Running Mattermost 4.1.0, Firefox 55.0.3.

I did testing on a new user and I am also able to get it to immediately show offline (and deliver e-mails) by closing the browser. Upon further digging, it appears this issue only occurs when there is an idling client running on a second computer. The second session didn't have any activity at all, but appears to prevent MM from noticing the active browser session has closed, and thus starts a 5 minute timeout window during which notification emails are dropped. So a workaround for this issue is to only use one browser session / computer at a time.

Apologies for the incomplete steps to reproduce. Actual steps are:
1. Log in to MM on computer A, let the session sit idle indefinitely
2. Log in to MM on computer B, be active writing messages
3. Close the browser on computer B, then receive a message in the 5 minute window after closing-- no e-mail notifications are ever sent for these messages.

**Comment by esethna** [comment] 2017-09-08 19:10
Got it. That sounds like a bug, appreciate the repro steps. Thanks @kyonifer! I've filed a [ticket to track this issue in JIRA](https://mattermost.atlassian.net/browse/PLT-7603).

**Closed by esethna** 2017-09-08 19:10 UTC
