### ISSUE TITLE
DB slow queries

### ISSUE THREAD

**Issue by firaxis** [mattermost/mattermost-server#6828] opened 2017-07-03 13:59 UTC
Good day.

We are using Mattermost Enterprise Edition with MariaDB 10.1.21-MariaDB-1~trusty
> Version: 3.10.0
> Database: mysql
> 
> Build Hash: 8b83e9d4279718c8f9797c6a9c081245231cbba0
> EE Build Hash: 7eab554702fb44fb7755e1a542cd7dd0d3acf261
> Build Date: Wed Jun 14 21:03:15 UTC 2017

We have about 2M rows in Posts table total, but on channels with >100k messages we do encounter 504 Gateway Timeout error because of queries that executing more that 90 seconds.

Our DBA says, the main reason of slow performance is using string columns as primary keys.
Mysql's optimizer doesn't work fine with such primary keys.
The second thing, is using 26 symbols and in UTF-8 makes indexes massive and non-optimal, like 236 primary key length.

The queries and steps to reproduce:
1) Toggle the "flagged posts" button at right upper conner in big channel.
The query is:
```sql
SELECT A.*
FROM
  (SELECT *
   FROM Posts
   WHERE Id IN
       (SELECT Name
        FROM Preferences
        WHERE UserId = '6zwwcchaj78tffb395d557k1qo'
          AND Category = 'flagged_post')
     AND DeleteAt = 0 ) AS A
INNER JOIN Channels AS B ON B.Id = A.ChannelId
WHERE B.TeamId = 'krq1en963jfo3jk8sfz3bakxdh'
  OR B.TeamId = ''
ORDER BY CreateAt DESC
LIMIT 60
OFFSET 0;
```
The fixed query, that works faster:
```sql
SELECT A.*
FROM
  (SELECT Posts.*
   FROM Posts
   INNER JOIN Preferences ON (Preferences.Name=Posts.Id)
   WHERE Preferences.UserId = '6zwwcchaj78tffb395d557k1qo'
     AND Preferences.Category = 'flagged_post'
     AND Posts.DeleteAt = 0 ) AS A
INNER JOIN Channels AS B ON B.Id = A.ChannelId
WHERE B.TeamId = 'krq1en963jfo3jk8sfz3bakxdh'
  OR B.TeamId = ''
ORDER BY CreateAt DESC
LIMIT 60
OFFSET 0;
```

2) Try to view channel. Yes, I can't even see the new messages in channel.
The query:
```sql
SELECT
                            q2.*
                        FROM
                            Posts q2
                                INNER JOIN
                            (SELECT DISTINCT
                                q3.RootId
                            FROM
                                (SELECT
                                RootId
                            FROM
                                Posts
                            WHERE
                                ChannelId = 'ncjjypf563d7xron969rr38dmy'
                                    AND DeleteAt = 0
                            ORDER BY CreateAt DESC
                            LIMIT 60 OFFSET 0) q3
                            WHERE q3.RootId != '') q1
                            ON q1.RootId = q2.Id OR q1.RootId = q2.RootId
                        WHERE
                            ChannelId = 'ncjjypf563d7xron969rr38dmy'
                                AND DeleteAt = 0
                        ORDER BY CreateAt
```
The fixed query, that works faster:
```sql
(
SELECT
                            q2.*
                        FROM
                            Posts q2
                                INNER JOIN
                                (SELECT
                                RootId
                            FROM
                                Posts
                            WHERE
                                ChannelId = 'ncjjypf563d7xron969rr38dmy'
                                    AND DeleteAt = 0
                            AND RootId != '') q1
                            ON q1.RootId = q2.Id
                        WHERE
                            ChannelId = 'ncjjypf563d7xron969rr38dmy'
                                AND DeleteAt = 0
) UNION ALL (
 SELECT
                            q2.*
                        FROM
                            Posts q2
                                INNER JOIN
                                (SELECT
                                RootId
                            FROM
                                Posts
                            WHERE
                                ChannelId = 'ncjjypf563d7xron969rr38dmy'
                                    AND DeleteAt = 0
                            AND RootId != '') q1
                            ON q1.RootId = q2.RootId
                        WHERE
                            ChannelId = 'ncjjypf563d7xron969rr38dmy'
                                AND DeleteAt = 0
)
                        ORDER BY CreateAt;
```
The fixed query has 3817 rows to be examined vs 228264 with "stock" query.

Please, fix the queries, because sooner or later, every channel should be inaccessible.
Many thanks.

**Comment by jasonblais** [comment] 2017-07-03 15:31
Thanks @firaxis! Ticket created here, and queued for us to discuss tomorrow: https://mattermost.atlassian.net/browse/PLT-6979

**Comment by firaxis** [comment] 2017-07-04 09:23
@jasonblais Thanks, nice to hear so fast reaction !

I've got more comments about how it works "inside".

When building index, MySQL assumes to use 3 bytes per utf8 character and for example 4 bytes per utf8mb character, and this is a pointer to row.
So, for table Posts, it's more than 100 bytes per row. (ENGINE=InnoDB DEFAULT CHARSET=utf8mb4)
And there are tables with composite primary keys. In tables like Preferences, Reactions, it's more than 300 bytes key_len..

The next thing is records order. Rows are sorted accordingly to primary key.
If you are using primary key with autoincrement, records just inserting to table one by one.
And it works fast.
With string PK, rows are inserting to random(according to PK) place in table.
And here appears one more expensive and slow effect called page splitting.
https://www.percona.com/blog/2017/04/10/innodb-page-merging-and-page-splitting/

After that, if you want to find something in table with such long key, frequently, optimizer decides to make a full scan, because it's also expensive to "shovel" so big indexes.
And if a subquery has to select IDs to temporary table, it's size also calculates like column_size * 4, with further processing(like joins, filters, sorting) is also kinda expensive on memory.

**Comment by grundleborg** [comment] 2017-07-04 09:45
Hi @firaxis 

Thanks very much for this feedback on the database performance issues. The query optimisations you suggested are definitely something that we'll be interested in trying out.

We are well aware of the issue with string primary keys. It's something that has been like that since the beginning of the project, and we have periodically discussed improving. However changing this would be quite involved. We rely very heavily on those random IDs in the application code - something which would need to be addressed before we could change this. We also have to consider existing large installs and how to migrate them without it being incredibly painful / causing significant downtime.

I'll queue this up to discuss in our next public developer meeting: 10am San Francisco time on Wednesday. If you'd like to join us for the discussion, please do drop in. Details on our development Mattermost instance [here](https://pre-release.mattermost.com/core/channels/developers-meeting).

**Comment by ccbrown** [comment] 2017-07-05 03:13
@firaxis

The 4 bytes per utf8mb character space requirement applies to CHAR columns, but _not_ VARCHAR columns, which is what our ids are.

> **CHAR(M):** M × w bytes, 0 <= M <= 255, where w is the number of bytes required for the maximum-length character in the character set. See Section 14.8.1.2, “The Physical Row Structure of an InnoDB Table” for information about CHAR data type storage requirements for InnoDB tables.
> **VARCHAR(M), VARBINARY(M):** L + 1 bytes if column values require 0 − 255 bytes, L + 2 bytes if values may require more than 255 bytes

– https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-innodb

> **Tip:** To save space with utf8mb4, use VARCHAR instead of CHAR. Otherwise, MySQL must reserve four bytes for each character in a CHAR CHARACTER SET utf8mb4 column because that is the maximum possible length.

– https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

I don't want to speak to the performance without doing some benchmarking, but I'm pretty skeptical that our performance issues are directly caused by using strings. Many very big companies with much larger workloads than we see use strings for primary keys (UUIDs are a very common choice).

I certainly wouldn't want to consider jumping ship and switching to integer ids without some solid benchmarks.

**Comment by ccbrown** [comment] 2017-07-05 07:21
In an attempt to actually get some data for this subject, I wrote up some cursory benchmarks:

```go
package pk_benchmarks

import (
	"bytes"
	"database/sql"
	"encoding/base32"
	"encoding/binary"
	"math/rand"
	"testing"

	_ "github.com/go-sql-driver/mysql"
	"github.com/pborman/uuid"
)

var encoding = base32.NewEncoding("ybndrfg8ejkmcpqxot1uwisza345h769")

func newId() string {
	var b bytes.Buffer
	encoder := base32.NewEncoder(encoding, &b)
	encoder.Write(uuid.NewRandom())
	encoder.Close()
	b.Truncate(26)
	return b.String()
}

func randomString(n int) string {
	charset := "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 /.,';][!@#$%^&*()-=_+?><\":}{|\\`~"
	b := make([]byte, n)
	for i := range b {
		b[i] = charset[rand.Intn(len(charset))]
	}
	return string(b)
}

func insert(db *sql.DB, rows int, idFunc func() string) {
	for i := 0; i < rows; i++ {
		if idFunc == nil {
			if _, err := db.Exec("INSERT INTO Benchmark SET IntData = ?, VarCharData = ?, TextData = ?", rand.Int31(), randomString(rand.Intn(200)), randomString(rand.Intn(200))); err != nil {
				panic(err)
			}
		} else {
			if _, err := db.Exec("INSERT INTO Benchmark SET Id = ?, IntData = ?, VarCharData = ?, TextData = ?", idFunc(), rand.Int31(), randomString(rand.Intn(200)), randomString(rand.Intn(200))); err != nil {
				panic(err)
			}
		}
	}
}

func setup(rows int, pkType string, idFunc func() string) *sql.DB {
	db, err := sql.Open("mysql", "mmuser:mostest@tcp(127.0.0.1:3307)/mattermost_test?charset=utf8mb4,utf8")
	if err != nil {
		panic(err)
	}
	if _, err := db.Exec("DROP TABLE IF EXISTS Benchmark"); err != nil {
		panic(err)
	}
	if _, err := db.Exec(`CREATE TABLE Benchmark (
		Id ` + pkType + ` PRIMARY KEY,
		IntData INT(11),
		VarCharData VARCHAR(200),
		TextData TEXT
	)`); err != nil {
		panic(err)
	}
	insert(db, rows, idFunc)
	return db
}

const rowCount = 100000

var packageLevelInt int

func BenchmarkIntAutoIncrementSelect(b *testing.B) {
	db := setup(rowCount, "INT(11) AUTO_INCREMENT", nil)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := db.QueryRow("SELECT IntData FROM Benchmark WHERE Id = ?", 1+rand.Intn(rowCount)).Scan(&packageLevelInt); err != nil {
			panic(err)
		}
	}
}

func BenchmarkBigIntAutoIncrementSelect(b *testing.B) {
	db := setup(rowCount, "BIGINT(11) AUTO_INCREMENT", nil)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := db.QueryRow("SELECT IntData FROM Benchmark WHERE Id = ?", 1+rand.Intn(rowCount)).Scan(&packageLevelInt); err != nil {
			panic(err)
		}
	}
}

func Benchmark4BytesSelect(b *testing.B) {
	x := 1
	db := setup(rowCount, "VARBINARY(4)", func() string {
		b := make([]byte, 4)
		binary.BigEndian.PutUint32(b, uint32(x))
		x++
		return string(b)
	})
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		b := make([]byte, 4)
		binary.BigEndian.PutUint32(b, uint32(1+rand.Intn(rowCount)))
		if err := db.QueryRow("SELECT IntData FROM Benchmark WHERE Id = ?", b).Scan(&packageLevelInt); err != nil {
			panic(err)
		}
	}
}

func Benchmark8BytesSelect(b *testing.B) {
	x := 1
	db := setup(rowCount, "VARBINARY(8)", func() string {
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, uint64(x))
		x++
		return string(b)
	})
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, uint64(1+rand.Intn(rowCount)))
		if err := db.QueryRow("SELECT IntData FROM Benchmark WHERE Id = ?", b).Scan(&packageLevelInt); err != nil {
			panic(err)
		}
	}
}

func BenchmarkOurIdsSelect(b *testing.B) {
	ids := make([]string, rowCount)
	i := 0
	db := setup(rowCount, "VARCHAR(26)", func() string {
		ids[i] = newId()
		i++
		return ids[i-1]
	})
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := db.QueryRow("SELECT IntData FROM Benchmark WHERE Id = ?", ids[rand.Intn(rowCount)]).Scan(&packageLevelInt); err != nil {
			panic(err)
		}
	}
}

func BenchmarkIntAutoIncrementInsert(b *testing.B) {
	db := setup(rowCount, "INT(11) AUTO_INCREMENT", nil)
	b.ResetTimer()
	insert(db, b.N, nil)
}

func BenchmarkBigIntAutoIncrementInsert(b *testing.B) {
	db := setup(rowCount, "BIGINT(11) AUTO_INCREMENT", nil)
	b.ResetTimer()
	insert(db, b.N, nil)
}

func Benchmark4BytesInsert(b *testing.B) {
	x := 1
	idFunc := func() string {
		b := make([]byte, 4)
		binary.BigEndian.PutUint32(b, uint32(x))
		x++
		return string(b)
	}
	db := setup(rowCount, "VARBINARY(4)", idFunc)
	b.ResetTimer()
	insert(db, b.N, idFunc)
}

func Benchmark8BytesInsert(b *testing.B) {
	x := 1
	idFunc := func() string {
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, uint64(x))
		x++
		return string(b)
	}
	db := setup(rowCount, "VARBINARY(8)", idFunc)
	b.ResetTimer()
	insert(db, b.N, idFunc)
}

func BenchmarkOurIdsInsert(b *testing.B) {
	db := setup(rowCount, "VARCHAR(26)", newId)
	b.ResetTimer()
	insert(db, b.N, newId)
}
```

That benchmarks SELECT and INSERT speeds for tables with 100k rows. The results showed no significant differences for varying PK types:

```
chris@mbp:~/go/src/github.com/mattermost/platform% go test -v ./pk_benchmarks -bench=. -timeout=60m
BenchmarkIntAutoIncrementSelect-8      	    3000	    576869 ns/op
BenchmarkBigIntAutoIncrementSelect-8   	    2000	    560810 ns/op
Benchmark4BytesSelect-8                	    3000	    535931 ns/op
Benchmark8BytesSelect-8                	    3000	    554633 ns/op
BenchmarkOurIdsSelect-8                	    3000	    557824 ns/op
BenchmarkIntAutoIncrementInsert-8      	    3000	    556089 ns/op
BenchmarkBigIntAutoIncrementInsert-8   	    3000	    545160 ns/op
Benchmark4BytesInsert-8                	    3000	    604384 ns/op
Benchmark8BytesInsert-8                	    3000	    593517 ns/op
BenchmarkOurIdsInsert-8                	    3000	    584460 ns/op
```

It's definitely not conclusive, but maybe it can kick-start more data-driven discussion. Maybe someone can point out what needs to be changed to produce the hypothesized performance impact of non-integer keys, or come up with a different benchmark that does.

But regardless of query speed, if we wanted a relatively easy change that would at least improve storage requirements, we could definitely change the column type of our ids to `VARBINARY(16)` instead of `VARCHAR(26)` since the ids are just 16 base32-encoded bytes. There's not really much downside other than the up-front development cost of adding those conversions to the codebase.

**Comment by ccbrown** [comment] 2017-07-05 07:47
@firaxis, if you have an example data set that you can share that actually triggers a full table scan, that would also be extremely useful. I can't figure out any ways that a full table scan might be caused by a lookup with a long primary key regardless of table size:

<img width="1343" alt="screen shot 2017-07-05 at 12 46 42 am" src="https://user-images.githubusercontent.com/1731074/27854376-76194dc2-611b-11e7-9921-208788bdddc7.png">

**Comment by firaxis** [comment] 2017-07-05 19:04
Hello @ccbrown, thanks for your reply.

> The 4 bytes per utf8mb character space requirement applies to CHAR columns, but not VARCHAR columns, which is what our ids are.

It's about storing data, not indexes.
Look at key_ken:
```sql
explain SELECT A.*
    -> FROM
    ->   (SELECT *
    ->    FROM Posts
    ->    WHERE Id IN
    ->        (SELECT Name
    ->         FROM Preferences
    ->         WHERE UserId = '6zwwcchaj78tffb395d557k1qo'
    ->           AND Category = 'flagged_post')
    ->      AND DeleteAt = 0 ) AS A
    -> INNER JOIN Channels AS B ON B.Id = A.ChannelId
    -> WHERE B.TeamId = 'krq1en963jfo3jk8sfz3bakxdh'
    ->   OR B.TeamId = ''
    -> ORDER BY CreateAt DESC
    -> LIMIT 60
    -> OFFSET 0;
+------+--------------+-------------+-------+----------------------------------------------------------------------------------------------------+----------------------+---------+--
| id   | select_type  | table       | type  | possible_keys                                                                                      | key                  | key_len | r
+------+--------------+-------------+-------+----------------------------------------------------------------------------------------------------+----------------------+---------+--
|    1 | PRIMARY      | B           | range | PRIMARY,idx_channels_team_id                                                                       | idx_channels_team_id | 107     | N
|    1 | PRIMARY      | Posts       | ref   | idx_posts_channel_id,ChannelId2,DeleteAt_ChannelId_CreateAt,ChannelId_UpdateAt,idx_posts_delete_at | ChannelId_UpdateAt   | 107     | m
|    3 | MATERIALIZED | Preferences | ref   | PRIMARY,idx_preferences_user_id,idx_preferences_category,idx_preferences_name                      | PRIMARY              | 236     | c
+------+--------------+-------------+-------+----------------------------------------------------------------------------------------------------+----------------------+---------+--
```
Indexes for char(26) and varchar(26) will be pretty same size.

> I don't want to speak to the performance without doing some benchmarking, but I'm pretty skeptical that our performance issues are inherently caused by using strings. Many very big companies with much larger workloads than we see use strings for primary keys (UUIDs are a very common choice).
I certainly wouldn't want to consider jumping ship and switching to integer ids without some solid benchmarks.

I completely endorse this point.

>In an attempt to actually get some data for this subject, I wrote up some cursory benchmarks:
Could you please tell more detail how to build and run this test on my side ?

>It's definitely not conclusive, but maybe it can kick-start more data-driven discussion. Maybe someone can point out what needs to be changed to produce the hypothesized performance impact of non-integer keys (more complex queries maybe?), or come up with a different benchmark that does.

Yeap, the results are weird, and not depends on what are you inserting to DB.
Looks like it's test for script, not DB 😃 

>But regardless of query speed, if we wanted a relatively easy change that would at least improve storage requirements, we could definitely change the column type of our ids to VARBINARY(16) instead of VARCHAR(26) since the ids are just 16 base32-encoded bytes. There's not really much downside other than the up-front development cost of adding those conversions to the codebase.

Yes, VARBINARY(16) will be much better.

>Even with more complicated queries, I haven't been able to generate any execution plans that look unusually slow as a result of longer string keys.

You can try queries from first post.

**Comment by ccbrown** [comment] 2017-07-05 19:39
@firaxis 

> It's about storing data, not indexes.
> Look at key_ken: [...]
> Indexes for char(26) and varchar(26) will be pretty same size.

I see... That's a bit counter-intuitive to me. But at least VARBINARY does what I would have expected. `VARBINARY(26)` results in a 28 byte index. That being a relatively easy migration to make seems like a really low-hanging fruit if we can't go straight to `VARBINARY(16)`.

I've been running some better benchmarks and queries with several million rows, but are taking quite some time...

**Comment by ccbrown** [comment] 2017-07-06 01:05
Hmm... I know the `EXPLAIN` output says `key_len` 107 bytes for a `VARCHAR(26)`, but I'm sitting here looking at tables with a few million rows, and there's no difference in size between it and `VARBINARY(16)`. The size on disk is the same. The clustered index and secondary index sizes are the same. Adding a secondary int index to the tables and dividing the total size of that index by the row count gives me about 36 bytes in all cases. I've tried with several character sets, and dynamic, compact, and redundant row formats, with no particularly interesting results...

Still no significant difference in SELECT or INSERT performance with millions of rows either (compared to int / auto-increment PKs).

InnoDB is just being too smart for me.

But someone else is looking into it as well.

**Comment by firaxis** [comment] 2017-07-06 11:49
Could you please tell me more detail how to build and run this test on my side ?

Btw, I ran optimize table, and it significantly accelerated the queries.
So, I can read that large channels again.
It seems that speed speed-size relation in non-linear.

**Comment by ccbrown** [comment] 2017-07-06 12:01
> Could you please tell me more detail how to build and run this test on my side?

Of course. This should do it:

* Make a directory in your GOPATH: `mkdir ./pk_benchmarks`
* Copy that script to ./pk_benchmarks/benchmark_test.go
* `go get -v ./pk_benchmarks`
* `go test -v ./pk_benchmarks -bench='.*Select' -timeout=1000m`

That script recreates the tables every time it's run, so for my larger, million+ tables I've been using slight variations that don't recreate the tables, along with some third-party tools.

**Comment by firaxis** [comment] 2017-07-07 08:22
Here's my results from the same VM where we run mattermost
```
$ go test -v ./pk_benchmarks -bench=. -timeout=1000m
testing: warning: no tests to run
PASS
BenchmarkIntAutoIncrementSelect-32         10000            317357 ns/op
BenchmarkBigIntAutoIncrementSelect-32      10000            252071 ns/op
Benchmark4BytesSelect-32                   10000            219186 ns/op
Benchmark8BytesSelect-32                   10000            229115 ns/op
BenchmarkOurIdsSelect-32                    5000            228286 ns/op
BenchmarkIntAutoIncrementInsert-32           200           9964830 ns/op
BenchmarkBigIntAutoIncrementInsert-32        200          11632641 ns/op
Benchmark4BytesInsert-32                     100          10162836 ns/op
Benchmark8BytesInsert-32                     100          13225821 ns/op
BenchmarkOurIdsInsert-32                     200          10410885 ns/op
ok      pk_benchmarks   31703.835s
```

**Comment by crspeller** [comment] 2017-07-14 14:46
Hi @firaxis,

Thanks for the report! I will be doing some more detailed work and hopefully coming up with a plan to address some of these issues.

Right now I am working on the mattermost loadtesting tools: https://github.com/mattermost/mattermost-load-test Hopefully these can give us some more real-world results on how these proposed changes effect performance.

**Comment by firaxis** [comment] 2017-07-24 14:55
Hi @crspeller,
Here's what I've collected
[slowquery.zip](https://github.com/mattermost/platform/files/1170175/slowquery.zip)
And `grep "FROM Status" /var/log/mysql/mariadb-slow.log|wc -l`
Shows zero records.
Maybe I can help with something else ?

**Comment by lindy65** [comment] 2017-09-07 19:31
Hi @firaxis,

Thank you for your feedback and your offer to help.  Once our devs start work on the [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6979) tracking this issue, I'm sure they'll reach out to you if there's any additional information they need.

Thanks again for your help and input thus far!  I'll close this issue off here for now and we can track via the ticket.

**Closed by lindy65** 2017-09-07 19:31 UTC

**Comment by vpecinka** [comment] 2019-07-30 10:12
Hi,

I suggest to reopen the issue. One of our channel has reached 4mio posts and the query 
```
SELECT 
      q2.*
    FROM
      Posts q2
        INNER JOIN
      (SELECT DISTINCT
        q3.RootId
      FROM
        (SELECT
          RootId
        FROM
          Posts
        WHERE
          ChannelId = :ChannelId1
            AND DeleteAt = 0
        ORDER BY CreateAt DESC
        LIMIT :Limit OFFSET :Offset) q3
      WHERE q3.RootId != '') q1
      ON q1.RootId = q2.Id OR q1.RootId = q2.RootId
    WHERE
      ChannelId = :ChannelId2
        AND DeleteAt = 0
    ORDER BY CreateAt
```

used in https://github.com/mattermost/mattermost-server/blob/e067272e16b962d04f9c83bb1cbd739ac1b6299c/store/sqlstore/post_store.go#L757 is very slow.

EXPLAIN says using filesort:

```
MySQL [mattermost]> explain SELECT q2.* FROM Posts q2 INNER JOIN (SELECT DISTINCT q3.RootId FROM (SELECT RootId FROM Posts WHERE ChannelId = 'onbayhh4mj81zpsz111ew3qq8r' AND DeleteAt = 0 ORDER BY CreateAt DESC LIMIT 100 OFFSET 100) q3 WHERE q3.RootId != '') q1 ON q1.RootId = q2.Id OR q1.RootId = q2.RootId WHERE ChannelId = 'onbayhh4mj81zpsz111ew3qq8r' AND DeleteAt = 0 ORDER BY CreateAt;
+----+-------------+------------+------------+------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+---------+-------------+---------+----------+----------------------------------------------------+
| id | select_type | table      | partitions | type | possible_keys                                                                                                                              | key                                      | key_len | ref         | rows    | filtered | Extra                                              |
+----+-------------+------------+------------+------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+---------+-------------+---------+----------+----------------------------------------------------+
|  1 | PRIMARY     | q2         | NULL       | ref  | PRIMARY,idx_posts_delete_at,idx_posts_channel_id,idx_posts_root_id,idx_posts_channel_id_update_at,idx_posts_channel_id_delete_at_create_at | idx_posts_channel_id_delete_at_create_at | 116     | const,const | 4061786 |   100.00 | Using temporary; Using filesort                    |
|  1 | PRIMARY     | <derived2> | NULL       | ALL  | NULL                                                                                                                                       | NULL                                     | NULL    | NULL        |     179 |    19.00 | Using where; Using join buffer (Block Nested Loop) |
|  2 | DERIVED     | <derived3> | NULL       | ALL  | NULL                                                                                                                                       | NULL                                     | NULL    | NULL        |     200 |    90.00 | Using where; Using temporary                       |
|  3 | DERIVED     | Posts      | NULL       | ref  | idx_posts_delete_at,idx_posts_channel_id,idx_posts_channel_id_update_at,idx_posts_channel_id_delete_at_create_at                           | idx_posts_channel_id_delete_at_create_at | 116     | const,const | 4061786 |   100.00 | Using where                                        |
+----+-------------+------------+------------+------+--------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+---------+-------------+---------+----------+----------------------------------------------------+
```
