### ISSUE TITLE
Unread message indicator  (* in tab) stopped working 

### ISSUE THREAD

**Issue by faljse** [mattermost/mattermost-server#8349] opened 2018-02-22 09:34 UTC
#### Summary
After 4.7.0 upgrade the star indicator doesnt show up anymore for public messages.
#### Steps to reproduce
Version 4.7.0
- channel needs to be in focus 
- Open other browser tab
- Post message in this (and only this) channel 
- ... nothing happens :(

#### Expected behavior
A mattermost browser tab should indicate unread messages by prepending a * to the title. 
#### Observed behavior (that appears unintentional) 
Direct messages and mentions do to trigger the star and message count correctly.
Issue exists for normal messages only.

**Comment by lindy65** [comment] 2018-02-22 10:16
Hi @faljse,

Thanks for the report,  

I've tried to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master and I'm not able to.  I still see the `*` appended to the Mattermost tab in the browser if I have unread messages.

![image](https://user-images.githubusercontent.com/13020833/36532678-0fb6ac12-17ca-11e8-8e3f-fbcbc1c69c20.png)


Could you try reproducing on the above server to see if the issue still persists for you?

**Comment by faljse** [comment] 2018-02-22 13:39
Its working fine on the nightly build server.

However, im not sure what that means:
- Has there actually been a bug that is now fixed?
or
- Is it a configuration/setup/.. issue on my side?

**Comment by SmartHoneybee** [comment] 2018-02-22 15:38
@faljse, which version did you upgrade from?

Two, in 4.7.0 fixed, notification related bugs according to the [changelog][1]:
* 4.7.0: "*Fixed an issue where notification preference settings didn’t respect case sensitivity for mention highlighting.*" (Sounds like: #8093)
* 4.6.0: "*Fixed an issue where channel notification preferences reverted to defaults after updating preferences in one of the channels.*" (Guess that's e.g.: #8116)

[1]: https://docs.mattermost.com/administration/changelog.html

**Comment by lindy65** [comment] 2018-02-23 07:35
Thanks @SmartHoneybee !

@faljse - I'll close off this issue as `smarthoneybee` has provided the information you were looking for :)

**Comment by faljse** [comment] 2018-02-25 12:06
I could reproduce the issue on the nightly build server - please consider re-opening this bug.
Additional step to reproduce:
- channel needs to be in focus (in out of focus tab)

Imo there should be a notification in this case; and this was true until 4.7.0

**Comment by lindy65** [comment] 2018-02-27 23:29
Hi @faljse,

Thanks for your feedback... 

To clarify, are you saying that there should be a star on  the Mattermost tab for a message posted to a channel you are actively viewing?

Or are you saying the star should appear on the Mattermost tab for the message received in the out of focus tab posted from the channel in the out of focus tab?

Our nightly build server is on v4.8 RC1 and I am still not able to reproduce this issue...

**Comment by faljse** [comment] 2018-02-28 06:39
Hi @lindy65,
thanks for looking at it again.
There should be a star on the mattermost tab for a message posted to a channel i am actively viewing _if_ the tab itself is not in focus.

Let me try to explain this with a screenshot:
- 2 Browsers
- 2 different user accounts
- Both viewing the same channel
- Client 1 is surfing on another tab
- Client 2 posts a message

![Screenshot](https://s14.postimg.org/rsmdp9h3l/star.png)

**Comment by lindy65** [comment] 2018-03-06 07:20
Hi @faljse 

Thanks for the additional information,

I've followed your steps on a test server running on the latest master and am able to reproduce.  If I am NOT currently in the channel the notification star works as expected so I'm wondering whether something was changed with regard to how the notifications work if you are viewing the channel but don't have the Mattermost tab in view...

I'll check with one of the product managers to find out what's expected in this case.

**Comment by lindalumitchell** [comment] 2018-03-07 17:02
Hi @faljse @lindy65, I checked on this and filed a bug: https://mattermost.atlassian.net/browse/MM-9754. 👍

**Comment by lindy65** [comment] 2018-03-07 18:23
Thanks @lindalumitchell :)

I'll close this issue off here for now then and we can track via the ticket you linked above 👍

**Closed by lindy65** 2018-03-07 18:23 UTC
