### ISSUE TITLE
New messages only visible after changing channel

### ISSUE THREAD

**Issue by noidic** [mattermost/mattermost-server#9042] opened 2018-07-03 13:28 UTC
#### Summary
I use the current version of the windows desktop app.
If new messages arrive in currently active channel, the messages are not displayed or after some time (observed delays of about 30 minutes). If I change the active channel and then change back, the new messages are displayed.

#### Steps to reproduce
Use current version of desktop app (windows), let someone else post a message into the channel currently active in the app.

#### Expected behavior
Message is displayed (almost) instantly

#### Observed behavior (that appears unintentional) 
Message does not appear until changing to another channel and changing back.

**Comment by noidic** [comment] 2018-07-05 06:37
We are using Mattermost server 5.0, team edition. The issue applies to the webapp to (tested in Firefox). As a sidenode, desktop notifications aren't working either, push notifications do.

**Comment by amyblais** [comment] 2018-07-05 15:20
Thank you for the additional details @noidic! 

I will test it out on Windows today - would you also be able to share more details on the following:

1. Your Notification settings (in Account Settings).
2. Specific Channel Notification Preferences for one of the channels where you see this issue.
3. Whether you have "Group unread channels" setting on or off (if this is enabled on your server).

**Comment by amyblais** [comment] 2018-07-05 23:51
@noidic I'm not able to reproduce this, but it might be if our settings are different. In addition to the above information I requested ^ can you also help with more details on whether this happens on DMs, public channels or any type of channels?

**Comment by noidic** [comment] 2018-07-06 14:03
Notifcation settings are Desktop for all activities, silent, show for 5 seconds, e-mail notifcations are off, push notifications when offline or away. No specific channel notification settings. Issue happens on DM and public channels, we do not use private channels. Group unread channels is not activated.
As a sidenote, the issue did not happen until we updated from 4.10 to 5.0.

**Comment by amyblais** [comment] 2018-07-09 13:15
Hi @noidic! Would you also be able to provide these additional details:

1. What Win version are you using?
2. Does this happen when you are online or when coming back from being idle?
3. Would you be able to test if the same happens on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676)?

**Comment by amyblais** [comment] 2018-07-20 14:09
Hi @noidic, we haven't received an update for a while so I'll close this Issue for now.

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by amyblais** 2018-07-20 14:09 UTC
