### ISSUE TITLE
Sync of unread count for archived channels

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11323] opened 2019-06-20 18:11 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13724)

With unread count on tab being calculated for all teams now we use team membership object keys `mention_count ` and `msg_count `

When a channel is archived which has an unread for a user the count stays team in membership object which will be out of sync wrt to LHS channel listing.

Expected: Count decreases for users who have unreads for archived channels
Observed: Count stays as it is.

**Comment by jespino** [comment] 2019-06-20 18:13
Assinged it to @RajatVaryani :)

**Comment by sudheerDev** [comment] 2019-06-20 18:18
> When a channel is archived which has an unread for a user the count stays team in membership object which will be out of sync wrt to LHS channel listing.

AFAIK We filter them on the UI as of now to keep the count in sync.

**Comment by jespino** [comment] 2019-06-20 18:21
@sudheerDev so this should be already fixed?

**Comment by sudheerDev** [comment] 2019-06-20 18:28
@jespino I just realised i create this ticket!. i think this a valid issue still count might be out of sync but either way i think it would be great if we could solve this issue server side.

**Comment by jespino** [comment] 2019-06-20 18:49
@sudheerDev Awesome :)

**Comment by sudheerDev** [comment] 2019-06-20 19:12
@jespino we fixed this on client with https://github.com/mattermost/mattermost-redux/pull/597. It rebased and picked from https://github.com/mattermost/mattermost-redux/pull/605.

I don't know the complexity involved in fixing this server side but my guess is it would be fairly complex. 

1. we have to consider existing archived channel count for various users. 
2. we have to decrease the count for all the existing users if there are any unreads in the channel after archiving.

You have to take a call on this if we want to fix this on server side.

**Comment by RajatVaryani** [comment] 2019-06-20 19:19
@sudheerDev @jespino I also verified. The values on the server side will be out of sync. Then where else is the API to get the unread message count?

**Comment by RajatVaryani** [comment] 2019-06-20 19:24
@sudheerDev Any idea is the mobile app also doing the same? Otherwise, we will have a mismatch in values.

**Comment by sudheerDev** [comment] 2019-06-20 19:25
I think it is odd the way we handled unreads for archived channels and deleted users. Whenever we archive or delete a user we remove it from LHS even if there is an unread message. 

So in order to keep the count insync with LHS we are decreasing the count but i feel we should keep the unread archived channel or deactivated user in LHS so it is obvious that there are messages to be read. Once user reads those posts then the channels are marked as read so we don't show them in LHS.

@esethna thoughts?

**Comment by sudheerDev** [comment] 2019-06-20 19:26
> @sudheerDev Any idea is the mobile app also doing the same? Otherwise, we will have a mismatch in values.

Mobile app uses the same selectors as webapp and the referenced PR has the changes in redux which are used in both the clients.

**Comment by RajatVaryani** [comment] 2019-06-26 13:12
I am analyzing how big the change on the backend it is going to be.

**Comment by jespino** [comment] 2019-06-26 13:36
If is something that is going to be huge or have a performance implication, probably we should rollback the decision of implementing it in the server side.

**Comment by RajatVaryani** [comment] 2019-06-26 14:21
The is going to be impacted because if we archive a channel containing 500 members, we would have to make 500 odd queries to decrement the count. Please correct me if I am wrong. @jespino

**Comment by jespino** [comment] 2019-06-26 17:18
Yes, It can be very hard in the backend side for highly populated channels. I'm not sure if we want to keep going here. What do you think @sudheerDev?

**Comment by sudheerDev** [comment] 2019-06-26 17:31
The reason why i raised this ticket was primarily because of the regression we caused for couple releases around unreads with archives/deactivated users because this had a separate flow and logic.

This seems stable now and i don't see a reason to do this not atleast when we know this would be a high impact code change.  If we want to consider changing the UX around it that would be great because it will decrease that logic complexity 

I feel that user should know that there are unreads from a deactivated user or from an archived channel so they can catch up to the latest posts. 
We are hiding from LHS as of now so there is no way for user to know that there are some unread messages left making it some what on the lines of missing messages. 

If we want to keep them in LHS till user reads then we wont be needing any logic of decreasing the count on clients which will decrease the entropy of the code because it will fall into usual flow or unreads.

@wiersgallak Can you go through the above and see if this is something we want to considering and create a ticket if needed?

**Comment by RajatVaryani** [comment] 2019-07-17 11:30
Bumping up! @wiersgallak What do you think?

**Comment by hanzei** [comment] 2019-09-16 10:22
@wiersgallak Gentle reminder about this

**Comment by wiersgallak** [comment] 2019-09-16 11:23
I can open a UX improvement ticket - we could consider matching Slack's behavior, where when you have an unread in a channel and the channel is archived, the channel is closed on the LHS and the unread is surpressed until the archived channel is opened after a search.

**Comment by hanzei** [comment] 2019-10-23 12:07
@wiersgallak Can you provide some next steps please?

**Comment by RajatVaryani** [comment] 2019-11-03 17:10
@wiersgallak A gentle reminder.

**Comment by jasonblais** [comment] 2019-12-21 00:08
@wiersgallak Do we have next steps for this help wanted issue? Perhaps we close this for now if it needs UX considerations?

**Comment by jespino** [comment] 2020-03-09 18:23
@wiersgallak gentle reminder

**Comment by wiersgallak** [comment] 2020-03-16 18:44
Closing this issue until we can get more direction on the UX for this.

**Closed by wiersgallak** 2020-03-16 18:44 UTC
Labels: Area/End User Feature, Difficulty/2:Medium, Help Wanted, Tech/Go
