### ISSUE TITLE
Probleme with gif and preview youtube video

### ISSUE THREAD

**Issue by proximiteclient** [mattermost/mattermost-server#11291] opened 2019-06-19 14:43 UTC
Hello, Since I update in 5.12.0 gifs are no longer displayed or youtube videos. Only the URL link is displayed ... Is this a problem already known?

**Comment by jchungvz** [comment] 2019-06-19 17:12
I just want to add that I have the same issue as well. I think it is related to the change "Fixed expand/collapse arrows not being visible for YouTube videos when image links are expanded by default." (https://docs.mattermost.com/administration/changelog.html#release-v5-12-feature-release), although I am not seeing the expand / collapse arrows for youtube links after upgrading to version 5.12. I had also tried clearing the browser cache, etc, in case that was related.

**Comment by amyblais** [comment] 2019-06-19 18:28
Hi all, do you see any Mattermost log errors or Console errors? What device and OS are you on?

**Comment by jchungvz** [comment] 2019-06-19 19:13
I don't see any errors or warning in either the mattermost.log or in the Firefox web developer console. I'm attaching the screenshot and a snippit of the log. The screenshot is redacted to prevent exposing internal server names and users.

[mattermost-log-snippit.txt](https://github.com/mattermost/mattermost-server/files/3307575/mattermost-log-snippit.txt)

![2019-06-19_14-05-15](https://user-images.githubusercontent.com/52008393/59793476-457ec480-929c-11e9-8446-76c75afe3ca0.jpg)


MatterMost Server is running on Red Hat 7

**Comment by amyblais** [comment] 2019-06-19 22:52
Are your link previews and images enabled by default?

Are link previews enabled on your server?

**Comment by zetaab** [comment] 2019-06-20 08:35
We have same issue, after updated from 5.11 -> 5.12 gifs and other images are not loaded anymore. 
Server:
Enable link previews: false
Account:
Default appearance of image previews: expanded

**Comment by jchungvz** [comment] 2019-06-20 14:21
Yes, link previews are not enabled, though I tried enabling them anyway in the System Console and then verifying that link previews were enabled in my account. The YouTube video previews still do not display.

Like the others, the issue was discovered after upgrading from MatterMost 5.11 to 5.12.

Interestingly, it appears that animated gifs seem to display fine for me, with or without link previews being enabled.

**Comment by jchungvz** [comment] 2019-06-20 21:29
Just to note, I was able to do a clean install of MatterMost 5.12 on a sandbox virtual machine, and it seems to verify the same issue with the youtube video previews not displaying (with the animated gifs displaying however).

Sandbox virtual machine setup:
MatterMost 5.12 on a CentOS 7 machine - with latest yum package updates.
MySQL 5.7.26

No special configuration setup - local authentication, etc. Besides the "DataSource" value to point to the mysql database, there are no other configuration changes in /opt/mattermost/config/config.json

My suspicion is that it is related to the recent commits in https://github.com/mattermost/mattermost-webapp/commits/master/components/youtube_video/youtube_video.jsx but that is just a guess currently.

**Comment by amyblais** [comment] 2019-06-20 23:27
Is any of you using image proxy?

**Comment by acidicX** [comment] 2019-06-21 08:49
Same here, with link preview disabled. Using the "local" setting of image proxy.

GIF preview worked before 5.12, deployed with the Docker setup.

**Comment by amyblais** [comment] 2019-06-21 12:29
Hey all, please take a look at the tips in the special note on this section of our docs: https://docs.mattermost.com/administration/image-proxy.html#local-image-proxy.

**Comment by acidicX** [comment] 2019-06-21 12:40
@amyblais I configured all IPs that I know of, but I'm not sure about Dockers internal IP resolution. I'm using nginx as a reverse proxy before handing over to Mattermost (on the same machine). Is there a way to see which requests are being blocked/not whitelisted?

**Comment by jchungvz** [comment] 2019-06-21 16:15
I was able to reproduce the youtube preview issue on a Centos 7 sandbox and on our MatterMost Dev on Red Hat 7 with MatterMost 5.12 without using the image proxy. I did try turning it on to see if there was any difference, but there wasn't. I've since turned it back off. No nginx, no docker installed on the centos 7 sandbox. Just Centos 7, mattermost 5.12 and mysql 5.7.26

The configuration file from the CentOS 7 sandbox, with the mysql password removed:
[config.json.txt](https://github.com/mattermost/mattermost-server/files/3315186/config.json.txt)

For @acidicX question, there are parameters in the `/opt/mattermost/config/config.json` to increase logging to debug level which could have more information: `"ConsoleLevel": "DEBUG",` and `"FileLevel": "DEBUG",` settings. I've also turned those on (after uploading the config file above to this comment) and I don't see any additional error messages there, although I don't have image proxy turned on. Docker running containers resolve ip addresses in `/etc/resolv.conf`, just like the host. Or, if you are looking for the Docker container's ip address, it can apparently be found in `/proc/net/fib_trie` . I personally don't think that this issue is related to docker, however. I'm not even sure it is related to image proxy or link previews since in my Centos 7 sandbox, I have those features turned off.

Still trying to reverse engineer the code, although without a background in react or go, its a bit of a steep learning curve.

**Comment by amyblais** [comment] 2019-06-21 22:08
Hi all, also, what is this setting set to on your servers: https://docs.mattermost.com/administration/config-settings.html#allow-untrusted-internal-connections-to?

**Comment by acidicX** [comment] 2019-06-24 06:57
@amyblais I've set it to `<public-hostname> 127.0.0.1 <public-ip> fe80::/0`

However: Image proxy does not seem to be the issue, I turned it off and it still did not work. I set `Enable Link Previews:` to `true` and now gif preview works again. Not sure why I have to enable this though, as it is no website preview but an image link? It seems that behaviour changed with `v5.12`?

Haven't found anything in the changelog...

**Comment by amyblais** [comment] 2019-06-24 13:24
I was able to reproduce this now, bug ticket: https://mattermost.atlassian.net/browse/MM-16545.

**Comment by jchungvz** [comment] 2019-06-24 14:27
Just curious on if anyone else can confirm that enabling the link previews to true resolves the issue with the youtube video previews ? I've tried enabling the feature on my MatterMost Dev setup and the youtube videos still do not show. Verified that "Website Link Previews" is also enabled under Account Settings.

Oddly, I've never had an issue with animated gifs - they still appear fine after upgrading to MatterMost 5.12. It has only been with Youtube video previews. I've been able to reproduce the issue regarding the youtube video previews on a clean CentOS 7 sandbox, taking out the nginx, and docker variables and working from the default mattermost configuration with minimal changes, so if anyone else can confirm that enabling the link previews also resolves the youtube video previews, it would help me to isolate the issue to just my own environment.

**Comment by acidicX** [comment] 2019-06-24 15:08
@jchungvz YouTube preview works for me with link preview enabled on 5.12 (and local image proxy enabled, not sure if that makes any difference).

**Comment by chumbalum** [comment] 2019-06-24 21:14
I can confirm this bug. I noticed the following behaviour:
If the setting "Enable Link Previews" is set to true, all **new posted** gifs will get a preview whereas already existing posts don't (we don't use image proxy, if that matters). With browser developer tools opened (with disabled cache) and a page refresh, all gifs will get a preview if "Enable Link Previews" was set to true.

Without "Enable Link Previews", no gif previews will come up

**Comment by jchungvz** [comment] 2019-06-24 23:33
Thank you. It appears that the link previews (and possibly the local image proxy) would result in the mattermost server sending out the request to generate and gather the preview image or other metadata of the website. For anyone in an environment that utilizes proxies to access the external internet, the following steps are also required in the current workaround:

- Specify the proxy URL in  `/etc/systemd/system/mattermost.service`:
```
[Service]
Environment="https_proxy=http://<username>:<my password>@<ip address>:<port>"
```

- And set the `AllowedUntrustedInternalConnections` parameter in `/opt/mattermost/config/config.json` to the proxy's IP address:
        `"AllowedUntrustedInternalConnections": "<proxy_IP_address>/32",`

This would be in addition to "Enable Link Previews" and possibly the image proxy (local) settings on Mattermost v 5.12. After that, I was then able to view the YouTube video previews and also website previews.

**Comment by amyblais** [comment] 2019-07-19 00:02
This was discussed with product managers. This change is an expected behavior in 5.12, though it is a breaking change and wasn't properly documented. Here is an explanation:

**What change was made:**
Previously image and Youtube previews were requested client-side so they worked regardless of the "Enable link previews" console setting. Link previews on the other hand were requested server-side and controlled by the "Enable link previews" console setting. Now all image, youtube and link previews are requested server-side, hence controlled by the "Enable link previews" setting.

**Why was this change necessary?**
 - Remove scroll pop with youtube and image link previews because now the dimensions and post-metadata are stored on the server instead of the client stuffing them in with no post-metadata available for scroll correction.
 - Quicker loading times of embedded content in posts since the data is stored on the server.
 - Supporting image and youtube previews as they used to work (ie backwards compatibility) will be difficult to re-add and maintain with the scrolling features we have now or what's upcoming ie bidirectional scrolling etc.

**Actions taken now:**
 - Added a note of this breaking change on our [important upgrade notes](https://docs.mattermost.com/administration/important-upgrade-notes.html).
 - Shipping a dot release fix in v5.13.1 with: 
   1. https://mattermost.atlassian.net/browse/MM-17043 which cleans up the log files around link previews that held some users back from enabling link previews.
    2. Help text updates to the console setting so it's obvious that the setting now affects image and youtube previews as well as normal link previews
 - Updated the docs around the enable link previews setting to make sure it's obvious how it works and that admins will need to make sure the Mattermost server has access within their network to the sites from which previews are expected.
   1. https://docs.mattermost.com/administration/config-settings.html#enable-link-previews 
   2. https://docs.mattermost.com/administration/config-settings.html#enable-gif-picker

**Comment by amyblais** [comment] 2019-07-23 16:24
Above action items are completed. I'll close this for now,

**Closed by amyblais** 2019-07-23 16:24 UTC
Labels: Bug Report/Open

**Comment by zetaab** [comment] 2019-07-29 11:51
@amyblais still this does not work for us. We have link previews true, gif picker on and image proxy camo enabled. When I choose gif from "emoji" button, I can see the gifs - and those are coming through camo. However, when I click the gif (like post it) it will just copy paste image url to channel but it does not display in UI. The account settings are following:

![Screenshot 2019-07-29 at 14 50 44](https://user-images.githubusercontent.com/22482503/62046299-4813f880-b210-11e9-8ead-f0706557d229.png)

**Comment by NgoHuy** [comment] 2019-08-09 04:54
The problem is time of period too short. 
Anyone with this issue can resolve by changing `Link Metadata Timeout:` in `EXPERIMENTAL -> Features`

**Comment by NgoHuy** [comment] 2019-08-09 04:58
I think Mattermost team should be written on documents.

**Comment by jasonblais** [comment] 2019-08-09 23:12
Thanks @NgoHuy! We have some documentation of this setting here https://docs.mattermost.com/administration/config-settings.html#link-metadata-timeout

Did you also have "Enable Link Previews" enabled in `System Console > Site Configuration > Posts`?

**Comment by NgoHuy** [comment] 2019-08-09 23:15
Yes, I must enable  "Enable Link Previews" in `System Console > Site Configuration > Posts`

**Comment by jasonblais** [comment] 2019-08-09 23:19
@NgoHuy Thanks! And what did you change the `Link Metadata Timeout` setting to?

**Comment by NgoHuy** [comment] 2019-08-09 23:22
I changed it to 6000, that means for 6s.

**Comment by jasonblais** [comment] 2019-08-12 13:20
Thanks! Someone on our team reproduced as well, we'll look at adding docs for it. Appreciate the report @NgoHuy!

**Comment by bbodenmiller** [comment] 2019-08-13 23:03
>  Now all image, youtube and link previews are requested server-side

@amyblais this should really be reconsidered. Many Mattermost servers are not allowed to connect directly to internet for security purposes. By removing client-side link preview loading this feature is effectively permanently broken for all these users.

**Comment by apexbryan** [comment] 2019-08-13 23:15
> @amyblais this should really be reconsidered. Many Mattermost servers are not allowed to connect directly to internet for security purposes. By removing client-side link preview loading this feature is effectively permanently broken for all these users.

Agreed, this doesn't work well in security focused enterprise situations.

**Comment by thephilz** [comment] 2019-08-14 17:04
> > @amyblais this should really be reconsidered. Many Mattermost servers are not allowed to connect directly to internet for security purposes. By removing client-side link preview loading this feature is effectively permanently broken for all these users.
> 
> Agreed, this doesn't work well in security focused enterprise situations.

I second this, @amyblais is there any chance for this to be reconsidered by the PM team? I think depending on environments 'scroll pop' is a better alternative than no image/video/youtube previews. This torpedos our usage of Mattermost, as other enterprise users mentioned our server too will never be connected to the external network; it's just IT and security policies. Proxy options are only client side for us. _It's something that will never change–_

I got a ton of 'What happened' or 'Mattermost is broken' messages after this update--now seeing this is intentional is quite the letdown..!

**Comment by zetaab** [comment] 2019-08-14 17:19
We tried to fix this issue with image-proxy, but it does not work either. https://github.com/mattermost/mattermost-server/issues/11857

So currently there is no way to have gif/image/youtube support in mattermost, if mattermost does not have internet access.

**Comment by esethna** [comment] 2019-08-14 19:50
Thanks all for the feedback. We understand the issues being faced here and I have created a follow-up ticket to investigate some potential options on our end: https://mattermost.atlassian.net/browse/MM-17825

More information on the decision can be found on the forums: https://forum.mattermost.org/t/link-previews-managed-server-side-in-v5-12-and-later/7712

**Comment by thephilz** [comment] 2019-11-04 16:06
> Thanks all for the feedback. We understand the issues being faced here and I have created a follow-up ticket to investigate if there are any potential options on our end: https://mattermost.atlassian.net/browse/MM-17825
> 
> More information on the decision can be found on the forums: https://forum.mattermost.org/t/link-previews-managed-server-side-in-v5-12-and-later/7712

I'm not sure how to understand the ticket, as it too is now closed, with a linked google doc that explains the situation. None of the proposed solutions in it actually solves the problem (as we're all saying here, many environments can't have their MM server connected to the internet–including by proxy.

The only working options for these environments are the first two alternative solutions (Re-add as a server option, re-add as a plugin).

_The regression of having page loading be worse from a UX perspective and/or break scrolling is preferable to forced server-side link previews that can't be enabled in all environments._

**Comment by amyblais** [comment] 2019-11-05 15:34
A doc PR has been submitted here to document how to configure Mattermost to connect through an outgoing proxy for organizations with strict security requirements https://github.com/mattermost/docs/pull/3096.

**Comment by thephilz** [comment] 2019-11-05 16:15
> A doc PR has been submitted here to document how to configure Mattermost to connect through an outgoing proxy for organizations with strict security requirements [mattermost/docs#3096](https://github.com/mattermost/docs/pull/3096).

As I stated in my message and others have in this thread–**_a server-side proxy is not an option in many high secure environments._** The doc PR doesn't address that, and the ticket was to look at getting it back as an option (even if it had the side-effect of springy chats scrolling).
