### ISSUE TITLE
signup_email page tooltip wrong position

### ISSUE THREAD

**Issue by kristapsdravnieks** [mattermost/mattermost-server#10461] opened 2019-03-17 14:04 UTC
#### Summary
On the signup page tooltit displayed for username field

> Username must begin with a letter, and contain between 3 to 22 lowercase characters made up of numbers, letters, and the symbols '.', '-' and '_' 

I believe it is ment to be placed under password field
containing 

> Password must begin with a letter, and contain between 3 to 22 lowercase characters made up of numbers, letters, and the symbols '.', '-' and '_'

**Comment by amyblais** [comment] 2019-03-18 12:42
Hi @kristapsdravnieks,

Thank you for reporting this,

This is currently expected but is being addressed via this ticket: https://mattermost.atlassian.net/browse/MM-14583.

Closing as duplicate of https://github.com/mattermost/mattermost-server/issues/10436. I'll ask our team if this is a UX issue or whether the help text is actually in the wrong place.

**Closed by amyblais** 2019-03-18 12:42 UTC
