### ISSUE TITLE
'Select Team' only shows first 

### ISSUE THREAD

**Issue by GCHQ77703** [mattermost/mattermost-server#13126] opened 2019-11-15 14:40 UTC
#### Summary
If you have more than 195 teams that you can join, not all of them display on the 'select_team' page.

#### Steps to reproduce
1. Create ~200 public teams with varying names.  Remember the name of the last team alphabetically.
2. Create a new user, observe this person cannot join the last five teams alphabetically.

#### Expected behavior
A user should be able to see all teams they can join.

#### Observed behavior (that appears unintentional) 
Only the first 195 teams were shown

#### Possible fixes
1. Add pagination to list more teams.
2. Show all teams available.

**Comment by amyblais** [comment] 2019-11-15 14:54
@GCHQ77703 Please help share more information about your environment from here along with Mattermost logs https://docs.mattermost.com/process/support.html?highlight=support#general-questions-for-any-issues.

**Comment by amyblais** [comment] 2019-11-15 14:57
Actually, I'll close this for now as a duplicate of this Help Wanted issue that's already open: https://github.com/mattermost/mattermost-server/issues/11265.

**Closed by amyblais** 2019-11-15 14:57 UTC

**Comment by GCHQ77703** [comment] 2019-11-15 15:21
Whoops, apparently my Github searching isn't up to par, thanks for pointing out that other issue!
