### ISSUE TITLE
[Help Wanted] [PLT-8369] Pagination for team members modal shows a next button when there are no more users to show

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7974] opened 2017-12-13 17:04 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8369)

**Comment by watadarkstar** [comment] 2017-12-13 17:22
Duplicate of #7971

**Comment by jasonblais** [comment] 2017-12-14 14:47
Thanks @watadarkstar! I've closed yours. Looks like https://github.com/mattermost/mattermost-webapp/pull/468 already fixes the issue

**Comment by lindalumitchell** [comment] 2018-02-06 21:31
Tested and verified the above-linked PR; looks great. Closing this issue, thanks!

**Closed by lindalumitchell** 2018-02-06 21:31 UTC
