### ISSUE TITLE
Post header elements overlap or hide in the mobile.

### ISSUE THREAD

**Issue by ninanung** [mattermost/mattermost-server#9873] opened 2018-11-23 05:41 UTC
Note: I think this is similar issue with [this](https://github.com/mattermost/mattermost-server/issues/8749).

#### Summary
When a username is too long, the elements in post header(reply and time) overlap with one another, or it goes behind the display.

#### Steps to reproduce
1. Set username to be a long string with API(in the account setting, i can't set username that long enough)
2. Post some test message.
3. See how it looks.

#### Expected behavior
Elements in component render normally, with enough space from each other to tell them apart

#### Observed behavior (that appears unintentional) 
Elements overlap, or hide behind the display.
![](https://postfiles.pstatic.net/MjAxODExMjNfNzIg/MDAxNTQyOTUwOTc1NTMz.glmj4XIIV46vf2rHlko89gF7eRJsUua4TdVGUDwyrjsg.l7A53cyITLVt8E_58gnrd23GhjXvTC4INGB9bnQoQM0g.PNG.ninanung/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2018-11-23_%EC%98%A4%ED%9B%84_2.29.02.png?type=w773)
![](https://postfiles.pstatic.net/MjAxODExMjNfMTY1/MDAxNTQyOTUwOTc1NTQz.4BQlAkaszkGGtPdbpELANaIWXPRt6zNKmbeRsQS-LOsg.zDPSt4sWr7hHqAEXfx28HQv6o_v8WvTj6rSmurqpGIIg.PNG.ninanung/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2018-11-23_%EC%98%A4%ED%9B%84_2.29.15.png?type=w773)

#### Possible fixes
It may be necessary to divide the sections of username, time and reply icon.

**Comment by amyblais** [comment] 2018-11-23 14:12
Hi @ninanung,

What Mattermost app version and server version are you using?

**Comment by ninanung** [comment] 2018-11-25 00:49
Thank you for your comment @amyblais,
I'm using server v5.4 and android app 1.14.0

**Comment by ninanung** [comment] 2018-11-26 08:16
Hi, @amyblais ,
I think i need to explain more about this.
This issue came from Mchat(Samsung's customed mattermost). When user start Mchat, app request SAML login data to BAS(another Samsung's system) and use it. App use BAS's username and it can be pretty long. This is the reason why issue comes out.

**Comment by amyblais** [comment] 2018-11-28 17:32
Thank you @ninanung, I'll ask our team to help test this out as I don't have an Android device. We will open a bug ticket if we can reproduce the issue.

**Comment by amyblais** [comment] 2018-11-28 21:48
Hi @ninanung, Our developers responded to me and said that a fix for this issue has been submitted for the next mobile app release (v1.15). v1.15 is scheduled to be released in December 16th.

**Comment by ninanung** [comment] 2018-11-29 01:57
Thank you @amyblais!
I will check this issue after the v1.15 release.

**Comment by amyblais** [comment] 2018-11-30 01:01
Great, I'll close this Issue for now since a fix for this has already been submitted. Please re-open this ticket if the issue persists after upgrading to v1.15.

**Closed by amyblais** 2018-11-30 01:01 UTC
