### ISSUE TITLE
Cannot type backtick on some non-English keyboards in Windows Desktop App

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9031] opened 2018-06-29 17:21 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-11077)

Similar to https://mattermost.atlassian.net/browse/MM-3274 which was fixed for Chrome.

Also from: https://github.com/mattermost/platform/issues/3696 and https://forum.mattermost.org/t/new-for-mattermost-3-1-keyboard-shorcuts/1660/2

Repro steps (on Windows 10 Home Spanish version, Desktop App):
1) Use keyboard layout 142
2) Press altgr-ù key

Observed: Keyboard Shortcuts dialog opens (which is opened via CTRL + /)

Expected: A backtick ` should be typed.

**Comment by DropNib** [comment] 2019-07-30 21:41
Hi

I wanted to request to start working on this ticket but after digging around a bit, it seems that the issue might already be fixed: https://github.com/mattermost/desktop/issues/721
I also couldn't reproduce the issue on a fresh Windows 10 Spanish install with keyboard layout 142.

So the question is if this issue still applies.

**Comment by hanzei** [comment] 2019-08-04 21:54
@esethna can you help with the above question?

**Comment by hanzei** [comment] 2019-08-05 14:24
@esethna Gentle ping

**Comment by larkox** [comment] 2019-12-02 16:22
Is this still a problem? The issue got stale a few months ago, and it seemed like it was already fixed by a different PR.

**Comment by hanzei** [comment] 2019-12-03 09:45
@deanwhillier Could you confirm that this not longer happens?

**Comment by amyblais** [comment] 2020-03-23 16:29
Closing as the Jira ticket was closed. This issue doesn't seem to be valid anymore,

**Closed by amyblais** 2020-03-23 16:29 UTC
Labels: Area/End User Feature, Difficulty/1:Easy, Good First Issue, Help Wanted, Tech/JavaScript, Tech/ReactJS, Up For Grabs
