### ISSUE TITLE
Incorrect Button Colors In Modal

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#10305] opened 2019-02-19 01:44 UTC
#### Summary
Background color for buttons with class `btn btn-default`is incorrectly set to black and is independent of the selected theme.

This was not the case before v5.8.

#### Steps to reproduce
Deploy any webapp plugin with a `Modal` containing a `Button` element. Notice it's background color. 

#### Expected behavior
The background color of `Button` should be dependent on the theme.

#### Observed behavior (that appears unintentional) 
The background color of `Button` is independent of the theme and is always black.

#### Possible fixes
The correct color is being set in `bootstrap.css` by `.btn-default`, however, it is being overridden in `style.css` by `.btn.btn-default`.

**Comment by amyblais** [comment] 2019-02-19 15:08
@sudheerDev Would you be able to help test if you can reproduce this?

**Comment by sudheerDev** [comment] 2019-02-20 08:10
@amyblais Yes i can replicate this issue we should be opening a ticket for this. 

@harshavardhana i understand the reason of using `bnt-default` as we were depending on that even in webapp modals before. 

Recently that change broke some webapp modal button styling to be black as well and we started using `btn-primary` instead for fixing this.
 
This would need discussion and eventually docs on the classes we want plugins to rely on so we can be careful of backwards compatibility before making changes similar to this.

Thanks for bringing this up 👍

**Comment by harshilsharma63** [comment] 2019-02-20 08:45
@sudheerDev just to point it out, the `btn btn-default` class is being produced by the use of `Button` react-bootstrap element.

**Comment by sudheerDev** [comment] 2019-02-20 09:26
@harshilsharma63 Right. As a default button react bootstrap has has `btn-default` stying but you could use
`<Button variant="primary">Primary</Button>` to not have the default class and use primary or `<Button variant="link">Link</Button>` which we are use a lot in webapp

**Comment by harshilsharma63** [comment] 2019-02-20 12:42
@sudheerDev neither of `primary` and `link` is alternatives of what we used to have before. `primary` makes the button blue (depending on the main color) and `link` makes it off-white.

**Comment by amyblais** [comment] 2019-02-20 14:17
Opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-14280.

**Comment by sudheerDev** [comment] 2019-02-20 16:08
@harshilsharma63 
I am looking at `btn-primary` in webapp which takes theme into effect. 
<img width="1248" alt="screenshot 2019-02-20 at 9 33 49 pm" src="https://user-images.githubusercontent.com/4973621/53105566-6423b780-3557-11e9-9f05-53901689b8f0.png">

I could be wrong but this is the reason why iam saying it could work by changing the class as a quick fix this on plugin end.

Nevertheless we have a ticket to look into this further

**Comment by amyblais** [comment] 2019-02-21 18:07
@sudheerDev Do you know if this is an issue only on the webapp or also on mobile?

Also, do you know if this is a regression from v5.8 (if yes, this probably should be fixed for v5.9)?

**Comment by asaadmahmood** [comment] 2019-02-22 02:02
@amyblais I think this was intentional as we wanted a darker color to be used as a tertiary button, especially in the system console.
For plugins etc, we need to use `btn-link` or the link variant in plugins, not `btn-default`.

**Comment by asaadmahmood** [comment] 2019-02-28 14:22
@harshilsharma63 I still have fixed that, since the different `btn-default` styling were only used in system console.
https://github.com/mattermost/mattermost-webapp/pull/2425

**Comment by amyblais** [comment] 2019-03-07 21:59
Closing this as this has been fixed for v5.10 release (to be released on April 16th).

**Closed by amyblais** 2019-03-07 21:59 UTC
