### ISSUE TITLE
[Help Wanted] [MM-12312] Server plugin: add missing API functions

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9511] opened 2018-09-30 15:45 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12312)

Original report: https://github.com/mattermost/mattermost-server/issues/9458

*Summary*
The server plugin API is missing (when comparing it with model.Client4) some functions.

*List of functions*

A community member categorized functions available for model.Client4, and these ones are most useful:

MessageHasBeenDeleted(c *plugin.Context, post *model.Post)
GetChannelMembers(channelId string, page, perPage int, etag string) (*ChannelMembers, *Response)
GetChannelsForTeamForUser(teamId, userId, etag string) ([]*Channel, *Response)
GetPostsForChannel(channelId string, page, perPage int, etag string) (*PostList, *Response)
GetTeamsForUser(userId, etag string) ([]*Team, *Response)
GetUsersInChannel(channelId string, page int, perPage int, etag string) ([]*User, *Response)
GetUsersInTeam(teamId string, page int, perPage int, etag string) ([]*User, *Response)
UpdateUserActive(userId string, active bool) (bool, *Response)

More functions listed here: 

https://github.com/mattermost/mattermost-server/issues/9458#issue-363600647

**Comment by jasonblais** [comment] 2018-09-30 15:46
Closing, duplicate of https://github.com/mattermost/mattermost-server/issues/9458

**Closed by jasonblais** 2018-09-30 15:46 UTC
Labels: Up For Grabs
