### ISSUE TITLE
Default select element in Interactive Dialogs is not selected by default

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11053] opened 2019-06-04 16:07 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15917)

Original report: https://forum.mattermost.org/t/select-element-default-value-not-displayed/7203/

**Summary**
If an Interactive Dialog has a default value in a select element, it's not selected by default.
Mattermost server v5.10

**Repro steps**
Use the API to create a dialog

**Observed**
All the select default values are not displayed:

```
'dialog': {
    'callback_id': 'callback',
    'title': 'title',
    'icon_url': 'http://www.mattermost.org/wp-content/uploads/2016/04/icon.png',
    'elements': [
        {
            'display_name': 'Task',
            'name': 'task',
            'default': 'opt1',
            'type': 'select',
            'options': [{'text': 'Option 1', 'value': 'opt1'}, {'text': 'Option 2', 'value': 'opt2'}],
            'optional': False
        }
    ],
    'submit_label': 'Submit Test',
    'notify_on_cancel': True,
    'state': 'state'
}
```

But on submit, the value default value is correctly in the payload as intended.

**Expected**
If an Interactive Dialog has a default value in a select element, it should be selected by default.

**Comment by Inconnu08** [comment] 2019-06-05 07:21
Correct me if I'm wrong but this seems to be a Tech/ReactJS problem and not Tech/Go?

**Comment by hanzei** [comment] 2019-06-06 08:52
Good catch, that is correct @Inconnu08. I fixed the labels.

**Comment by bolariin** [comment] 2019-06-11 11:42
I would like to resolve this

**Comment by hanzei** [comment] 2019-06-12 18:25
Thanks for working on this @bolariin :+1:

**Comment by hanzei** [comment] 2019-06-23 18:37
Hey @bolariin,

How are you doing with this ticket? Do you have questions?

**Comment by bolariin** [comment] 2019-06-23 21:04
@hanzei Yeah I have some questions. I had asked the question in the contributors channel but I think it got lost in the contributor channel. I was having issues using the API to create the dialog. 

I initially used Postman to create the dialog and was told that I need the `trigger_id` and I can only get the `trigger_id` by using the URL for the slash command. I setup a python server just to listen for the request and print the request. I got this error ```Post http://localhost:8885: address forbidden, you may need to set AllowedUntrustedInternalConnections to allow an integration access to your internal network.``` I found that adding the IP address or hostname to AllowedUntrustedInternalConnections in `config.json`. Adding the IP address to `config.json` did not resolve this. I asked a question about this on the contributors channel.

**Comment by hanzei** [comment] 2019-06-24 05:33
Instead of helping with resolving your issue, may I suggest to use the `/dialog` command of https://github.com/mattermost/mattermost-plugin-demo instead? You have to compile the plugin by yourself, but this is very easy.


A short idea to fix your original problem: Would you please make sure the content of `AllowedUntrustedInternalConnections` is `localhost 127.0.0.1`? Please keep in mind that changing the content of `config.json` should only be done when the server is not running.

**Comment by bolariin** [comment] 2019-06-27 14:55
I kind of have an issue with my mattermost-server. After I deploy the demo plugin, I was able to use the `/dialog` command. On restarting my server, It does not load, on the developer console, it says `To use mattermost, Please enable javascript` but my javascript is enabled.

I followed the instructions from the sample plugin to deploy the plugin.

**Comment by hanzei** [comment] 2019-06-28 05:40
What OS/Browser are you using?

**Comment by hanzei** [comment] 2019-06-28 05:40
What OS/Browser are you using?

**Comment by bolariin** [comment] 2019-06-28 11:13
elementary OS (Ubuntu) / Chrome

**Comment by hanzei** [comment] 2019-07-01 13:58
I wasn't enable to reproduce your problem. Would you please post it on the [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) on the [Mattermost community server](http://community.mattermost.com/) so a broader audience can help with debugging this.

**Comment by hanzei** [comment] 2019-09-11 11:46
Hey @bolariin,

Did you got your dev environment running?

**Comment by hanzei** [comment] 2019-09-11 14:01
Hey @bolariin, I've responded on the server to your message.

**Comment by hanzei** [comment] 2019-09-24 09:18
@bolariin Do you still encounter this problem?

**Comment by bolariin** [comment] 2019-09-28 17:46
@hanzei Yes, I'm still experiencing the issue

**Comment by bolariin** [comment] 2019-10-15 17:11
Is there an alternative way to create a dialog? For some reason, I'm having issues with the demo plugin and can't use the plugin to test out creating an interactive dialog.

**Comment by hanzei** [comment] 2019-10-15 19:52
Yes, you can use [Matterpoll](https://github.com/matterpoll/matterpoll). You can modify the "Add option button" in https://github.com/matterpoll/matterpoll/blob/master/server/plugin/api.go#L265-L289.

**Comment by bolariin** [comment] 2019-10-15 19:54
Thanks @hanzei

**Closed** 2020-01-03 13:46 UTC
Labels: Area/Toolkit, Difficulty/1:Easy, Help Wanted, PR Exists, Tech/JavaScript, Tech/ReactJS
