### ISSUE TITLE
Can I Modify the Mattermost Team Edition - Open Source?

### ISSUE THREAD

**Issue by rathishkumar** [mattermost/mattermost-server#16049] opened 2020-10-21 07:43 UTC
I am in need of Chatting app for group of students. We don’t have any budget to spend on Enterprise Edition. Features of Open Source Team Edition is sufficient for us our activities.

Can I modify the code for our internal use? License is bit confusing. So I am asking again, Is Team Edition Open Source is under MIT license? Can I modify as I wish (w/o branding as Mattermost).

I will be rebranding as per my requirement and will not include anything related to Mattermost (as other cases in OSS).

My project is not for commercial purpose, incase if I have to redistribute, I will include all the changes and same MIT license (distribution is nowhere in the plan).

Please give me a DIRECT ANSWER consider me as non-technical user, w/o making me go through a huge doc, simply I don’t have time.

Thanks for making this wonderful software.

**Comment by amyblais** [comment] 2020-10-21 14:48
I'll close this as a duplicate of https://forum.mattermost.org/t/can-i-modify-the-mattermost-open-source/10588.

**Closed by amyblais** 2020-10-21 14:48 UTC
