### ISSUE TITLE
User and status icons and the status dropdown menu dissappears in narrow screen

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/mattermost-server#7589] opened 2017-10-06 07:44 UTC
#### Summary
User icon and status changing icon and dropdown menu dissappears if the Mattermost screen is too narrow like in mobile screen (happens in desktop 3.7.1 also).

#### Steps to reproduce
Change the Mattermost client or browser window narrower than 785px and open the left sidebar.

#### Expected behavior
User icon and status icon should appear on the top of the left sidebar.

#### Observed behavior (that appears unintentional) 
User icon and status indicator do not show up.

Linked to this you cannot change your status on mobile device nor in desktop if the window is narrow. 
I did not find conversation regarding this issue or feature but I think that the status should be editable also from the mobile apps and the latest change from any client should rule (meaning this would be very nice feature).

**Comment by lindy65** [comment] 2017-10-09 16:38
Hi @kaksikanaa,

Thank you for your feedback,

What you're describing above is currently by design.  Perhaps you'd like to open a feature suggestion on our [forum](https://mattermost.uservoice.com/forums/306457-general) where you and others can upvote it to increase it's popularity.

**Comment by lindy65** [comment] 2017-10-18 09:11
I'll close this issue off for now and perhaps @kaksikanaa can link back the feature suggestion once he's created it.

**Closed by lindy65** 2017-10-18 09:11 UTC
