### ISSUE TITLE
Reducing size of YouTube preview ?

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#8005] opened 2017-12-25 18:39 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: http://www.mattermost.org/filing-issues/

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please report using the following format: 

#### Summary
Currently 2 YouTube video previews fill up the whole page/screen

#### Steps to reproduce
Version: 4.5.0

#### Expected behavior
Previews should ideally be smaller in size and clicking on the preview should either,
1. Launch a modal like player to play the video and then close when done
2. Expand the video on "play"

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Currently just 2 videos fill up the whole page which isn't too ideal,

Mattermost,
Whole page taken up by the image previews,

![image](https://user-images.githubusercontent.com/363587/34342262-48d8a91e-e9d0-11e7-825c-2dd40af9254d.png)

HipChat,
Just took up around the normal area of say ~6-8 text messages,

![hipchat_2017-12-26_00-04-43](https://user-images.githubusercontent.com/363587/34342281-e3221c4e-e9d0-11e7-9acc-9f06a7621b77.png)

Clicking on the Thumbnail in HipChat opens up a modal like player which plays the video, similar to what Mattermost has for normal video files.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

1. Reduce the image / thumbnail size to as least as possible, and re-size or so when actually playing the video
or
2. Open the video in a modal like player which plays the video similar to what mattermost does for normal video files.

**Comment by lindy65** [comment] 2017-12-28 08:43
Hi @arjitc,

Thanks for your feedback,

Although I have reproduced your issue on our nightly build server, I believe this is by design and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8453) for one of our product managers to take a look at and verify the expected.

They're out for the holidays but will respond after January 2nd.

**Comment by arjitc** [comment] 2017-12-28 23:17
Thank you @lindy65

**Comment by lindy65** [comment] 2018-01-09 20:02
I'll close this off for now and we can track via the ticket linked above.

**Closed by lindy65** 2018-01-09 20:02 UTC
