### ISSUE TITLE
Mattermost does not load after upgrade to 4.7.2

### ISSUE THREAD

**Issue by limenleap** [mattermost/mattermost-server#7465] opened 2017-09-18 14:41 UTC
#### Summary
Mattermost 4.2 does not load in Windows browsers (Chrome and Firefox and Opera and Microsoft Edge) Works fine on the Android  and iPhone app. 
#### Steps to reproduce
Upgrade to 4.2 following the instructions given on the Mattermost site.  Then start Chrome or Firefox and give the url as that of the mattermost server http://chat.tad.in.net

#### Expected behavior
Expected to get the login screen but does not happen at all.  

Versions of browsers being used:
Windows 10 Firefox 55.0.3 (32 bit)
Windows 10 Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Windows 10 Opera  Version 47.0.2631.71 (PGO)
Windows 10 Microsoft Edge 40.15063.0.0

#### Observed behavior (that appears unintentional) 
The default loading page is shown with the animation of the three dots.  Nothing gets loaded. I tried clearing the cache, cookies, using a private browser window, restarting the server, restarting Nginix, rebooting the server, restarting the windows client machine, installed Fiddler to see what is going across, etc, etc. No idea what is going wrong. Spent two days on this. But adamantly, it just shows the animation of the three dots at the beginning and does not proceed

Sometimes I get an error in the console as follows (Note the curious "undefined" at the end):

jQuery.Deferred exception: window.mm_config is null r@http://chat.tad.in.net/static/main.1e36730a59d3633263b2.js:1:2459518
n/<@http://chat.tad.in.net/static/main.1e36730a59d3633263b2.js:1:1682535
l@http://chat.tad.in.net/static/main.1e36730a59d3633263b2.js:1:42253
fireWith@http://chat.tad.in.net/static/main.1e36730a59d3633263b2.js:1:43024
c@http://chat.tad.in.net/static/main.1e36730a59d3633263b2.js:1:44280
o/</u<@http://chat.tad.in.net/static/main.1e36730a59d3633263b2.js:1:44327
 undefined

Sometimes I get this after a long, long time in the browser console of Opera

bootstrap 1e36730a59d3633263b2:98 Uncaught (in promise) Error: Loading chunk 38 failed.
    at n (bootstrap 1e36730a59d3633263b2:98)

#### Possible fixes
It works fine on the Android Mattermost (Beta) app  Also works fine on the iPhone app

**Comment by ccbrown** [comment] 2017-09-18 17:21
Looks like there's something going on at the TCP level, which would explain why it's OS-specific and not browser-specific. The connection used by the first API request always breaks:

![image 1](https://user-images.githubusercontent.com/1731074/30554913-a3403316-9c6b-11e7-972c-6df22cccb40a.png)

Can you try connecting to the server directly, without going through NGINX?

**Comment by limenleap** [comment] 2017-09-19 05:06
Thank you for your efforts. I think the Mattermost server which is proxied by Nginx is tied only to the localhost. I don't know how to configure Mattermost so that I can directly access it from my browser. I would really appreciate your advise. I need to get to the bottom of this as lot of users are waiting

**Comment by limenleap** [comment] 2017-09-19 06:02
I just checked this on Ubuntu 16.04  on the same machine as the Windows one.  It works fine on Ubuntu! So evidently there is something going on in Windows. Initially I thought it could be an issue of some virus attack on my specific machine. But it looks like @ccbrown also has experienced the same issue. This is most perplexing. I am supporting a free software with this Mattermost, and all my users use Windows as the free software runs on Windows -- and we are all stuck!

**Comment by limenleap** [comment] 2017-09-19 06:04
One more clue: A few days before this, there was a massive update from Microsoft for Windows 10. It took a few hours to finish that update. Could that have a bearing on this issue?

**Comment by limenleap** [comment] 2017-09-20 06:31
How I wish this problem would get solved.

This seems to be like a major deal breaker.  We are currently a small set of users of around 160 people and I am getting frantic calls from them as I cannot provide support for now almost 4 days.

Most likely it is something to do specifically with Windows and possibly Mattermost developers may not have nothing to do with it.  Nevertheless, I would have thought this was an opportunity for the Mattermost team to cater to this particular quirk in Windows

Strangely, the API is still working! Yes, from Windows itself!

It looks like I have to quit using Mattermost and migrate to something else. Though not sure how the migration can really happen... Now need to worry about that too! I hope before the migration there is a good explanation for this odd behaviour

**Comment by ccbrown** [comment] 2017-09-20 06:38
For what it’s worth, we aren’t ignoring the issue. I’ve been asking around in the dev channels to see if anyone knows what might be up. I’ve got nothing though.

If you want to try exposing Mattermost directly, without NGINX, see the `ListenAddress` configuration: https://docs.mattermost.com/administration/config-settings.html#configuration

You probably just need to stop NGINX, change that to “:80”, and restart Mattermost. Might need to also do something to allow binding to such a low port number depending on the server OS.

**Comment by limenleap** [comment] 2017-09-20 07:11
Thank you for your efforts. I am obliged and grateful

I have changed the configuration so that the Go server of Mattermost is exposed to the outside world too. However I retained the port (4444) just so that the behaviour with the Nginx proxy can also be checked

Yes, it is now working! http://chat.tad.in.net:4444 is now working on Windows too. That is good news. And the Nginx proxy is still behaving as before -- just the loading screen and nothing else

So somewhere the Nginx configuration is in conflict with whatever that the latest update of Windows 10 is doing

I will leave the port intact (4444) for now so that your developers now have both the methods available (one through the Go server of Mattermost on port 4444, and the other using Nginx on port 80)  If no solution is found, then I will simply stop Nginx and live with the Go server, serving out at 80

Thanks a lot. At least there is a way out :-)

**Comment by limenleap** [comment] 2017-09-20 14:56
I have stopped the Nginx server on http://chat.tad.in.net Now it is only the Go server there.  Kindly let me know if anything progresses on this issue

Thank you !

**Comment by jasonblais** [comment] 2017-09-21 13:40
@limenleap Are there any errors in your NGINX logs? 

Also, this page may or may not be helpful: https://blog.serverdensity.com/troubleshoot-nginx/

**Comment by lindy65** [comment] 2017-10-04 08:36
Hi @limenleap, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by jabis** [comment] 2018-03-03 08:00
I'm having this exact same issue on both 
Chrome 64.0.3282.186 (Official Build) (64-bit) (cohort: Stable) 
and 
FireFox 58.0.2 (64-bit) after upgrading the server to 4.7.2 mobile and tablet work fine, but accessing thru webpage gives blank result:

![image](https://user-images.githubusercontent.com/27401/36931933-24e377de-1ef3-11e8-9018-2a46468ce552.png)
![image](https://user-images.githubusercontent.com/27401/36931937-3a5efb4c-1ef3-11e8-8d50-98a89e43e935.png)

**Comment by jabis** [comment] 2018-03-04 13:06
@jasonblais not via mattermost itself, but yes it's letsencrypt certificate Nginx terminating the SSL, proxying to MM server. Note that Mobile mattermost clients work with the configuration, and only thing changed was the update to 3.7.1. I upgraded immediately to 3.8.0-rc1 (creating another database from earlier 3.6-version) and that seemed to have resolved it, tho I am a little hesitant to be using an RC version in production, it seems to have corrected my problem.

**Comment by jabis** [comment] 2018-03-04 13:11
My NginX conf has stayed the same:

```  
server {
  server_name mm.omega.coder.fi;
  include /usr/local/nginx/conf/le-coder.conf;
  ssl_certificate /etc/letsencrypt/live/omega.coder.fi/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/omega.coder.fi/privkey.pem;
  listen 443 ssl;
  ssl on;
  ssl_session_timeout  1d;
  ssl_session_cache  shared:SSL:50m;
  ssl_session_tickets  off;

  ssl_dhparam    /etc/ssl/certs/dhparam.pem;  
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';  #generate here: https://mozilla.github.io/server-side-tls/ssl-config-generator/

  # OCSP Stapling ---
  # fetch OCSP records from URL in ssl_certificate and cache them
  ssl_stapling   on;
  ssl_stapling_verify  on;
  error_log   /opt/mattermost/logs/mm.error.log;
  access_log  /opt/mattermost/logs/mm.access.log;

  location ~ /api/v[0-9]+/(users/)?websocket$ {
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       client_max_body_size 50M;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_pass http://192.168.2.251:8065;
   }

   location / {
       client_max_body_size 50M;
       proxy_set_header Connection "";
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Frame-Options SAMEORIGIN;
       proxy_buffers 256 16k;
       proxy_buffer_size 16k;
       proxy_read_timeout 600s;
       proxy_cache mattermost_cache;
       proxy_cache_revalidate on;
       proxy_cache_min_uses 2;
       proxy_cache_use_stale timeout;
       proxy_cache_lock on;
       proxy_pass http://192.168.2.251:8065;
   }
}
```

**Comment by lindy65** [comment] 2018-03-05 07:01
Hi @jabis 

I've reopened this issue so we can help troubleshoot.  I've asked our engineers for input and either they or I will post back here with feedback...

**Comment by jabis** [comment] 2018-03-05 16:52
Hi @lindy65, 
Thanks for re-opening. You might see from the screenshots that I even tried disabling gzip and everything that I thought could spasm out the client - but no configuration option could sort it out. Immediately after updating to 4.8.0-rc1 the service was restored - I'm just guessing here but was there a change in webpack version between the 4.7.2 release and 4.8?

**Comment by lindy65** [comment] 2018-03-06 06:52
Hey @jabis,

I've asked our engineers about the change to webpack version you asked about so will let you know...

In the meantime, I'm wondering if we can ask your help to open a new GitHub issue for your input here from [this comment](https://github.com/mattermost/mattermost-server/issues/7465#issuecomment-370128651)...  It was a couple of months since we closed this issue and it's better for us to track and troubleshoot your issue in a new one as it might not be related to the original report and a new ticket will get more traffic...

Sorry for the additional work!  I'll close this one off here so please mention me in the new issue you open and we can continue from there?

**Closed by lindy65** 2018-03-06 06:52 UTC
