### ISSUE TITLE
Double dashes in mobile inside code block get converted to emdash

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9432] opened 2018-09-18 16:12 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12148)

One way to solve this might be to detect that the user is currently typing code and set the TextInput's autocomplete prop to false when this is happening

h3. Steps to Reproduce
0. iOS, 1.12.0
1. Open a code block (triple backticks, itself a hard chore on the keyboard)
2. Type some code, including two dashes (e.g. as part of a command )
3. Post message

h3. Expected
1. Double dashes preserved

h3. Observed
1. At some point in the composing, the double dashes get silently converted to an emdash.

**Comment by imisshtml** [comment] 2019-06-09 05:55
I'm working on this issue

**Comment by hanzei** [comment] 2019-06-09 06:50
Thanks @imisshtml :+1:

**Comment by imisshtml** [comment] 2019-07-01 15:36
Still working on this issue. Had success in stopping the double-dash, but solution produced another bug in testing, so reevaluating how to approach this issue.

**Comment by hanzei** [comment] 2019-09-11 11:45
@imisshtml Just want to check if you are still working on this

**Comment by chuttam** [comment] 2019-09-17 18:37
> Still working on this issue. Had success in stopping the double-dash, but solution produced another bug in testing, so reevaluating how to approach this issue.

Awesome @imisshtml ! I faced the opposite problem, and I can account for the double-dash **after** iOS already applies Smart Punctuation to the entered text. So, could you give me a tip/pointer/solution for how to stop the double-dash itself, and perhaps we could come together with a joint resolution?

**Comment by chuttam** [comment] 2019-09-17 18:44
> One way to solve this might be to detect that the user is currently typing code and set the TextInput's autocomplete prop to false when this is happening

I can confirm that setting `autoCorrect={false}` and/or `autoCompleteType='off'` on the `<TextInput>` have no effect on the entered text. iOS still replaces `--` with `–` instantly, which makes sense since the auto-correction likely happens well before the (changed) character is even received by the app as text input. Boo.

**Comment by chuttam** [comment] 2019-09-21 00:00
I thought I'd replace `–` emdash occurrences back to `--` in the `onChangeText` handler.

The trouble is that iOS Smart Punctuation converts both `--` **and** `---` to an emdash. So when entering a third dash now, iOS sends over a single, converted emdash, which the replace logic now converts to a double dash, instead of the desired triple dash!

User types `--`
iOS converts to `–`
onChangeText converts to `--` (so far so good)

User now tries to type `-` (i.e. a third `-` after the current `--`)
iOS converts `---` to `–`
onChangeText converts to `--` (losing the third `-` entry)

Any ideas?

**Comment by esethna** [comment] 2019-09-21 01:17
Thanks @chuttam, @hmhealey any thoughts on the implementation here? Seems like the onChangeText fix mentioned above is better than what we have now but still not ideal.

**Comment by hmhealey** [comment] 2019-09-24 14:02
I don't think that would work since a user could type an emdash on purpose.

If disabling both autocorrect and autocomplete doesn't stop that behaviour, I don't think there's anything we can do here. It seems like this is built into the iOS keyboard like how double tapping space puts a period followed by a space, so we might be stuck here. I'd suggest we look to see if any other app prevents this behaviour, and if we can't find anyone else who's solved this, then we'll just have to close this ticket.

**Comment by chuttam** [comment] 2019-09-24 14:07
Thanks for looking into this @hmhealey . I kinda hit this wall too.

**Comment by imisshtml** [comment] 2019-10-12 17:58
I'm going to release this one back into the wild! In researching though I ran into the same issues and in further discussing with @enahum, it looks like we will need to address this by overriding the Native Module for the text input.

From @enahum:

> Perhaps just extend the RCTTextInput and set it to `textView.automaticQuoteSubstitutionEnabled = NO;`
> I think we are already extending it in `MattermostManaged.m` and actually we could even remove it from there and create a `Mattermost+RCTUITextView` class
>

**Comment by ami9000** [comment] 2020-02-03 08:10
Hi folks. I think I can solve this without overriding Native Modules, etc. Can I take a crack at this?

**Comment by hanzei** [comment] 2020-02-03 08:41
That would be great, thanks @ami9000 :+1:

**Closed** 2020-02-26 23:51 UTC
Labels: Area/End User Feature, Difficulty/2:Medium, Good First Issue, Help Wanted, Tech/React Native
