### ISSUE TITLE
Slack Import not working at all for me

### ISSUE THREAD

**Issue by fmantek** [mattermost/mattermost-server#8761] opened 2018-05-10 14:42 UTC
#### Summary
Using an output.zip file, created with the advanced exporter, import is doing absolutely nothing

#### Steps to reproduce
Download my zip file from ftp://ftpuser@mantek.noip.me/output.zip. Use none as the pwd. Log into the instance and use 
the command: sudo ./platform import slack "yourteam" output.zip 

#### Expected behavior
Expected to get a good 10 channels with a lot of posts recreated, including uploads done to the local server. 

#### Observed behavior (that appears unintentional) 
Nothing. Mattermost log, set to debug, produces this:

2018/05/10 14:31:25 UTC] [INFO] Using config file at /opt/bitnami/apps/mattermost/server/config/config.json
[2018/05/10 14:31:25 UTC] [INFO] Loaded system translations for 'en' from '/opt/bitnami/apps/mattermost/server/i18n/en.json'
[2018/05/10 14:31:25 UTC] [INFO] Server is initializing...
[2018/05/10 14:31:25 UTC] [DEBG] Parsing server templates at /opt/bitnami/apps/mattermost/server/templates
[2018/05/10 14:31:25 UTC] [INFO] Pinging SQL master database
[2018/05/10 14:31:25 UTC] [DEBG] Deleting any unused pre-release features
[2018/05/10 14:31:25 UTC] [DEBG] Initializing built-in plugin: ldapextras
Running Slack Import. This may take a long time for large teams or teams with many messages.
[2018/05/10 14:31:26 UTC] [INFO] Post.Message supports at most 16383 characters (65535 bytes)
[2018/05/10 14:31:26 UTC] [INFO] Purging all caches
[2018/05/10 14:31:26 UTC] [DEBG] We could not find the license key in the database or on disk at /opt/bitnami/apps/mattermost/server/config/mattermost.mattermost-license
F
#### Possible fixes
Point me to the importer code and I probably can fix it myself.

**Comment by amyblais** [comment] 2018-05-11 00:05
Hi @fmantek, 

Thank you for reporting this,

I just have a few initial questions:
1. Which Mattermost server version are you seeing this issue on?
2. Is there anything on this doc that might help: https://docs.mattermost.com/administration/migrating.html?highlight=slack%20export#migrating-from-slack?

**Comment by fmantek** [comment] 2018-05-11 13:55
1. This is working against a bitnami installation on a google cloud instance. The default installation was upgraded to 4.9.2 before attempting the slack import.

2. Nope. Already read this doc and am using the CLI version of importing.


Gruss


Frank Mantek

**Comment by fmantek** [comment] 2018-05-14 14:06
I have tried this with the default bitnami installation, where it failed with the issue, that only the first user got imported. Which was supposed to be fixed in 4.9.2, hence I tried that.

Let me know if I can help, or if you like me to test a fix.

Gruss


Frank Mantek

**Comment by matshch** [comment] 2018-05-14 16:03
Also applies to us.

**Comment by amyblais** [comment] 2018-05-14 16:45
@matshch Just wanted to check, which version of Mattermost are you using?

**Comment by matshch** [comment] 2018-05-14 17:30
We are using Omnibus (now on gitlab-ee 10.7.3, tried also on 10.6.4), Mattermost now reports 4.8.1.

**Comment by amyblais** [comment] 2018-05-14 22:35
@matshch Would you also have any error logs for us to take a look?

Turns out the file I was testing with was corrupt so that is why I was seeing issues earlier, and I asked a co-worker to test as well and she could not reproduce the issue.

I will have our team take a further look at this.

**Comment by matshch** [comment] 2018-05-15 05:55
That's what we are getting:
[MattermostImportSummary.txt](https://github.com/mattermost/mattermost-server/files/2003596/MattermostImportSummary.txt)

So, only two users are created — one is the real and other is "Integrations/Slack Boot".

We tried this on several exports, including created with https://github.com/grundleborg/slack-advanced-exporter, and getting the same issues.

**Comment by fmantek** [comment] 2018-05-15 06:03
Did you try the file I provided you with?

Gruss


Frank Mantek

**Comment by amyblais** [comment] 2018-05-15 12:31
@matshch Is this a new issue (did you recently upgrade or start to use Mattermost) or has this been happening for a while?

@fmantek We are releasing a new version (4.10) tomorrow and it might be a good idea to upgrade and see if the issue reproduces after upgrading. Another option is that you can test the file on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and see if the issue reproduces there.

Let me know if these suggestions sound good?

**Comment by matshch** [comment] 2018-05-15 12:55
This is a new issue. We thinking of switching on Mattermost, so we
self-hosted it, tried it in test workload for two weeks, and then tried to
import backup from Slack. When we have seen that only a few messages and
users was imported, we tried to start over, with DB removing, reconfiguring
and starting import again, with no success. Then we tried same actions
after upgrade, same result.

> --

С уважением,
Артем

**Comment by amyblais** [comment] 2018-05-16 17:40
@matshch @fmantek We released 4.10 today, would you like to upgrade and see if the issue reproduces after upgrading?

**Comment by fmantek** [comment] 2018-05-16 17:42
Should I still disable email notifications after the upgrade to 4.10 if I use the CLI?

Frank

**Comment by amyblais** [comment] 2018-05-16 18:05
It might be the best option, as the issue with Slack import failing through the CLI if email notifications are enabled was not fixed in 4.10 (it remains as a known issue for now).

**Comment by fmantek** [comment] 2018-05-16 18:17
Ok, just tried this with my output.zip file.  Here is the output from the platform command:

sudo ./platform import slack TestForImport /opt/bitnami/output.zip
{"level":"info","ts":1526494324.2533443,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/opt/bitnami/apps/mattermost/server/i18n/en.json'"}
{"level":"info","ts":1526494324.2539353,"caller":"app/app.go:181","msg":"Server is initializing..."}
{"level":"debug","ts":1526494324.2540326,"caller":"utils/html.go:29","msg":"Parsing server templates at /opt/bitnami/apps/mattermost/server/templates"}
{"level":"info","ts":1526494324.2728744,"caller":"sqlstore/supplier.go:198","msg":"Pinging SQL master database"}
{"level":"debug","ts":1526494324.2988849,"caller":"sqlstore/preference_store.go:41","msg":"Deleting any unused pre-release features"}
{"level":"debug","ts":1526494324.3003356,"caller":"app/plugin.go:45","msg":"Initializing built-in plugin","plugin_id":"ldapextras"}
Running Slack Import. This may take a long time for large teams or teams with many messages.
{"level":"info","ts":1526494324.536853,"caller":"sqlstore/post_store.go:1243","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"info","ts":1526494324.605299,"caller":"app/admin.go:140","msg":"Purging all caches"}
{"level":"debug","ts":1526494324.6061473,"caller":"utils/license.go:83","msg":"We could not find the license key in the database or on disk at /opt/bitnami/apps/mattermost/server/config/mattermost.mattermost-license"}
{"level":"info","ts":1526494324.6065667,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
Finished Slack Import.
{"level":"info","ts":1526494324.6067367,"caller":"app/app.go:225","msg":"Stopping Server..."}
{"level":"info","ts":1526494324.6068091,"caller":"app/web_hub.go:112","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1526494324.6068723,"caller":"app/web_hub.go:117","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1526494324.6069245,"caller":"sqlstore/supplier.go:761","msg":"Closing SqlStore"}
{"level":"info","ts":1526494324.6072507,"caller":"app/app.go:245","msg":"Server stopped"}

At the end of this, server is running, I have 2 new slack import users in the user list (both deactivated), but that is it. No channels, no messages, nothing.

This is missing some serious logging :). Or is slack import considered to be an enterprise feature?

Frank
ls

**Comment by amyblais** [comment] 2018-05-17 15:43
Hi all! Just wanted to let you know that I have asked our engineers to take a look at this!

**Comment by matshch** [comment] 2018-05-17 16:31
@amyblais we have tried to deploy 4.10 via docker, and have successfully imported our data from Slack in this instance. However, threads information was lost during import, and this unfortunately doesn't fit our needs.

**Comment by amyblais** [comment] 2018-05-18 22:50
Just wanted to give you an update that our engineers are working on testing this to see if they can reproduce the issue.

One thing to note is that we don't currently support importing threads - if this is something you would like us to add, please [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html). If you submit a feature request, please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by lieut-data** [comment] 2018-05-19 18:29
@fmantek, there's definitely a bug in the Slack importer that is incorrectly suppressing logs when using the command line importer. I've filed https://mattermost.atlassian.net/browse/MM-10684 to get that resolved.

Working around that, I see the same behaviour when importing your Slack export -- basically nothing seems to happen. The slack importer is expecting files in very particular places, but I notice that the root of your export looks like:
```
'TheManteks Slack export May 4 2018'/
__MACOSX/
__uploads/
```

Was this a vanilla export from Slack? The contents of the `'TheManteks Slack export May 4 2018'` folder contain the needed files, but `__uploads` aren't located where the importer expects them either.

It's possible Slack has changed their export format. If you can let us know when and how this export was made, we can probably assist in addressing the import failure.

**Comment by fmantek** [comment] 2018-05-19 20:45
Done with the advanced slackexporter from git hub, that I had to modify as well as the slack export format seem to have changed.

If you tell me what the importer expects I can probably fix that.

Gruss


Frank Mantek

**Comment by lieut-data** [comment] 2018-05-23 13:41
@fmantek, the importer is essentially expecting everything in the root of the zip:
* channels.json
* users.json
* <channel_name>/*.json
* __uploads/

I suspect when you modified it, your zip program repackaged things to add the extra `TheManteks Slack export May 4 2018` folder within, as well as relocated the `__uploads` folder.

Let me know if that helps you make progress!

**Comment by amyblais** [comment] 2018-05-30 21:49
Hi @fmantek! Did Jesse's instructions above help? 

Optionally we can also track this issue through the ticket that was opened.

**Comment by fmantek** [comment] 2018-05-31 06:13
Sorry, was on a business trip. Will try this weekend.

Frank

**Comment by fmantek** [comment] 2018-06-01 18:35
Ok, so just tried it, carefully making sure the zip file is correct. 

Using the GUI it does not work at all, but, heck, it is a 2.4GB zip file, I am not too surprised.

Command line: I am getting output, but a lot of errors:

"level":"info","ts":1527877656.501212,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/opt/bitnami/apps/mattermost/ser
ver/i18n/en.json'"}
{"level":"info","ts":1527877656.5018897,"caller":"app/app.go:181","msg":"Server is initializing..."}
{"level":"debug","ts":1527877656.502033,"caller":"utils/html.go:29","msg":"Parsing server templates at /opt/bitnami/apps/mattermost/server/templates"}
{"level":"info","ts":1527877656.504475,"caller":"sqlstore/supplier.go:198","msg":"Pinging SQL master database"}
{"level":"debug","ts":1527877656.5589898,"caller":"sqlstore/preference_store.go:41","msg":"Deleting any unused pre-release features"}
{"level":"debug","ts":1527877656.5605004,"caller":"app/plugin.go:45","msg":"Initializing built-in plugin","plugin_id":"ldapextras"}
Running Slack Import. This may take a long time for large teams or teams with many messages.
{"level":"info","ts":1527877660.547828,"caller":"sqlstore/post_store.go:1243","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"warn","ts":1527877661.0214381,"caller":"app/slackimport.go:160","msg":"Slack Import: User {{.Username}} does not have an email address in the Slack export. Used {{.Email}} as a placeholder. The user should update their email address once logged in to the system."}
{"level":"error","ts":1527877667.4902422,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877684.0545132,"caller":"app/file.go:535","msg":"Unable to upload thumbnail path= err=WriteFile: Encountered an error writ
ing to local server storage, open /opt/bitnami/apps/mattermost/data: is a directory"}
{"level":"error","ts":1527877684.0932286,"caller":"app/file.go:557","msg":"Unable to upload preview err=WriteFile: Encountered an error writing to l
ocal server storage, open /opt/bitnami/apps/mattermost/data: is a directory","path":""}
{"level":"error","ts":1527877690.2875142,"caller":"app/file.go:535","msg":"Unable to upload thumbnail path= err=WriteFile: Encountered an error writ
ing to local server storage, open /opt/bitnami/apps/mattermost/data: is a directory"}
{"level":"error","ts":1527877691.130025,"caller":"app/file.go:557","msg":"Unable to upload preview err=WriteFile: Encountered an error writing to lo
cal server storage, open /opt/bitnami/apps/mattermost/data: is a directory","path":""}
{"level":"error","ts":1527877692.9070563,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877696.9158273,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877700.5685725,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877702.344082,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877704.6814837,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877714.1926076,"caller":"app/file.go:535","msg":"Unable to upload thumbnail path= err=WriteFile: Encountered an error writ
ing to local server storage, open /opt/bitnami/apps/mattermost/data: is a directory"}
{"level":"error","ts":1527877714.7798293,"caller":"app/file.go:557","msg":"Unable to upload preview err=WriteFile: Encountered an error writing to l
ocal server storage, open /opt/bitnami/apps/mattermost/data: is a directory","path":""}
{"level":"error","ts":1527877715.3963165,"caller":"app/file.go:535","msg":"Unable to upload thumbnail path= err=WriteFile: Encountered an error writ
ing to local server storage, open /opt/bitnami/apps/mattermost/data: is a directory"}
{"level":"error","ts":1527877716.0688016,"caller":"app/file.go:557","msg":"Unable to upload preview err=WriteFile: Encountered an error writing to l
ocal server storage, open /opt/bitnami/apps/mattermost/data: is a directory","path":""}
{"level":"error","ts":1527877723.346665,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"warn","ts":1527877739.6656938,"caller":"app/slackimport.go:407","msg":"Slack Import: An error occurred when uploading file {{.FileId}}: {{
.Error}}."}
{"level":"error","ts":1527877751.6430984,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877757.2211123,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"warn","ts":1527877767.2771938,"caller":"app/slackimport.go:407","msg":"Slack Import: An error occurred when uploading file {{.FileId}}: {{
.Error}}."}
{"level":"error","ts":1527877767.7457385,"caller":"app/file.go:535","msg":"Unable to upload thumbnail path= err=WriteFile: Encountered an error writ
ing to local server storage, open /opt/bitnami/apps/mattermost/data: is a directory"}
{"level":"error","ts":1527877768.310269,"caller":"app/file.go:557","msg":"Unable to upload preview err=WriteFile: Encountered an error writing to lo
cal server storage, open /opt/bitnami/apps/mattermost/data: is a directory","path":""}
{"level":"error","ts":1527877784.2287507,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877784.3960032,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877789.651494,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877799.23807,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877802.1336865,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877818.5405648,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877831.9724107,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877888.3470747,"caller":"app/file.go:453","msg":"Unable to decode image err=image: unknown format"}
{"level":"error","ts":1527877908.4036615,"caller":"app/file.go:535","msg":"Unable to upload thumbnail path= err=WriteFile: Encountered an error writ
ing to local server storage, open /opt/bitnami/apps/mattermost/data: is a directory"}
{"level":"error","ts":1527877909.6356611,"caller":"app/file.go:557","msg":"Unable to upload preview err=WriteFile: Encountered an error writing to l
ocal server storage, open /opt/bitnami/apps/mattermost/data: is a directory","path":""}

as a start. There seem to be 2 issues: the data directory and the image format. Anything I can do?

Frank

**Comment by fmantek** [comment] 2018-06-02 07:14
So, going into the server, I see that, e.g., I have something like this in the data directory:

directory: 
20170601/teams/8fhbm1xnppg3z8ia99j67b5xdh/chan
nels/rm87kexcdbrxjj47ytiamqkpyc/users/asoc4ygq4pgs7yk8f9bp6ejj7y/qi63fcw74pnr5mbzn4ra8okuze

-rw-r--r-- 1 root root 1758699 Jun  1 18:29 Image uploaded from iOS.jpg
-rw-r--r-- 1 root root  254882 Jun  1 18:29 Image uploaded from iOS_preview.jpg
-rw-r--r-- 1 root root    8670 Jun  1 18:29 Image uploaded from iOS_thumb.jpg

so files are there. But when I am using any UI (web, app, mobile), images never load.

**Comment by fmantek** [comment] 2018-06-02 07:21
A little more. Using the web, this is the DIV that of one of the posts. What I find curious is that the profile image loads fine (and is a fully fleshed URL), where the content image is just a file name.

<div><div id="post_738eth8sdi8budnhc15p6un5th" class="post  other--root  current--user"><div class="post__content "><div class="post__img"><span class="status-wrapper"><img class="more-modal__image" alt="frank profile image" width="36" height="36" src="https://chat.mantek.info/api/v4/users/fha9ju3srbfqtckxxtnrazd3ih/image?_=1525710461154"><span class="status "><svg width="100%" height="100%" viewBox="0 0 20 20" style="fill-rule: evenodd; clip-rule: evenodd; stroke-linejoin: round; stroke-miterlimit: 1.41421;"><path class="online--icon" d="M10,0c5.519,0 10,4.481 10,10c0,5.519 -4.481,10 -10,10c-5.519,0 -10,-4.481 -10,-10c0,-5.519 4.481,-10 10,-10Zm6.19,7.18c0,0.208 -0.075,0.384 -0.224,0.53l-5.782,5.64l-1.087,1.059c-0.149,0.146 -0.33,0.218 -0.543,0.218c-0.213,0 -0.394,-0.072 -0.543,-0.218l-1.086,-1.059l-2.891,-2.82c-0.149,-0.146 -0.224,-0.322 -0.224,-0.53c0,-0.208 0.075,-0.384 0.224,-0.53l1.086,-1.059c0.149,-0.146 0.33,-0.218 0.543,-0.218c0.213,0 0.394,0.072 0.543,0.218l2.348,2.298l5.24,-5.118c0.149,-0.146 0.33,-0.218 0.543,-0.218c0.213,0 0.394,0.072 0.543,0.218l1.086,1.059c0.149,0.146 0.224,0.322 0.224,0.53Z"></path></svg></span></span></div><div><div class="post__header"><div class="col col__name"><div class="user-popover">frank</div></div><div class="col"><div class="post__header--info"><div class="col"><a class="post__permalink" href="/testforimport/pl/738eth8sdi8budnhc15p6un5th"><time class="post__time" datetime="2018-03-28T11:22:57.000Z" title="Wed Mar 28 2018 13:22:57 GMT+0200 (CEST)"><span>13:22</span></time></a></div><div class="col col__reply"></div></div></div></div><div><div class="post__body  "><div id="738eth8sdi8budnhc15p6un5th_message" class=""><div><span class="post-message__text"><p>Kein Nachtisch heute....</p>
</span></div></div><div class="file-view--single"><div class="file__image"><div class="file-details"><span class="file-details__name">Bild von iOS hochgeladen.jpg</span></div><div class="image-container" style="width: 262.5px;"><div class="image-loaded " style="height: 350px;"><img class=" " style="height: 350px;"></div><div class="image-preload"><div class="file__image-loading"><img class="loader-image" src="/static/files/1171271cb71e89919600b8c3ae1774cb.gif"></div></div></div></div></div></div></div></div></div></div></div>

**Comment by amyblais** [comment] 2018-06-04 12:58
Hi @fmantek! The engineer who was helping with this earlier is currently off, and I'll ping him to take a look at the errors you are getting when he comes back later this week.

Thanks for your patience.

**Comment by fmantek** [comment] 2018-06-04 12:59
No problem. I like mattermost so far, and I am sure we get this solved.

Frank

**Comment by lieut-data** [comment] 2018-06-05 19:37
@fmantek, thanks for the detailed observations above. I've filed https://mattermost.atlassian.net/browse/MM-10790 to get to the bottom of the broken logging messages, and https://mattermost.atlassian.net/browse/MM-10791 to stop logging warnings re: non-image files. 

Some of the image uploads are failing due to the attachments exceeding a maximum size of `6048 * 4032 // 24 megapixels, roughly 36MB as a raw image`, which will be more obvious once the logging is fixed. Does that match your expectations re: some uploaded files?  The failures to write to disk are also related to the logging issue above, in that some code is trying to write thumbnails for files that aren't actually images.

I'm sorry this is so broken!

**Comment by fmantek** [comment] 2018-06-05 20:15
No problem, i work as a Team Manager for Google, so broken code is nothing i can not deal with :)

More than happy to help here. I have set the binary max. Upload size to 500MB, so i am surprised a bit that this is not taking into account when uploading/importing. We like to move to a self controlled environment, and if this takes a bit of time, that is ok,.

Do you mind pointing me to the source responsible for the import? I might be able to fix it and submit a patch.

Frank

**Comment by amyblais** [comment] 2018-07-10 12:34
Hi @fmantek, we haven't received an update so I'll close this Issue for now. The two tickets referenced above (https://mattermost.atlassian.net/browse/MM-10790 and https://mattermost.atlassian.net/browse/MM-10791) have been marked complete and the fixes will be available in v5.1.

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by amyblais** 2018-07-10 12:34 UTC
