### ISSUE TITLE
Create CLI command `webhook webhook move-outgoing`

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9769] opened 2018-10-30 18:44 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12374)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `webhook webhook move-outgoing` command in the CLI.

Allow moving webhooks from one team to another.

Example: `webhook webhook move-outgoing newteam oldteam:w16zb5tu3n1zkqo18goqry1je`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by falcon78921** [comment] 2018-10-31 12:29
I'm new to Go, but I'd love to take this on.

**Comment by amyblais** [comment] 2018-10-31 12:47
Thank you @falcon78921!

**Comment by hanzei** [comment] 2018-11-16 12:32
Hey @falcon78921 

Is there anything we can help you with? if you have any questions, let me know!

**Comment by falcon78921** [comment] 2018-11-28 02:53
My apologies @hanzei for the delayed response.

Being very new to Go, I think I'll have to pass on this. I still have much to learn!

**Comment by hanzei** [comment] 2018-11-28 07:49
No problem @falcon78921.
Feel free to grab a react related ticket if you feel more comfortable with react.

**Comment by falcon78921** [comment] 2018-11-28 18:02
Actually @hanzei, I have some questions about this...

In Go, what modules do you need to import for the database manipulations? I understand Mattermost runs on MySQL or PostgreSQL. To create a ``webhook move`` command, you would need Go to authenticate into the database backend, modify the row containing the old webhook, and insert the new webhook into that row, right?

**Comment by hanzei** [comment] 2018-11-28 18:07
Mattermost uses a `App` struct defined [here](https://github.com/mattermost/mattermost-server/blob/master/app/app.go), which offers a loot of methods to interact with the database. These a used e.g. [here](https://github.com/mattermost/mattermost-server/blob/master/cmd/mattermost/commands/webhook.go#L140). Sometimes its needed to interactive the the DB via the `Store` layer, e.g. [here](https://github.com/mattermost/mattermost-server/blob/master/cmd/mattermost/commands/webhook.go#L86).

**Comment by hanzei** [comment] 2018-11-28 18:11
With [`(a *App) CreateOutgoingWebhook`](https://github.com/mattermost/mattermost-server/blob/master/app/webhook.go#L397) you can create a new outgoing webhook.

**Comment by hanzei** [comment] 2018-12-01 08:00
@patniharshit Great! If you have any questions, let us know.

**Comment by hanzei** [comment] 2019-01-07 11:43
Hey @patniharshit, Did you had time to work on this? Do you have any questions?

**Comment by hanzei** [comment] 2019-01-31 12:18
Making this one available for the public again.

**Comment by hanzei** [comment] 2019-02-03 15:42
Hey @jonathanwiesel,

Feel free to ask as many questions ask you want!

This ticket is about **moving** webhook around. I don't there we have considered a copy command. But this isn't so easy to do. Incoming Webhooks use a unique URL to receive the message. Coping this URL isn't a possibility.

**Comment by patniharshit** [comment] 2019-02-03 20:17
@hanzei apologies for not responding. I will be no longer be able to do it.

**Comment by hanzei** [comment] 2019-02-04 14:05
Hey @patniharshit,

No problem. I'v made this available for the public again, so someone else can pick it up.

**Comment by vildapavlicek** [comment] 2019-02-04 15:18
I will do it.

**Comment by hanzei** [comment] 2019-02-04 19:46
Great @vildapavlicek! :+1: Let me know, if you have any questions.

**Comment by joshuabezaleel** [comment] 2019-02-22 05:26
Hi @vildapavlicek , are you still on this issue? If not, may I take this one? 

Also @hanzei , I noticed from the [Mattermost Command Line Tols docs page](https://docs.mattermost.com/administration/command-line-tools.html) that only the outgoing webhook that needs to be entitled to a team from the flag that needs to be supplied when creating it, and the incoming webhook doesn't have any flags to input the team id or name. 
Does this mean that this move command that move webhook from oldteam to newteam only applies to outgoing webhook, and not incoming webhook?

Thank you very much :slightly_smiling_face:

**Comment by vildapavlicek** [comment] 2019-02-22 07:30
@joshuabezaleel
Hey, yes Im still on the issues, but it will be delayed because I got sick

**Comment by joshuabezaleel** [comment] 2019-02-22 07:51
> @joshuabezaleel
> Hey, yes Im still on the issues, but it will be delayed because I got sick

Got it. Get well really soon, @vildapavlicek ! 🙂

**Comment by hanzei** [comment] 2019-02-26 06:44
> Also @hanzei , I noticed from the [Mattermost Command Line Tols docs page](https://docs.mattermost.com/administration/command-line-tools.html) that only the outgoing webhook that needs to be entitled to a team from the flag that needs to be supplied when creating it, and the incoming webhook doesn't have any flags to input the team id or name.
> Does this mean that this move command that move webhook from oldteam to newteam only applies to outgoing webhook, and not incoming webhook?

Good catch @joshuabezaleel. There is definitely some inconsistently between the two commands.

@wiersgallak [`mattermost webhook create-incoming`](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-webhook-create-incoming) [`mattermost webhook create-outgoing`](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-webhook-create-outgoing) have very different (required) flags. What are the "right" flags and which are required?

**Comment by hanzei** [comment] 2019-03-11 15:12
Hey @vildapavlicek,

Just want to check how the work on this issue is going. Do you have any questions?

**Comment by hanzei** [comment] 2019-03-20 14:42
Making this one available for the public again due to inactivity. Let me know if you still want to work on this @vildapavlicek!

**Comment by checkaayush** [comment] 2019-03-21 21:28
Hey @hanzei, I'd like to pick this up.

**Comment by hanzei** [comment] 2019-03-21 22:13
Thanks @checkaayush. Let me know, if you have questions.

**Comment by checkaayush** [comment] 2019-03-22 07:11
**Assumption:** 

In `webhook move newteam oldteam:w16zb5tu3n1zkqo18goqry1je`, `newteam` and `oldteam` are team names and the last part is the `webhookId`.

**Initial thoughts:**

1. Use `GetTeamByName` to fetch the new team by its name.
2. Use `GetOutgoingWebhook` to fetch webhook with given webhookId.
3. Use `CreateOutgoingWebhook` with newteam's id in the fetched webhook.
4. Use `DeleteOutgoingWebhook` to delete old webhook.

@hanzei Let me know if I missed something.

**Comment by hanzei** [comment] 2019-03-22 08:06
> **Assumption:**
> 
> In `webhook move newteam oldteam:w16zb5tu3n1zkqo18goqry1je`, `newteam` and `oldteam` are team names and the last part is the `webhookId`.

That's correct.

One pitfall I want to make your aware of, is that there are two types to webhook: outgoing and incoming. You need to check for both of the types. But since IDs are unique, this isn't a problem.
I propose to move the logic inside a `(a *App) MoveWebhook` method in `app/webhook.go`.

> P.S.: I'm new here but am absolutely loving how this project is being maintained and managed. Kudos!

Glad you like it! If you have more feedback about the community process, I would love it hear it. (Now or later) Also, feel free to join the [Mattermost Community Server](https://community.mattermost.com).

**Comment by hanzei** [comment] 2019-03-22 08:06
> @wiersgallak [`mattermost webhook create-incoming`](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-webhook-create-incoming) [`mattermost webhook create-outgoing`](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-webhook-create-outgoing) have very different (required) flags. What are the "right" flags and which are required?

@wiersgallak Could you please take a look at this questions?

**Comment by checkaayush** [comment] 2019-03-22 08:19
Here's the progress till now: https://github.com/checkaayush/mattermost-server/commit/b8e79cda5c83264cc799aaa68bfd860c0348f12b.

**Next steps:**

1. Cater to incoming webhooks as well and move the logic inside a `(a *App) MoveWebhook` method in `app/webhook.go`, as suggested by hanzei.
2. Add tests.

**Comment by hanzei** [comment] 2019-03-22 08:30
I would suggest to open a WIP PR to get feedback as soon as possible.

**Comment by checkaayush** [comment] 2019-03-22 10:40
Almost every method inside `app/webhook.go` is specific to either an incoming or an outgoing webhook. So in order to maintain consistency, I propose addition of 2 new methods:  `MoveIncomingWebhook` and `MoveOutgoingWebhook`.

To decide which method to call for a given webhookId, I'll call `GetIOutgoingWebhook` first from the command function, and if none exists with the webhookId, I'll call `GetIIncomingWebhook`, and call the appropriate new method above.

**Comment by hanzei** [comment] 2019-03-22 10:53
@checkaayush That's a fine approach :+1:

**Comment by checkaayush** [comment] 2019-03-23 04:28
As I understand, moving incoming webhook to another team doesn't seem to be the same as moving an outgoing webhook (CreatIncomingWebhookForChannel exists but CreateIncomingWebhook doesn't). Also, the cli interaction `webhook move` doesn't clarify whether an incoming webhook is being moved to another channel or to another team.

**Comment by hanzei** [comment] 2019-03-25 11:23
> As I understand, moving incoming webhook to another team doesn't seem to be the same as moving an outgoing webhook (CreatIncomingWebhookForChannel exists but CreateIncomingWebhook doesn't).

There is a method called `https://github.com/mattermost/mattermost-server/blob/master/app/webhook.go#L307-L331` which you can use.

> Also, the cli interaction `webhook move` doesn't clarify whether an incoming webhook is being moved to another channel or to another team.

That's a good catch. I suppose it should move to different team and a different channel. @wiersgallak Could you help clarify this?

**Comment by checkaayush** [comment] 2019-03-25 12:22
> I suppose it should move to different team and a different channel.
@hanzei Doesn't moving to a new team by default imply moving to a different channel (since channels are tied to teams AFAIK), even when the channel name is same?

Also, this means that then we'll take an added optional argument of channel name in the command, but it'd be useful only for incoming webhooks.

I think we should separate them into `webhook move-incoming` and `webhook move-outgoing`.

**Comment by hanzei** [comment] 2019-03-25 12:35
> Doesn't moving a webhook to a new team by default imply moving it to a different channel (since channels are tied to teams AFAIK), even when the channel name is same?

Technically you could try to find a channel with the same name in the new team. But this is kind of tricky for UX.

> I think we should separate them into `webhook move-incoming` and `webhook move-outgoing`.

I agree. Maybe we should even split the command into `webhook incoming move` and  `webhook outgoing move`.

**Comment by wiersgallak** [comment] 2019-03-26 14:50
My apologies on delayed responses @checkaayush @hanzei. 

> I think we should separate them into webhook move-incoming and webhook move-outgoing.

I also agree.  My recommendation would be to approach the webhook move-outgoing since the team is a required parameter of that command and likely is more straightforward to support.  Incoming Webhooks and Outgoing Webhooks do currently have different requirements and we will need to determine what changes to make to Incoming Webhooks to support the move command.

**Comment by checkaayush** [comment] 2019-03-26 16:57
Cool. Going ahead with just the `webhook move-outgoing` command for now.

**Comment by checkaayush** [comment] 2019-03-27 11:20
@hanzei I've run into another issue: `CreateOutgoingWebhook` expects the webhook's channel's TeamId to be the same as the webhook's TeamId as seen [here](https://github.com/mattermost/mattermost-server/blob/master/app/webhook.go#L433). 

As per my [current approach](https://github.com/mattermost/mattermost-server/pull/10489), it'll fail since I'm calling CreateOutgoingWebhook with everything but the team id from the existing webhook.

There's a channel id attached to outgoing webhooks, which again brings up the question whether to search for a channel with same name in the target team as in old team.

Not sure how I should proceed in this case. 

cc: @jwilander Would love your inputs here as well.

**Comment by jasonblais** [comment] 2019-04-01 15:14
@hanzei Wondering your thoughts on the above?

**Comment by hanzei** [comment] 2019-04-04 11:09
@checkaayush Why not:
- Get the channel name from the old channel
- Try to get a channel in the new team with the name name
- Use the id from the new channel

This would make the semantic of reusing the channel name in the new team clear.

@wiersgallak Is this the expected behaviour?

**Comment by hanzei** [comment] 2019-05-08 15:37
@wiersgallak Gently reminder about the above questions.

**Comment by wiersgallak** [comment] 2019-05-08 18:04
@checkaayush I would expect to provide the channel ID from the channel I want to move the command to in the new team and the Team ID.  In my opinion, it is better to be explicit about where you want to move the command to.

**Comment by RajatVaryani** [comment] 2019-06-26 16:01
@hanzei I am taking this up!

**Comment by hanzei** [comment] 2019-06-26 16:02
Thanks @RajatVaryani :+1:

**Comment by RajatVaryani** [comment] 2019-06-27 01:42
@wiersgallak @hanzei I have a few questions:

1. For what purpose this cli command is going to be used for?

> I would expect to provide the channel ID from the channel I want to move the command to in the new team and the Team ID. In my opinion, it is better to be explicit about where you want to move the command to.

2. @wiersgallak So we should also have a channel name or id as an argument to the command?

**Comment by wiersgallak** [comment] 2019-06-28 13:33
@RajatVaryani 
1. The purpose of this is so that users can move an existing outgoing Webhooks to a new team and/or channel.  
2.  Per the webhook create-outgoing command accepts either channel name or id in the channel string parameter, I would expect this command to accept either as well.

**Comment by RajatVaryani** [comment] 2019-06-28 13:36
@wiersgallak Thanks. 
 `webhook move newteam oldteam:w16zb5tu3n1zkqo18goqry1je --channel some-channel`

Does this look good? And if the channel does not exist in the new team then an error is thrown. Sounds good?

**Comment by wiersgallak** [comment] 2019-06-28 13:37
@RajatVaryani Yes the format and the error sounds good.  Thank you!

**Comment by RajatVaryani** [comment] 2019-07-01 11:34
There is a problem. This [function](https://github.com/mattermost/mattermost-server/blob/1aa1363e63f4e0421ec83bed07135e2ed7f9884b/app/webhook.go#L440) assumes the outgoing webhook being moved to the **same** team. We might need to write a new method to support moving the webhook to a different team.

**Comment by RajatVaryani** [comment] 2019-07-09 04:36
Bumping up!

**Comment by jasonblais** [comment] 2019-07-09 13:09
@jespino wondering if you're open to taking a look at the above question?

**Comment by RajatVaryani** [comment] 2019-07-12 06:00
Can someone please help me close this?

**Comment by jespino** [comment] 2019-07-12 06:37
@RajatVaryani I'm sorry the delay, yes, I think delete from one team and creating it in another one can be the solution, actually, I would suggest, create it in the another team, if everything goes well, delete the old one. and if something goes wrong, try to revert the action, or at least inform about the final state of the action (if something was created and if something wasn't properly deleted).

**Comment by RajatVaryani** [comment] 2019-07-15 04:35
@jespino Let me try that.

**Comment by BenKnigge** [comment] 2019-08-23 23:47
@RajatVaryani is it possible to use a db transaction to ensure that the move either succeeds  in full or fails in full?

**Comment by hanzei** [comment] 2019-09-11 11:30
@RajatVaryani You want to check if you have any outstanding questions.

**Comment by RajatVaryani** [comment] 2019-09-11 12:54
Looking to close this pretty soon. @hanzei

**Closed** 2020-01-06 09:58 UTC
Labels: Area/CLI, Difficulty/1:Easy, Good First Issue, Help Wanted, PR Exists, Tech/Go
