### ISSUE TITLE
MM sends Invalid Invitation links

### ISSUE THREAD

**Issue by jelmd** [mattermost/mattermost-server#16931] opened 2021-02-13 07:38 UTC
When a user creates a new account, MM seems to send an invalid e-mail verification link: If the user clicks on the link, he gets presented a login page, where he must enter a password. Unfortunately the loginId input field contains the user's e-mail address and _not_ its account, even so login by e-mail address is disabled. So users send a lot of e-mail complaining about a not working account creation service.

So if login via e-mail address is disabled, MM should send a proper link/create  a correct "login page", where the loginId input field contains the account name instead off the users e-mail address.

env: MM 5.31.1 downloaded from mattermost.com - fresh install

**Comment by amyblais** [comment] 2021-02-15 18:07
@jelmd Would you be open to sharing more details on your [Signup](https://docs.mattermost.com/administration/config-settings.html#signup) and [Email](https://docs.mattermost.com/administration/config-settings.html#email) related settings? Do you see any server log errors?

**Comment by jelmd** [comment] 2021-02-15 19:05
The following patch shows the modifications wrt. the original config:
[mm-5.31.1.patch.txt](https://github.com/mattermost/mattermost-server/files/5983544/mm-5.31.1.patch.txt) . No server errors related to this.

**Comment by amyblais** [comment] 2021-02-15 23:58
It looks like "EnableSignInWithEmail": is set to both "true" and "false". If sign-in with email is disabled, then another SAML or LDAP should be used https://docs.mattermost.com/administration/config-settings.html#enable-sign-in-with-email. Can you help clarify what the expected behaviour is in your case?

**Comment by jelmd** [comment] 2021-02-16 00:42
`EnableSignInWithEmail`: no, in [unified patches](https://en.wikipedia.org/wiki/Diff#Unified_format) a leading `-` (minus) means, this line is part of the file prefixed with `---` on the head (above `./config/config.json.orig`) but not of the file prefixed with `+++` on the head (above `./config/config.json`). A leading `+` is the same for the other file (thus part of `./config/config.json` but not in `./config/config.json.orig`). So in the current config `EnableSignInWithEmail` exists only once and is set to `false` for reason. Users have to use their account name to login, nothing else (using e-mail to sign in is one of the most annoying, counter  productive things, crazy web developers came up with in the stone edge of web dev) and here the storage location of account data (whether local or on LDAP, etc.) shouldn't make any difference.

**Comment by amyblais** [comment] 2021-02-17 19:06
Thanks, opened a ticket for this: https://mattermost.atlassian.net/browse/MM-32958

**Comment by amyblais** [comment] 2022-05-11 16:23
Hi @jelmd, are you still experiencing this issue on one of our latest server versions (e.g. v6.3)?

**Comment by amyblais** [comment] 2022-09-12 19:13
The Jira ticket was closed as we're no longer able to reproduce this. Please let us know if the issue still happens on the latest version.

**Closed by amyblais** 2022-09-12 19:13 UTC
Labels: Bug Report/Open
