### ISSUE TITLE
Deactivated users appear in New Direct Message menu

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#13667] opened 2020-01-21 15:25 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary

Deactivated users appear in the list of users with which a direct message can be initiated.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

Click on the "+" symbol beside the DIRECT MESSAGES menu on the left hand side
Modal / Menu to select user to initiate direct messages opens
Deactivated users appear here

#### Expected behavior
Describe your issue in detail

Deactivated users appear in the list of users with which a direct message can be initiated.
Ideally, deactivated users should not appear in this list as they are deactivated.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

Deactivated users appear in the list of users with which a direct message can be initiated.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Hide/do not list deactivated users from this list

**Comment by amyblais** [comment] 2020-01-21 23:38
@arjitc What Mattermost server version are you on? What OS and version are you seeing this on?

**Comment by arjitc** [comment] 2020-01-22 00:14
Hey,
I'm using mattermost 5.18.0 currently via the desktop app on Windows

**Comment by amyblais** [comment] 2020-01-22 00:40
@arjitc Based on [documentation](https://docs.mattermost.com/help/getting-started/managing-members.html#deactivating-users) this seems to be an expected behaviour.

"Direct Message channels with deactivated users are hidden in users’ sidebars, but can be reopened using the More… button or the Channel Switcher (CMD/CTRL + K)."

Let me know any questions,

**Comment by arjitc** [comment] 2020-01-22 20:30
@amyblais -- how about hiding it for users who have never interacted with each other over private message before ? 

For example, 
User A is active
User B is a disabled user

if user A has never messaged user B, don't show that user under his private message option?

**Comment by amyblais** [comment] 2020-01-24 19:39
Opened a ticket: https://mattermost.atlassian.net/browse/MM-22038.

**Comment by amyblais** [comment] 2020-03-11 13:05
This is scheduled to be fixed in v5.21.

**Closed by amyblais** 2020-03-11 13:05 UTC
Labels: Bug Report/Scheduled for Release
