### ISSUE TITLE
API attachments with text doesn't display emojis

### ISSUE THREAD

**Issue by HLeithner** [mattermost/mattermost-server#8309] opened 2018-02-16 10:23 UTC
#### Summary
Submitting a attachment with text data per api will not show any emojis, in Version 4.5.0 this worked fine. In Version 4.7.0 it doesn't work any longer...

#### Steps to reproduce
Post a message with payload attachment to the Webhook and add a emojis like : white_check_mark : (without the spaces) to the text

#### Expected behavior
Showing a Green icon with a white check mark

#### Observed behavior (that appears unintentional) 
Showing the emoji macro ": white_check_mark :"

#### Possible fixes
I can't

**Comment by thiyagaraj** [comment] 2018-02-18 00:15
I am encountering the same issue after upgrading to 4.7.0 (We were previously on 4.1). We use a [mattermost plugin for jenkins](https://wiki.jenkins.io/display/JENKINS/Mattermost+Plugin) that is sending emojis in the fields/value section. These emojis are not being displayed, this used to work  prior to the upgrade. Other formatting works though, such as bold text. I am assuming it is not expected behavior...

#### What jenkins is posting to the webhook:
```
{
  "icon_url": "",
  "attachments": [
    {
      "color": "good",
      "mrkdwn_in": [
        "pretext",
        "text",
        "fields"
      ],
      "fields": [
        {
          "short": false,
          "value": "Test-Jobs » Test Mattermost Job - #6 :white_check_mark: This is some **bold** text"
        }
      ],
      "fallback": "Test-Jobs » Test Mattermost Job - #6 :white_check_mark: This is some **bold** text"
    }
  ],
  "text": "This is a message from Jenkins :white_check_mark:",
  "username": "jenkins"
}
```
#### How it is displayed (notice the white-check-mark emoji text)
![image](https://user-images.githubusercontent.com/167320/36346883-b95271be-1416-11e8-8f6b-4e56d43a680c.png)

**Comment by HLeithner** [comment] 2018-02-19 16:50
Sill not working in 4.7.1

**Comment by hmhealey** [comment] 2018-02-20 14:53
Hi,

It looks like this broke when we added lazy loading for custom emojis in 4.7. I've filed a ticket to fix this [here](https://mattermost.atlassian.net/browse/MM-9659)

**Comment by amyblais** [comment] 2018-02-20 18:17
Hi @HLeithner,

Thank you for this report,
Just wanted to let you know that we are working on a 4.7.2 dot release to fix this ticket. We are expecting 4.7.2 to be released this week.

**Comment by lindy65** [comment] 2018-02-23 07:50
Hi @HLeithner,

[v4.7.2](https://about.mattermost.com/download/) is released so I'll close this issue off here for now and you can let us know if you still have a problem after upgrading 👍

**Closed by lindy65** 2018-02-23 07:50 UTC

**Comment by HLeithner** [comment] 2018-02-23 10:54
@lindy65 thx I can confirm works for me with 4.7.2.
