### ISSUE TITLE
Channel Not Found

### ISSUE THREAD

**Issue by MrSorcus** [mattermost/mattermost-server#11613] opened 2019-07-12 04:14 UTC
#### Summary

```
Channel Not Found

The channel you're requesting is private or does not exist. Please contact an Administrator to be added to the channel.

Back to Town Square
```

#### Steps to reproduce
Version: 5.12.0
Build Number: 5.12.2-1
Build Date: 2019-07-10 19:28:29
Build Hash: 5.12.2-1 Arch Linux (x86_64)
Build Enterprise Ready: false
DB Version: 5.12.0
Just delete all channels.

#### Expected behavior
Mattermost should works without channels (make them optional).

#### Observed behavior (that appears unintentional) 

```
Channel Not Found

The channel you're requesting is private or does not exist. Please contact an Administrator to be added to the channel.

Back to Town Square
```

**Comment by amyblais** [comment] 2019-07-12 14:37
Hi @MrSorcus, what do you expect to see in the UI in this case?

**Comment by MrSorcus** [comment] 2019-07-12 14:44
Something like `Welcome page`?

**Comment by amyblais** [comment] 2019-07-12 18:53
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-16995.

**Comment by amyblais** [comment] 2019-07-15 17:19
Hi @MrSorcus, the Jira ticket was closed as it is not possible to delete the Town Square. We are planning to add this possibility with upcoming Guest Accounts feature which is shipping as an Enterprise Edition feature.

**Comment by jasonblais** [comment] 2019-07-29 17:12
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by jasonblais** 2019-07-29 17:12 UTC
Labels: Bug Report/Open

**Comment by sneak** [comment] 2024-05-06 09:42
This bit me too, when upgrading from a very old version to a current version.  Something happened where it didn't migrate properly and all my channels disappeared.  I had to make a new team because I couldn't even re-create channels in the old team due to this bug.

**Comment by sneak** [comment] 2024-05-06 09:43
@jasonblais @MrSorcus please reopen.

**Comment by MrSorcus** [comment] 2024-05-06 09:48
@sneak I don't have permission to do that.
