### ISSUE TITLE
/me formatting not displayed in thread view

### ISSUE THREAD

**Issue by Gittenburg** [mattermost/mattermost-server#14269] opened 2020-04-10 10:56 UTC
#### Summary

The `/me` built-in command produces a special formatting. In the webapp this formatting is not shown in the thread view making the message indistinguishable from regular text.

**Mattermost Version:**  5.21.0

#### Steps to reproduce
1. Type `/me example` and hit enter.
2. Open the message in thread view.
#### Expected behavior
The message is formatted the same way as in the channel view.

#### Observed behavior (that appears unintentional)
The message is not formatted at all.

#### Possible fixes
Fix the CSS.

**Comment by amyblais** [comment] 2020-04-13 18:05
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-24116.

**Comment by amyblais** [comment] 2020-04-13 20:56
The above tickets is a duplicate of https://mattermost.atlassian.net/browse/MM-23213 which is already fixed for upcoming v5.23 quality release.

**Closed** 2020-04-13 20:56 UTC
Labels: Bug Report/Scheduled for Release
