### ISSUE TITLE
Non-emoji text that matches emoji shortcode adds that emoji to the quick reactions bar

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-server#19175] opened 2021-12-15 05:01 UTC
#### Summary

Typing text like this (including the backticks):

    `:chair:`

in a message adds the 🪑 emoji to the quick reactions bar even though the emoji wasn't actually used in the message.

#### Steps to reproduce

1. Write a message like that show above

**Mattermost Version:** 6.1.0 accessed in Firefox on Linux.

#### Expected behavior

I expect that only when my message text renders an emoji or I use one as a reaction that it gets added to the quick bar.

#### Observed behavior (that appears unintentional) 

The emoji is added to the quick bar when it shouldn't be.

#### Possible fixes

It seems that code that is scanning for emoji in message text in order to populate the quick reactions bar needs to be aware of Markdown.

**Comment by amyblais** [comment] 2021-12-15 15:17
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40662.

**Comment by amyblais** [comment] 2021-12-15 16:08
By the way, nice find!

**Comment by endgame** [comment] 2021-12-15 22:31
Yeah @wezm , how on earth did you find this?

**Comment by wezm** [comment] 2021-12-15 23:45
I actually did as described in the issue (but with a different emoji). I deliberately put it in backticks to make it come out verbatim in the message but then noticed the emoji was now in my quick reactions bar.

**Comment by amyblais** [comment] 2022-02-24 13:35
> As I closed most of the issues assigned to me. I am in search for new ones 😎
> 
> @amyblais @hmhealey is this still an issue? If I remember correctly, there were some works by @M-ZubairAhmed on emoji picker. Maybe with recent changes this might be fixed.
> 
> If it is still an issue, I can give it a try (it seems like an interesting problem 🤞 )

I was able to reproduce this still, I'll assign this to you 👍

**Comment by M-ZubairAhmed** [comment] 2022-02-24 14:37
@sinansonmez feel free to take a look at this one because this isnt strictly related to emoji picker but more of the rendered

**Comment by hmhealey** [comment] 2022-02-24 17:28
What's happening here is that when we're sending a post, we look at the text to see if there's any emoji used in it, and then we add those to the recent emojis. That code doesn't know about Markdown though, so it picks up things that aren't rendered as actual emojis. If we render the Markdown using something like the MentionableRenderer (which only outputs text that can contain mentions), that might help us do this

**Comment by sinansonmez** [comment] 2022-02-25 21:58
Thanks for the guidance @hmhealey. I had to review relevant parts of the codebase to better understand your guidance. 

The fix of this issue depends on the expected behavior (maybe expected behavior is not clear to me). Therefore what should be the expected behaviour? Therefore, which of the following changes are you suggesting? 

**Option 1:** 
- **Expected behavior:** If the text contains markdown and emoji, the emoji should be rendered as emoji description (i.e. `:smile:`)
- **Fix:** Update [code](https://github.com/mattermost/mattermost-webapp/blob/ce09efbcd9d67519f0b795a00eaa3567b76a9285/utils/emoticons.tsx#L28) (which reviews the text if there is emoji is included) to be aware of Markdown. If the emoji is within the markdown don't add to recentEmojis

**Option 2:** 
- **Expected behavior:** If the text contains markdown and emoji, the emoji should be rendered as emoji image (i.e. 😄)
- **Fix:** Update code (which renders the text as markdown) so if there is emoji within the code it renders emoji image (i.e. 😄) and not text (i.e. `:smile:`)

**Comment by hmhealey** [comment] 2022-02-28 15:15
Option 1 would be the expected case. We want to keep the text exactly as the user typed it in the code block.

**Closed** 2022-03-10 16:46 UTC
Labels: Difficulty/1:Easy, Tech/ReactJS, Help Wanted
