### ISSUE TITLE
[Help Wanted] [PLT-3856] Help break HTML blocks to individual strings for translations

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6174] opened 2017-04-20 16:57 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3856)

Break HTML blocks into individual strings for easier translations.

Strings like this: https://translate.mattermost.com/es/mattermost/translate/platform.po#unit=163796 should be decomposed to smaller strings. Mixing HTML with the translation is not a good practice.

**Comment by kaakaa** [comment] 2017-12-28 14:11
> http://translate.mattermost.com/nl/mattermost/translate/#filter=untranslated&unit=237152 

It looks that this translation unit cannot be found.

**Comment by amyblais** [comment] 2018-03-23 16:46
@esethna Does the above link need to be changed?

**Comment by amyblais** [comment] 2018-04-09 12:15
@jasonblais Would you know? ^

**Comment by jasonblais** [comment] 2018-04-09 12:25
Updated, thanks @kaakaa and @amyblais!

**Comment by kaakaa** [comment] 2018-04-12 13:01
Thanks @amyblais & @jasonblais.

But it seems that this message isn't used in product code.
[Search · api\.templates\.upgrade\_30\_body\.info](https://github.com/mattermost/mattermost-server/search?utf8=%E2%9C%93&q=api.templates.upgrade_30_body.info&type=)

Should I remove it?

**Comment by jasonblais** [comment] 2018-04-12 13:12
@kaakaa If it's not used in the code, then I think it can be removed. It was probably used during the v3.0 upgrade.

I also updated the example with a string we still use in the code: https://translate.mattermost.com/es/mattermost/translate/platform.po#unit=163796

**Comment by kaakaa** [comment] 2018-04-12 14:10
I see. I'll work this issue.

I search messages including `<br>` tag and devide message by `<br>` tag, right?
Offcourse, I will not fix `<br>` tag for giving appropriate space.

**Comment by jasonblais** [comment] 2018-04-18 17:59
@kaakaa Also wanted to say a huge thank you for looking into this :)

**Comment by kaakaa** [comment] 2018-05-27 12:31
Hi @jasonblais.
Sorry for my late reply. I'm back.

I looked into server messages including html tags. Since most of that messages are used to be embedded in email templates, I'm going to modify messages and email template files.

At first, I make one exmple and I'm going to modify other messages on this way.
[Modifying message and templates about mfa\_change · kaakaa/mattermost\-server@84f7790](https://github.com/kaakaa/mattermost-server/commit/84f779087e889e7bc0fefa1e24800453d1a5412b)

After completing to modify server messages including html tags(about 15 messages), I will make PR.
Thank you.

**Comment by jasonblais** [comment] 2018-05-28 11:31
That looks great! You can also consider posting your proposal in the localization channel for early feedback. https://pre-release.mattermost.com/core/channels/localization

Big thanks @kaakaa :)

**Comment by kaakaa** [comment] 2018-07-07 12:56
Hi, I started work on webapp.
I think that in many cases the fixing will be done by converting `FormattedHTMLMessage` to `FormattedMarkdownMessage` and modifying messages in markdown style.

At first, I listed all messages with html tags by using [my script](https://gist.github.com/kaakaa/025f29a427f6ae33d68c646353ba87b3#file-mm-message-html-tags-go).
https://docs.google.com/spreadsheets/d/1e4RdAAsbwBjlkz_nLYjgVCJCFYYP_vyo2Xtm7PiDrtk/edit?usp=sharing

In webapp, there are 100+ messages with html tags and `i18n/en.json` is often changed. So I'll be required to rebase manytimes. In order to avoiding it, I'll complete this task by dividing it into several PRs.

I'll fix messages in the following orders.

1. Fix message with `Used in FormattedHTMLMessage directly` = `NO`, because this kind messages could be difficult to fix
2. Fix messages with multi html tags
3. Fix messages with just a tag. This kind messages is easy to fix.

If you have any concerns, please let me know.

**Comment by jasonblais** [comment] 2018-07-07 14:48
This is awesome! Thank you @kaakaa 👍

**Comment by kaakaa** [comment] 2018-07-09 14:47
I'm working on webpp. And now I have some concerns about messages and `FormattedMarkdownMessage` component.
Would you please answer my questions?

### 1. Custom classes
Some messages has custom classes (e.g.: `<h4 class=banner__heading">Note:</h4>`) in html tag. How can I add these classes with markdown style? or can I remove these custom classes?
* admin.compliance.noLicense
* admin.ldap.noLicense
* intro_messages.default
* intro_messages.offTopic
  
### 2.  Not HTML tag `<XXXX>`
Some messages has strings not HTML tag, but surrounded by `<` and `>`. That strings are confused with html tags, so I think that we should change it to other symbols. (e.g.: `<blank>` -> `[blank]`). How does it sound?

* admin.cluster.OverrideHostnameDesc (`<blank>`)
* admin.saml.assertionConsumerServiceURLDesc, admin.saml.assertionConsumerServiceURLEx (`<your-mattermost-url>`)
* admin.webrtc.gatewayAdminUrlDescription, admin.webrtc.gatewayWebsocketUrlDescription (`<mattermost-webrtc-gateway-url>` & `<port>`)
* admin.webrtc.stunUriDescription, admin.webrtc.turnUriDescription (`<your-stun|turn-url>` & `<port>`)

### 3. `\n\n` is not new lines
When I modify `<br /><br />` to `\n\n`, it isn't converted to any `<br>` tags by `FormattedMarkdownMessage` (`\n` converted `<br>`). Now I use `\n \n` instead of `\n\n`, it works fine. Is this okay?

* admin.general.localization.availableLocalesDescription
* admin.image.storeDescription
* admin.ldap.idAttrDesc
* admin.ldap.loginAttrDesc
* admin.service.enforceMfaDesc
* admin.service.forward80To443Description.disabled

### 4. Converting url strings to links automatically
`FormattedMarkdownMessages` converts url strings (`http(s)://~`) to links automatically. For avoiding it, I can modify url strings to inline code. How does it sound?

* `admin.service.siteURLDescription` has two example urls (`http://example.com:8065`, `http://example.com:8065/company/mattermost`)

![2018-07-09 23 32 49](https://user-images.githubusercontent.com/1453749/42456699-82dd7690-83d0-11e8-94ed-95969e4bf718.png)

**Comment by mkraft** [comment] 2018-07-09 15:53
1) At this point `FormattedMarkdownMessage` doesn't support custom classes so I would look into wrapping the whole thing in a custom class and then targetting the contained markup. So instead of using `.banner__heading {}` directly you could do `banner__heading h4 {}`, for example. That should work in most of the cases.

2) I wonder if backslashes work to render `<` and `>` like this: `\<` and `\>`?

3) The space between the newlines is fine I suppose as it probably doesn't change the view for the user. That does sound like a bug in the markdown parser though... I'll open a ticket to look into that.

4) I think that should be fine to show links that we don't want hyperlinked as inline code.

**Comment by mkraft** [comment] 2018-07-12 14:48
@kaakaa 
1) I think the translation should be changed to this anyhow:

`Compliance is an enterprise feature. Your current license does not support Compliance. Click [here](!http://mattermost.com) for information and pricing on enterprise licenses.`

![localhost_8065_admin_console_general_compliance](https://user-images.githubusercontent.com/1149597/42640768-03878eba-85c1-11e8-863b-49ea11e234d6.png)

@jasonblais thoughts? ^

2) I just tested it and you don't need to escape `<blank>` in a string to `FormatedMarkdownMessage`. They should just work as-is.

**Comment by jasonblais** [comment] 2018-07-12 16:12
@mkraft In which cases would the banner in 1) show up? Since you need an Enterprise license to view that page. Can we remove the string?

**Comment by mkraft** [comment] 2018-07-12 16:47
@jasonblais Seems you see it if you navigate to that page without a license. Doesn't seem very necessary to me either.

**Comment by jasonblais** [comment] 2018-07-12 17:17
I think that's an old banner, possible from a time when Enterprise features were exposed without a license. @kaakaa feel free to remove `admin.compliance.noLicense`

**Comment by kaakaa** [comment] 2018-07-14 14:50
Okay, I'll remove it.
Thanks @mkraft and @jasonblais!

Since I finished about one third of messages to be fixed, I think I will make PullRequest once.  But PR for [MM-10997] is duplicated with a part of my work. So I will rebase and make PR after it is merged.

**Comment by jasonblais** [comment] 2018-07-14 14:53
Sounds good, thanks @kaakaa!!

**Comment by jasonblais** [comment] 2018-10-02 11:48
@kaakaa Is this issue now completed?

**Comment by kaakaa** [comment] 2018-10-03 22:48
@jasonblais 
I checked [`en.json` in mattermost-mobile](https://github.com/mattermost/mattermost-mobile/blob/master/assets/base/i18n/en.json) and confirmed that it has no HTML tag.

And I re-checked mattermost-server and mattermost-webapp, I found some messages to fix.
[Fix messages to markdown style by kaakaa · Pull Request \#1824 · mattermost/mattermost\-webapp](https://github.com/mattermost/mattermost-webapp/pull/1824)
If merging this PR, this issue is completed.

Sorry for responding late.

**Closed** 2018-10-05 00:03 UTC
Labels: Difficulty: Intermediate, Hacktoberfest, Localization, ReactJS

**Comment by jasonblais** [comment] 2018-10-07 02:01
Huge thanks @kaakaa for your help throughout :)
