### ISSUE TITLE
Hitting Team Switch button multiple times too fast results in locked up application

### ISSUE THREAD

**Issue by loofou** [mattermost/mattermost-server#8109] opened 2018-01-16 13:17 UTC
#### Summary
On a server with multiple teams, switching between teams too fast can result in a locked up state where no team button does anything anymore and a refresh is the only way to continue working. The refresh will end in the team screen of the team button that was first pressed.

#### Steps to reproduce
Mattermost 4.5.0, server with multiple teams.
1. Join at least two teams.
2. Click on one of the teams to switch to it.
3. While the app is loading, immediately click on another team button.
or
3. Click spam on all the team buttons.

#### Observed behavior (that appears unintentional) 
App will lock up and user is stuck in the current team and can't switch anymore.

#### Expected behavior
As long as team switch was initiated, buttons should deactivate so that no other team switch can be started, or app should recover from click spam and just join the last team which button was pressed.

**Comment by lindy65** [comment] 2018-01-17 09:11
Hi @loofou,

Thanks for the feedback,

Please update to the [latest version](https://about.mattermost.com/download) of Mattermost release January 16th.  There have been various improvements to team switching.

**Comment by loofou** [comment] 2018-01-17 13:18
Hi @lindy65,

Unfortunately even with 4.6 we experience the lockup. It is mainly experienced by higher ping external clients that connect over the internet. It can happen multiple times per day and forces the user to reload the client every few hours, with can be very distracting and annoying.

**Comment by jasonblais** [comment] 2018-01-17 13:27
@loofou Thanks for the report!

1) Does this happen if you click spam on channels? Or only on click spam of team buttons?
2) Which operating system (Windows/Mac/Linux) and browser does this reproduce?

**Comment by loofou** [comment] 2018-01-17 14:30
@jasonblais 

1. As far as I'm aware this only happens on the team buttons. Because of latency it can take a few seconds for some users to switch to the new team and because of missing feedback they just click on the team buttons some more, thus locking the web app.

2. It happens with Chrome and with the Windows Application. It might happen on other browsers and OS as well, but we only use Windows and the App mainly, so I can't confirm.

**Comment by jasonblais** [comment] 2018-01-17 18:29
Sounds good. And last questions to help replicate the environment for troubleshooting:

1) How many teams are on your system (you can find this in System Console > Site Statistics)?
2) How many teams does one user typically belong to?
3) Does it reproduce across all users, or only some?

**Comment by loofou** [comment] 2018-01-18 08:06
@jasonblais 

1. We have four teams at the moment
2. Typically users are part of two teams, sometimes three. One of the teams is the general company team which everyone is part of, the others are project-related teams.
3. I could not reproduce it on my machine, but I saw it happen on one other and have reports of at least five people who experience this problem. We have around 50 users, so at least 10% of our users have this problem. But as it seems to be latency-related, the external users are more prone to the issue than internal ones.

**Comment by lindy65** [comment] 2018-01-18 19:38
Thanks @loofou,

Are there any errors in the JavaScript console?

**Comment by loofou** [comment] 2018-01-19 08:55
@lindy65 

Unfortunately no. I see only a few warnings about embedded images not using https but that's it on the client.
In the backend logs I see only assumingly unrelated messages. Mainly throttling messages, but those are from all over the place and seem related to pasted links. Nothing that would indicate issues with team switching and also no logs with a time close to when I was reproducing the issue.

**Comment by lindy65** [comment] 2018-01-20 12:25
Thanks for the feedback @loofou,

I'll ask an engineer to take a look at this and see if they can help troubleshoot further...

**Comment by lindy65** [comment] 2018-01-25 09:25
Hi @loofou,

Can we have your help trying to reproduce this on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master?  There have been some performance improvements which we believe will fix your issue and will be released February 16th.

**Comment by loofou** [comment] 2018-01-26 08:22
@lindy65 

I would gladly test it, but I can't see any other teams on the server. Without at least two teams, I can't use the team buttons :)

**Comment by lindy65** [comment] 2018-01-26 08:34
Ah, of course @loofou :)

I've added you to a test team I have on the server...

**Comment by loofou** [comment] 2018-01-26 08:37
@lindy65 

Yes, I noticed, thank you! 

I can't reproduce the issue on the nightly server, which gives me hope! But I want to test it in our environment first, so I would like to keep the ticket open until I could test it in the new version in February, if you don't mind.

**Comment by lindy65** [comment] 2018-01-26 08:49
@loofou - great news :)

There's a good chance the issue is fixed so no worries keeping this ticket open until you've tested the new release on Feb 16th.

**Comment by lindy65** [comment] 2018-02-23 08:10
Hi @loofou,

I'm going to close this issue off here for now as [4.7.2](https://about.mattermost.com/download/) released yesterday and this issue should be fixed.

If you still experience problems, please let us know and we can investigate.

**Closed by lindy65** 2018-02-23 08:10 UTC
