### ISSUE TITLE
The notification of an unread message does not disappear

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost-server#22946] opened 2023-04-13 05:54 UTC
The notification of an unread message does not disappear. The messages can't be found and it's nowhere to be found. But there is a notification.
![image](https://user-images.githubusercontent.com/109951790/231666249-9483d2bb-7dc5-414f-b5ff-a3d3b1db8d34.png)

Mattermost: 7.7
version db: 100
DB: postgres

**Comment by amyblais** [comment] 2023-04-13 12:35
Closing as a duplicate of https://github.com/mattermost/mattermost-server/issues/22060.

**Closed by amyblais** 2023-04-13 12:35 UTC
