### ISSUE TITLE
Slack Import fails to add users

### ISSUE THREAD

**Issue by zfstest** [mattermost/mattermost-server#8868] opened 2018-05-29 01:58 UTC
#### Summary
Mattermost 4.2 only imports the first user from Slack-Import (users.json),and can't set the users' email address correct.

#### Steps to reproduce
Version: Mattermost 4.2
1. I exported my slack settings  like it is descriped in the documentation.
   I don 't have installed any addons.
2. I imported the zip file into mattermost.

#### Expected behavior
In the ImportSummary, only the first user is added,and not the email is not correct.
The user's mail is ：XXXXXX@gmail.com
And other uesrs is not added.I don't know the reason.

ImportSummary:
Users created:===============
User XXXXX does not have an email address in the Slack export. Used XXXXX@example.com as a placeholder. The user should update their email address once logged in to the system.
Slack user merged with an existing Mattermost user with matching email XXXXX@example.com and username XXXXX.
The Integration/Slack Bot user with email slackimportuser_byo1n7tunjyxxgrzsfpdawuzfr@localhost and password x6yysi6dmdfdlfkldrhrrf6h48kbc has been imported.

Channels added:===============
Unable to add Slack user ? to channel.

#### Observed behavior (that appears unintentional) 
It looks like the ticket MM-9934.But the first user in MM-9934 is added successful.
So I think maybe this is another bug ? or not.

**Comment by zfstest** [comment] 2018-05-30 00:18
Hi @amyblais 
Thanks for your replay.
But I only can use the 4.2 version.
 
If this is a bug in 4.2 version ,I'll report to my colleague.
Do you think this is a bug?

**Comment by amyblais** [comment] 2018-05-30 16:37
Hi @zfstest! 

Yes, this sounds like a bug since you should be able to import all users and there shouldn't be errors in users' emails.

We have fixed different kinds of bugs related to Slack Import in past releases, and it is very well possible that this issue has been fixed in one of our recent releases.

If a user is hitting issues on an older version, we usually recommend upgrading. Is this something you could check with your System Admin?

**Comment by amyblais** [comment] 2018-06-11 12:13
Hi @zfstest! Following up here - please let me know if the above suggestion helped ^

**Comment by amyblais** [comment] 2018-06-15 13:12
Hi @zfstest, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by amyblais** 2018-06-15 13:12 UTC
