### ISSUE TITLE
[Help Wanted] Remove hard black outline on scrollbar in IE11/Win10 and Firefox/Win10 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-server#4852] opened 2016-12-20 16:37 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

---

#### Summary
Remove hard black outline on scrollbar in IE11/Win10 and Firefox/Win10

#### Steps to reproduce
Open Mattermost in IE11/Win10 and type enough messages into Town Square to trigger a scroll bar to the right of the center channel 

#### Observed behavior
Scroll bar in IE has heavy black outline 

![image](https://cloud.githubusercontent.com/assets/177788/21358832/df0be4b6-c68e-11e6-9081-e74c5e85430a.png)

#### Expected behavior
No heavy black outline, use outline color from user's theme. 

#### Possible fixes
Update CSS for default scrollbar 

##### Note

There's a plug-in that's used to render the scrollbar in Chrome/Win10 that doesn't work in IE11 or Firefox, so we just need to style the default scrollbar. 

One option is to replace the existing scrollbar with `react-custom-scrollbars`.

**Comment by KishoreFartiyal** [comment] 2017-11-13 11:55
@jasonblais I am on it

**Comment by jasonblais** [comment] 2017-11-13 13:13
Sweet, thanks @KishoreFartiyal!

**Comment by jasonblais** [comment] 2017-12-13 13:17
Hey @KishoreFartiyal, anything we can help with?

**Comment by jasonblais** [comment] 2018-09-13 11:33
Duplicate of a newly created help wanted ticket https://github.com/mattermost/mattermost-server/issues/9406

**Closed by jasonblais** 2018-09-13 11:33 UTC
Labels: Difficulty: Introductory, ReactJS, Up For Grabs
