### ISSUE TITLE
[API] wrong permission

### ISSUE THREAD

**Issue by renchili** [mattermost/mattermost-server#17918] opened 2021-07-14 02:52 UTC
#### Summary
Bot account cannot call create_bot
 "error": "Failed to Create Bot: : You do not have the appropriate permissions., "

#### Steps to reproduce
using a bot token with system_admin right to call this 
```
bot.Username = botName
bot.DisplayName = botName
bot.OwnerId = ownerID
Bot,resp := Client.CreateBot(&bot)
```

#### Expected behavior
system_admin should able to call API to create a bot

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
This code is no sense 
![image](https://user-images.githubusercontent.com/33677006/125553352-16f15608-977a-401a-a0fb-eae4f564f8b8.png)
https://github.com/mattermost/mattermost-server/blob/0276a69f0c61da8609259426001c194a494833a0/api4/bot.go#L55

**Comment by amyblais** [comment] 2021-07-14 13:08
@catalintomai @isacikgoz Are you able to reproduce this and is this a regression?

**Comment by amyblais** [comment] 2021-07-14 18:39
cc @DHaussermann @furqanmlk if you're able to reproduce ^

**Comment by DHaussermann** [comment] 2021-07-14 19:45
@amyblais and @renchili It is the expected behavior that a bot token is not permitted to create a bot. 

This is the existing behavior and I believe has been the case since bot accounts were introduced. I don't recall the reason for this exception. We could follow-up with a PM if we feel there is value in changing this.

**Comment by amyblais** [comment] 2021-09-03 19:44
Closing for now, please open a feature request here https://mattermost.uservoice.com/forums/306457-general!

**Closed by amyblais** 2021-09-03 19:44 UTC
