### ISSUE TITLE
Mattermost 4.9: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by discostur** [mattermost/mattermost-server#8649] opened 2018-04-19 07:39 UTC
#### Summary
Upgraded Mattermost to latest release (4.9) and it was running for one day, now we get the following exception:

```
Apr 19 08:19:31 mattermost systemd: Starting Mattermost...
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Using config file at /opt/mattermost/config/config.json
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Server is initializing...
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Pinging SQL master database
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Current version is 4.9.0 (4.9.0/Sat Apr 14 03:08:33 UTC 2018/3176e13b1f9b14192bef2337ff3fb9346f26ef66/004f26d8eb84cd548eb6c56c37f8ca49413e1322)
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Enterprise Enabled: true
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Current working directory is /opt/mattermost/bin
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Loaded config file from /opt/mattermost/config/config.json
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Able to write files to local storage.
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] License key from https://mattermost.com required to unlock enterprise features.
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Starting up plugins
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [WARN] unable to create user namespace: fork/exec /proc/self/exe: invalid argument
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [WARN] plugin sandboxing is not supported. plugins will run with the same access level as the server. See documentation to learn more: https://developers.mattermost.com/extend/plugins/security/
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Stopping Server...
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] stopping websocket hub connections
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [WARN] We appear to have already sent the stop checking for deadlocks command
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Shutting down plugins
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Closing SqlStore
Apr 19 08:19:31 mattermost platform: [2018/04/19 08:19:31 CEST] [INFO] Server stopped
Apr 19 08:19:31 mattermost platform: panic: runtime error: invalid memory address or nil pointer dereference
Apr 19 08:19:31 mattermost platform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcf6748]
Apr 19 08:19:31 mattermost platform: goroutine 1 [running]:
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/app.(*App).removePlugin(0xc42012a480, 0x13e6862, 0x4, 0x352701, 0x3ffe00)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/plugin.go:264 +0x1e8
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/app.(*App).InitPlugins(0xc42012a480, 0xc422081460, 0x18, 0xc422081480, 0x1e, 0x0)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/plugin.go:421 +0x499
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/cmd/commands.runServer(0x13f6bce, 0xb, 0xc420118400, 0xc4201184e0, 0x0, 0x0)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:91 +0x87b
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/cmd/commands.serverCmdF(0x24800c0, 0x24ba100, 0x0, 0x0, 0x0, 0x0)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:53 +0x10d
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x24800c0, 0xc420010180, 0x0, 0x0, 0x24800c0, 0xc420010180)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:753 +0x475
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24800c0, 0x24ba100, 0xc4201dbf40, 0x10f863c)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:843 +0x334
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x24800c0, 0x0, 0xc4201dbf40)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:791 +0x2b
Apr 19 08:19:31 mattermost platform: github.com/mattermost/mattermost-server/cmd.Run(0xc420010180, 0x0, 0x0, 0xc4201dbf70, 0x1109719)
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/cmd.go:14 +0x6d
Apr 19 08:19:31 mattermost platform: main.main()
Apr 19 08:19:31 mattermost platform: /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/main.go:33 +0x63
Apr 19 08:19:31 mattermost systemd: mattermost.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 19 08:19:31 mattermost systemd: Unit mattermost.service entered failed state.
Apr 19 08:19:31 mattermost systemd: mattermost.service failed.
```

#### Steps to reproduce
Start mattermost 4.9 via systemd script

#### Possible fixes
If i start mattermost via systemd it fails (yesterday it worked); However i can start mattermost manually via ./platform server command (CLI)

**Comment by lindy65** [comment] 2018-04-19 08:29
Hi @discostur,

Thanks for your feedback,

I'm not sure whether you'll find anything useful in [a previous discussion about this error](https://github.com/mattermost/mattermost-server/issues/5323) but I'll also ask our devs for their feedback to help troubleshoot.

**Comment by discostur** [comment] 2018-04-19 16:44
@lindalumitchell thanks, didn't find anything that would help from the other issue.

The error only happens if i try to start mattermost via systemd unit file:

```
[Unit]
Description=Mattermost
After=syslog.target network.target mysqld.service

[Service]
Type=simple
WorkingDirectory=/opt/mattermost/bin
User=mattermost
ExecStart=/opt/mattermost/bin/platform 
PIDFile=/var/spool/mattermost/pid/master.pid
LimitNOFILE=49152

[Install]
WantedBy=multi-user.target
```

Error:
```
Apr 19 18:41:08 mattermost.intern.internetx.de systemd[1]: mattermost.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 19 18:41:08 mattermost.intern.internetx.de systemd[1]: Unit mattermost.service entered failed state.
Apr 19 18:41:08 mattermost.intern.internetx.de systemd[1]: mattermost.service failed.
``` 

If i start it manually via
```
/opt/mattermost/bin/platform server
```
it runs fine

**Comment by lindalumitchell** [comment] 2018-04-20 22:47
@lindy65 I think the previous comment was meant for you. ;)

**Comment by lindy65** [comment] 2018-04-21 17:52
Thanks @lindalumitchell!

@discostur I've asked our engineers to help troubleshoot...

**Comment by jwilander** [comment] 2018-04-23 12:11
@discostur if your update your WorkingDirectory to `/opt/mattermost`, does that help?

Also which MM version did you upgrade from?

**Comment by lindy65** [comment] 2018-05-02 08:42
Hi @discostur,

Is your issue resolved?  OK to close this off here now?

**Comment by razorness** [comment] 2018-05-02 10:26
Having same issue ...

Ugraded from 4.8.x to 4.9.1. Using manual installation with systemd on Debian 8.10 (jessie) with Kernel Version 3.16.0-5-amd64 and locally running MariaDB behind Nginx Proxy.

Running as root works while running as user mattermost / starting via systemd results in:

```bash
mattermost@...:/opt/mattermost$ ./bin/platform
[2018/05/02 12:11:51 CEST] [INFO] Using config file at /opt/mattermost/config/config.json
[2018/05/02 12:11:51 CEST] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
[2018/05/02 12:11:51 CEST] [INFO] Server is initializing...
[2018/05/02 12:11:51 CEST] [INFO] Pinging SQL master database
[2018/05/02 12:11:51 CEST] [INFO] Current version is 4.9.0 (4.9.1/Fri Apr 27 03:49:57 UTC 2018/30b5547a57bd348b04ab587a6b4a22274fed3808/004f26d8eb84cd548eb6c56c37f8ca49413e1322)
[2018/05/02 12:11:51 CEST] [INFO] Enterprise Enabled: true
[2018/05/02 12:11:51 CEST] [INFO] Current working directory is /opt/mattermost
[2018/05/02 12:11:51 CEST] [INFO] Loaded config file from /opt/mattermost/config/config.json
[2018/05/02 12:11:51 CEST] [INFO] Able to write files to local storage.
[2018/05/02 12:11:51 CEST] [INFO] License key from https://mattermost.com required to unlock enterprise features.
[2018/05/02 12:11:51 CEST] [INFO] Starting up plugins
[2018/05/02 12:11:51 CEST] [WARN] unable to prepare namespace: unable to open os.DevNull: open /dev/null: permission denied
[2018/05/02 12:11:51 CEST] [WARN] plugin sandboxing is not supported. plugins will run with the same access level as the server. See documentation to learn more: https://developers.mattermost.com/extend/plugins/security/
[2018/05/02 12:11:52 CEST] [INFO] Stopping Server...
[2018/05/02 12:11:52 CEST] [INFO] stopping websocket hub connections
[2018/05/02 12:11:52 CEST] [WARN] We appear to have already sent the stop checking for deadlocks command
[2018/05/02 12:11:52 CEST] [INFO] Shutting down plugins
[2018/05/02 12:11:52 CEST] [INFO] Closing SqlStore
[2018/05/02 12:11:52 CEST] [INFO] Server stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcf65d8]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/app.(*App).removePlugin(0xc42009db00, 0x13e6862, 0x4, 0x352701, 0x3ffe00)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/plugin.go:264 +0x1e8
github.com/mattermost/mattermost-server/app.(*App).InitPlugins(0xc42009db00, 0xc42258a590, 0x9, 0xc42258a5b0, 0x10, 0x0)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/app/plugin.go:421 +0x499
github.com/mattermost/mattermost-server/cmd/commands.runServer(0x13f6bb4, 0xb, 0xc420114700, 0xc4201147e0, 0x0, 0x0)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:91 +0x87b
github.com/mattermost/mattermost-server/cmd/commands.serverCmdF(0x24800c0, 0x24ba100, 0x0, 0x0, 0x0, 0x0)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/commands/server.go:53 +0x10d
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x24800c0, 0xc420010180, 0x0, 0x0, 0x24800c0, 0xc420010180)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:753 +0x475
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24800c0, 0x24ba100, 0xc4201d5f40, 0x10f84cc)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x24800c0, 0x0, 0xc4201d5f40)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:791 +0x2b
github.com/mattermost/mattermost-server/cmd.Run(0xc420010180, 0x0, 0x0, 0xc4201d5f70, 0x11095a9)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/cmd/cmd.go:14 +0x6d
main.main()
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/mattermost-server/main.go:33 +0x63
```
Here is a working output of running on root level:

```bash
root@...:/opt/mattermost# ./bin/platform
[2018/05/02 12:15:45 CEST] [INFO] Using config file at /opt/mattermost/config/config.json
[2018/05/02 12:15:45 CEST] [INFO] Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
[2018/05/02 12:15:45 CEST] [INFO] Server is initializing...
[2018/05/02 12:15:45 CEST] [INFO] Pinging SQL master database
[2018/05/02 12:15:45 CEST] [INFO] Current version is 4.9.0 (4.9.1/Fri Apr 27 03:49:57 UTC 2018/30b5547a57bd348b04ab587a6b4a22274fed3808/004f26d8eb84cd548eb6c56c37f8ca49413e1322)
[2018/05/02 12:15:45 CEST] [INFO] Enterprise Enabled: true
[2018/05/02 12:15:45 CEST] [INFO] Current working directory is /opt/mattermost
[2018/05/02 12:15:45 CEST] [INFO] Loaded config file from /opt/mattermost/config/config.json
[2018/05/02 12:15:45 CEST] [INFO] Able to write files to local storage.
[2018/05/02 12:15:45 CEST] [INFO] License key from https://mattermost.com required to unlock enterprise features.
[2018/05/02 12:15:45 CEST] [INFO] Starting up plugins
[2018/05/02 12:15:45 CEST] [WARN] unable to prepare namespace: unable to open os.DevNull: open /dev/null: permission denied
[2018/05/02 12:15:45 CEST] [WARN] plugin sandboxing is not supported. plugins will run with the same access level as the server. See documentation to learn more: https://developers.mattermost.com/extend/plugins/security/
[2018/05/02 12:15:47 CEST] [INFO] Activated jira plugin
[2018/05/02 12:15:47 CEST] [INFO] Starting Server...
[2018/05/02 12:15:47 CEST] [INFO] Server is listening on [::]:8065
[2018/05/02 12:15:47 CEST] [INFO] Starting 8 websocket hubs
[2018/05/02 12:15:47 CEST] [INFO] Post.Message supports at most 16383 characters (65535 bytes)
[2018/05/02 12:15:47 CEST] [INFO] Using config file at /opt/mattermost/config/config.json
[2018/05/02 12:15:47 CEST] [INFO] Starting workers
[2018/05/02 12:15:47 CEST] [INFO] Starting schedulers.
```
I guessed the problem could be related to jira plugin, so I disabled jira plugin in config.json without any change. Deactivating plugin feature entirely resolves problem.

**Comment by discostur** [comment] 2018-05-02 11:07
@jwilander not really, problem still exists after changing working directory to /opt/mattermost. Upgrade was from 4.8.0 -> 4.9.0; Will give it a new try with version 4.9.1 ...

@razorness disableing plugins is no option for us because we need the jira plugin

**Comment by amyblais** [comment] 2018-05-19 17:17
Hi @discostur and @razorness Have you still experienced issues related to this?

**Comment by amyblais** [comment] 2018-05-22 22:46
Hi @discostur, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by amyblais** 2018-05-22 22:46 UTC

**Comment by razorness** [comment] 2018-06-09 21:11
@amyblais Sorry for the delay. I just deactivated jira plugins, so I had no further problems. I made no deep analysis.
