### ISSUE TITLE
It's possible to determine the existence of user in the system by HTTP response code

### ISSUE THREAD

**Issue by xtimon** [mattermost/mattermost-server#7897] opened 2017-11-23 13:10 UTC
#### Summary
It's possible to determine the existence of user in the system by HTTP response code:
if response code is 400 - user doesn't exist
if response code is 401 - user exist.

#### Steps to reproduce
Mattermost version 4.3.1 with LDAP Authorization.
Login with wrong password and login of existing user.
Login with wrong password and login which not exist.

#### Expected behavior
Response code should be the same for the both cases: 401

#### Observed behavior (that appears unintentional) 
Different response codes if login exist and if it doesn't (401 and 400).

**Comment by lindy65** [comment] 2017-11-25 18:00
Hi @xtimon,

Thanks for your feedback,

This is by design and we have a pull request [here](https://github.com/mattermost/docs/issues/885) to document the reasoning behind the decision.

**Comment by it33** [comment] 2017-11-25 18:08
@xtimon thanks again for the feedback, here's a draft response: https://github.com/mattermost/docs/pull/1657

This is work-in-progress, would highly appreciate your feedback.

**Comment by xtimon** [comment] 2017-11-28 12:47
In my opinion shouldn't matter where my service will be deployed. It's not 'Mattermost Inc' decision. What I want is to know from http logs, who tried to login using wrong credentials. But with status code 400 I can't. Because here a lot of other requests with such status, even the desktop application can create bad request and get response with code 400.

**Comment by it33** [comment] 2017-11-30 06:43
If you're looking to monitor login errors, the system is designed to support this via logs: https://docs.mattermost.com/administration/config-settings.html#logging

**Comment by xtimon** [comment] 2017-11-30 08:59
Unfortunately this logs are useless in my case because Mattermost server works behind a load balancer, which provides HTTPS and TLS. And I'll see only load balancer IP address in the logs.
Also instead of response code 404 Mattermost returns 200, is also by design?
Perhaps international standards was not created for Mattermost:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1

**Comment by ccbrown** [comment] 2017-12-04 09:52
> Unfortunately this logs are useless in my case because Mattermost server works behind a load balancer, which provides HTTPS and TLS. And I'll see only load balancer IP address in the logs.

This is actually pretty easy to fix. All you have to do is make sure your load balancer is forwarding the client's IP address with either the "X-Forwarded-For" or "X-Real-IP" HTTP header. If you're using NGINX, it's as simple as adding a "proxy_set_header" line to your configuration. Then your logs will always show the user's actual IP address instead of the load balancers'. You should be sure to do this anyways as it impacts Mattermost's ability to rate limit requests correctly.

> Also instead of response code 404 Mattermost returns 200. Is it also by design?

Which endpoint are you referring to? If something's incorrectly reporting 200 when it should be reporting a 404, I can go fix it right away.

**Comment by swestmeier** [comment] 2017-12-04 12:59
> This is actually pretty easy to fix. All you have to do is make sure your load balancer is forwarding the client's IP address with either the "X-Forwarded-For" or "X-Real-IP" HTTP header. If you're using NGINX, it's as simple as adding a "proxy_set_header" line to your configuration.

In our case it's that easy, as mattermost is running behind an AWS Application Load Balancer, which does not yet support those headers.

**Comment by MusikPolice** [comment] 2017-12-04 13:54
@swestmeier are you sure that the `X-Forwarded-For` header is not supported by ALBs? I can't find any official documentation to support this, but there exist [forum](https://forums.aws.amazon.com/message.jspa?messageID=738145#738145) and [blog posts](https://blog.kloud.com.au/2016/11/29/experiences-with-the-new-aws-application-load-balancer/) that claim that it still works, and the feature is mentioned [in the marketing docs](https://aws.amazon.com/elasticloadbalancing/details/) for the ALB as well:
 
> Layer-7 Load Balancing
> You can load balance HTTP/HTTPS applications and use layer 7-specific features, such as X-Forwarded-For headers.

**Comment by swestmeier** [comment] 2017-12-04 14:37
@MusikPolice Thx for the hint! Will check on the X-Forwarded-For header content for our ALB!

**Comment by xtimon** [comment] 2017-12-05 06:21
> Which endpoint are you referring to? If something's incorrectly reporting 200 when it should be reporting a 404, I can go fix it right away.
For example: https://demo.mattermost.com/myabe_such_url_exist

**Comment by xtimon** [comment] 2017-12-05 06:36
> Which endpoint are you referring to? If something's incorrectly reporting 200 when it should be reporting a 404, I can go fix it right away.

I was wrong. If found, it will be reported.

Thank you for the hint!

**Comment by xtimon** [comment] 2017-12-11 10:36
> Which endpoint are you referring to? If something's incorrectly reporting 200 when it should be reporting a 404, I can go fix it right away.

But it works only for curl. For any other client it doesn't work properly:

curl:
```
 curl -I https://oss.mattermost.com/non-existent-page
HTTP/1.1 404 Not Found
Server: nginx/1.4.6 (Ubuntu)
Date: Mon, 11 Dec 2017 10:05:09 GMT
Content-Type: text/plain; charset=utf-8
Connection: keep-alive
Location: /error?message=Sorry%2C+we+could+not+find+the+page.&details=
```

httpie (https://github.com/jakubroztocil/httpie):
```
http https://oss.mattermost.com/non-existent-page
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache, max-age=31556926, public
Connection: keep-alive
Content-Length: 3113
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/html; charset=utf-8
Date: Mon, 11 Dec 2017 10:45:54 GMT
Last-Modified: Wed, 22 Nov 2017 22:45:39 GMT
Server: nginx/1.4.6 (Ubuntu)
X-Frame-Options: SAMEORIGIN
X-Request-Id: c96zjt18qf87tnink68xojkemo
X-Version-Id: 4.4.0.4.4.2.477610ceae13c4ae1cb940d8ea3d3905.false

<!DOCTYPE html> <html> <head> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0"> <meta name=robots content="noindex, nofollow"> <meta name=referrer content=no-referrer> <title>Mattermost</title> <meta name=apple-mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-status-bar-style content=default> <meta name=mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-title content=Mattermost> <meta name=application-name content=Mattermost> <meta name=format-detection content="telephone=no"> <link rel=apple-touch-icon sizes=57x57 href=/static/files/787db8d8b82538cc1d5e8bcb8c21722d.png> <link rel=apple-touch-icon sizes=60x60 href=/static/files/cd9987714f4d92336c3ab203ff150a9a.png> <link rel=apple-touch-icon sizes=72x72 href=/static/files/1728fd5a009aabc77654b1f958c6f596.png> <link rel=apple-touch-icon sizes=76x76 href=/static/files/17cb12b7fc37d8229a6e72f3d6da0949.png> <link rel=apple-touch-icon sizes=144x144 href=/static/files/fba6362db1d8b3e27c9fb02fd0695c85.png> <link rel=apple-touch-icon sizes=120x120 href=/static/files/08959a08dc2488dfeb8660fc4630b145.png> <link rel=apple-touch-icon sizes=152x152 href=/static/files/bca263be9acd1df84b988b02c621b8ca.png> <link rel=icon type=image/png sizes=16x16 href=/static/files/532142b052832f94ffc35860545a7e5c.png> <link rel=icon type=image/png sizes=32x32 href=/static/files/c220e89731c31367c0f4e86e3442bee0.png> <link rel=icon type=image/png sizes=96x96 href=/static/files/173682cef105829829a008f1fc97e980.png> <link rel=icon type=image/png sizes=192x192 href=/static/files/0d367a00a16bde58f7e87c4481516a68.png> <link rel=manifest href=/static/files/fee9721a6305a49662a40ffd052a7965.json> <link rel=stylesheet class=code_theme> <style>.error-screen{font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;padding-top:50px;max-width:750px;font-size:14px;color:#333;margin:auto;display:none;line-height:1.5}.error-screen h2{font-size:30px;font-weight:400;line-height:1.2}.error-screen ul{padding-left:15px;line-height:1.7;margin-top:0;margin-bottom:10px}.error-screen hr{color:#ddd;margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}.error-screen-visible{display:block}</style> <script type="text/javascript" src="/static/main.d0d2ee96fc2c25e74c2c.js"></script></head> <body class=font--open_sans> <div id=root> <div class=error-screen> <h2>Cannot connect to Mattermost</h2> <hr/> <p>We’re having trouble connecting to Mattermost. If refreshing this page (Ctrl+R or Command+R) does not work, please verify that your computer is connected to the internet.</p> <br/> </div> <div class=loading-screen style=position:relative> <div class=loading__content> <div class="round round-1"></div> <div class="round round-2"></div> <div class="round round-3"></div> </div> </div> </div> <script>"function"!=typeof window.setup_root&&document.querySelector(".error-screen").classList.add("error-screen-visible"),window.setup_root()</script> <noscript> To use Mattermost, please enable JavaScript. </noscript> </body> </html>
```
postman:
![screenshot from 2017-12-11 13-35-42](https://user-images.githubusercontent.com/12657794/33827125-45be39fa-de78-11e7-8e84-005b4947132b.png)

**Comment by ccbrown** [comment] 2017-12-11 11:02
Yeah, that is weird.

It looks like we're responding with a status of 404 and "Location" header, which I don't believe is valid at all. But these clients seem to respect it and redirect anyways. If you omit the "-I" flag from curl you'll see it follows the redirect as well and appears to get a 200 status:

`curl -v https://oss.mattermost.com/non-existent-page`

This does looks to me like something we should address, and I've created a bug ticket in JIRA, here: https://mattermost.atlassian.net/browse/PLT-8345

Thanks for the info!

**Comment by xtimon** [comment] 2017-12-11 12:31
> If you're looking to monitor login errors, the system is designed to support this via logs: https://docs.mattermost.com/administration/config-settings.html#logging

> This is actually pretty easy to fix. All you have to do is make sure your load balancer is forwarding the client's IP address with either the "X-Forwarded-For" or "X-Real-IP" HTTP header. If you're using NGINX, it's as simple as adding a "proxy_set_header" line to your configuration. Then your logs will always show the user's actual IP address instead of the load balancer's. You should be sure to do this anyways as it impacts Mattermost's ability to rate limit requests correctly.

My log settings:
```  
  "LogSettings": {
        "EnableConsole": true,
        "ConsoleLevel": "DEBUG",
        "EnableFile": true,
        "FileLevel": "DEGUG",
        "FileFormat": "",
        "FileLocation": "",
        "EnableWebhookDebugging": true,
        "EnableDiagnostics": true
    }
```

And I have such log:
```
[2017/12/11 12:27:27 UTC] [DEBG] /
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/config/client
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me/preferences
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me/teams
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me/teams/members
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me/teams/unread
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/emoji
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/license/client
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/channels/nuh5thoczfgcifhm3emdj9hixe
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/channels/nuh5thoczfgcifhm3emdj9hixe/members/me
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me/teams/fq4wz5izoprsfrbb76cssc7ueh/channels
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/users/me/teams/fq4wz5izoprsfrbb76cssc7ueh/channels/members
[2017/12/11 12:27:28 UTC] [DEBG] POST - /api/v4/users/status/ids
[2017/12/11 12:27:28 UTC] [DEBG] POST - /api/v4/users/ids
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/channels/nuh5thoczfgcifhm3emdj9hixe/members/me
[2017/12/11 12:27:28 UTC] [DEBG] POST - /api/v4/users/ids
[2017/12/11 12:27:28 UTC] [DEBG] GET - /api/v4/channels/nuh5thoczfgcifhm3emdj9hixe/stats
[2017/12/11 12:27:28 UTC] [DEBG] POST - /api/v4/channels/members/me/view
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/teams
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/channels/nuh5thoczfgcifhm3emdj9hixe/posts
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/users/iyeujz86mfged8ybh6ag5r5zoh/status
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/websocket
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/emoji
[2017/12/11 12:27:29 UTC] [DEBG] POST - /api/v4/users/ids
[2017/12/11 12:27:29 UTC] [DEBG] POST - /api/v4/users/status/ids
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/posts/qpz78x1513dcifzute46cthuma/reactions
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/posts/3ja5jpcrf7nmjyce15r65s57qo/reactions
[2017/12/11 12:27:29 UTC] [DEBG] GET - /api/v4/posts/e7zgymyy8ididrpy3bes8s8hjh/reactions
[2017/12/11 12:27:33 UTC] [DEBG] POST - /api/v4/channels/members/me/view
```

How can I configure log format to see here client ip address?

**Comment by MusikPolice** [comment] 2017-12-11 13:55
@xtimon to the best of my knowledge, we don't log the IP address and HTTP response code. We're working on improving logging to include this kind of context in future releases. For the time being, if you're explicitly looking for what's logged if a user fails to authenticate, you can read through [this code](https://github.com/mattermost/mattermost-server/blob/master/app/authentication.go#L141) to see what you might expect in the logs.

**Comment by lindy65** [comment] 2017-12-20 08:00
Hi @xtimon,

I'll close this issue off for now but please feel free to come back with questions at any time :)

**Closed by lindy65** 2017-12-20 08:00 UTC
