### ISSUE TITLE
LDAP Sync not working anymore after Upgrade from 5.9.

### ISSUE THREAD

**Issue by eni23** [mattermost/mattermost-server#14510] opened 2020-05-08 12:10 UTC
## Summary
After upgrading from 5.9 LTS to 5.19 LTS, LDAP sync is not working anymore.

#### Steps to reproduce
Upgrade from 5.9 to 5.19 with LDAP sync enabled, but whitout group sync.

#### Expected behavior
LDAP sync is still working.

#### Observed behavior (that appears unintentional) 
LDAP sync is not working:
```
May 08 13:52:15 hostname-censored mattermost[17916]: 2020-05-08T13:52:15.613+0200        error        mlog/log.go:174        Failed job        {"workername": "EnterpriseLdapSync", "error": "LdapSession.getAllGroups: error retrieving ldap groups, LDAP Result Code 2 \"Protocol Error\": ", "job_id": "exj7d61g9tg6uk4kxxmggj5une"}
```
Looks like mattermost tries to do a group sync which we do not want.

LDAP connection works fine tough:
![Screenshot (4)](https://user-images.githubusercontent.com/3918506/81404374-9c4fef80-9135-11ea-89ca-283c3196de70.png)

#### Additional informations
We run mattermost in HA-Mode

**Comment by eni23** [comment] 2020-05-08 12:11
More additonal Infos: we can oly upgrade to LTS releases.

**Comment by amyblais** [comment] 2020-05-08 12:22
@eni23 What are your LDAP related settings set to?

**Comment by eni23** [comment] 2020-05-08 12:29
OK, i found the issue:

The following settings create the issue:
```json
    "LdapSettings": {
        "Enable": false,
        "EnableSync": true,
        "LdapServer": "CENSORED",
        "LdapPort": "636",
        "ConnectionSecurity": "TLS",
        "BaseDN": "CENSORED",
        "BindUsername": "CENSORED",
        "BindPassword": "CENSORED",
        "UserFilter": "(&(objectClass=CENSORED)(CENSORED=TRUE)(CENSORED=TRUE))",
        "GroupFilter": "",
        "GuestFilter": "",
        "GroupDisplayNameAttribute": "",
        "GroupIdAttribute": "",
        "FirstNameAttribute": "givenName",
        "LastNameAttribute": "sn",
        "EmailAttribute": "mail",
        "UsernameAttribute": "mail",
        "NicknameAttribute": "",
        "IdAttribute": "uid",
        "PositionAttribute": "",
        "LoginIdAttribute": "mail",
        "SyncIntervalMinutes": 5,
        "SkipCertificateVerification": false,
        "QueryTimeout": 60,
        "MaxPageSize": 0,
        "LoginFieldName": "Email",
        "LoginButtonColor": "",
        "LoginButtonBorderColor": "",
        "LoginButtonTextColor": "",
        "Trace": false
    },
```
if set the group stuff to something like (does not matter if search not returns any results):
```json
        "GroupFilter": "(objectClass=group)",
        "GroupDisplayNameAttribute": "cn",
        "GroupIdAttribute": "uid",
```
Then the LDAP-sync works again. But this is definitely a bug.

**Comment by amyblais** [comment] 2020-05-13 12:14
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-25121.

**Comment by mkraft** [comment] 2020-05-22 17:49
@eni23 Are you able to clear those fields again and see if your sync works? Those fields are not required and I was not able to reproduce the bug you experienced when upgrading from v5.9.0 to v5.19.0.

**Comment by amyblais** [comment] 2020-06-30 14:54
Closing for now as there hasn't been feedback on this for a while. Please re-open this issue if the problem persists,

**Closed by amyblais** 2020-06-30 14:54 UTC
Labels: Bug Report/Open
