### ISSUE TITLE
Firefox: Clicking on PDF attachment raises PDFJS error

### ISSUE THREAD

**Issue by tsipizic** [mattermost/mattermost-server#8382] opened 2018-02-28 10:28 UTC
#### Summary
Clicking on PDF attachment preview raises error on the console
No PDFJS.workerSrc specified

#### Steps to reproduce
Mattermost version 4.7.2
Share PDF in a channel and instead of clicking download click on the title of the document

#### Expected behavior
Show PDF preview

#### Observed behavior (that appears unintentional) 
Error on JS console
No PDFJS.workerSrc specified

#### Possible fixes
Error is in minified JS file

**Comment by lindy65** [comment] 2018-03-05 09:29
Hi @tsipizic,

Thanks for your feedback,

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) ...  Wondering whether it reproduces there for you?  I see the .pdf preview when clicking on the file or the title of the file.

Are you in browser or on the desktop app?

**Comment by tsipizic** [comment] 2018-03-05 09:41
Thanks for your answer @lindy65 . I can reproduce with Firefox but not with Chromium on nightly build server

**Comment by Rudloff** [comment] 2018-03-05 14:40
I can also repoduce this issue with Firefox 52.6.0 on Mattermost 4.7.2 and 4.8.0-rc1.

**Comment by M1dgard** [comment] 2018-03-05 19:40
I can reproduce with Firefox 58.0.2 (with [some patches](https://aur.archlinux.org/packages/firefox-eme-free/)) and Firefox 52.6.0 on your pre-release server.

This is what the page and JavaScript log look like:
![screenshot_2018-03-05_20-35-51](https://user-images.githubusercontent.com/4283376/36995618-dd00e6a4-20b4-11e8-8a0f-884ae1895c53.png)

**Comment by lindy65** [comment] 2018-03-06 06:45
@tsipizic @Rudloff @M1dgard 

Thanks for the feedback and JS console error log.  Seems like this is a Firefox-only issue...

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-9735) to investigate so will close this issue off here and we can track via the ticket.

**Closed by lindy65** 2018-03-06 06:45 UTC
