### ISSUE TITLE
fresh install 5.6 remain no initial configuration and setup (but login screen)  while ok in 5.5.1

### ISSUE THREAD

**Issue by nephaste** [mattermost/mattermost-server#10007] opened 2018-12-15 12:41 UTC
Hi Mattermost Team

I built a qpkg on Qnap NAS... based on generic linux x64 pacakge you propose

while in 5.5.1 with fresh install there was no issue... port 8065 drop me to the initial config setup

i did a 5.6.0 this morning, and a new fresh install port 8065 drop me on Login screen directly (not working because no init done previously), it drops on http://192.168.0.8:8065/login

do you have any clue.. ?  migration to 5.5.1 to 5.6 doesnt seems create issue 

nothing in revelant in logs... may be somethin changed in install process but cant find

i simply start ./bin/mattermost as usual

DB are well created everything look ok in mattermost 5.6 logs...

`{"level":"info","ts":1544877685.4952974,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/share/CACHEDEV1_DATA/.qpkg/MattermostPRO/mattermost/i18n/en.json'"}
{"level":"info","ts":1544877685.495576,"caller":"app/app.go:143","msg":"Server is initializing..."}
{"level":"info","ts":1544877685.5053344,"caller":"sqlstore/supplier.go:207","msg":"Pinging SQL master database"}
{"level":"info","ts":1544877691.9721217,"caller":"sqlstore/upgrade.go:103","msg":"The database schema has been set to version 5.6.0"}
{"level":"error","ts":1544877709.3719351,"caller":"commands/server.go:79","msg":"SiteURL must be set. Some features will operate incorrectly if the SiteURL is not set. See documentation for details: http://about.mattermost.com/default-site-url"}
{"level":"info","ts":1544877709.3720853,"caller":"commands/server.go:82","msg":"Current version is 5.6.0 (5.6.0/Fri Dec 14 20:58:12 UTC 2018/0c1207215852a8726c3f09dea157d597fec368df/2c2d33b22b4c2938938eade4b9914748c1be9d3b)"}
{"level":"info","ts":1544877709.3721285,"caller":"commands/server.go:83","msg":"Enterprise Enabled: true"}
{"level":"info","ts":1544877709.3721843,"caller":"commands/server.go:84","msg":"Current working directory is /share/CACHEDEV1_DATA/.qpkg/MattermostPRO/mattermost"}
{"level":"info","ts":1544877709.372494,"caller":"commands/server.go:85","msg":"Loaded config file from /share/CACHEDEV1_DATA/.qpkg/MattermostPRO/mattermost/config/config.json"}
{"level":"info","ts":1544877709.3727775,"caller":"filesstore/localstore.go:33","msg":"Able to write files to local storage."}
{"level":"info","ts":1544877709.3767552,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1544877709.3780055,"caller":"app/migrations.go:25","msg":"Migrating roles to database."}
{"level":"info","ts":1544877710.0525384,"caller":"sqlstore/post_store.go:1286","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"info","ts":1544877710.151196,"caller":"app/migrations.go:101","msg":"Migrating emojis config to database."}
{"level":"info","ts":1544877710.2418342,"caller":"app/plugin.go:130","msg":"Starting up plugins"}
{"level":"info","ts":1544877714.7802174,"caller":"app/server.go:168","msg":"Starting Server..."}
{"level":"info","ts":1544877714.7804759,"caller":"app/server.go:228","msg":"Server is listening on [::]:8065"}
{"level":"info","ts":1544877714.802874,"caller":"app/web_hub.go:75","msg":"Starting 8 websocket hubs"}
{"level":"info","ts":1544877714.8793347,"caller":"jobs/workers.go:68","msg":"Starting workers"}
{"level":"info","ts":1544877714.880772,"caller":"jobs/schedulers.go:72","msg":"Starting schedulers."}
`
did i miss something ?

logs in 5.5.1 all is perfect

{"level":"info","ts":1544879471.5019069,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/share/CACHEDEV1_DATA/.qpkg/MattermostPRO/mattermost/i18n/en.json'"}
{"level":"info","ts":1544879471.5020764,"caller":"app/app.go:204","msg":"Server is initializing..."}
{"level":"info","ts":1544879471.505077,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
{"level":"info","ts":1544879471.506172,"caller":"sqlstore/channel_store_experimental.go:47","msg":"Enabling experimental public channels materialization"}
{"level":"info","ts":1544879478.4752612,"caller":"sqlstore/upgrade.go:101","msg":"The database schema has been set to version 5.5.0"}
{"level":"error","ts":1544879500.1406312,"caller":"commands/server.go:79","msg":"SiteURL must be set. Some features will operate incorrectly if the SiteURL is not set. See documentation for details: http://about.mattermost.com/default-site-url"}
{"level":"info","ts":1544879500.1407008,"caller":"commands/server.go:82","msg":"Current version is 5.5.0 (5.5.1/Thu Dec 6 09:21:58 UTC 2018/826252252404c13bf564a8c4fd51616fc2cc4df9/19ede6fcdfbfa13d72f67e4c76307efce8d8ee56)"}
{"level":"info","ts":1544879500.140714,"caller":"commands/server.go:83","msg":"Enterprise Enabled: true"}
{"level":"info","ts":1544879500.1407242,"caller":"commands/server.go:84","msg":"Current working directory is /share/CACHEDEV1_DATA/.qpkg/MattermostPRO/mattermost"}
{"level":"info","ts":1544879500.1408267,"caller":"commands/server.go:85","msg":"Loaded config file from /share/CACHEDEV1_DATA/.qpkg/MattermostPRO/mattermost/config/config.json"}
{"level":"info","ts":1544879500.1409335,"caller":"filesstore/localstore.go:33","msg":"Able to write files to local storage."}
{"level":"info","ts":1544879500.142633,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1544879500.1431584,"caller":"app/app.go:545","msg":"Migrating roles to database."}
{"level":"info","ts":1544879500.5977263,"caller":"sqlstore/post_store.go:1297","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}
{"level":"info","ts":1544879500.6550121,"caller":"app/app.go:621","msg":"Migrating emojis config to database."}
{"level":"info","ts":1544879500.7548027,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
{"level":"info","ts":1544879501.3832812,"caller":"app/server.go:88","msg":"Starting Server..."}
{"level":"info","ts":1544879501.383419,"caller":"app/server.go:148","msg":"Server is listening on [::]:8065"}
{"level":"info","ts":1544879501.391863,"caller":"app/web_hub.go:75","msg":"Starting 8 websocket hubs"}
{"level":"info","ts":1544879501.423718,"caller":"jobs/workers.go:63","msg":"Starting workers"}
{"level":"info","ts":1544879501.4242878,"caller":"jobs/schedulers.go:68","msg":"Starting schedulers."}
{"level":"info","ts":1544879572.6187336,"caller":"migrations/worker.go:109","msg":"Worker: Job is complete","worker":"Migrations","job_id":"eq7sgyauiibppm9ekpprrqotfh"}

**Comment by jasonblais** [comment] 2018-12-17 13:20
@nephaste Thank you for the report! We've created a ticket to investigate, but it appears to be a bug. You should be redirected to user account creation page if no users exist on the system.

https://mattermost.atlassian.net/browse/MM-13520

**Comment by MagnificentPako** [comment] 2018-12-17 17:40
Not sure if my problem is linked to this but after manually creating an account (I never got to the register page so I tried to do it from the CLI) I couldn't access the system console from that account even after making it a system admin.

**Comment by jasonblais** [comment] 2018-12-17 17:43
@MagnificentPako Thanks for the note, have added that detail to the ticket as well. https://mattermost.atlassian.net/browse/MM-13520

We have a triage in the next hour where we'll discuss these issues.

**Comment by jasonblais** [comment] 2018-12-17 18:40
@nephaste @MagnificentPako Heads up that we're now investigating both issues reported above separately and planning a 5.6.1 for them.

https://mattermost.atlassian.net/browse/MM-13520
https://mattermost.atlassian.net/browse/MM-13536

We'll announce the release date, but expect it to be this week before the holidays.

**Comment by nephaste** [comment] 2018-12-17 18:48
thanks Jason

**Comment by MagnificentPako** [comment] 2018-12-17 19:38
@jasonblais looks like the ticket for my (separate) issue was flagged "not reproducable". I hope  you don't mind if I provide some info here:

I set mattermost up with `docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview`. After that I went to https://instance.url/signup_email/ and created an account. After that I assumed I should be able to create a team but instead I only get this !()[https://0x0.st/skv2.png]. After creating a team manually and adding the initial user I am unable to access the console; the menu at the top left doesn't have any administrative options.

**Comment by jasonblais** [comment] 2018-12-17 20:34
@MagnificentPako Would you know if you have other users and/or System Admins on the system?

The console is only accessible to System Admins - if you create a team, you'll become the team owner but would not have System Admin privileges.

**Comment by jasonblais** [comment] 2018-12-21 15:57
@nephaste Fix for your issue is resolved in 5.6.1 and is available for download at https://mattermost.com/download/. Thank you for letting us know about it!

@MagnificentPako I'll close the issue, but feel free welcome to open a new one for the issue you're experiencing. As a note, if there are other users or System Admins already in the system, creating a team won't give you System Admin privileges and access to the System Console.

**Closed by jasonblais** 2018-12-21 15:57 UTC

**Comment by nephaste** [comment] 2018-12-23 19:09
confirmed it is fixed .. thanks to everyones
