### ISSUE TITLE
Log `FileLocation` config behavior changed

### ISSUE THREAD

**Issue by kemenaran** [mattermost/mattermost-server#7456] opened 2017-09-17 07:33 UTC
#### Summary
In the 4.2.0 release the behavior of the `FileLocation` config key for log files changed: it is now treated as a path (rather than a file).

#### Steps to reproduce
1. Install Mattermost 4.1.0
2. Open `config/config.json`
2. Configure the log file `FileLocation` configuration parameter to be `"/var/log/mattermost.log"`
3. Upgrade to Mattermost 4.2.0

#### Expected behavior
The upgraded Mattermost server starts correctly.

#### Observed behavior (that appears unintentional) 
The upgraded Mattermost server crashes with this message:

```
FileLogWriter("/var/log/mattermost.log/mattermost.log"): open /var/log/mattermost.log/mattermost.log: not a directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x95da6f]
```

#### Possible fixes
As a workaround, changing the log `FileLocation` to be a path (e.g. `/var/log`) fixes the issue. But the change of behavior still breaks app during the upgrade process.

**Comment by MusikPolice** [comment] 2017-09-18 14:44
This behaviour was intentionally changed as a part of https://github.com/mattermost/mattermost-server/commit/0b5c0794fdcbb551c1233dcdfbdf5c7deb585fd6

See the following tickets for context:
- https://github.com/mattermost/mattermost-server/pull/5949
- https://mattermost.atlassian.net/browse/PLT-5906

**Comment by MusikPolice** [comment] 2017-09-18 14:48
Closing this issue, as the reported behaviour is intended.

**Comment by jasonblais** [comment] 2017-09-18 15:23
Hey @kemenaran, thanks again for the report!

Just a couple of quick questions:
1) We had an upgrade note for v3.8 related to the filepath, not sure if you were aware? https://docs.mattermost.com/administration/important-upgrade-notes.html
2) Do you know if the log files were working properly in Mattermost v4.1 or not ?

**Comment by kemenaran** [comment] 2017-09-18 16:17
@jasonblais thanks for the link to the documentation. I missed the upgrade notes for the 3.8 version, indeed. Anyway if this change was intentional I'll definitely fix the `mattermost_ynh` upgrade script to perform the relevant migration, and use the new behavior.

> Do you know if the log files were working properly in Mattermost v4.1 or not ?

I looked at the log, and it seems in Mattermost 4.1 the messages were logged, but to an erroneous file. For instance with `FileLocation: "/var/log/mattermost.log"` the messages would be logged to `/var/log/mattermost.logmattermost.log`.

**Comment by jasonblais** [comment] 2017-09-18 16:38
Thanks @kemenaran, sounds like it was most likely caused by the v3.8 breaking change. 

Anything we could do better to announce/inform developers like yourself about such breaking changes?

**Comment by lindy65** [comment] 2017-09-27 08:17
I'll close this issue off for now but feel free to re-open in need.

**Closed by lindy65** 2017-09-27 08:17 UTC
