### ISSUE TITLE
Disconnection when tagging someone

### ISSUE THREAD

**Issue by eloi29** [mattermost/mattermost-server#8852] opened 2018-05-25 13:41 UTC
#### Summary
We are using mattermost server 4.8.1 with 80+ users.
When tagging someone, we encounter random disconnection on the web browser. 

#### Steps to reproduce
Add @user in your message. Randomly you get disconnected

Have you ever see this issue.

Thanks

**Comment by amyblais** [comment] 2018-05-25 22:36
Hi @eloi29! Thank you for reaching out.

Can you help with the following additional information:

1. Which web browser does this issue reproduce on?
2. Does this also reproduce on mobile (if you have used / are using it)?
3. Do you see any errors in logs when the disconnection occurs?

I have been personally unable to reproduce the issue on the latest server (v4.10) so I also recommend upgrading. 

You can also test this on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) (which is on the latest server version) to see what you experience there.

Happy to help further troubleshoot this!

**Comment by eloi29** [comment] 2018-06-01 13:03
Hi @amyblais,

Thanks for your answer:

1. We reproduce the issue with firefox and chrome
2. We do not reproduce the issue on mobile
3. Please see the logs when the issue occurs:

> [2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/a5kach11rjy93pbgbi3oo57aza/image:ServeHTTP code=401 rid=oh7utythstggbn1ufqgk33zh5y uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/wpyhz64q8bn5mq7u556dt984ec/image:ServeHTTP code=401 rid=ctuya31bmjbw9pofy4ew3j4epy uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/ar5kgy8xapn79qzd43fiair1uw/image:ServeHTTP code=401 rid=rh8afguyi7ynxcpf5b494spqac uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/zo69f1m6m3rejn8g6h3ukjzgwc/image:ServeHTTP code=401 rid=u5c4g8k8wfr53pti3gn394xhnh uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/p1jxody1xt8zimo7up9w7xmohc/image:ServeHTTP code=401 rid=t9hyf6t4yjftdcihwhpbtg9n9r uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/14y4tmjjgfb39mfaakwh8mrcgr/image:ServeHTTP code=401 rid=4i7bh3f4iib5uyzcngicq7tyjc uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:55 EDT] [INFO] Invalid Session err=GetSession: Invalid session token=xxxxxxxxxxxxxxxxxxxxxxxx, err=<no value>, createSessionForUserAccessToken: Invalid or missing token, EnableUserAccessTokens=false
[2018/05/31 08:57:55 EDT] [INFO] /api/v4/users/ixbm51xgqtrcuc1e7rbamioype/image:ServeHTTP code=401 rid=fhmiwpw9y3yczqad5p6t17ga4r uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: token=xxxxxxxxxxxxxxxxxxxxxxxx]
[2018/05/31 08:57:56 EDT] [INFO] /api/v4/users/autocomplete: code=401 rid=11e3eebsyif5fpqzf5a6hsjn6r uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: UserRequired]
[2018/05/31 08:57:56 EDT] [INFO] /api/v4/emoji/name/plusun: code=401 rid=5scmsbect7fqbxw8yydatzmxdr uid= ip=1.2.3.4 Invalid or expired session, please login again. [details: UserRequired]

**Comment by amyblais** [comment] 2018-06-01 14:43
Hi @eloi29! Thank you for the additional information.

I can ask a colleague to take a look at the logs that you posted - in the meanwhile, can you help test if you see the same behaviour on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) (which is on v4.10). We also usually recommend upgrading to the latest server version as there might be bugs related to this that have been resolved in the latest server versions along with performance related improvements.

Let me know if the above suggestion sounds good, or if upgrading is not an option at this point.

**Comment by amyblais** [comment] 2018-06-11 12:12
Hi @eloi29! Following up here - please let me know if the above suggestion sounds good ^

**Comment by amyblais** [comment] 2018-06-15 13:11
Hi @eloi29, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by amyblais** 2018-06-15 13:11 UTC
