### ISSUE TITLE
Deleted Team Relationship Prevents Login

### ISSUE THREAD

**Issue by tooolbox** [mattermost/mattermost-server#8320] opened 2018-02-17 02:32 UTC
#### Summary
Relationship with Deleted Team Prevents Login

#### Steps to reproduce
Version: 4.0.0  (4.0.2)
Database: mysql

On a particular MM instance, I was previously a member of Team A.  I then became a member of Team B.  At some point in time, I was removed from Team A and I believe Team A was deleted.  This has created an issue where I can't login to this MM instance.

Unfortunately, I can't know for sure the sequence of removal and/or deletion as I am not the administrator of the instance.  And frankly, I'm not 100% sure there isn't some other factor involved as well.

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

There are three phenomena here:

### Login
When I go to log on in Chrome, I type in my credentials and hit "Login".  I get no feedback, nothing in the console, no redirect.  It does seem to log me in, though, see below.

### Chat
When I have "logged on", and manually navigate to a chat location such as Town Square, I get a blank screen.  (Sometimes get the three little blinking dots for a split second.)   In my console, I have the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'substring' of undefined
    at t.value (team_button.jsx:55)
    at d._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:802)
    at d._renderValidatedComponent (ReactCompositeComponent.js:825)
    at d.performInitialMount (ReactCompositeComponent.js:365)
    at d.mountComponent (ReactCompositeComponent.js:261)
    at Object.mountComponent (ReactReconciler.js:49)
    at mountChildren (ReactMultiChild.js:240)
    at m._createInitialChildren (ReactDOMComponent.js:707)
    at mountComponent (ReactDOMComponent.js:526)
    at Object.mountComponent (ReactReconciler.js:49)
```

This traces to the following code:
```html
<div className='team-btn__initials'>
    {this.props.displayName.substring(0, 2)} // <- bork
    <div className='team-btn__content'>
        {this.props.displayName}
    </div>
</div>
```

The problem is that `props` contains no `displayName`.  Here are the stringified props:
```json
{
  "url": "/undefined",
  "tip": "",
  "active": false,
  "isMobile": false,
  "unread": true,
  "mentions": 2,
  "btnClass": "",
  "placement": "right",
  "disabled": false
}
```

I can sometimes get past this error by erasing the offending line, saving, closing the console, opening up another browser tab and hitting a chat URL again.  Sometimes not; its unpredictability makes me uncertain about how I'm getting around it.

### Mobile

When I try to sign into the MM instance on the iOS mobile app, I get the following message:

```
undefined is not an object (evaluating 't.mention_count=e.mention_count')
```

However, I can tell that I'm logged in, because my phone immediately starts receiving notifications when someone chats me in that MM instance.

#### Possible fixes

Digging around in `team_sidebar_controller.jsx`, I find this function:
```js
    getStateFromStores() {
        const teamMembers = TeamStore.getMyTeamMembers();
        const currentTeamId = TeamStore.getCurrentId();

        return {
            teams: TeamStore.getAll(),
            teamListings: TeamStore.getTeamListings(),
            teamMembers,
            currentTeamId,
            show: teamMembers && teamMembers.length > 1,
            isMobile: Utils.isMobile()
        };
    }
```

When I put some breakpoints in, I can see that the return value is: (sanitized)
```json
{
  "teams": {
    "teamId#1": {
      "id": "teamId#1",
      "create_at": 55555555555,
      "update_at": 55555555555,
      "delete_at": 0,
      "display_name": "Team Name",
      "name": "team-name",
      "description": "",
      "email": "example@example.com",
      "type": "O",
      "company_name": "",
      "allowed_domains": "",
      "invite_id": "blahblahblah",
      "allow_open_invite": false
    }
  },
  "teamListings": {},
  "teamMembers": [
    {
      "team_id": "teamId#1",
      "user_id": "xyz123",
      "roles": "team_user",
      "delete_at": 0,
      "mention_count": 0,
      "msg_count": 0
    },
    {
      "mention_count": 2,
      "msg_count": 154
    }
  ],
  "currentTeamId": "teamId#1",
  "show": true,
  "isMobile": false
}
```

You can see that in `teamMembers` there's a second team, but all it has is a mention & msg count.  That's what causes the UI to explode when it's thrown in there.

When I checked with my admin, he said that he doesn't see that I'm a member of any team except the one I'm currently active in, and he doesn't want to dive into the DB to find expired relationship records or something.

I hope this is enough information, let me know if anything else is needed.

**Comment by lindy65** [comment] 2018-02-19 08:40
Hi @tooolbox,

Thanks for your detailed report!

There have been many changes to teams since v4.0...  Could we have your help upgrading to [the latest version](https://about.mattermost.com/download/) and letting us know if the issue still reproduces for you?

**Comment by lindy65** [comment] 2018-02-23 07:45
Hi @tooolbox 

Is your issue resolved after upgrading?

**Comment by tooolbox** [comment] 2018-02-23 17:14
Hey @lindy65, thanks for checking in on this.

I talked with the admin of the instance and he's planning to upgrade soon.  Due to a variety of factors, it might not be for a week or two.

How should we handle this?  Leave the issue open?  Close it and reopen if upgrading doesn't solve it?

Thanks.

**Comment by lindy65** [comment] 2018-02-23 17:59
Hi @tooolbox,

Let's leave the issue open until you've upgraded and we can take it from there 👍

**Comment by lindy65** [comment] 2018-03-06 09:56
Hi @tooolbox,

Just popping in to see how it's going and whether you've upgraded yet and been able to test to see whether your issue is still reproducing on the latest version?

**Comment by tooolbox** [comment] 2018-03-06 17:26
Hey @lindy65,

Hasn't happened yet :/  I'm nudging the admin and think it'll be another week or two due to things on his plate.  Sorry for the delay...

**Comment by lindy65** [comment] 2018-03-07 08:34
No worries @tooolbox,

We'll keep this issue open for now and wait to hear back after your upgrade :)

**Comment by avasconcelos114** [comment] 2018-04-27 09:45
I can't say for sure if this will be @tooolbox 's case. 

But we faced the same issues when using version 4.5. 

I tried reproducing this bug on version 4.9, and while it seems that you're able to log in normally. The screen goes blank when switching to another team (which led me to believe that [this](https://github.com/mattermost/desktop/issues/767) issue I originally reported for desktop may not have been a desktop issue after all).

To offer more information on the issue in question, the console shows this error:
![image](https://user-images.githubusercontent.com/29700158/39355655-bb614b7a-4a48-11e8-8a2d-88d2dbfa3df4.png)

Which was pointing to [this bit](https://github.com/mattermost/mattermost-redux/blob/f1c26dd9e95996ecb84ce98371dad66adfc5c2d5/src/selectors/entities/roles.js#L26) of the `mattermost-redux` project.

What seems to be happening is that the `team_sidebar_controller.jsx` is initially receiving empty hunks of data from what would be deleted teams (which them somehow dissappear once the component is re-rendered) 
![image](https://user-images.githubusercontent.com/29700158/39356249-853ec048-4a4a-11e8-93ab-47b388778e1d.png)

I suspect both the issue I submitted and this one are symptoms of the same cause... the root cause still escapes me though

**Comment by avasconcelos114** [comment] 2018-05-02 06:43
New update to why It seems that this is happening.

It looks like when a Team is deleted using the API `https://your-mattermost-url.com/api/v4/teams/{team_id}`, the data pertaining to getting team members for a user still remains, as it can be verified by running the `https://your-mattermost-url.com/api/v4/users/me/teams/members`.

Meaning that as the reducer for `state.entities.teams` adds team members, data from deleted teams also gets included in that bunch.

I went ahead and added the following condition to prevent `getMyTeamRoles` from trying to split an `undefined` variable, and now everything seems to be put back in order:
```diff
export const getMyTeamRoles = createSelector(
    getTeamMemberships,
    (teamsMemberships) => {
        const roles = {};
        if (teamsMemberships) {
            for (const key in teamsMemberships) {
+                if (teamsMemberships.hasOwnProperty(key) && teamsMemberships[key].roles) {
                    roles[key] = new Set(teamsMemberships[key].roles.split(' '));
                }
            }
        }
        return roles;
    }
);
```

However I feel like the real fix to this would be to ensure a member's roles for a team also gets deleted when a team is deleted.

**Comment by lindy65** [comment] 2018-05-03 07:03
Hi @avasconcelos114 

We've opened a [ticket](https://mattermost.atlassian.net/browse/MM-10432) to fix the issue in your comment above.

**Comment by lindy65** [comment] 2018-05-09 08:27
I'll close this issue off here for now as the PR in the above-linked ticket has been merged.

**Closed by lindy65** 2018-05-09 08:27 UTC

**Comment by tooolbox** [comment] 2018-05-28 18:14
@lindy65 

Thanks for keeping this open as long as you did :)

My server admin upgraded to 4.10, and while I'm not seeing the issue I was previously having, I *am* seeing what @avasconcelos114 was running into.

```js
var getMyTeamRoles = exports.getMyTeamRoles = (0, _reselect.createSelector)(_teams.getTeamMemberships, function (teamsMemberships) {
    var roles = {};
    if (teamsMemberships) {
        for (var key in teamsMemberships) {
            if (teamsMemberships.hasOwnProperty(key)) {
                roles[key] = new Set(teamsMemberships[key].roles.split(' ')); // <- Cannot read property 'split' of undefined
            }
        }
    }
    return roles;
});
```

This strikes me as odd because you said the PR that fixes this was merged, and the ticket you linked to says version 4.10, and our MM server is now on 4.10.0...

Any thoughts?

**Comment by tooolbox** [comment] 2018-05-28 18:27
Aha, I see that in [4.10](https://docs.mattermost.com/administration/changelog.html) we have:
> - Fixed an issue where a member’s roles for a team wasn’t properly deleted when the team was deleted via the API, causing crashing issues.

Seems like the underlying bug was fixed, but I still have the symptoms since my particular team was deleted under an old version.  I guess I would have expected the `roles` truthiness check to have been included in the PR to handle existing, affected users.

Ah, well!  Is there a way to handle this?

**Comment by tooolbox** [comment] 2018-05-28 19:01
I got my admin to root around in the DB and he found that while I did not have some sort of stuck record as belonging to another team, I was in a Channel that belonged to another team and therefore was getting a `mention` count for that Channel that was then causing this problem.

Anyway, he just removed my membership of that Channel straight in the DB and it works fine now.

**Comment by lindy65** [comment] 2018-05-29 07:18
Hey @tooolbox :)

Thanks for coming back to report on your issue and how you resolved it!  Glad it's working for you now :)
