### ISSUE TITLE
User Management User Status Filter for Member Missing

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#13982] opened 2020-03-03 15:29 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
User Status Filter for Member Missing

#### Steps to reproduce

System Console --> Users

and in here, the option to filter by "Member" is missing

![image](https://user-images.githubusercontent.com/363587/75790784-b0701d00-5d91-11ea-9572-0cd0fb182530.png)

#### Expected behavior

Options for Inactive, System Admin, Guest are available, but no filter option for Member exists.

#### Observed behavior (that appears unintentional) 

Options for Inactive, System Admin, Guest are available, but no filter option for Member exists.

#### Possible fixes

Options for Member could be added to help filter existing members on the server.

**Comment by amyblais** [comment] 2020-03-03 15:51
@arjitc What server version are you on?

**Comment by arjitc** [comment] 2020-03-03 18:26
@amyblais I'm on,
Mattermost Version: 5.20.1
Database Schema Version: 5.20.0

**Comment by amyblais** [comment] 2020-03-04 21:26
@arjitc Our team confirmed this is not a bug. Would you be open to creating a feature request issue for this?

**Comment by amyblais** [comment] 2020-03-31 14:59
I'll close this for now but I hope you will open a feature request issue for this,

**Closed by amyblais** 2020-03-31 14:59 UTC
