### ISSUE TITLE
No notification comming from the active channel 

### ISSUE THREAD

**Issue by koopernick** [mattermost/mattermost-server#14121] opened 2020-03-22 10:50 UTC
#### Summary
No notification from the active channel, from windows 10

server : 5.21
client (windows) : 4.4.0

#### Steps to reproduce
There is no notification coming from the active channel, when the windows client is minimize.
All notifications are working for all other channels but the active one (especially when minimized)
All of our users have this issue (it's not just a random one).

#### Expected behavior
We expect every notifications, doesn't matter if the channel is active, or if the client is minimized.

#### Observed behavior (that appears unintentional) 
No notification (no sound notification, no count in windows task bar, no notification in windows notification center, absolutely nothing from the active channel).

#### Possible fixes
I have absolutely no idea !

**Comment by amyblais** [comment] 2020-03-23 13:19
I'll close this as a duplicate of https://github.com/mattermost/desktop/issues/1234.

**Closed by amyblais** 2020-03-23 13:19 UTC
