### ISSUE TITLE
Jump to Flagged Post cannot be consecutively used for the same Flagged Post

### ISSUE THREAD

**Issue by mattrampolla** [mattermost/mattermost-server#8010] opened 2017-12-27 21:10 UTC
#### Summary
Once the ‘Jump’ to Flagged Post function is used, a user cannot jump back to the same post until they navigate out of the current channel or select a different flagged post to ‘Jump’ to.  

This becomes an issue when a user jumps to a post, scrolls away, and then needs to quickly get back to the Flagged Post.

#### Steps to reproduce
1. Log in to Mattermost (Version: 4.4.0  (4.4.2))
2. Navigate to any channel or direct message
3. Flag a post, by selecting the flag icon next to the timestamp of a message or comment
4. Scroll in the current channel or message, until the flagged post is not visible, or at least not centered in the window
5. Select the flag icon in the top right corner of the window, to expand the ‘Flagged Posts’ drawer on the right of the screen
6. Select ‘Jump’, next to the post you flagged in step 3
7. Verify the channel/message window jumps to the flagged post, placing it in the middle of the window, and that it is highlighted
8. Scroll until the Flagged Post is no longer visible or at least not centered in the window
9. Attempt to select ‘Jump’ next to the previously selected Flagged Post, again

#### Expected behavior
- Re-selecting ‘Jump’ for the most recently jumped to Flagged Post should always bring the select post to the center of the screen, regardless of leaving the channel, leaving the message, or only scrolling so the Flagged Post is no longer centered. 

#### Observed behavior (that appears unintentional) 
- Re-selecting ‘Jump’ for the most recently jumped to Flagged Post only bring the selected post to the center of the screen when the user has navigated away from the channel or message in which the post is located.  Staying in a channel or message of the post and re-selecting ‘Jump’ does nothing and the user must scroll to find the highlighted post.
- If the user selects 'Jump' for a different Flagged Post or navigates away from the current channel or message, then the previously selected Flagged Post can be jumped to

See attached gif for Observed Behavior
![jump to flagged post bug](https://user-images.githubusercontent.com/17954664/34393125-45337240-eb1e-11e7-9fa3-c4daefa1b846.gif)
- Note how 'Jump' works when it is initially selected, and after leaving the Flagged Post's channel.  It does not work if re-selected, while still in the channel, but the Flagged Post does remain highlighted.

**Comment by lindy65** [comment] 2017-12-28 08:28
Hi @mattrampolla,

Thanks for your feedback,

I've reproduced your issue on our nightly build server running v4.5 and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8451) for one of our product managers to take a look at to verify the intended behavior.

They're out for the holidays but should respond after Jan 2nd.

**Comment by lindy65** [comment] 2018-01-09 20:01
I'll close this issue off for now and we can track via the ticket linked above.

**Closed by lindy65** 2018-01-09 20:01 UTC
