### ISSUE TITLE
How to transition a user to GitLab authentication?

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9918] opened 2018-11-30 17:05 UTC
We have a number of users signed up via email, but now we want to move them all to a gitlab authentication (and obviously preserve their history).

I tried to switch the authentication method from email to gitlab, by sending a PUT request to the above endpoint with the following payload:

`data = {`
 `   'auth_data': '',`
 `   'auth_service': 'gitlab',`
`    'password': '12345678'`
`}`
But it didn’t succeed, the error was

`{'detailed_error': '',`
` 'id': 'api.context.invalid_body_param.app_error',`
` 'message': 'Invalid or missing user in request body',`
` 'request_id': 'moesc9nrhfbyi8mgky6zsfbpuw',`
` 'status_code': 400}`
What would be the proper way to update AuthService, AuthData and Password like you said in your comment?

**Comment by amyblais** [comment] 2018-11-30 20:15
Hi @swood,

Letting you know that I've asked our team about this I'll let you know once I get their feedback.

I have started to do research on this as well if I can find details on what the specific values should be.

**Comment by amyblais** [comment] 2018-11-30 23:43
Hi @swood,

While I'm waiting for replies from our team, here is a workaround:

You can enable Gitlab authentication here: https://docs.mattermost.com/administration/config-settings.html#gitlab. After this, users can switch the sign in method themselves from Account Settings > Security > Sign-in Method. (This requires both email and GitLab sign on to be enabled). Once all users have switched over to Gitlab auth, you could then turn off email.

We also have a ticket open here to force users to use a specific auth method: https://mattermost.atlassian.net/browse/MM-2520.

I'll come back to you on the API payload question again next week.

**Comment by swood** [comment] 2018-12-03 13:34
Wow... Probably you could to fix documentation as well?

**Comment by amyblais** [comment] 2018-12-06 15:14
Hi @swood, documentation for this is here: https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D~1auth%2Fput.

**Comment by swood** [comment] 2018-12-19 10:53
Hey, @kyxap1. Your repo isn't available for me.

**Comment by kyxap1** [comment] 2018-12-19 11:32
> Hey, @kyxap1. Your repo doensn't available for me.
try now

**Comment by amyblais** [comment] 2018-12-31 19:51
Closing this Issue as the problem is solved,

**Closed by amyblais** 2018-12-31 19:51 UTC
