### ISSUE TITLE
Failed to attach file to post

### ISSUE THREAD

**Issue by RomanChernyshev** [mattermost/mattermost-server#20396] opened 2022-06-08 06:35 UTC
#### Summary
Error when trying to attach an existing file

#### Steps to reproduce
1. Upload a file
2. Post a message attaching the file id(it works once)
3. Post the same message again

#### Expected behavior
The message contains the file regardless of the number of uses.

#### Observed behavior (that appears unintentional) 
The second+ message doesn't have any attachments in the chat.
Message in the logs:
```
"msg":"Failed to attach file to post","caller":"app/post.go:380","file_id":"7m4e1p1n43bz8eytcodw16qh6y","post_id":"1int4d4xtbbqurpdf8dycw7mmw","error":"invalid input: entity: FileInfo field: <id, postId, creatorId> value: <7m4e1p1n43bz8eytcodw16qh6y, 1int4d4xtbbqurpdf8dycw7mmw, bcd3i17myiryuern5w5zpdrcxo>"
```
Important: all of these entries exist, and I even can get an image using `GET api/v4/files/7m4e1p1n43bz8eytcodw16qh6y`.
I used `mattermost/mattermost-preview:6.5.0` docker image for tests. And our deploy 6.7 shows the same behavior.
Thanks.

**Comment by amyblais** [comment] 2022-06-08 16:41
@RomanChernyshev 
1. Can you reproduce this on our community server here https://community.mattermost.com/?
2. What browser and OS are you using?

**Comment by RomanChernyshev** [comment] 2022-06-09 04:43
Hi. I use API directly

**Comment by RomanChernyshev** [comment] 2022-06-09 13:11
CURLs in order of usage:
```
curl --location --request POST 'http://localhost:8065/api/v4/files' \
--header 'Authorization: Bearer cr3nq1ybsfgc58k4178e9xie1o' \
--form 'channel_id="n5dciu5n1pyembtt635sozicge"' \
--form 'files=@"/C:/Users/r.chernyshev/Desktop/T2V37EATG-U01PNH31XLJ-101b45cb2ab5-512.png"'
```
```
curl --location --request POST 'http://localhost:8065/api/v4/posts' \
--header 'Authorization: Bearer cr3nq1ybsfgc58k4178e9xie1o' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": "",
    "channel_id": "n5dciu5n1pyembtt635sozicge",
    "file_ids": ["aheok3kdjib7dmxpjp9sfcpeqc"]
}'
```
Here it works expectably and attaches a file

```
curl --location --request POST 'http://localhost:8065/api/v4/posts' \
--header 'Authorization: Bearer cr3nq1ybsfgc58k4178e9xie1o' \
--header 'Content-Type: application/json' \
--data-raw '{
    "message": "",
    "channel_id": "n5dciu5n1pyembtt635sozicge",
    "file_ids": ["aheok3kdjib7dmxpjp9sfcpeqc"]
}'
```
Here I get an error, the message is received but it's empty

**Comment by agnivade** [comment] 2022-06-09 14:52
Thanks @RomanChernyshev. @amyblais - we can file a ticket for the Channels team to triage.

**Comment by Willyfrog** [comment] 2022-06-15 20:50
Files are only expected to be attached once. Closing the issue as it is working as intended.

**Closed by Willyfrog** 2022-06-15 20:50 UTC
Labels: Bug Report/Open

**Comment by RomanChernyshev** [comment] 2022-06-16 17:00
@hmhealey Hi, I've seen this [comment](https://mattermost.atlassian.net/browse/MM-44961?focusedCommentId=129557). Answering : our task is weekly bulk mailing of 20k users. Reusing is critical for space limits.

**Comment by Willyfrog** [comment] 2022-06-17 11:11
does it need to be attached to the post? I'd expect in your use case to be linked and hosted elsewhere.

cc/ @esethna for awareness

**Comment by RomanChernyshev** [comment] 2022-06-17 15:42
It's an image. We have a bot-informer and it used to send kind of postcard using slack. After migration to MM we faced with problem of supporting this feature

**Comment by agnivade** [comment] 2022-06-18 03:38
You can upload the image once. Get a link to that image, and use that link that in your message contents.

**Comment by RomanChernyshev** [comment] 2022-06-18 15:35
It's pretty simple but sounds like a solution. Thanks I will try. I even didn't think about it.

**Comment by hmhealey** [comment] 2022-06-21 14:51
Good idea, Agniva. You might need to turn on public links for files for that, but that sounds like it'd probably work
