### ISSUE TITLE
Extremly large images break sending messages

### ISSUE THREAD

**Issue by PTS93** [mattermost/mattermost-server#8650] opened 2018-04-19 12:58 UTC
**Summary**
When loading very large images it is not possible to cancel the image upload and the channel becomes unusuable to send messages. Client restart / Browser refresh is necessary. Happens on web/linux desktop/mac desktop, windows not tested.

**Steps to reproduce**
Try to load image with f.e. 10080x2560 resolution by attaching via file menu or drag and drop. File size does not have any impact on this. ~200kb PNG has the same issue as a 10MB jpeg.

**Expected behavior**
Cancel image upload should remove the image from the message and sending text messages should work as usual.

**Observed behavior**
Unable to ever send any message until you restart client because image upload never completes and you are unable to cancel it.

**Possible fixes**
Check if image is of certain size and warn user or refuse upload if technically unable to support such large images. Otherwise fix image preview code as this is likely the culprit.

**Comment by lindy65** [comment] 2018-04-20 07:37
Hi @PTS93 

Thanks for your feedback,

On our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running the latest master, I am not able to reproduce your issue.  The file uploads fine and posts.  I can also cancel the upload of the file.

Which server version of Mattermost do you have installed?  Perhaps [upgrading to the latest version](https://about.mattermost.com/download/) will resolve your issue.  

You can also try reproducing it on our nightly build server.

**Comment by X41** [comment] 2018-04-20 11:59
i can confirm the same issue on version 4.0.1 from the Arch Linux/AUR mattermost-desktop-bin package

![demo](https://user-images.githubusercontent.com/2126863/39049702-de7138f6-44a2-11e8-81b1-d4d577708777.gif)

the image used in the gif can be found [here](https://user-images.githubusercontent.com/2126863/39049720-f332f464-44a2-11e8-910d-6e7534c62b87.png)

**Comment by lindy65** [comment] 2018-04-21 17:30
Hi @X41,

Thanks for your feedback, 

Let us know how it goes after you've updated the server to the latest version 👍

**Comment by lindy65** [comment] 2018-05-02 08:41
Hi @PTS93 @X41 

Has your issue been resolved after upgrading to the latest server version?

**Comment by lindy65** [comment] 2018-05-09 08:19
I'll close this issue off here for now.  Please feel free to open a new issue with reproduction steps should you still be experiencing problems after server upgrade.  Thanks!

**Closed by lindy65** 2018-05-09 08:19 UTC
