### ISSUE TITLE
Team unread API for a user always returns msg_count = 0

### ISSUE THREAD

**Issue by raphaelmerx** [mattermost/mattermost-server#8591] opened 2018-04-09 06:32 UTC
#### Summary
When getting the number of team unread for a user through the API, the response always contains `"msg_count": 0`, even when there are unread messages.

I'm using Mattermost 4.7.3 with Postgres 9.5.12.

#### Steps to reproduce
* Create two users, one admin and a system user.
* Log in as the admin user.
* Send a message to the system user. 
* Make a GET request to `/api/v4/users/<system user id>/teams/unread`

#### Expected behavior
The response contains `"msg_count": 1`

#### Observed behavior (that appears unintentional) 
The response contains `"msg_count": 0`

#### Possible fixes
I see that [`GetChannelUnreadsForTeam`](https://github.com/mattermost/mattermost-server/blob/659ce8c60012a7d5fd597997b1794ac512b3b155/store/sqlstore/team_store.go#L513) is using `(Channels.TotalMsgCount - ChannelMembers.MsgCount)` to compute the number of unread for that user and team. And indeed when making SQL queries I see the `totalmsgcount = 3` on the `Channel` row, while the `msgcount = 2` on the `ChannelMember` row. So the difference should be 1. However the API keeps returning 0. What am I missing here?

**Comment by lindy65** [comment] 2018-04-13 08:44
Hi @raphaelmerx,

Thanks for your feedback,

As there have been many improvements and bug fixes since v4.7.3, we recommend upgrading to [the latest version](https://about.mattermost.com/download/) to see whether this issue still reproduces for you.

v4.9 is releasing on April 16th, so you might want to wait until then before upgrading.

**Comment by enahum** [comment] 2018-04-24 11:13
Hi @raphaelmerx direct channels do not belong to any team, that is why when the mention count increases for a Direct or Group message the unread count for the team remains the same.

**Comment by raphaelmerx** [comment] 2018-04-24 11:48
Hi @enahum thanks that makes sense! However does that mean we cannot currently get the total number of unread messages for a user through the API?

One approach that seems to do the trick is to get channels for a user, then make an api request to `/api/v4/users/{user_id}/channels/{channel_id}/unread` per channel the user is a member of. But that means potentially many requests!

**Comment by lindy65** [comment] 2018-05-02 08:50
Thanks @raphaelmerx 

Pleased you've resolved your issue.  I'll close this off here for now.  Feel free to open a new issue if you need further assistance in future :)

**Closed by lindy65** 2018-05-02 08:50 UTC
