### ISSUE TITLE
:thumbsdown: beats :thumbsup: in autocomplete.

### ISSUE THREAD

**Issue by jsha** [mattermost/mattermost-server#8316] opened 2018-02-16 18:57 UTC
#### Summary
When typing emoji or emoji reactions, the prefix :thumbs autocompletes by default to :thumbsdown:, while on other platforms like Slack and GitHub, it autocompletes by default to :thumbsup:.

#### Steps to reproduce
In Mattermost in Chrome, type :thumbs and hit Enter.

#### Expected behavior
Generate a :thumbsup:

#### Observed behavior (that appears unintentional) 
Generate a :-1:

I mention this because :thumbsup: is a much more common reaction than :-1:, and it is much more embarassing to accidentally send a :-1: on something that one is expected to feel positively about.

**Comment by lindy65** [comment] 2018-02-17 18:52
Hi @jsha,

Thanks for your feedback!

We have [this ticket](https://mattermost.atlassian.net/browse/MM-8408) to fix the issue in the emoji autocomplete so I'll close this issue off here and we can track via the ticket...

**Closed by lindy65** 2018-02-17 18:52 UTC

**Comment by jsha** [comment] 2019-08-29 21:17
Any updates on this? It seemed for a while like it was fixed, and more recently (in 5.11.0) it's not fixed anymore. It appears https://mattermost.atlassian.net/browse/MM-8408 is still open, so maybe the "fix" was accidental?

**Comment by lindy65** [comment] 2019-08-30 06:29
Hi @jsha 

Thanks for the report! I can reproduce your issue on v5.13.3 but am not able to reproduce it on v5.14 or `master`. Would you be open to upgrading to the [latest server version](https://mattermost.com/download/) to see if the issue is fixed for you?
