### ISSUE TITLE
Channel search uses "starts with" instead of "contains"

### ISSUE THREAD

**Issue by pmayeur** [mattermost/mattermost-server#8047] opened 2018-01-05 18:45 UTC
#### Summary
When searching all channels the search is a "starts with" search and not a "contains search"

#### Steps to reproduce
Create the following channels

AAAA
BAAB
CAAC

Search for "AA"

#### Expected behavior
 All 3 should be returned.

#### Observed behavior (that appears unintentional) 
Notice only the first is returned.

#### Code
https://github.com/mattermost/mattermost-server/blob/91bfc72a99477b6d611b13e225786e3ca7add10c/api4/channel.go#L492

**Comment by lindy65** [comment] 2018-01-08 10:50
Hi @pmayeur,

Thanks for your feedback,

I'm not able to reproduce your issue on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running the v4.6 RC1 version.

Which server version are you running?

**Comment by pmayeur** [comment] 2018-01-08 13:25
@lindy65 looks to be reported/fixed -- https://mattermost.atlassian.net/browse/PLT-8312

**Comment by lindy65** [comment] 2018-01-08 19:16
Ah, thanks @pmayeur - I'll close this issue off for now then :)

**Closed by lindy65** 2018-01-08 19:16 UTC
