### ISSUE TITLE
Problem with sending images much higher than a wider.

### ISSUE THREAD

**Issue by Ryba04** [mattermost/mattermost-server#15438] opened 2020-09-12 10:05 UTC
#### Summary
An attempt to send image much higher than a wider causes problems with the chat. Tested three times on different chats mattermost 5.25.0.

#### Steps to reproduce
1. Create image much higher than a wider (for example 1x100000pix).
2. Try to send this image on Mattemost chat.
3. Sending goes on and on and on, after some minutes you will probably see a 504 server error and you will not be able to reload the chat (sometimes it crashes the first time, sometimes the second time you try to send a picture).

#### Expected behavior
Send a picture correctly like everyone else, or better discard pictures like this one to prevent such problems in the future

#### Observed behavior (that appears unintentional) 
Freeze of the entire server on which the chat is located.

#### Possible fixes
I don't know, but this bug/gap can paralyze the entire system, if everything is on the server that the chat is on (like forum, multiplayer etc.).

**Comment by agnivade** [comment] 2020-09-13 05:37
Would you be able to upload such an image so that we can test this?

**Comment by Ryba04** [comment] 2020-09-13 09:56
There it is, but anyone can generate such a file in GIMP in 10 seconds, so I didn't see any point in uploading this image.
[https://zapodaj.net/b1387c6bb3253.png.html](url)

**Comment by agnivade** [comment] 2020-09-13 10:33
Thanks for the help @Ryba04 and my apologies for not generating it myself. Sorry for the extra work there!

The issue is happening during postProcessing and it gets stuck trying to resize the image. I have created a ticket here: https://mattermost.atlassian.net/browse/MM-28638.

**Comment by amyblais** [comment] 2021-01-29 16:08
Closing as this was fixed in v5.30.0 release,

**Closed by amyblais** 2021-01-29 16:08 UTC
Labels: Bug Report/Scheduled for Release
