### ISSUE TITLE
Email format problems: "name <email@address.do>" vs "email@address.do"

### ISSUE THREAD

**Issue by treba123** [mattermost/mattermost-server#7869] opened 2017-11-21 10:27 UTC
#### Summary
The email invitation field accepts emails in the format `name <email@address.do>` and sets the email of the corresponding user to that value.

When these users try to log in via email (instead of user name), they can't just use `email@address.do`, but have to use `name <email@address.do>`.

#### Steps to reproduce
4.2, upgraded to 4.4

Invite a user using the email invitation. Write the email address in the format `test <test@address.do>`.
Accept the invitation and create an account.
Try to log in via email address in the format `test@address.do`.

Domain restriction has to be off. If turned on, in gives an error (even if address.do is allowed)

#### Expected behavior
The format `test@address.do` works for login.

#### Observed behavior (that appears unintentional) 
`test@address.do` is reported as unknown user. `test <test@address.do>` works fine.

#### Possible fixes
The email invitation form should either not accept the format `test <test@address.do>` or save it internally as `test@address.do`. 
That would also fix domain restriction, which is broken with `test <test@address.do>`

**Comment by lfbrock** [comment] 2017-11-22 17:56
Hi @treba123 - sorry to clarify, is this adding something like <name>name@email.com in the invite field? 

Or would you be able to send screenshots of an example of what exactly is entered on the invite and then sign in screen?

**Comment by treba123** [comment] 2017-11-23 09:12
I entered "Alexej <alexej@gmail.com>" in the invite field (this is common when copying from an email client).

He gets the invitation delivered correctly to alexej@gmail.com.

On the login screen, he can now login with "Alexej <alexej@gmail.com>", but not with "alexej@gmail.com".

**Comment by MusikPolice** [comment] 2017-11-29 13:51
I suspect that there isn't much that we can do about this. Verifying that email addresses are valid [is notoriously difficult to do correctly](https://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address/201378#201378), so most applications, [including Mattermost](https://github.com/mattermost/mattermost-webapp/blob/master/utils/utils.jsx#L31) just check to see that the address contains an `@` character. By that logic, the "address" `Alexej <alexej@gmail.com>` is valid, which explains why the form accepts it as the email address for the new account.

When I try to reproduce this issue in my local dev environment, I get an error from the email subsystem, complaining that the address is invalid (perhaps because of the space):
```
[2017/11/29 08:41:09 EST] [EROR] Failed to send invite email successfully err=SendMail: utils.mail.send_mail.to_address.app_error, 501 Bad recipient address syntax
```
Thing is, I suspect that the error that I'm seeing was thrown by the email subsystem that I'm using, which is a development system. My guess is that if you're using a system like Microsoft Exchange to send email, and it recognizes that email address format, it will send the email invite with no issues. 

Can you check your server logs for a message like the one I pasted above, that appears shortly after you send the invite? If you have debug logging enabled, and the message sends successfully, you'll see a line like this in the logs instead:
```
[2017/11/29 08:45:19 EST] [DEBG] sending mail to Test User <test.user@testdomain.com> with subject of '[Mattermost] musikpolice invited you to join test Team'
```

The only thing that I can think of to "fix" this behaviour is to disallow spaces in the email address input form, but [according to wikipedia](https://en.wikipedia.org/wiki/Email_address#Examples), `"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com` is _technically_ a valid email address.

**Comment by treba123** [comment] 2017-11-29 14:06
Well yeah, whitespace in invalid aswell as a special characters in the domain, right? I mean `gmail.com>`
I use sendmail/postfix as the underlying mail system, will check what it reports

**Comment by treba123** [comment] 2017-11-29 14:14
Oh well, I actually don't use postfix but smtp login. And I guess most smtp-server understand the mentioned format quite well.

**Comment by MusikPolice** [comment] 2017-11-29 14:28
Yes, technically, we could check that everything after the `@` symbol is a valid domain name. The regex to do this [is complicated](https://stackoverflow.com/questions/10306690/domain-name-validation-with-regex), but pretty well understood.

**Comment by MusikPolice** [comment] 2017-11-29 18:40
We've decided to fix this problem, and are tracking the issue [in JIRA](https://mattermost.atlassian.net/browse/PLT-8248). I'm going to close this ticket in the meantime.

**Closed by MusikPolice** 2017-11-29 18:40 UTC
