### ISSUE TITLE
Invitation link doesn't work for open team

### ISSUE THREAD

**Issue by kpyorala** [mattermost/mattermost-server#10059] opened 2019-01-03 09:17 UTC
#### Summary
Invitation link doesn't work for open team

#### Steps to reproduce
Version 5.5.0 in Docker via Gitlab
1. Team settings-> "Allow any user with an account on this server to join this team": yes
2. Regenerate Invite code
3. Click link "Invite others to this team"

#### Expected behavior
New user can join team with given link

#### Observed behavior (that appears unintentional) 
Opening the link gives error "The invite link was invalid. Please speak with your Administrator to receive an invitation."
In system console > Log there is line: "Invite is invalid because this is not an open team."

#### Possible fixes
-

**Comment by amyblais** [comment] 2019-01-03 14:58
Hey @pichouk, the reporter mentioned that they are on Docker, does this issue seem Docker specific?

**Comment by kpyorala** [comment] 2019-01-03 15:03
Actually I just noticed that the problem exists only for teams which are created by Gitlab - when you create new group in Gitlab, it asks if you want to it create automatically Mattermost team for your group. So problem is probably more on Gitlab's side or in the API it uses to create the group.

**Comment by amyblais** [comment] 2019-01-03 15:17
Hi @kpyorala, thank you for clarifying that - @hmhealey this seems to be Gitlab related, would you be able to help test this out?

**Comment by pichouk** [comment] 2019-01-03 20:40
As said above, if it is Gitlab related I think that Docker is not the issue here :)

**Comment by hmhealey** [comment] 2019-01-04 14:59
@kpyorala To clarify, exactly which of these menu options are you selecting to invite users? They all work slightly differently, so they're a bit confusing
![image](https://user-images.githubusercontent.com/3277310/50693782-fc94c580-1005-11e9-84de-456e464de17f.png)

And I agree that the problem is probably to do with GitLab since I'm pretty sure it's creating a "private" team which is a poorly documented feature that is hard to access normally. If that's the case, you shouldn't see the "Get Team Invite Link" option shown in the screenshot above, and if you look at the team in the database or using the debugger, you should see that its `type` field would be set to `'I'`.

If that's the case, you can fix it for that one teamby changing the type field from the database, but any newly created teams will have the same problem

**Comment by amyblais** [comment] 2019-01-22 21:58
Closing this as we haven't received a response for a while,

**Closed by amyblais** 2019-01-22 21:58 UTC

**Comment by simonv3** [comment] 2022-06-21 18:38
We're getting this on our local server running 6.7

After selecting "Invite People" and then clicking on "Copy invite link"

![image](https://user-images.githubusercontent.com/485583/174873611-0c3be447-3f2c-40cc-9b5a-ae67d14f6dfb.png)

Unfortunately at the moment (though I'm working on it) I don't have server access to the Mattermost, so can't debug it that way, just curious if there's a setting or something similar we should enable.

**Comment by simonv3** [comment] 2022-06-23 15:54
Okay we upgraded to 7.0.0 and this now looks like it should work. I'll create a ticket if it doesn't!
