### ISSUE TITLE
Add an "emoji_icon" field to incoming webhooks.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11194] opened 2019-06-14 23:55 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16389)

The “emoji_icon” field should use and emoji in place of the display picture when the webhook posts into Mattermost.

**Comment by krjn** [comment] 2019-06-25 14:41
Working on this one.

**Comment by hanzei** [comment] 2019-06-25 20:18
Awesome, thanks @krjn :rocket:

**Comment by krjn** [comment] 2019-06-28 20:54
After implementing `emoji_icon` as a field throughout the pipeline, I found the `override_icon_url` prop, which I had previously missed, that can be set through the command line and through webhooks. It seems to me that piggy-backing on this prop would be better than having another field specific for emojis. This prop allows an URL (image) to be shown instead of the profile picture, and it's already implemented on the webapp and on mobile.

To use `override_icon_url`, the server would learn to format a relative URL to the static asset (emoji), to be sent when a webhook receives `override_icon_emoji` field (new proposed name).
The URL would be relative to the app as a full URL would conflict with different endpoints because of different addresses for internal/external access, or testing (e.g. mobile).

When the webapp/mobile receives a relative URL on `override_icon_url` it would concatenate with the server base URL.

At this point, there would be enough changes for the feature to be working on all ends.

There are a couple of other considerations.
  - if reusing `override_icon_url`, and effectively overriding it itself through the `override_icon_emoji` is the correct approach (3/5), or having a totally separate field and code for this is best;
  - currently, the profile picture has a circular border/cut that doens't lend itself aesthetically when showing an emoji - I propose this border to be removed/ignored _when either_ an override URL or emoji is present for the post (1/5)
  - currently, on the webapp, the overriden URL is also used for the profile image after clicking on the profile icon (the pop-up) - I propose this to not use the override anymore, considering the override is per-post and masks the user identity, which the purpose of the pop-up it is to show, I believe (3/5)
  - how unicode emojis should work in this case, specially those we don't seem to have a mapping, like 🛳

@aaronrothschild

**Comment by aaronrothschild** [comment] 2019-06-28 21:22
Thanks for working on this @krjn ! 

> currently, the profile picture has a circular border/cut that doens't lend itself aesthetically when showing an emoji - I propose this border to be removed/ignored when either an override URL or emoji is present for the post (1/5)

That makes sense to me, although it *may* expose some visual oddities (edgy), I think it's worth it.

> currently, on the webapp, the overriden URL is also used for the profile image after clicking on the profile icon (the pop-up) - I propose this to not use the override anymore, considering the override is per-post and masks the user identity, which the purpose of the pop-up it is to show, I believe (3/5)

@jasonblais may have some thoughts on this one too - we currently have a few issues open where it is not apparent to the user WHY a 'different' user is presented when something is overridden.  I am on the fence about this one currently, but working out my thoughts.  I wonder if we should show an indicator to the user that the message is not who it appears to be (it is likely a bot that would use such a scenario).

**Comment by jasonblais** [comment] 2019-06-29 03:47
Thanks @krjn! Overall this approach makes a lot of sense to me.

> if reusing `override_icon_url`, and effectively overriding it itself through the `override_icon_emoji` is the correct approach (3/5), or having a totally separate field and code for this is best;

Overall this approach makes a lot of sense to me as well. What would happen if someone specifies both an `override_icon_url` and `override_icon_emoji` parameters?

> currently, the profile picture has a circular border/cut that doens't lend itself aesthetically when showing an emoji - I propose this border to be removed/ignored when either an override URL or emoji is present for the post (1/5)

I'm curious how this would look like without the border on various themes.

> currently, on the webapp, the overriden URL is also used for the profile image after clicking on the profile icon (the pop-up) - I propose this to not use the override anymore, considering the override is per-post and masks the user identity, which the purpose of the pop-up it is to show, I believe (3/5)

Echo what Aaron mentioned that this is something we're figuring out (there's actually a related ticket for it here https://mattermost.atlassian.net/browse/MM-15336). I'm wondering, for the scope of this issue, if we leave the existing behaviour as-is and consider updates to the profile popover separately via https://mattermost.atlassian.net/browse/MM-15336 ?

(I can see arguments both ways - to show the user info in profile popover to indicate their identity; or not to show it because the post is intended to be posted as a webhook post, not as a user, causing user confusion)

> how unicode emojis should work in this case, specially those we don't seem to have a mapping, like 🛳

@hmhealey would you have thoughts on how we might handle this?

**Comment by krjn** [comment] 2019-07-01 14:44
> Overall this approach makes a lot of sense to me as well. What would happen if someone specifies both an `override_icon_url` and `override_icon_emoji` parameters?

I think we should return a `Bad Request`. Would be a nice place to use HTTP `422` code too.

> I'm curious how this would look like without the border on various themes.

![image](https://user-images.githubusercontent.com/51929404/60440448-5fa59480-9c04-11e9-8f54-11ac8cf6e0fc.png)

(normal profile pictures would keep the border, and maybe we could keep them on images (non emoji) too)

> I'm wondering, for the scope of this issue, if we leave the existing behaviour as-is and consider updates to the profile popover separately via https://mattermost.atlassian.net/browse/MM-15336 ?

The ticket seems to not be public.

> (I can see arguments both ways - to show the user info in profile popover to indicate their identity; or not to show it because the post is intended to be posted as a webhook post, not as a user, causing user confusion)

I see it like that too. I think, not showing the info would be more elegant/neat for webhooks, but not having the information in case of abuse/confusion/curiosity would lead to frustration, and we should optimize for least frustration.

> > how unicode emojis should work in this case, specially those we don't seem to have a mapping, like 🛳

To clarify for anyone else reading: this unicode emoji does not have a mapping, in the sense that there is no file/image to link to, so it is more complicated to show it, considering we have webapp/mobile but also push notifications. (I haven't researched this matter, though).

**Comment by aaronrothschild** [comment] 2019-07-01 17:20
>> (I can see arguments both ways - to show the user info in profile popover to indicate their identity; or not to show it because the post is intended to be posted as a webhook post, not as a user, causing user confusion)

> I see it like that too. I think, not showing the info would be more elegant/neat for webhooks, but not having the information in case of abuse/confusion/curiosity would lead to frustration, and we should optimize for least frustration.

Agreed on frustration ---> which comes from lack of clarity --> "Why is this message seemingly coming from someone, then when I click on their name - it shows me someone else"

What do we really mean when a BOT is taking control of a user's account?  An action has been automated on their behalf.   I'm wondering if we should be displaying more info when you hover over the BOT indicator to show: 
1) That a user's credentials have been used with their permission (presumably)
2) That the BOT indicator shows when an action was done by an automated tool

Something like might mitigate the confusion and add clarity to what is happening behind the scenes:
![2019-07-01_10-09-25](https://user-images.githubusercontent.com/915956/60454742-7f7b8f00-9be9-11e9-8aa6-b144542e23b7.png)

@asaadmahmood I'm not sure if you have any opinions on this issue.

**Comment by asaadmahmood** [comment] 2019-07-02 09:56
@aaronrothschild Can you highlight what the problem is to me that we are trying to resolve?

**Comment by hmhealey** [comment] 2019-07-03 13:16
> how unicode emojis should work in this case, specially those we don't seem to have a mapping, like 🛳

I think we can just ignore unicode emojis that we don't support the same way that we handle invalid input (either by ignoring them or returning an error). I don't think there's much else we can do for those until the system emojis are updated.

**Comment by krjn** [comment] 2019-07-04 21:16
What of the case regarding custom emojis:
 - post sent with emoji as icon
 - a month passes, and the emoji is changed (same name, other image/id)
 - someone looks at the post again

What should happen? I was implementing the URL discovery to be at post retrieval instead of post creation, but, that means the image/emoji could change. If not done this way, though, we'd require deleted emojis to keep their image/file and id. From a quick look at the store, it seems they do but are moved.

Also, for this case, does it matter that/if the emoji was deleted? Might we retrieve the 'newest' emoji by name, regardless of deletion date? Or show a default emoji - perhaps the default webhook one.

**Comment by aaronrothschild** [comment] 2019-07-05 13:34
> Also, for this case, does it matter that/if the emoji was deleted? Might we retrieve the 'newest' emoji by name, regardless of deletion date? Or show a default emoji - perhaps the default webhook one.

I would suggest that it show the current emoji and it doesn't matter that the emoji was deleted.  IF the emoji is deleted, then show the webhook default.  If that value is blank, use the default icon for the profile image (ie:blank profile image).

**Comment by hmhealey** [comment] 2019-07-10 14:40
> > I'm curious how this would look like without the border on various themes.
> 
> ![image](https://user-images.githubusercontent.com/51929404/60440448-5fa59480-9c04-11e9-8f54-11ac8cf6e0fc.png)
> 

@jasonblais Thoughts on how this looks? I think it looks good for emojis, but not for other overridden profile pictures since we're suddenly treating them differently than regular profile pictures

**Comment by jasonblais** [comment] 2019-07-10 22:44
> > > I'm curious how this would look like without the border on various themes.
> > 
> > ![image](https://user-images.githubusercontent.com/51929404/60440448-5fa59480-9c04-11e9-8f54-11ac8cf6e0fc.png)
> > 
> 
> @jasonblais Thoughts on how this looks? I think it looks good for emojis, but not for other overridden profile pictures since we're suddenly treating them differently than regular profile pictures

I'm wondering why we need to special case it for emojis..what happens if I have a trophy as my profile pic? Does it get cut off because of the circular border? 

I agree that the trophy emoji looks fine, but I worry we'll have cases where it looks inconsistent, e.g. when custom emojis themselves are rectangular.

[I wonder why our profile pics are round..I like the more rectangular shape. But that's a separate conversation, don't want to diverge the discussion here.. 😇 ]

**Comment by krjn** [comment] 2019-07-12 15:08
> Does it get cut off because of the circular border?

Yes.

Just to link it here:
 - https://github.com/mattermost/mattermost-mobile/pull/2961#pullrequestreview-259488383 some discussion about the icons.

**Comment by jasonblais** [comment] 2019-07-12 19:04
@krjn Thanks! Didn't notice the discussion there, will post there instead

**Comment by hanzei** [comment] 2019-07-17 09:03
Reopening until https://github.com/mattermost/mattermost-server/issues/11194 is merged.

**Closed** 2019-07-20 07:00 UTC
Labels: Area/Extension, Difficulty/2:Medium, Help Wanted, Tech/Go, Tech/JavaScript, Tech/React Native, Tech/ReactJS
