### ISSUE TITLE
display bug with compact view and deleted replies

### ISSUE THREAD

**Issue by dmwit** [mattermost/mattermost-server#8192] opened 2018-02-02 17:55 UTC
#### Summary
The user name and the "reply marker bar" can overlap sometimes, which looks bad.

#### Steps to reproduce
I'm not too sure. I took my best guess about how to reproduce it and failed; so I've attached an anonymized image showing the bug in the hopes that it will suggest reproduction experiments to try. Please feel free to propose experiments for me to run on our local mattermost instance in case you are worried that the bug may be version-specific.

#### Expected behavior
The name should start to the right of the gray vertical bar.

#### Observed behavior (that appears unintentional) 
The name is aligned with other names, but overlaps the gray vertical bar.

![name-and-structure-overlap-redacted](https://user-images.githubusercontent.com/203613/35747402-02f7fbfa-07ff-11e8-8e05-1beaa19e2e0f.png)

**Comment by lindy65** [comment] 2018-02-05 07:18
Hi @dmwit,

Thank you for your feedback,

Could you share which version of Mattermost server you have installed?

I tried to reproduce your issue on our nightly build server running off the latest master but could not so I believe the issue is fixed.

![image](https://user-images.githubusercontent.com/13020833/35792367-6bb6acb0-0a55-11e8-9fdf-0fc8ca5fa4d2.png)

**Comment by dmwit** [comment] 2018-02-05 22:28
Here are the pieces that look relevant from the "About Mattermost" menu:

> Mattermost Enterprise Edition
> 
> Modern communication from behind your firewall.
> 
> Version: 4.6.0  
> Database: postgres

**Comment by lindy65** [comment] 2018-02-06 08:39
Thanks @dmwit,

The [latest released version](https://about.mattermost.com/download/) is 4.6.1 but 4.7 will release on February 16th.  As the issue is not reproducing for me on the nightly build server running off the latest master, I believe it is fixed.  

You could either upgrade to v4.6.1 or wait until 4.7 is released to check that the issue is resolved for you.

**Comment by lindy65** [comment] 2018-02-14 10:33
I'll close this issue off for now and we can reopen if it still reproduces after v4.7 releases on Feb 16th.

**Closed by lindy65** 2018-02-14 10:33 UTC
