### ISSUE TITLE
Broken "System statistics"

### ISSUE THREAD

**Issue by maxtar** [mattermost/mattermost-server#7760] opened 2017-11-02 07:29 UTC
Version: 4.3.0  (4.3.1)
Database: postgres.

#### Summary
When I open `System console/System statistics` I see the following behavior:
![default](https://user-images.githubusercontent.com/10290098/32314327-693ea4c0-bfb8-11e7-87bc-306dc92f44ad.png)

#### Steps to reproduce
Open `System console/System statistics`.

#### Expected behavior
Early I've got actual using statistics.

**Comment by lindy65** [comment] 2017-11-02 07:44
Hi @maxtar 

Thank you for your feedback,

We previously fixed [a bug](https://mattermost.atlassian.net/browse/PLT-3051) in v3.1 where this was happening.  I'm also not able to reproduce your issue on our nightly build server.

I'll ask the team whether they have any idea what could be happening on your set-up...

**Comment by maxtar** [comment] 2017-11-02 07:49
@lindy65 Thanx. May it depends from OS version? it's only one change what we did. Upgrade centos version on this machine.

**Comment by lindy65** [comment] 2017-11-02 08:02
Ah, this could be it @maxtar, let's see what help our devs have :)

**Comment by MusikPolice** [comment] 2017-11-02 12:12
The bug wasn't in our software, it was that one of the major lists that ad some blockers use had (mistakenly?) added the URL of the resource that the statistics page calls to one of their block lists. 

Do you have an ad blocker enabled? If so, try disabling it, or accessing the page with a browser that doesn't have the ad blocker enabled. If that works, check to see if an update is available for your ad blocker.

**Comment by maxtar** [comment] 2017-11-02 12:29
Wow. Realy! Thanx, I've switched off ad blockers and statistic returned. :)

**Comment by jasonblais** [comment] 2017-11-02 12:33
@maxtar Do you have any ad blockers enabled on your browser?

**Comment by jasonblais** [comment] 2017-11-02 12:34
Sorry, didn't have the most recent posts visible. @maxtar which ad blocker did you have enabled?

**Comment by maxtar** [comment] 2017-11-02 12:35
ublock origin

**Comment by MusikPolice** [comment] 2017-11-02 12:56
We've requested that the ad blocker in question removes this URL from their list. Unfortunately, there's nothing else that we can do about this, so I'm going to close this ticket for the time being. Thanks for the report.

**Closed by MusikPolice** 2017-11-02 12:56 UTC

**Comment by jasonblais** [comment] 2017-11-02 13:50
@maxtar The ad blocker has removed the URL. Next time a new version of uBlock is released, update to it, and the System Console stats should show up even with the ad blocker enabled.

**Comment by maxtar** [comment] 2017-11-02 13:56
@jasonblais Cool! I will check. Thank you.
