### ISSUE TITLE
Unable to upload 500MB+ Files On Mattermost Latest Release

### ISSUE THREAD

**Issue by ghost** [mattermost/mattermost-server#14452] opened 2020-05-03 12:51 UTC
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
unable to upload 500MB+ file size in latest Mattermost on Nginx Reverse Proxy + S3

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Latest Release of MM (April 26, 2020)
S3 Bucket
Nginx Reverse Proxy

client_boxy_size is set to 10000M and so is mattermost config.json

#### Expected behavior
Successfully Uploaded

#### Observed behavior (that appears unintentional) 
We received an unexpected status code from the server. (502)

![Screenshot 2020-05-03 at 6 20 24 PM](https://user-images.githubusercontent.com/42859854/80914687-ca66b580-8d6a-11ea-9d37-e6706e561c64.png)

**Comment by lieut-data** [comment] 2020-05-04 12:04
@chinyasuhail, can you share the server logs that show the error in question?

**Comment by chinyasuhail** [comment] 2020-05-04 13:33
@lieut-data 
[error.log](https://github.com/mattermost/mattermost-server/files/4574782/error.log)

**Comment by lieut-data** [comment] 2020-05-04 13:36
Thanks, @chinyasuhail! Are those logs from your load balancer? The line of interest definitely looks like:
```
2020/05/04 12:05:20 [error] 2143#2143: *43621 upstream prematurely closed connection while reading response header from upstream, client: 54.172.174.179, server: mm.unboxrobotics.com, request: "POST /api/v4/files HTTP/2.0", upstream: "http://127.0.0.1:8065/api/v4/files", host: "mm.unboxrobotics.com"
```

I'm wondering if you can also share the Mattermost server logs around this time.

**Comment by chinyasuhail** [comment] 2020-05-04 13:46
I'm using NGINX as a reverse proxy. I've followed this [guide ](https://www.cloudbooklet.com/install-mattermost-on-ubuntu-18-04-with-nginx-google-cloud/)

[mattermost.log](https://github.com/mattermost/mattermost-server/files/4574994/mattermost.log)

**Comment by chinyasuhail** [comment] 2020-05-04 13:56
@lieut-data I believe it's the Nginx reverse proxy that's causing the issue.

**Comment by chinyasuhail** [comment] 2020-05-04 13:57
@lieut-data  I tried uploading a 1gb file again and checking the logs both on Nginx and mattermost; However; Nginx has these errors in the file.

```
2020/05/04 13:51:29 [error] 2143#2143: *44267 connect() failed (111: Connection refused) while connecting to upstream, client: 54.172.174.179, server: mm.unboxrobotics.com, request: "GET /api/v4/websocket HTTP/1.1", upstream: "http://127.0.0.1:8065/api/v4/websocket", host: "mm.unboxrobotics.com"
2020/05/04 13:51:33 [error] 2143#2143: *44269 connect() failed (111: Connection refused) while connecting to upstream, client: 54.172.174.179, server: mm.unboxrobotics.com, request: "GET /api/v4/websocket HTTP/1.1", upstream: "http://127.0.0.1:8065/api/v4/websocket", host: "mm.unboxrobotics.com"
2020/05/04 13:51:36 [error] 2143#2143: *44271 connect() failed (111: Connection refused) while connecting to upstream, client: 54.172.174.179, server: mm.unboxrobotics.com, request: "GET /api/v4/websocket HTTP/1.1", upstream: "http://127.0.0.1:8065/api/v4/websocket", host: "mm.unboxrobotics.com"
2020/05/04 13:51:40 [error] 2143#2143: *44273 connect() failed (111: Connection refused) while connecting to upstream, client: 54.172.174.179, server: mm.unboxrobotics.com, request: "GET /api/v4/websocket HTTP/1.1", upstream: "http://127.0.0.1:8065/api/v4/websocket", host: "mm.unboxrobotics.com"
```

**Comment by lieut-data** [comment] 2020-05-04 14:23
Thanks, @chinyasuhail! Could it be your `*_timeout` settings in Nginx? (i.e. `proxy_send_timeout`, `proxy_read_timeout` and `send_timeout`)? If you increase those, does the problem go away.

To confirm, are there no error logs in Mattermost at all when this upload fails?

**Comment by chinyasuhail** [comment] 2020-05-04 15:33
@lieut-data I've doubled my timeout and still there's the same error. 
have a look at the nginx.conf


```
upstream backend {
    server localhost:8065;
    keepalive 32;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m use_temp_path=off;

server {
     listen [::]:80;
     listen 80;

     server_name mm.unboxrobotics.com www.mm.unboxrobotics.com;

     return 301 https://mm.unboxrobotics.com$request_uri;
}

server {
     listen [::]:443 ssl;
     listen 443 ssl;

     server_name www.mm.unboxrobotics.com;

     ssl_certificate /etc/letsencrypt/live/mm.unboxrobotics.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/mm.unboxrobotics.com/privkey.pem;

     return 301 https://mm.unboxrobotics.com$request_uri;
}

server {
     listen [::]:443 ssl http2;
     listen 443 ssl http2;

     server_name mm.unboxrobotics.com;

     ssl_certificate /etc/letsencrypt/live/mm.unboxrobotics.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/mm.unboxrobotics.com/privkey.pem;

     location ~ /api/v[0-9]+/(users/)?websocket$ {
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
         
         client_max_body_size 0;
        
         proxy_set_header Host $http_host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Frame-Options SAMEORIGIN;
         proxy_buffers 256 16k;
         proxy_buffer_size 16k;
        
         client_body_timeout 120;
         send_timeout 600;
         lingering_timeout 10;
        
         proxy_connect_timeout 180;
         proxy_send_timeout 600;
         proxy_read_timeout 180s;
         proxy_pass http://backend;
    } 

    location / {
         client_max_body_size 0;
        
         proxy_set_header Connection "";
         proxy_set_header Host $http_host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Frame-Options SAMEORIGIN;
         
         proxy_buffers 256 16k;
         proxy_buffer_size 16k;
         proxy_read_timeout 1200s;
        
         proxy_cache mattermost_cache;
         proxy_cache_revalidate on;
         proxy_cache_min_uses 2;
         proxy_cache_use_stale timeout;
         proxy_cache_lock on;
         proxy_http_version 1.1;
         proxy_pass http://backend;
    }
}

```

**Comment by chinyasuhail** [comment] 2020-05-04 16:04
@lieut-data  in fact launch mattermost on any platform; heroku, bitnami and digital ocean; mattermost fails for large file sizes for some reason

**Comment by lieut-data** [comment] 2020-05-04 18:04
Thanks, @chinyasuhail! When you launch in these environments, do you see any Mattermost server logs that correlate with the error? i.e. out of memory written to `mattermost.log`?

**Comment by chinyasuhail** [comment] 2020-05-04 18:42
@lieut-data  no errors written to mattermost.log; however; Nginx logs match with what I've shared above.

Out of curiosity, have you tried uploading 1GB+ file to mattermost on Nginx+s3?

**Comment by lieut-data** [comment] 2020-05-04 18:48
Thanks again for confirming, @chinyasuhail. I haven't personally attempted to reproduce this issue yet, no. I'm hoping to route this to the right team who can help, though!

One more question comes to mind: did this stop working on the latest release, or is this just the first time it has been observed?

**Comment by chinyasuhail** [comment] 2020-05-04 18:52
tbh, I've seen this issue in almost all the previous releases and was hoping it would be fixed in upcoming releases.

**Comment by chinyasuhail** [comment] 2020-05-04 18:54
@lieut-data this may be out of the topic, but even Elastic Bean Deployments fail and I've not been able to deploy mattermost on AWS EBD to date.

**Comment by chinyasuhail** [comment] 2020-05-05 18:39
@lieut-data I tried uploading a large file /posts of api endpoint.
I received an Nginx 502 error.

**Comment by lieut-data** [comment] 2020-05-06 14:19
@chinyasuhail, I haven't been able to reproduce this:
* Uploading a 1GB file directly to Mattermost (no reverse proxy) works out of the box
* Uploading a 1GB file through Nginx to Mattermost works once I configure `client_max_body_size` accordingly (in my case, I just set it to `0` to remove all limits).

**Comment by chinyasuhail** [comment] 2020-05-06 18:04
@lieut-data Thanks will try to see what I can do; also, what's the max upload limit on Mattermost Server without proxy?

**Comment by lieut-data** [comment] 2020-05-06 18:08
@chinyasuhail, it's [configurable](https://docs.mattermost.com/administration/config-settings.html#maximum-file-size), but defaults to 50mb. Beyond that, I don't think there is any hard-coded limit, other than what is imposed organically by the memory constraints.

**Comment by chinyasuhail** [comment] 2020-05-06 18:10
Thank you so much @lieut-data; before I go ahead and close this issue; would you let me know the ports to be open on the servers?

I've enabled `8065` on Mattermost Server and `443,80 ` in Proxy all in the same `vpc`

**Comment by lieut-data** [comment] 2020-05-06 18:12
You're welcome, @chinyasuhail! In a single-server setup, only port `8065` is required by the Mattermost server, but I note this port is configurable if you require that flexibility. Depending on your security needs, only `443` may be required by Nginx, or additionally `80` if you want to expose a non-SSL connection.

**Comment by chinyasuhail** [comment] 2020-05-06 18:16
Awesome @lieut-data. Thank you so much for helping me out :)
Super grateful !!

**Comment by chinyasuhail** [comment] 2020-05-09 13:19
Hi @lieut-data,
After failing 70 times! yeah that's 70times I've destroyed and rebuilt a droplet and installed mattermost on it; I'm still unable to pass beyond 500MB on my installations.

I use this bash script to automate the installation 
```
https://github.com/The-Bash-Project/mattermost/blob/master/mattermost.sh
```

and the create a large file using `fallocate -l <size> <filename>` command and post it to the mattermost file upload endpoint

```
curl -o /tmp/n.tmp -# example.mattermost.com/api/v4/files -F 'files=**@filename.zip**' -F 'channel_id=**id**' --header 'authorization: Bearer **key**'
```

And every time beyond 500MB it gives me `connection reset by peer` or 'unable to read the file` or `500`; I'm not using any NGINX proxy

Would you please help me our @lieut-data

**Comment by lieut-data** [comment] 2020-05-11 16:25
@chinyasuhail, thanks for the extra detail. I wonder if you might be open to raising this issue in our peer-to-peer help channel at https://community.mattermost.com/core/channels/peer-to-peer-help? I don't have the ability to spin up a Digital Ocean droplet to exactly reproduce your test case, but it's possible someone from our community is able to do so and can help debug further.

Feel free to tag me there (`@jesse.hallam`) and link this conversation -- I'd love to follow along with any ensuing conversation.

**Comment by akulpeissov** [comment] 2020-09-25 11:35
Hi @lieut-data @chinyasuhail 
I have the same problem with uploading 500Mb files to MM on premises installation with or without nginx. Did someone solved this problem? Any help would be appreciated :)

**Comment by amyblais** [comment] 2021-09-03 16:41
Closing as this is an old issue. If it still reproduces, please help raise this issue in our peer-to-peer help channel at https://community.mattermost.com/core/channels/peer-to-peer-help,

**Closed by amyblais** 2021-09-03 16:41 UTC
