### ISSUE TITLE
Update Email

### ISSUE THREAD

**Issue by LocalHeroPro** [mattermost/mattermost-server#11371] opened 2019-06-24 10:57 UTC
Can't update user email with build in option in dropdown on Users list on System Console. After try update email I can see status 400 error code in console log.

**Comment by amyblais** [comment] 2019-06-24 12:42
Hi @LocalHeroPro,

To give you the best help we can, could you review [this web page](https://docs.mattermost.com/process/support.html#general-questions-for-any-issues) and send us the relevant environment details, logs, config files, etc. so we can diagnose this issue? Thank you,

**Comment by LocalHeroPro** [comment] 2019-06-24 19:58
Host OS and version: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-51-generic x86_64)
Mattermost server version: 5.12.0
Browser webapp: everywhere
Desktop App: 4.2.1 on Windows / Linux
Mobile App: don't have System Console
I'm running Mattermost on server, without any wirtualization etc.

**Comment by amyblais** [comment] 2019-06-24 22:13
@LocalHeroPro, Thank you for that information, would you also be open to posting your full Mattermost logs from the time when this issue occurs? I tried to reproduce this just now and wasn't able to.

**Comment by LocalHeroPro** [comment] 2019-06-25 07:58
That action don't save any log in log file.

**Comment by amyblais** [comment] 2019-06-25 12:35
@LocalHeroPro Can you help post the 400 error code you see in console log? Also, what do you see happen on the user interface when the email fails to update?

**Comment by LocalHeroPro** [comment] 2019-06-25 21:09
In private channel with official support maybe yes. In log file we have sensitive data!
In addition of that I send screenshot when I try change my own password.
![2019-06-25](https://user-images.githubusercontent.com/42643563/60133292-6b74ff00-979d-11e9-9e5a-501f74a48518.png)
That bug occur when I try change my own password,
When I try change password for other members - by clicking ENTER or RESET button - modal disappear and right now nothing happens on frontend. On network are send two requests. One request is PUT with new data one request is GET with user data, but unchanged.

**Comment by kongr45gpen** [comment] 2019-06-25 22:02
I am experiencing exactly the same issue. Updating my e-mail fails with:
`{"id":"api.context.invalid_body_param.app_error","message":"Invalid or missing password in request body","detailed_error":"","request_id":"dghn9qjqwfd4unmnckdtmx7eoa","status_code":400}`
(on Mattermost 5.12.0, hosted on Ubuntu 16.04, on Firefox)

**Comment by amyblais** [comment] 2019-06-27 00:15
Hi @LocalHeroPro @kongr45gpen Would one of you be open to sharing your config settings related to email settings, including if you have set any restrictions to email domains? Trying to think if this could be a configuration issue.

**Comment by kongr45gpen** [comment] 2019-06-27 11:11
These are my email settings. If I could warrant a guess, I'd say that the API believes that a non-admin user is editing their own profile, requesting that the current password is provided, since that's how it is done on the _Account Settings_ page (screenshot below)

![image](https://user-images.githubusercontent.com/720678/60261668-1ba14f80-98e5-11e9-8afc-00b76d445a2d.png)
![image](https://user-images.githubusercontent.com/720678/60261679-22c85d80-98e5-11e9-996f-c8b794cfce46.png)

![image](https://user-images.githubusercontent.com/720678/60261792-68852600-98e5-11e9-91dc-79d2afd0fc24.png)

**Comment by LocalHeroPro** [comment] 2019-06-27 13:55
If I try change email address in System Console i have that window:
![image](https://user-images.githubusercontent.com/42643563/60272193-fd8f1b80-98f3-11e9-8eca-41786f51c043.png)

**Comment by amyblais** [comment] 2019-06-27 15:56
@hanzei / @maruTA-bis5 Wondering if you'd be able to help test if updating a user's email with API has a bug?

**Comment by maruTA-bis5** [comment] 2019-06-28 12:37
Hi all.

For security reason, patch user api (`/api/v4/users/{user_id}/patch`) disallow change own email without re-entering credential (https://github.com/mattermost/mattermost-server/pull/10207, [Mattermost Security Update #5.8.0.6](https://mattermost.com/security-updates/)).
So you couldn't change your email using System Console.
You have to use Account Settings to change your own email.

**Comment by LocalHeroPro** [comment] 2019-06-28 12:53
If disallow that option in System Console or better option: give prompt for password?

**Comment by amyblais** [comment] 2019-06-28 22:34
Hi @LocalHeroPro, would you like to share this improvement idea on our feature request forum: https://mattermost.uservoice.com/forums/306457-general?

**Comment by kongr45gpen** [comment] 2019-06-28 23:09
I believe that, at least the error message for this, could be considered a bug, since it does not explain the situation (or further steps) to the user

**Comment by amyblais** [comment] 2019-07-02 17:49
Agree, opened a ticket here: https://mattermost.atlassian.net/browse/MM-16727.

**Comment by LocalHeroPro** [comment] 2019-07-03 21:20
Thanks for a ticket, but what with changing other users email address from System Console? I still can't make it start working.

**Comment by amyblais** [comment] 2019-07-03 23:22
Do you have email notifications enabled in System Console?

**Comment by LocalHeroPro** [comment] 2019-07-04 20:55
Yes.

**Comment by amyblais** [comment] 2019-07-04 23:15
Do the users get an email to verify their new email address?

**Comment by LocalHeroPro** [comment] 2019-07-05 20:02
No.

**Comment by amyblais** [comment] 2019-07-05 22:32
@LocalHeroPro You can send log errors and config settings via email at amy@mattermost.com or via our [community server](https://community.mattermost.com) at @amy.blais.

**Comment by amyblais** [comment] 2019-08-13 12:32
We haven't received feedback for a while so I'll close this issue for now. I hope you'll be able to provide logs and config settings if you still experience this issue.

**Closed by amyblais** 2019-08-13 12:32 UTC
Labels: Bug Report/Open
