### ISSUE TITLE
Version object

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9842] opened 2018-11-16 16:44 UTC
Hello.

It's me, again and again :)

Could you explain the function of this object? I thought that it needs for import of delta history: I imported the first version, have checked and after that could import second version export from the previous system. But version number has to be 1. Why?

**Comment by amyblais** [comment] 2018-11-16 17:45
Hi @swood!

I've asked our team to take a look at this as I'm not sure what the answer is.

**Comment by amyblais** [comment] 2018-11-16 21:59
@swood From our developer: 

Version object is the version number of the import data format. We are currently at version 1 still, so it will always be 1.

Does this help?

**Comment by swood** [comment] 2018-11-16 22:40
So, you assume to release the next generation of data format, and this object is a purpose to that aim? Right?

Okay. I have a question about my situation.
I have a HipChat, and I created a tool to convert HipChat export to Mattermost Jsonl (if you'd like I could publish it in future.).
I have been imported vast archive of HipChat to Mattermost and a lot of users started to examine software. 
During the import process, I faced with some problems, and I want to re-import that data. And I can't because there is a lot of unique object in the database (MySQL), a tool for bulk import was broken down and data don't import.

I think it will be great to tell with Jsonl format that "this is the second version of data, please drop existing history and write again".

**Comment by amyblais** [comment] 2018-11-20 01:08
Hi @swood, I've forwarded this feedback to our developer and I'll give you an update within the next few days.

**Comment by amyblais** [comment] 2018-11-20 12:59
Hi @swood, you should already be able to repeatedly run a bulk import file through the importer if it fails part way. It is idempotent.

What issues are you seeing when attempting to re-import data?

**Comment by swood** [comment] 2018-11-20 13:46
For example, if the import tool faced the image with max dimensions or with the Deadlock error. 
In that case, I have to re-import data, but I have a chance to get duplicates. 
I saw that and could reproduce. Also if the Jsonl contains attachments I 100% will have duplicates and the errors about this.

**Comment by amyblais** [comment] 2018-11-21 18:07
@swood What error messages are you seeing when the duplicates get created?

**Comment by swood** [comment] 2018-11-22 12:22
@amyblais something like:

>{"level":"warn","ts":1542774090.945285,"caller":"app/channel.go:284","msg":"Failed to update ChannelMemberHistory table SqlChannelMemberHistoryStore.LogJoinEvent: Failed to record channel member history, Error 1062: Duplicate entry 'ix7gd5duwjnqzdmrtbe6jkckoa-g4oy633yb3g88xdwccc9j8fjoa-1542774090' for key 'PRIMARY'"}

**Comment by amyblais** [comment] 2018-12-06 16:18
Hi @swood, one of our community members responded and said what you're seeing could possibly be a warning, not an error. It's caused by the way channels are created: [code](https://github.com/mattermost/mattermost-server/blob/v5.5.0/app/channel.go#L230) always tries to create a channel and takes care of errors if that failed because the channel existed. (Instead of testing if the channel exists and creating it if not.) That warning simply states: "hey, the channel already exists."

**Comment by amyblais** [comment] 2019-01-10 00:47
Closing this as there hasn't been activity on this for a while,

**Closed by amyblais** 2019-01-10 00:47 UTC
