### ISSUE TITLE
inconsistent member counts in direct message member selection

### ISSUE THREAD

**Issue by joriki** [mattermost/mattermost-server#12206] opened 2019-09-14 15:10 UTC
#### Summary
In the dialog for starting a direct message conversation, the count of options displayed on the current page can be larger than the total, since it includes multi-user conversations whereas the total does not.

#### Steps to reproduce
Start at least one multi-user direct message conversation and then open the dialog for starting a new direct message conversation (with the plus icon or with "More ...").

#### Expected behavior
The count of options displayed on the current page should not be greater than the total.

#### Observed behavior (that appears unintentional) 
The count of options displayed on the current page includes multi-user conversations, whereas the total does not; thus the page count can be greater than the total count:

<img width="588" alt="Bildschirmfoto 2019-09-14 um 17 08 00" src="https://user-images.githubusercontent.com/1418717/64909961-48aa1500-d712-11e9-814e-7fc0b4541c04.png">

#### Possible fixes
The merges displayed at the end of #6521 could be related to this.

**Comment by joriki** [comment] 2019-09-14 15:11
(Also, "members" doesn't really describe what that page count counts; the multi-user conversations aren't "members".)

**Comment by amyblais** [comment] 2019-09-16 13:29
@joriki I'm not able to reproduce this, are you on server v5.13 and is there any other relevant information you would be able to share about your environment?

**Comment by amyblais** [comment] 2019-10-16 22:00
I'll close this for now as there haven't been updates for a while. If the issue persists, please re-open this with additional relevant information to help us troubleshoot this,

**Closed by amyblais** 2019-10-16 22:00 UTC
Labels: Bug Report/Open
