### ISSUE TITLE
Selecting "Send Message" from user's mini-profile redirects to #town-square

### ISSUE THREAD

**Issue by slowbro** [mattermost/mattermost-server#8380] opened 2018-02-27 23:52 UTC
#### Summary
When clicking on "Send Message" in the pop-up profile (from clicking a user's profile image in a channel), you are redirected to the #town-hall channel instead of a DM to that user.

#### Steps to reproduce
Using version 4.7.1.

1. Open a chat window and navigate to a channel, public or private (web).
2. Click on a user's profile image to show their mini-profile popup.
3. Click 'Send Message'

#### Expected behavior
When you click 'Send Message', it should open and move you to a DM.

#### Observed behavior (that appears unintentional) 
When trying to open a new DM via the mini-profile, or even via the channel users list, you are redirected to #town-square. No errors were observed in the Javascript console. 

It seems that the DM is actually opened, but you are not changed over to it.

#### Possible fixes
Unfortunately I am a fledgling Mattermost contributor, and just barely have a dev environment up and running - so I can't point at any specific code right now.

**Comment by slowbro** [comment] 2018-02-28 00:20
I also made a little gif showcasing this.. https://i.imgur.com/phucUJs.gifv

**Comment by SmartHoneybee** [comment] 2018-02-28 07:30
Hi,

nice bug report. The issue you describe seems similar to #8365 and [should be fixed in 4.7.2][1].
Could you please check if you are (still) able to reproduce it on https://pre-release.mattermost.com?

Thanks,
Bee

[1]: https://github.com/mattermost/mattermost-server/issues/8365#issuecomment-368158545

**Comment by slowbro** [comment] 2018-02-28 23:57
Ah!  Of course. I somehow missed that when searching. I can verify that it seems to work on pre-release, though it seems to reload the whole chat client when switching to the DM (versus the smoothness of actually switching channels manually).

**Comment by lindy65** [comment] 2018-03-05 09:35
Hi @slowbro and thank you @SmartHoneybee :)

The issue is fixed in v4.7.2 but I am also seeing the reload of the entire app when switching to the DM instead of a smooth transition so have created [this ticket](https://mattermost.atlassian.net/browse/MM-9723) to investigate...

**Closed by lindy65** 2018-03-05 09:35 UTC
