### ISSUE TITLE
Categories lose child items periodically

### ISSUE THREAD

**Issue by trainey-dsa** [mattermost/mattermost-server#16517] opened 2020-12-08 18:02 UTC
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

After an indeterminate amount of time, Categories lose child channels and direct messages. 

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.6.1 
- Mattermost Server version: 5.28.1 

**Steps to reproduce**
Organize groups and direct messages into categories.  
Use as normal.  After some period of time, channels and direct messages within the category will return back to the Channels and Direct Messages group

**Expected behavior**
Items within Categories retain/persist indefinitely 

**Observed behavior**

More information about environment.  Our company is using a branded enterprise version. The webapp is older than the desktop application vs the Desktop version that I downloaded from Mattermost. 

The vanishing children (channels and direct messages) is intermittent.  I've seen the categories retain items through a reboot.  Not all categories lose their children at the same time.  It might be a specific amount of time since the category was created.  The category name persists, but all items within the category return back to their initial place.  I can't give a specific time, however, I noticed that category that I created yesterday has just lost its children.  It could be around 24 hours time. 

**Possible fixes**

**Comment by Willyfrog** [comment] 2020-12-08 18:03
moving this to the server repo as it is an issue with the new sidebar

**Comment by amyblais** [comment] 2020-12-08 18:33
There is a ticket open here: https://mattermost.atlassian.net/browse/MM-30314

**Comment by esethna** [comment] 2020-12-08 19:00
@trainey-dsa a few questions:

1) does this happen for just you, or is it all users on a team or all users on your server? 
2) What type of database is your server running?
3) Is it happening repeatedly for the same category or always different categories?

**Comment by esethna** [comment] 2020-12-08 19:00
cc// @hmhealey ^

**Comment by trainey-dsa** [comment] 2020-12-08 21:11
@esethna 

1) I haven't heard from anyone else on the team.  Most of the team is using the branded web application provided by our company.  I can ask around if there are other folks using the desktop version and request that they create some categories and see what happens. 
2)  From the server information it looks like postgres with schema version 5.28.0
3) I will try to pay attention to this request. I have a category labeled 'Team Phoenix' that I "lost" this morning.  But my 'SD MGMT' category has retained its children so far.  I *think* I lost both of them yesterday, but I can't confirm that yet.

Could this be a new client feature that isn't compatible with our current server version?  If so, then not a problem, we can close this.  I really like this feature, but the server is taken care of by another team that I have no interaction with so I wouldn't be able to suggest an upgrade.

**Comment by esethna** [comment] 2020-12-08 22:57
Thanks @trainey-dsa for the answers. It shouldn't be an issue of server-client compatibility, we are working on tracking down this bug as others have reprod it as well: https://mattermost.atlassian.net/browse/MM-30314

I'll leave it to @hmhealey to ask more questions as needed as we investigate. Thanks for reporting!

**Comment by trainey-dsa** [comment] 2020-12-09 22:00
Another interesting piece of information.  Today I noticed that my category repopulated itself.  This morning, I didn't have anything in the category, so I 'favorited' the folks and groups that I wanted to segregate.  I'm not sure what time this happened, but I checked and my category now has everything I had in it prior to it vanishing.

**Comment by hmhealey** [comment] 2020-12-10 18:42
Thanks for the info. I was expecting we were accidentally deleting some stuff in the database (specifically, all entries that said where each channel on a team goes for you), but what you've described sounds different than that. Perhaps it's only deleting the entries for one of the categories on the team, or maybe it's something different entirely...

**Comment by trainey-dsa** [comment] 2020-12-10 21:58
@hmhealey Yeah, A strange one.  I wish I could provide better info to help reproduce and diagnose it.  It is very intermittent though and I couldn't detect a pattern.  Since the category repopulated yesterday, everything has been stable.  I use this every day so if I run across anything else, I'll update. 
Thanks!

**Comment by donghun-park** [comment] 2020-12-22 05:54
This happens when a some user with below condition is removed from the team.
 * Direct message or group message is registered in the channel category in removed team's sidebar category
That time lost sidebarchannel row.

**Comment by hmhealey** [comment] 2021-01-14 00:46
Thanks everybody for your reports on this, and extra thanks for helping test out the new sidebar.

I finally had a chance to dig into this, and it was indeed caused by leaving a team with a DM in a custom category while the server was using a Postgres database. I don't entirely know why the DELETE FROM statement deleted rows that weren't returned by an equivalent SELECT query, but I made the new code much clearer about what it should delete, so this should be fixed in 5.32 coming in February.

**Closed** 2021-01-18 17:42 UTC
Labels: Bug Report/Open
