### ISSUE TITLE
Misleading app version in X-Version-Id header

### ISSUE THREAD

**Issue by dmke** [mattermost/mattermost-server#16897] opened 2021-02-09 10:19 UTC
#### Summary

`X-Version-Id` header does not show the true app version.

#### Steps to reproduce

Install and start mattermost-server v5.31.0. Then throw cURL against it:

```console
$ curl -I http://localhost:8080 | grep -i x-version-id
x-version-id: 5.30.0.5.31.6{PATCH}.4eff79e15993f5fd6dc1d915f1c2ba06.false
```

That version string contains the following information:

- `5.30.0` = DB schema
- `5.31.6{PATCH}` = app version
- a commit hash
- `false` = team edition

You may alternatively throw [mattercheck](https://github.com/dmke/mattercheck) against it:

```console
$ mattercheck http://localhost:8080
[Feb  9 11:10:01]  INFO mattercheck: instance is up-to-date url=http://localhost:8080 version=v5.31.6-team
```

In case of mattercheck, the detection of new releases obviously fails (at the time of writing, [5.31.1 was released a few days ago](https://docs.mattermost.com/administration/changelog.html#release-v5-31-esr)).

*(Getting mattercheck to produce an "update available" message is my primary concern here.)*

#### Expected behavior

The `X-Version-Id` should report "5.31.0" as app version.

#### Observed behavior (that appears unintentional) 

The `X-Version-Id` reports "5.31.6{PATCH}" as app version.

#### Possible fixes

IIRC, mattermost-server v5.30.x was the first release to show this behaviour. In 5.29.x and earlier, the `X-Version-Id` contained the correct app version.

**Comment by amyblais** [comment] 2021-02-09 13:06
I believe this is a duplicate of https://github.com/mattermost/mattermost-server/issues/16830, so I'll close this one.

The {PATCH} section was an error during the release process, and will be fixed in future versions. You can find more discussion on this here: https://community.mattermost.com/core/pl/zsuaan8su78p3qzsq1oapa8nqh.

**Closed by amyblais** 2021-02-09 13:06 UTC
