### ISSUE TITLE
Incorrect time stamp when submitting a message to a channel

### ISSUE THREAD

**Issue by jimbothree** [mattermost/mattermost-server#8241] opened 2018-02-12 03:01 UTC
#### Summary
When submitting a message to a channel, the time stamp on the message is 12 minutes ahead of the actual time.  

#### Steps to reproduce
Assumption: Logged into an account on the Mattermost demo site (https://oss.mattermost.com) 
- Submit a message in the Open Discussion forum or a Custom created channel 
- Time stamp for the message appears to be 12 minutes ahead of the actual time

#### Expected behavior
When submitting a message to a channel, it is expected that the time stamp of the message is accurate.

#### Observed behavior (that appears unintentional) 
(See steps to reproduce)

**Comment by lindy65** [comment] 2018-02-12 07:33
Hi @jimbothree 

Thanks for the report,

I have reproduced the issue on oss.mattermost.com but am not able to reproduce it on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master so I believe the issue is fixed.

Can you see if the issue reproduces for you on the nightly build server?

**Comment by jimbothree** [comment] 2018-02-12 14:07
Hi @lindy65 

Submitting a message seems to have the accurate time stamp on the nightly build server you linked.  I tried in a public and private channel and both instances had the correct time when submitting a message.

**Comment by lindy65** [comment] 2018-02-12 17:03
Perfect, thanks for testing @jimbothree!

The fix for this will ship with v4.7 on Feb 16th...

**Comment by lindy65** [comment] 2018-02-14 10:42
I'll close this off for now and we can reopen if the issue reproduces after v4.7 releases on Feb 16th.

**Closed by lindy65** 2018-02-14 10:42 UTC
