### ISSUE TITLE
Mattermost plugin API's OpenInteractiveDialog method fails to open a dialog

### ISSUE THREAD

**Issue by girish17** [mattermost/mattermost-server#17835] opened 2021-06-27 06:54 UTC
#### Summary
OpenInteractiveDialog method in plugin API fails to open a dialog for a TriggerID generated from a menu action. It provides no error message upon failure.

#### Steps to reproduce
This [line of code](https://github.com/girish17/op-mattermost-plugin/blob/36d64250772eac25acde930d7468f0c125295e11/server/util/uiActions.go#L437) fails.
Trigger ID is obtained on select of a menu element. The return value of the OpenInteractiveDialog function is not captured as it has `nil` value.

However, this [line of code](https://github.com/girish17/op-mattermost-plugin/blob/36d64250772eac25acde930d7468f0c125295e11/server/plugin.go#L97) works. This also uses the same dialog method but the Trigger ID is obtained from the slash command invocation.

#### Expected behavior
As per the API description - "OpenInteractiveDialog will open an interactive dialog on a user's client that generated the trigger ID. Used with interactive message buttons, menus and slash commands."  On error, it should generate the relevant message.

#### Observed behavior (that appears unintentional) 
 In case of menus, it seems to be failing and no relevant error is being generated. The dialog fails to open and no error is produced.

#### Possible fixes
This [method]( https://github.com/girish17/mattermost-server/blob/33e319366cc30ae2bed03efbfee7459e9a31b45b/plugin/api.go#L744) may need to be fixed.

**Comment by amyblais** [comment] 2021-06-28 15:03
@hanzei @DHaussermann Are you able to reproduce this and should we create a ticket?

**Comment by hanzei** [comment] 2021-06-28 18:44
Thanks for the report @girish17.

Does https://github.com/girish17/op-mattermost-plugin/blob/36d64250772eac25acde930d7468f0c125295e11/server/util/uiActions.go#L437 return an error. If so, which? Also, does the log message in https://github.com/girish17/op-mattermost-plugin/blob/36d64250772eac25acde930d7468f0c125295e11/server/util/uiActions.go#L408 show a triggerID?

**Comment by girish17** [comment] 2021-06-29 04:07
- No error is returned. The debug log shows `<nil>` as the return value.
- The triggerID is always shown. For instance one of the generated triggerIDs is `ZHM1d2U5aXRtcGQ3YmRvNTRrZjlqa3Brcnc6d3J6eHlrcmdjaXJqODhlYWI3NG1kc2N6dGM6MTYyNDkzOTI0NTA5NzpNRVVDSUJueVB0Ulp6cXhEazcxUGVFL2MrRXlYSzdDdi8yMWUyeEk2TXNJMmVpRmZBaUVBK3hEMFI0bGZ3YlZNaGFwK0Z6dndqVGZrNGxob1Z3UkEvTFRmU3ZQZVF4TT0=`

**Comment by amyblais** [comment] 2021-06-29 12:32
@hanzei ^

**Comment by amyblais** [comment] 2021-06-30 12:26
@larkox Could this be a bug?

**Comment by larkox** [comment] 2021-06-30 12:30
This is almost sure caused by not returning a proper response to the post action. I haven't checked in code, but this is my guess:

- You don't return a proper response
- The post action fails because the response has an empty body (or not recognizable)
- The client see the post action failing, so it doesn't set the triggerID in redux
- The client receives the websocket event, but since the triggerID is not set, it does not use it.

If you return a proper response, it should work. An oversimplified code example would be the following:
```
handlePostAction(w responseWriter, r request) {
   triggerID = doStuff(r)
   openDialog(triggerID)
   w.Write('{}')
}
```

I am inclined to consider this a bug, and handle an empty body the same as an empty response (as in the example). But I would prefer some feedback from someone else from the team. @hanzei , thoughts?

**Comment by hanzei** [comment] 2021-06-30 14:02
@larkox I'm also inclined to accept and empty response body as a response. Redux should load the triggerID anyway IMO, as it's not obvious why it's returned but not valid.

**Comment by amyblais** [comment] 2021-06-30 14:32
Opened a ticket https://mattermost.atlassian.net/browse/MM-36757

**Closed** 2021-07-20 13:48 UTC
Labels: Bug Report/Scheduled for Release
