### ISSUE TITLE
File attachments stuck at processing randomly

### ISSUE THREAD

**Issue by olodar** [mattermost/mattermost-server#22117] opened 2023-01-20 19:23 UTC
Hello, we got a problem with attachments - sometimes when someone trying to attach image (select file or screenshot from clipboard) it is stuck with "processing":
![stuck](https://user-images.githubusercontent.com/32993068/213786488-aa4280df-00c0-4ded-a4a4-0ce687131f06.PNG)
and nothing happens after, need cancel attachment and upload again, then maybe will upload normally. This problem appears randomly, and especially appears more frequently after upgrade mattermost to 7.7.0 / 7.7.1 version.
Nothing said in server/client logs about that.
Same problem with browser client, so this is only server side problem.
Mattermost version: 7.7.0
Client version: 5.2.2
Ubuntu 20.04
Any suggestions where is to dig up?

**Comment by amyblais** [comment] 2023-01-20 19:54
Closing as a duplicate of https://mattermost.atlassian.net/browse/MM-49088 / https://github.com/mattermost/mattermost-server/issues/21903.

**Closed by amyblais** 2023-01-20 19:54 UTC

**Comment by olodar** [comment] 2023-01-20 21:24
> Closing as a duplicate of https://mattermost.atlassian.net/browse/MM-49088 / #21903.

I don't think this is the same, because we have disabled all plugins, including anti-virus, it is not help.

**Comment by amyblais** [comment] 2023-01-20 21:34
We use the ticket (https://mattermost.atlassian.net/browse/MM-49088) to investigate the general issue where files are getting stuck at "Processing..." in some cases. We're still investigating the root cause and I don't think it's necessarily caused by plugins.

**Comment by trengri** [comment] 2023-01-23 16:39
@olodar, I can suggest to do some troubleshooting.
When using a browser client, could you please open a Chrome Developer Tools (F12), go to Network tab and try attaching a file. What I'm interested in is the response code from the server that you can see on the Network tab. In my case it was error 400. There is a bug in MM WebApp - it does not handle 400 at all, so it doesn't understand that the file is rejected. If that's the case, you will also be able to find some message text in the server response, this can give a clue why the server rejected request.

**Comment by olodar** [comment] 2023-02-08 01:32
> @olodar, I can suggest to do some troubleshooting. When using a browser client, could you please open a Chrome Developer Tools (F12), go to Network tab and try attaching a file. What I'm interested in is the response code from the server that you can see on the Network tab. In my case it was error 400. There is a bug in MM WebApp - it does not handle 400 at all, so it doesn't understand that the file is rejected. If that's the case, you will also be able to find some message text in the server response, this can give a clue why the server rejected request.

No, I'm not getting any errors about attaching a file. Simply stuck and no any errors.

**Comment by trengri** [comment] 2023-02-08 02:08
I think you have misunderstood my message. I know you that it is just stuck and you don't get any visible errors.
In my message above I have provided instructions how to extract additional information with Chrome Developer Tools which you get by pressing F12. Can you do it?

**Comment by anx-ag** [comment] 2023-02-08 12:23
Hey,

I think this has been fixed by https://github.com/mattermost/mattermost-webapp/pull/12107 already.

**Comment by olodar** [comment] 2023-02-21 01:04
> Hey,
> 
> I think this has been fixed by [mattermost/mattermost-webapp#12107](https://github.com/mattermost/mattermost-webapp/pull/12107) already.

Yes, finally it's fixed in 7.8
