### ISSUE TITLE
Able to sign up with an email address WITHOUT domain extension

### ISSUE THREAD

**Issue by darkzcythe** [mattermost/mattermost-server#7868] opened 2017-11-21 07:18 UTC
#### Summary
User is able to sign up with an email address without the domain extension (e.g. '.com'). 

#### Steps to reproduce
1) Access https://oss.mattermost.com/ 
2) On the login page, click the **Create one now** link
3) On the **What's your email address?** text box, enter an email address WITHOUT a domain name extension. e.g. invalid@email
4) Enter a VALID username on the **Choose your username** text box 
5) Enter a VALID password on the **Choose your password** text box 
6) Click the **Create Account** button 

#### Expected behavior
User should be unable to proceed on creating a new account; An error message should be displayed saying that the email address entered is INVALID. 

#### Observed behavior (that appears unintentional) 
User is able to proceed to verify email address page even the email address entered has NO domain name extension. 

See attached screenplay (GIF file) - 
![signup_emailad_nodomainext](https://user-images.githubusercontent.com/13311521/33059454-378e4996-cecf-11e7-84d5-f73343817b41.gif)

**Comment by lindy65** [comment] 2017-11-21 08:25
Thanks for the report @darkzcythe,

I've reproduced your issue on oss.mattermost.com as well as our nightly build server and have created [this ticket](https://mattermost.atlassian.net/browse/PLT-8205) for our team to investigate.

**Comment by lindy65** [comment] 2017-11-22 06:43
I'll close this issue off for now as it's intended behavior.

**Closed by lindy65** 2017-11-22 06:43 UTC
