### ISSUE TITLE
Managing members in the any team available any team member

### ISSUE THREAD

**Issue by 0xSheff** [mattermost/mattermost-server#10076] opened 2019-01-08 13:16 UTC
Hello!
We use Mattermost server (TEAM plan) and noticed that any member (not system admin or team admin, just member) can manage members (or remove them) in the any channel.
This is wrong and is contrary to the documentation: https://docs.mattermost.com/help/getting-started/managing-members.html
According to this doc only Team Admins and System Admins can manage members.

**Comment by amyblais** [comment] 2019-01-08 13:34
Closing this as a duplicate of https://forum.mattermost.org/t/managing-members-in-the-any-team-available-any-team-member/6463.

**Closed by amyblais** 2019-01-08 13:34 UTC
