### ISSUE TITLE
Minimized App-Window has new position on reopen

### ISSUE THREAD

**Issue by Bissel** [mattermost/mattermost-server#14051] opened 2020-03-13 09:55 UTC
#### Summary
After minimize or close the app-window, a reopen positions the window at the most top-left (in the screen space).

#### Steps to reproduce
I am using
Mattermost Version: 5.20.1
Database Schema Version: 5.20.0
on Linux Mint 19 Cinnamon (3.8.9) with Linux-Kernel 5.0.0-16

#### Expected behavior
The application window should be opened at the same position it was minimized or closed.

#### Observed behavior (that appears unintentional) 
If the application window is minimized or closed and then reopened its new position is at the most left display in the top-left-corner, after been shown at the right place for half a second.

**Comment by amyblais** [comment] 2020-03-13 13:13
Closing as a duplicate of https://github.com/mattermost/desktop/issues/1225.

We have a ticket to investigate this here: https://mattermost.atlassian.net/browse/MM-23195.

**Closed by amyblais** 2020-03-13 13:13 UTC
