### ISSUE TITLE
if server comes only via GPO "Add Server" appears on each startup

### ISSUE THREAD

**Issue by neeral85** [mattermost/mattermost-server#21603] opened 2022-11-07 10:34 UTC
Issue https://mattermost.atlassian.net/browse/MM-37863 did appear again in client version 5.2.0

https://github.com/mattermost/desktop/issues/1686

**Comment by amyblais** [comment] 2022-11-07 13:31
Duplicate of https://github.com/mattermost/desktop/issues/2335 and will be fixed in 5.2.1,

**Closed by amyblais** 2022-11-07 13:31 UTC
