### ISSUE TITLE
Don't play Gif automatically; trigger animation when mouse is over instead

### ISSUE THREAD

**Issue by kleintim** [mattermost/mattermost-server#16424] opened 2020-11-30 14:17 UTC
basically this is a copy of:
https://github.com/mattermost/mattermost-server/issues/7355

it really provokes [motion sickness](https://en.wikipedia.org/wiki/Motion_sickness) and needs to be assigned, please!

Using the `/collapse` command is not working but would be a good solution as well as the mouse over idea.

Best regards!
Tim

**Comment by esethna** [comment] 2020-12-01 20:08
@kleintim we have a ticket open for pausing after 6 loops, would this help solve this issue?

**Comment by evelynhathaway** [comment] 2021-05-28 20:32
Pausing after six loops is a start, but a setting that pauses all gifs unless hovered or focused would be a godsend for accessibility. I have to minimize my Matermost to not get pulled in by party parrot and reaction gifs (ADHD).

Even if the six loops feature was added, it could still be non-compliant with WCAG level A (bare minimums for accessibility) violation of [Pause, Stop Hide](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html) because some gifs could last longer than 5 seconds over 6 loops. If the hover feature was not implemented, the criteria for looping must be "loop up to 6 times, but no more than 5 seconds". [Related technique](https://www.w3.org/WAI/WCAG21/Techniques/general/G152).

However, I still strongly recommend the hover setting since the loop maximum strategy would still distract me while reading messages or having Mattermost in another window.

**Comment by esethna** [comment] 2021-06-03 18:45
@evelynhathaway makes sense. We have a ticket here for a setting, I'm going to open it as HW if anyone is interested in addressing it https://mattermost.atlassian.net/browse/MM-22242

**Comment by amyblais** [comment] 2021-09-03 13:45
Closing as duplicate of https://github.com/mattermost/mattermost-server/issues/17740.

**Closed by amyblais** 2021-09-03 13:45 UTC
