### ISSUE TITLE
Gitlab Authentication Fail - Bad response from token request

### ISSUE THREAD

**Issue by jpudell** [mattermost/mattermost-server#19750] opened 2022-03-08 22:44 UTC
After Upgrading Mattermost on Ubuntu from 6.2.1 -> 6.4.1 the authentification via gitlab returns: Bad response from token request.

**Comment by amyblais** [comment] 2022-03-08 23:39
@jpudell What OS and version are you on? Do you see errors in the Mattermost server logs?

**Comment by han911976** [comment] 2022-03-10 09:27
Same problem, just fixed with some config tweak.

Not sure the root cause, guessing might be related to deprecation of oauth 2.0
https://docs.mattermost.com/onboard/sso-gitlab.html#migrating-from-oauth-2-0-to-openid-connect

My Mattmost build was deployed behind a nginx server, standalone using omnibus build, with another omnibus gitlab build on different VM. Users are limited to login with gitlab sso.

Existing session did not drop, while new session could not be established.

### server log example:
```json
{"timestamp":"2022-03-10 16:14:00.451 +08:00","level":"error","msg":"Bad response from token request.","caller":"web/context.go:105","path":"/signup/gitlab/complete","request_id":"...","ip_addr":"...","user_id":"","method":"GET","err_where":"AuthorizeOAuthUser","http_code":500,"err_details":"response_body={\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}, status_code=400, error=<nil>"}
```
*some field are masked*

### fix:

```bash
sudo mmctl --local config edit
```

```json
"GitLabSettings": {
    "Enable": true,
    "Secret": "********************************",
    "Id": "...",
    // "Scope": "" <-- not sure if it is needed to modified ,
    "Scope": "profile email openid",
    "AuthEndpoint": "https://<gitlab.yourdomain.com>/oauth/authorize",
    "TokenEndpoint": "https://<gitlab.yourdomain.com>/oauth/token",
    "UserAPIEndpoint": "https://<gitlab.yourdomain.com>/api/v4/user",
    // "DiscoveryEndpoint": "" <-- by my understanding this should allow mattermost to auth with gitlab using openid ,
    "DiscoveryEndpoint": "https://<gitlab.yourdomain.com>/.well-known/openid-configuration",
    "ButtonText": "hi!",
    "ButtonColor": ""
  },
```

Then restart mattermost service to apply the config.

Also grant related scopes in gitlab
![image](https://user-images.githubusercontent.com/24373139/157630438-f99b8b3a-210b-4fce-b646-d0e6b94e6d93.png)


Things go right again and user could login again.


GitLab Version: 14.8.2-ee
Mattermost Version: 6.4.0
OS: Ubuntu 20.04.4 
kernel: 5.4.0-104-generic

**Comment by amyblais** [comment] 2022-03-10 15:16
@han911976 Is this similar to this report https://github.com/mattermost/mattermost-server/issues/17499?

**Comment by han911976** [comment] 2022-03-11 05:40
@amyblais 
yes and no?

As @jpudell said, sso functions normally before updating to 6.4. I was able to login with gitlab account without any scope set up in config, using OAuth with "api" scope set in gitlab application and no scope and DiscoveryEndpoint defined in mattermost config.  

It seems the issue you mentioned was related to a mattermost server wants to auth with gitlab using OAuth but not success, while this issue is about the default / config change lead to sso auth changed to openid.

Overall: 
#17499 -> wants to use OAuth but Scope != "" leaded to openID 
#19750 -> used to be able to OAuth but in someway it failed after update 
^ as my understanding

I am not sure whether the error are from gitlab or mattermost since I updated both at the same time. 
The error log should came from this line btw.

https://github.com/mattermost/mattermost-server/blob/caa30c9bc48341f604bfce4459a23ee428871d1d/app/oauth.go#L853-L855

**Comment by amyblais** [comment] 2022-03-11 14:35
I opened a ticket: https://mattermost.atlassian.net/browse/MM-42474.

**Comment by physiker05** [comment] 2022-03-11 20:40
> @jpudell What OS and version are you on? Do you see errors in the Mattermost server logs?

@amyblais Hi. I'm a colleague of @jpudell. I can give you the following information:

Ubuntu 20.04.4 LTS
Kernel: 5.4.0-100-generic
Gitlab version: 14.8.2

Entries in log look like below. So (as far as I can see) similar to what @han911976 described.

{"timestamp":"2022-03-08 19:37:53.410 +01:00","level":"error","msg":"Bad response from token request.","caller":"web/context.go:105","path":"/signup/gitlab/complete","request_id":"...","ip_addr":"...","user_id":"","method":"GET","err_where":"AuthorizeOAuthUser","http_code":500,"err_details":"response_body={\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}, status_code=400, error=<nil>"}

**Comment by apollo13** [comment] 2022-03-23 10:03
I am also seeing this on mattermost 6.5 with legacy E10 edition if this matters. The fixes from above do not seem to work :/

**Comment by apollo13** [comment] 2022-03-23 12:01
After digging deeper I found the following issue from the Gitlab logs:
```
Started GET "/oauth/authorize?response_type=code&client_id=CLIENT_ID&redirect_uri=https%3A%2F%2Fmattermost.TLD%2Fsignup%2Fgitlab%2Fcomplete&state=STATE" for 172.22.2.110 at 2022-03-23 12:58:39 +0100
Redirected to https://gitlab.TLD/users/sign_in
Filter chain halted as :redirect_unlogged_user rendered or redirected
Completed 302 Found in 13ms (ActiveRecord: 0.0ms | Elasticsearch: 0.0ms | Allocations: 3837)
Processing by Oauth::AuthorizationsController#new as HTML
  Parameters: {"response_type"=>"code", "client_id"=>"CLIENT_ID", "redirect_uri"=>"https://mattermost.TLD/signup/gitlab/complete", "state"=>"STATE"}
Completed 200 OK in 19ms (Views: 1.9ms | ActiveRecord: 5.4ms | Elasticsearch: 0.0ms | Allocations: 3130)
Started POST "/oauth/token" for 172.22.3.171 at 2022-03-23 12:58:39 +0100
Processing by Oauth::TokensController#create as JSON
  Parameters: {"client_id"=>"CLIENT_ID", "client_secret"=>"[FILTERED]", "code"=>"[FILTERED]", "grant_type"=>"authorization_code", "redirect_uri"=>"http://mattermost.TLD/signup/gitlab/complete"}
Completed 400 Bad Request in 6ms (Views: 0.2ms | ActiveRecord: 2.2ms | Elasticsearch: 0.0ms | Allocations: 1000)
```

The requested redirect URI when calling `/auth/token` is `http://` and not `https://`! This is probably the reason why it cannot get the token.

**Comment by apollo13** [comment] 2022-03-23 12:16
Fixed it by sending X-Forwarded-Proto from the loadbalancer. I dug deeper and found the following:

When creating the `oauth/authorize` request the following code is used to calculate the redirect URL:
https://github.com/mattermost/mattermost-server/blob/68382c5fb71abc36a962a8bd4b86d3430fd4b268/app/oauth.go#L751-L754
That has the effect of properly querying and using the SiteURL defined in the system console.

When it tries to access the token it uses:
https://github.com/mattermost/mattermost-server/blob/68382c5fb71abc36a962a8bd4b86d3430fd4b268/web/oauth.go#L276
instead, which doesn't consult settings. IMO both should use the same code path.

**Comment by han911976** [comment] 2022-04-27 01:35
![image](https://user-images.githubusercontent.com/24373139/165419948-aa86ea0e-8ef5-447e-9cff-221691173765.png)

Happened again when I upgraded the servers.

gitlab 14.8 -> 14.10
mattermost 6.4 -> 6.6

not yet figure out how to solve,
established session did not drop as before, 

manually change the redirect_uri to https in the url could allow user to login mattermost by sso.
![image](https://user-images.githubusercontent.com/24373139/165420629-f32b66e8-ca79-442e-b094-630bc7fd91bd.png)

**Comment by han911976** [comment] 2022-04-27 07:42
Turn out that the site url was changed to http when upgrading the mattermost server.

I was able to fix the above problem by re-config the site url to https again.

---
### What I did:

modify the variable
`nano /etc/mattermost/mmomni.mattermost.env`
```
...
# MM_SERVICESETTINGS_SITEURL=http://{fqdn}
MM_SERVICESETTINGS_SITEURL=https://{fqdn}
...
```
 
 reload config
```
systemctl restart mattermost
```

check that the site url was modified.
```
mmctl --local config show | grep SiteURL
```

The SSO run smooth again.

---
### One thing to note:
`mmomni reconfigure` will cause `MM_SERVICESETTINGS_SITEURL` reset to http in my server, which explains why the SSO broke after server upgrade, as the reconfiguration will occur during the upgrade.

**Comment by jpudell** [comment] 2022-05-12 21:32
I solved today the problem by changing following lines of the apache2 configuration (with Mattermost version 6.6.1) from

`RequestHeader add 'X-Forwarded-SSL' expr=%{HTTPS}
RequestHeader set 'X-Forwarded-Proto' expr=%{REQUEST_SCHEME}
`
to

`RequestHeader set X-Forwarded-Proto 'https'
RequestHeader set X-Forwarded-Ssl 'on'`

**Comment by amyblais** [comment] 2022-07-19 13:21
Closing as docs have been updated via https://github.com/mattermost/docs/pull/5579.

**Closed by amyblais** 2022-07-19 13:21 UTC
Labels: Bug Report/Open
