### ISSUE TITLE
Sorting of channel list ignores non-alphabetic characters

### ISSUE THREAD

**Issue by MarkMaldaba** [mattermost/mattermost-server#8240] opened 2018-02-12 01:22 UTC
#### Summary

We've just upgraded Mattermost from 3.6.1 and 4.6.0, and the sorting of the channel list has changed.  

Our `(General Chat)` channel, which we previously forced to the top of the list (by adding the parentheses) is listed alphabetically under `G` and so is no longer easily locatable.

Note that we experienced this for private channels, but I assume this affects all types of channel.

#### Steps to reproduce

Create three private channels: `A project`, `Some other project` and `(General)`.

#### Expected behavior

List is sorted as follows:
* `(General)`
* `A project`
* `Some other project`

#### Observed behavior (that appears unintentional) 

List is sorted as follows:
* `A project`
* `(General)`
* `Some other project`

#### Possible fixes

Presumably, trivial to fix, assuming it's not deliberate.

If this is a deliberate change, then I ask that the decision be revisited, as it is very important for us to be able to 'pin' the general discussion channel to the top of the list otherwise it gets lost amongst all the various project channels.  Adding a method of pinning, grouping, promoting or ordering channels might be an acceptable alternative to fixing this issue, in this case.

**Comment by lindy65** [comment] 2018-02-12 07:49
Hi @MarkMaldaba,

There have been numerous changes to the way channel names are sorted since v4.6 which will release with v4.7 on February 16th.  I believe this will fix the issue for you - screenshot below is from our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) running off the latest master.

![image](https://user-images.githubusercontent.com/13020833/36087184-b4444e5e-0fd9-11e8-893b-7cbefb2fe1ef.png)

Let us know how it goes once you upgrade after the release :)

**Comment by MarkMaldaba** [comment] 2018-02-12 22:13
Will do - it looks very promising!

**Comment by lindy65** [comment] 2018-02-14 10:41
I'll close this off for now and we can reopen if the issue still reproduces after v4.7 releases on Feb 16th.

**Closed by lindy65** 2018-02-14 10:41 UTC

**Comment by MarkMaldaba** [comment] 2018-02-16 16:19
I don't see anything about this in the release notes for 4.7, so I'm not sure if the change made it in or not.

Either way, I'll be upgrading sometime next week and will let you know whether this resolves the issue.

**Comment by lindy65** [comment] 2018-02-16 18:25
Hi @MarkMaldaba,

Thanks for your feedback,

Apologies that it was skipped from the Changelog but the channel ordering is definitely in v4.7 as the screenshot I posted above from my testing was from the nightly build server that v4.7 built from...

**Comment by MarkMaldaba** [comment] 2018-02-20 23:13
Hi @lindy65,

I've just upgraded to 4.7.1, and the issue does, indeed, appear to be fixed.

Any chance the release notes could be updated?  I believe the intention is for them to be a complete list of user-visible changes.

**Comment by lindy65** [comment] 2018-02-21 06:47
Thanks @MarkMaldaba,

I've updated the Changelog which will be updated once the pull request is merged...
