### ISSUE TITLE
Users can't see my nickname if I use special characters like Æ in contact list

### ISSUE THREAD

**Issue by WuglyakBolgoink** [mattermost/mattermost-server#17584] opened 2021-05-07 13:51 UTC
#### Summary
Users cannot see my nickname

#### Steps to reproduce
- Change nickname to "blablabla" - users can see it
- Change nickname to "Æ" - users cannot see, only status

![image](https://user-images.githubusercontent.com/2271337/117459238-78430c00-af4b-11eb-9c99-58828a792cc3.png)

but in chat all can see my nickname correct
![image](https://user-images.githubusercontent.com/2271337/117459647-ec7daf80-af4b-11eb-9519-2e660730efab.png)

**Update**:
in grouped chat nickname was correct showed:
![image](https://user-images.githubusercontent.com/2271337/117459924-38c8ef80-af4c-11eb-9131-b3e2272b916b.png)

**Update-2**
if I change nickname to "blabla Æ" it will be correct showed

![image](https://user-images.githubusercontent.com/2271337/117460336-b4c33780-af4c-11eb-89e5-307297efd31c.png)

#### Expected behavior

show nickname same as in settings

![image](https://user-images.githubusercontent.com/2271337/117459772-0fa85f00-af4c-11eb-8ecc-461649433359.png)

**Comment by amyblais** [comment] 2021-05-07 16:38
@WuglyakBolgoink What Mattermost server version are you on? You can find it at Main Menu > About Mattermost.

**Comment by amyblais** [comment] 2021-05-07 16:59
@WuglyakBolgoink What are the other users' setting set to for Account Settings > Display > Teammate Name Display?

I believe the nickname will only show if the setting is set to "Show nickname if one exists, otherwise show first and last name".

**Comment by WuglyakBolgoink** [comment] 2021-05-10 09:17
> @WuglyakBolgoink What are the other users' setting set to for Account Settings > Display > Teammate Name Display?
> 
> I believe the nickname will only show if the setting is set to "Show nickname if one exists, otherwise show first and last name".

same on both users 
![image](https://user-images.githubusercontent.com/2271337/117636553-38656a00-b181-11eb-9da5-1013713a82a8.png)

with a same version
![image](https://user-images.githubusercontent.com/2271337/117636586-41eed200-b181-11eb-8fb4-9e13d244c8ed.png)

**Comment by amyblais** [comment] 2021-05-10 13:24
@lindy65 I tried this a few times but wasn't able to reproduce. Would you be open to testing this? I'm guessing that the reporter is on v5.33 or v5.34 because the screenshots show custom statuses.

**Comment by lindy65** [comment] 2021-05-10 16:21
Hi @amyblais @WuglyakBolgoink - I will take a look - although I am on Windows 10/Chrome

**Comment by amyblais** [comment] 2021-09-03 20:43
I'll close this for now, but feel free to re-open this if the problem persists on the latest server version (5.38.2) and latest desktop app version (4.7.1),

**Closed by amyblais** 2021-09-03 20:43 UTC

**Comment by WuglyakBolgoink** [comment] 2021-09-04 19:50
@amyblais now I can confirm, that on a new version all work fine! thank you!
