### ISSUE TITLE
[Help Wanted] [MM-8860] Bulk loading: Support every 15 minutes and every 1 hour intervals for email notification preferences

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8889] opened 2018-05-31 13:36 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8860)

Mattermost supports a bulk import tool feature for migrating data from an existing messaging system, or for pre-populating a new installation with data. https://docs.mattermost.com/deployment/bulk-loading.html

The import tool lets one specify a user's notification preferences, including email: https://docs.mattermost.com/deployment/bulk-loading.html#fields-of-the-usernotifyprops-object

Currently, the import tool only supports the "Immediately" and "Never" email notification preference options. However, when [email batching is enabled|https://docs.mattermost.com/administration/config-settings.html#enable-email-batching], Mattermost also supports sending email notifications every 15 minutes and every 1 hour intervals.

Proposed change: Allow the bulk import tool to support the following options:
 - When email batching isn't enabled: Immediately; Never
 - When email batching is enabled: Immediately; Every 15 minutes; Every 1 hour; Never

Speak to @jason on [pre-release|https://pre-release.mattermost.com] (@jasonblais on GitHub) for help if needed.

**Comment by jasonblais** [comment] 2018-06-01 14:28
Duplicate of https://github.com/mattermost/mattermost-server/issues/8498

**Closed by jasonblais** 2018-06-01 14:28 UTC
Labels: Up For Grabs
