### ISSUE TITLE
Can't read direct_channel with inactive user

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-server#9874] opened 2018-11-23 12:51 UTC
Hello.

I faced with the problem from the header after upgrade version from 5.4 to 5.5.
Yes, I enabled the option about "Allow users to view archived channels". 
So, why the inactive users can't be searched?

**Comment by amyblais** [comment] 2018-11-23 14:19
Hi @swood,

For bug reports, can you help use the Github template and include all relevant information:

#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Thanks!

**Comment by swood** [comment] 2018-11-23 15:21
#### Summary

Can't find a user if inactive.

#### Steps to reproduce

After upgrade Mattermost server to version 5.5, I haven't a possibility to read direct_channels with inactive users. In 5.4 I still can do it (I have both versions with the same data).

#### Expected behavior

I need to read that channels.

#### Observed behavior (that appears unintentional) 

The inactive users can't be founded by the search.

#### Possible fixes

Permit to read direct_channels with inactive users when I turned on the option "Allow users to view archived channels".

**Comment by swood** [comment] 2018-11-23 15:21
@amyblais better?

**Comment by amyblais** [comment] 2018-11-23 16:21
Hi @swood,

It appears I'm not currently able to reproduce this. Is this happening with all inactive users? We did have a ticket open for an issue related to this, but it was closed because we couldn't consistently reproduce it. Feel free to read the comments in the ticket: https://mattermost.atlassian.net/browse/MM-12139.

**Comment by swood** [comment] 2018-11-23 17:08
Hello, @amyblais.

I understand that you can't. But I can right now. What do you need to investigate this case with the new power?

**Comment by amyblais** [comment] 2018-11-23 18:44
Hi @swood, just to confirm, are these users that you previously discussed with on a Direct Message? You are only able to search for Direct Messages for those inactive users that you previously had a conversation with on Direct Message channel.

**Comment by amyblais** [comment] 2018-11-27 19:59
Hi @swood, some additional questions:

1. Are you seeing this issue with all inactive users?
2. Are other users on your server seeing this issue?
3. Can you help with more details on your environment from here https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by swood** [comment] 2018-11-27 22:56
Hello, @amyblais.
1. Yes.
2. Yes.
3. :
Mattermost Version: 5.5.0
Database Schema Version: 5.5.0
Database: mysql
Operation system: ubuntu 16.04;
All applications includes mobile clients;
There isn't any logs of event "I can't find a deactivated user";
Yes, Mattermost run in container;
......
I don't understand how the logical error between previous and current version should be faced with a technical question like "what your operation system". I can downgrade the release of the software, and we will close this issue. Or you could reproduce it. It's effortless if you are interested in the fix the bug.

**Comment by amyblais** [comment] 2018-11-27 23:47
Thank you for those details - I have been trying to reproduce this but haven't seen this issue so far, so I thought maybe it helps to know the specific environment details. I asked our team and community members last week to take a look at this but haven't received any feedback yet, so I will ask for more help again tomorrow.

**Comment by swood** [comment] 2018-11-30 21:11
Hi, @amyblais.
Do you have an updates?

**Comment by amyblais** [comment] 2018-12-06 16:20
Hi @swood, one of our community members responded and said that we'll need detailed, step-by-step reproduction steps to diagnose this issue. Also, we'll need any log errors from around the time this issue occurs. Thanks!

**Comment by swood** [comment] 2018-12-19 10:51
Hi, @amyblais. Sorry for the long answer.

I can write about all my process.
1. I had HipChat, the old message system. I made an export from HipChat and converted it to a lot of Jsonl files: Mattermost import.
2. I imported all data to the Mattermost with version 5.4. I can search an inactive man via cmd+k, and I can read chat with him as well.
3. I upgraded a version Mattermost server to 5.5. After that, the chat which has been opened with inactive man was still available. But I saw a banner (this chat with inactive user). Okay. I has been closed this chat, and after that, I can't search this user via cmd+k. 

If I activate that user I can find him and read the chat with him. 
Is it enough or you need some other details about the process?

**Comment by amyblais** [comment] 2019-01-10 00:46
Closing this as there hasn't been activity on here for a while,

**Closed by amyblais** 2019-01-10 00:46 UTC
