### ISSUE TITLE
Message notification sound during phone calls

### ISSUE THREAD

**Issue by alesswin** [mattermost/mattermost-server#7858] opened 2017-11-17 09:47 UTC
#### Summary
When receiving a message while taking a phone call the message notification sound is played.
Since the focus usually is to be able to talk and understand the other person, hearing that sound is quite surprising.

#### Environment
iOS 11.1.2
Mattermost Classic - Team Edition Version 4.2.0

#### Steps to reproduce
* talk on the phone
* receive a message
=> message notification sound during phone call

#### Expected behavior
During phone calls the message notification system is suppressed.

**Comment by lindy65** [comment] 2017-11-20 06:37
Hi @alesswin,

Thanks for your feedback,

Could you share whether you're using the Android or iOS app and whether it's the "classic" or "native" app?

I use the native app on Android and I can disable (in my phone's settings) playing sounds while I'm on a phonecall.  Just wondered whether you're also able to change this setting on your phone?

**Comment by alesswin** [comment] 2017-11-20 10:25
@lindy65 
I encountered the problem on the iOS classic app.

Thanks in advance!

**Comment by lindy65** [comment] 2017-11-21 08:38
Thanks @alesswin,

Are you able to change your actual phone's settings to not play sounds while on phonecalls?  Or have you already done this and sounds from the iOS classic app still play?  Just want to understand your issue better as I do not have an iOS phone.

**Comment by alesswin** [comment] 2017-11-21 08:56
@lindy65 
I could turn off the notfications for mattermost classic, but there is no condition to limit the notification beeing suppressed only during a phone call.

**Comment by lindy65** [comment] 2017-11-21 09:21
Thank for the feedback @alesswin,

Yes, agree, that is not a good solution...

What I was wondering is that, without being in any app on your phone, is there a general setting in your phone's settings where you can disable sounds while on phonecalls?  I can do this on my Android phone but do not have an iOS phone to test with.

**Comment by alesswin** [comment] 2017-11-21 09:50
@lindy65 
On iOS there is no such option.

**Comment by lindy65** [comment] 2017-11-22 06:39
Thanks @alesswin,

I'll post this issue to the product team and ask for their input.

**Comment by alesswin** [comment] 2017-11-22 08:32
@lindy65 
Thank you as well

**Comment by lindy65** [comment] 2017-11-22 18:45
Hi @alesswin,

Could you share the OS version on your phone as well as the Mattermost server version you're running?  (You can check this by clicking on the "hamburger" menu to the right of your team name then selecting "About Mattermost")

It would just help us trying to reproduce your issue...

**Comment by alesswin** [comment] 2017-11-23 09:44
@lindy65 
I extended the first post.
Unfortunately I have no clue which server version is running.
Thanks in advance,
Alessandro.

**Comment by lindy65** [comment] 2017-11-23 10:05
Thanks @alesswin 

I think you've listed the server version where you added it to your first post?

>Mattermost Classic - Team Edition Version 4.2.0

I'm not sure whether you'd be open to using the native beta app?  You can sign up for testing [here](https://github.com/mattermost/mattermost-mobile/blob/master/README.md#testing)

In the meantime, one of the product managers tested Mattermost Classic while receiving a phonecall on Facetime and heard only a vibrate, not a notification sound when a message came through.  She is going to do further testing on her iPhone.

What could also help is upgrading to the [latest server version](https://about.mattermost.com/download/) of Mattermost as there have been quite a few improvements and bug fixes since v4.2.

**Comment by lindy65** [comment] 2017-11-29 09:30
Hi @alesswin,

Did upgrading to the latest serversion of Mattermost resolve the issue for you?

**Comment by alesswin** [comment] 2017-11-29 09:47
Hello @lindy65,

unfortunately I cannot update since the application distribution is handled via a limited corporate app store.
So it looks like I have to wait until the update is approved.
I will come back to you to post my results as soon as the update is available.

Thank you for your efford,
Alessandro.

**Comment by lindy65** [comment] 2017-11-29 10:25
Thanks @alesswin 

Hoping the upgrade is approved soon!

**Comment by lindy65** [comment] 2017-12-20 08:02
Hi @alesswin,

I'll close this issue off for now. Please feel free to come back with further detail if your issue is not resolved once you've upgraded to the latest version.  

Thanks!

**Closed by lindy65** 2017-12-20 08:02 UTC
