### ISSUE TITLE
Loading Indicator flickers, when multiple large size images are previewed simultaneously

### ISSUE THREAD

**Issue by alapanme** [mattermost/mattermost-server#8061] opened 2018-01-07 15:58 UTC
#### Summary
Loading Indicator flickers, when multiple large size images are previewed simultaneously

#### Steps to reproduce
1. Upload 5 images. Make sure images are of large size like 15MB+.
2. Upon successful upload, click Enter to post them.
3. Click on any one of the images and simultaneously click the Right arrow button, so that loading indicator appears for each image.
4. Keep on clicking on right icon and observe the loading indicator for each image, while the image previews are being loaded.

#### Expected behavior
Loading indicator shouldn't fickle

#### Observed behavior (that appears unintentional) 
Loading Indicator is fickling.

![def](https://user-images.githubusercontent.com/25705483/34651071-0ff80d76-f3f1-11e7-974a-f77409685741.gif)

**Comment by lindy65** [comment] 2018-01-08 10:08
Hi @alapanme,

Thanks for the report,

I'm not able to reproduce your issue but have asked the team to see if anyone can reproduce.  Are you on Windows or Mac?  (I saw from a previous issue you reported that you're testing on oss.mattermost.com?)

**Comment by alapanme** [comment] 2018-01-08 10:11
Hi @lindy65

I have tested this on Windows 10, Google Chrome. Yes I am testing on oss.mattermost.com. Make sure you take images of large sizes.

**Comment by lindy65** [comment] 2018-01-09 09:49
Hi @alapanme 

Could you try testing this again on oss.mattermost.com please?  The server was updated so this issue might well be fixed now.

**Comment by lindy65** [comment] 2018-01-24 08:54
We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If you still experience the same problem, try upgrading to the latest version.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by lindy65** 2018-01-24 08:54 UTC
