### ISSUE TITLE
New user cannot connect with GitLab SSO after Slack import

### ISSUE THREAD

**Issue by bbenoist** [mattermost/mattermost-server#7354] opened 2017-09-01 23:14 UTC
#### Steps to reproduce
Using server version 4.1, use GitLab SSO.
1. Import a Slack room with messages from a user which has never logged in to Mattermost yet.
2. Invite the user to your Mattermost instance.
3. User can't sign-in to Mattermost using GitLab SSO since the same username is already registered with email sign-in method.

#### Expected behavior
Let the user use GitLab SSO if he never logged-in to Mattermost yet.

#### Observed behavior (that appears unintentional) 
Slack importer registered the new user with _email_ sign-in method instead of _GitLab_.

#### Possible fixes
Not looked at the code yet.  
Since we only use GitLab sign-in method, the Slack importer could just switch to it when registering new users.

**Comment by lfbrock** [comment] 2017-09-11 16:01
Just to summarize the discussion that happened at https://pre-release.mattermost.com - the options for a work around are: 

1. Temporarily turn on email sign in, and people can manually reclaim their accounts through password reset and then convert to GitLab login. 
2. Use the bulk importer to update the auth method for those accounts: https://docs.mattermost.com/deployment/bulk-loading.html

In the future, we plan on updating the Slack importer to convert the slack export file to the bulk import format. Then people should be able to change the auth method to GitLab instead of email if they choose. 

@bbenoist - is it okay if we close this issue now?

**Comment by lindy65** [comment] 2017-09-20 10:50
Hi @bbenoist, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by lindy65** 2017-09-20 10:50 UTC
