### ISSUE TITLE
Collapse reply threads: link to a message should open in the main pane

### ISSUE THREAD

**Issue by biva** [mattermost/mattermost-server#21936] opened 2022-12-21 19:18 UTC
#### Steps to reproduce
1. Be in the right pane
2. Click on a link pointing to a message in another thread
3. The message opens in the right pane → we lose the original thread where we clicked on the link

#### Expected behavior
The behaviour without "Collapse reply" activated should be maintained:
3. The message should open in the main pane, in the middle, so that we don't lose the original thread we were in.

**Comment by amyblais** [comment] 2022-12-21 19:54
Opened: https://mattermost.atlassian.net/browse/MM-49346.

**Comment by amyblais** [comment] 2022-12-21 20:19
Notes from our product manager: Good UX feedback but this is not a bug, as the new reply thread is opened in the RHS. We’re potentially looking at nav improvements like this next year.

Closing based on the comment,

**Closed by amyblais** 2022-12-21 20:19 UTC
Labels: Bug Report/Open
