### ISSUE TITLE
Can't load Mattermost when the PassFF Firefox extension is enabled

### ISSUE THREAD

**Issue by babolivier** [mattermost/mattermost-server#8390] opened 2018-03-01 10:17 UTC
#### Summary

When the [PassFF](https://addons.mozilla.org/fr/firefox/addon/passff/) Firefox addon is enabled in Firefox, Mattermost's web app won't load.

#### Steps to reproduce

The version with which the issue is occurring is 4.7.2. Note that this started happening after a v4.2.0 to v4.7.2 migration. This is also happening on https://pre-release.mattermost.com/, though.

My Firefox version is 58.0.2 (64-bit), and my PassFF version is 1.1.

The only thing I did to trigger this error is load the Mattermost web app in Firefox with the PassFF extension enabled. I tried clearing my cache, cookies, local storage and IndexDB, and restarting Firefox, and even all of them together, and the issue still remained.

#### Expected behavior

Mattermost loads normally.

#### Observed behavior (that appears unintentional) 

Only a loading icon on a white background, infinitely loading. In the console, there's the following error:

```
TypeError: t is not a function
```

pointed at [this line](https://github.com/mattermost/mattermost-webapp/blob/v4.7.2/root.jsx#L69).

### Possible fixes

I don't know the Mattermost codebase enough for that, or even if my case is a subset of a bigger issue, but I might save someone some time by pointing them directly to [PassFF's source repo](https://github.com/passff/passff).

**Comment by fujexo** [comment] 2018-03-02 13:04
I have the same problem. I've just disabled the PassFF addon and the webapp is running.

I get the same error as reported above when I have the PassFF addon enabled:
```
TypeError: t is not a function
window.onload
```

**Comment by hmhealey** [comment] 2018-03-05 14:52
Hi @babolivier and @fujexo,

Thanks for the report. It sounds like this may be related to https://github.com/passff/passff/issues/279 which was just reported last month. I'm not familiar with their release cycle, but would it be possible for one of you to try the latest version of the plugin from their GitHub repo to see if that fixes the issue?

**Comment by babolivier** [comment] 2018-03-05 14:59
Hey @hmhealey,

Thanks for bringing up the PassFF issue, I didn't see it. I just cloned the repo and loaded the extension as it is on their master in Firefox, and loading/refreshing Mattermost works!

I'll run with it for now and switch back to the AMO releases when there's a new one.

Thanks!

**Comment by fujexo** [comment] 2018-03-05 15:18
Hi @hmhealey 
Thanks, I've also quickly tested the master from passff and it seems that the issue is fixed.
Let's hope they will release a new version soon :)

**Comment by lindy65** [comment] 2018-03-06 09:21
Thanks @babolivier @fujexo 

Glad the issue is resolved by using the latest version of the plugin from their GitHub repo and, yes, let's hope they release a new version soon 👍

**Closed by lindy65** 2018-03-06 09:21 UTC

**Comment by babolivier** [comment] 2018-05-17 11:13
FWIW, and as a the closing point for this issue, there's been a couple release for this extension, and the issue is now definitely fixed.

**Comment by hmhealey** [comment] 2018-05-18 13:14
@babolivier Great to hear! Thanks for the followup
