### ISSUE TITLE
[Help Wanted] [MM-7920] 508 Compliance: Improve how UI elements in the message view indicate focus

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8960] opened 2018-06-18 16:14 UTC
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-7920)

For 508 compliance, each interactive element should have visible focus when the user tabs to the element using the keyboard. Some interactive elements on the page have visible focus using a dotted outline, change in color, or in the case of the + signs on the page getting brighter.  

Currently, the user is not able to determine where they are while tabbing because of frequent loss of a visible indicator of current focus.

Proposed changes for the expected tab order (follows Slack):
1. Assume message box is in focus
2. File upload paperclip icon (current: not tabbed + no visual cue when in focus)
3. Emoji picker icon (current: not tabbed + no visual cue when in focus)
4. "Preview" below message box (current: not tabbed + not underlined when in focus)
5. "Help" below message box (current: gets tabbed + visual cue)
6. Team icons and + sign in the team sidebar (current: gets tabbed + visual cue)
7. Profile status indicator in channel sidebar (current: not tabbed)
7. Main menu in channel sidebar (current:  gets tabbed + visual cue)
8. Channel sidebar from top to bottom, including "+" signs, channel names, "x" button on DMs, "More.." and channel switcher button. (current: get tabbed but no visual cue)
9. Channel header from left to right, including star, "v" next to channel name, channel description, channel member list, pin icon, search bar, at-mention icon, flag icon (current: most don't get tabbed nor have a visual cue)
10. "Set a header" in channel intro, if shown on the UI (current:  gets tabbed + visual cue)
11. For each message, tabs through profile picture, username, timestamp, flag icon, [...] menu, emoji icon, reply arrow, links in post, emoji reactions (current: only timestamp and links gets tabbed)
12. Right-hand sidebar, from top to bottom, including expand arrow, close sidebar icon, username, timestamp, [...], emoji, links, and reactions of messages, comment box, file upload icon, emoji picker icon, "Preview" link, "Help" link, "Add Comment" box (current: not tabbed)
13. URL bar if on browser
14. Back to center pane message box.

**Comment by jasonblais** [comment] 2018-06-18 17:09
Duplicate of https://github.com/mattermost/mattermost-server/issues/8034

**Closed by jasonblais** 2018-06-18 17:09 UTC
Labels: Up For Grabs
