### ISSUE TITLE
Backslash before underscore not shown in message

### ISSUE THREAD

**Issue by sharcslife** [mattermost/mattermost-server#7601] opened 2017-10-10 09:21 UTC
#### Summary
Backslash directly before underscore not shown in message

#### Steps to reproduce
Input text containing  \_

#### Expected behavior
Should be displayed as typed

#### Observed behavior (that appears unintentional) 
Backslash is not shown in message. It is still there though when editing the message.

#### Possible fixes
Display it correctly :-p

**Comment by MusikPolice** [comment] 2017-10-11 12:35
Huh. That is odd. Confirmed the bug in [our Public Test Channel|https://pre-release.mattermost.com/core/pl/f3tkbm9wabna5g934ptduujgee]. Thanks for the report!

**Comment by sharcslife** [comment] 2017-10-11 12:53
Thanks for you confirmation, @MusikPolice 
The issue does not occur in Slack, that's all I know :-)
I hope someone gets to the bottom of this.

**Comment by MusikPolice** [comment] 2017-10-11 13:04
Looks like [the backslash is intended to escape the underscore](https://github.com/google/WebFundamentals/issues/3161), because markdown treats an underscore as _the start of a section of text that should be formatted_. By putting a backslash in front of the underscore, you disarm it, so that it doesn't start formatting the following text, and consequentially, the backslash is removed for display. That's a pretty shortsighted way of detecting formatting though. I would argue that it'd be more appropriate to scan ahead for another underscore that ends the formatting, and only render the formatting if one exists.

**Comment by hmhealey** [comment] 2017-10-11 13:24
That's correct that the backslash is used for escaping, so it is intended behaviour. We tend to match GitHub's markdown rendering, so I'd suggest we probably leave it as is, but what's the case that you're using `\_` in? We've added some more intelligent escaping so common use cases like the double backslashes on `\\127.0.0.1\folder` URLs render correctly, so we could consider doing something similar here

**Comment by lindy65** [comment] 2017-10-19 08:27
@sharcslife,

Any feedback for `hmhealey` so we can discuss your use case?

**Comment by sharcslife** [comment] 2017-10-19 12:39
@lindy65 @hmhealey 
Thanks for your explanations.
I understand where you're coming from, so I guess there won't be a way to fix it since it's intended that way.

Our users here like to pin folders to the top of listings with a prefixed underscore, links look something like this:  X:\Data\Files\Software\_Things\Stuff

I guess it's either change that behaviour or accept the (rather small) issue it leads to.

**Comment by MusikPolice** [comment] 2017-10-19 13:13
@sharcslife [I don't see any problems](https://pre-release.mattermost.com/core/pl/ob9fdrdkffga8b3rujkxatudyc) with pasting the example path that you gave. It renders just fine. Do your users often paste paths that contain directories whose names start with an underscore character?

**Comment by sharcslife** [comment] 2017-10-19 13:53
huh, but you confirmed the problem in your posting a days ago.
![1](https://user-images.githubusercontent.com/3924964/31774272-8fd76230-b4e5-11e7-84db-75a921de1de9.png)
![2](https://user-images.githubusercontent.com/3924964/31774273-8fef9c6a-b4e5-11e7-9d11-b2a12a26fa2d.png)

**Comment by MusikPolice** [comment] 2017-10-19 14:09
To be clear, if you paste the string `X:\Data\Files\_Things\Stuff`, it will render as `X:\Data\Files_Things\Stuff` because the combination of the backslash and the underscore is an escape sequence. However, if you paste `X:\Data\Files\Software_Things\Stuff`, everything will render as typed, since there is no backslash underscore combination.

**Comment by hmhealey** [comment] 2017-10-19 15:12
Ah, so it's Windows file paths again. I'd lean towards this behaviour being fine since it matches GitHub (ie. `X:\Data\Files\_Things\Stuff` renders as X:\Data\Files\_Things\Stuff), and it only happens when one of the folder names starts with an underscore. When we added a special case similar to this in the past, it was because `\\localhost\share` (\\localhost\share on GitHub) is how any link to a Windows network share looks, so it'll come up much more frequently.

**Comment by lindy65** [comment] 2017-10-20 07:13
Thanks @sharcslife @MusikPolice @hmhealey 

I'll close this issue off here for now and we can revisit in future if needs be.

**Closed by lindy65** 2017-10-20 07:13 UTC

**Comment by lindy65** [comment] 2018-03-06 06:36
Thanks for the feedback @ryantm :)

Agree we should try to fix Windows-related issues as they arise...

@hmhealey, is this something we'd like to look at fixing in the near future?  As `ryantm` mentioned, there is a workaround at the moment but it makes sense to work on a fix sometime?

**Comment by Wildhorn** [comment] 2021-12-07 13:06
> That's correct that the backslash is used for escaping, so this is the intended behaviour. We tend to match GitHub's markdown rendering, so I'd suggest we probably leave it as is, but what's the case that you're using `\_` in? We've added some more intelligent escaping so common use cases like the double backslashes on `\\127.0.0.1\folder` URLs render correctly, so we could consider doing something similar here

To write this emoji: ¯\_(ツ)_/¯
