### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by mcp11** [mattermost/mattermost-server#11326] opened 2019-06-20 21:14 UTC
#### Summary
I deployed mattermost in a docker container on an Ubuntu 18.04 machine. When I enter my SMTP credentials and test the connection, it doesn't connect to the SMTP server and it doesn't send mail.
#### Steps to reproduce
1. Deploy Mattermost in a docker container using docker-compose on a fresh Ubuntu 18.04 machine following this guide: https://docs.mattermost.com/install/prod-docker.html
Version:
Mattermost Enterprise Edition
Mattermost Version: 5.12.0
Database Schema Version: 5.12.0
Database: postgres

2. Open the system-console from Browser (Google Chrome)
3. Go to SMTP Settings and fill in the FQDN, Port 465, enable authentication, fill in username and password, click in SAVE and Test connection

#### Expected behavior
It should connect to the SMTP Server and send a test mail.

#### Observed behavior (that appears unintentional) 
The connection test runs forever. When switching to Port 25, it says: "Connection unsuccessful: Connection unsuccessful: SendMail: Failed to authenticate on SMTP server, unencrypted connection - undefined"

When using Port 465, Logs say:
{"level":"error","ts":1561064866.4216301,"caller":"mailservice/mail.go:134","msg":"Failed to open a connection to SMTP server EOF"}
{"level":"error","ts":1561064866.42187,"caller":"mlog/log.go:172","msg":"Connection unsuccessful: SendMail: Failed to open TLS connection, EOF","path":"/api/v4/email/test","request_id":"nfpnbxsp4ir4ppu1zrmqkjhu9e","ip_addr":"1.2.3.4","user_id":"sbuj48gghibjidj5eqjeixpj1o","method":"POST","err_where":"testEmail","http_code":500,"err_details":""}

**Comment by mcp11** [comment] 2019-06-20 21:15
Of course I tried that with different SMTP Servers which are definitely working and I double-checked the credentials. Also tried port 587, same behavior

**Comment by amyblais** [comment] 2019-06-20 23:15
Hi @mcp11, thank you for the report. Would you be open to posting this issue on our docker repo and our docker maintainers will take a look: https://github.com/mattermost/mattermost-docker/issues?

**Comment by hotlong** [comment] 2019-06-21 03:46
I'm testing v5.12 on my Mac make from source, got the same error.
```
make run-server 
```

**Comment by mcp11** [comment] 2019-06-21 07:34
> 
> 
> Hi @mcp11, thank you for the report. Would you be open to posting this issue on our docker repo and our docker maintainers will take a look: https://github.com/mattermost/mattermost-docker/issues?

Hi @amyblais, I created an issue on your docker repo: https://github.com/mattermost/mattermost-docker/issues/398
Should I delete the issue here?

**Comment by amyblais** [comment] 2019-06-21 13:38
Hi all, would you be open to sharing your config settings related to SMTP?

**Comment by pichouk** [comment] 2019-06-21 17:06
(I'm answering on this issue because there are more people here)

It seems that you cannot reach at all the SMTP server, can you provide your SMTP configure (**with obfuscated credentials** of course) please ?

**Comment by cpanato** [comment] 2019-06-21 17:14
Can you post also this part of the settings of the config.json?

The emailsettings part

Thanks

**Comment by hmenzagh** [comment] 2019-06-26 15:10
Got the same issue.
The UI does not display the `Connection Security` option.
I had to set `"ConnectionSecurity": "",` to `"ConnectionSecurity": "TLS",` for it to work.

Server version is 5.12

**Comment by amyblais** [comment] 2019-06-26 16:28
Hi @hmenzagh, I think your issue is different, I opened a ticket for it here as I was able to reproduce on a team edition server: https://mattermost.atlassian.net/browse/MM-16627.

**Comment by Xairoo** [comment] 2019-06-28 23:25
Testing on Debian, tried TLS and also STARTTLS directly with the config. Nothing helped.

`tls: first record does not look like a TLS handshake`

I'm running UNMS on the same host and SMTP (Exchange) works well, only Mattermost won't.

**Comment by amyblais** [comment] 2019-06-28 23:29
Hi all, following up on this. Would you be open to sharing your config settings related to SMTP and email?

**Comment by Xairoo** [comment] 2019-06-29 08:37
Sure! But I'm really confused now. Haven't change anything, only again TLS to STARTTLS - now it works. No idea why. I just tried it again to copy the error message for TLS and STARTTLS.


`"http_code":500,"err_details":"err=Fehler beim Öffnen der TLS Verbindung"`
```
        "EnableSMTPAuth": true,
        "SMTPUsername": "user@example.com",
        "SMTPPassword": "password",
        "SMTPServer": "ex2.mail.ovh.net",
        "SMTPPort": "587",
        "ConnectionSecurity": "TLS",
```

Works: `"ConnectionSecurity": "STARTTLS",`

Can't reproduce `tls: first record does not look like a TLS handshake`

Using in other apps always TLS without any problems.

**Comment by amyblais** [comment] 2019-07-02 14:57
Hi @Xairoo, do you mean it works with STARTTLS, but it doesn't work with TLS?

@mcp11 @hotlong Please let me know if you have any updates on this?

**Comment by amyblais** [comment] 2019-08-08 12:49
https://mattermost.atlassian.net/browse/MM-16627 is fixed in v5.13 and we haven't received any feedback for a while, so I'll close this issue for now. Please re-open this issue with additional information for troubleshooting if the problem persists.

**Comment by developweekly** [comment] 2019-08-08 13:36
> Got the same issue.
> The UI does not display the `Connection Security` option.
> I had to set `"ConnectionSecurity": "",` to `"ConnectionSecurity": "TLS",` in `/opt/mattermost/config/config.json` for it to work.
> 
> Server version is 5.12

UI still does not update the config on server v5.13.0.

Setting environment variable MM_EMAILSETTINGS_CONNECTIONSECURITY also helps.

**Comment by amyblais** [comment] 2019-08-08 18:09
Hi @developweekly, would you be able to share your SMTP settings as well as email settings?

**Comment by developweekly** [comment] 2019-08-08 19:20
```json 
   "EmailSettings": {
        "EnableSignUpWithEmail": true,
        "EnableSignInWithEmail": true,
        "EnableSignInWithUsername": true,
        "SendEmailNotifications": true,
        "UseChannelInEmailNotifications": false,
        "RequireEmailVerification": true,
        "FeedbackName": "mattermost",
        "FeedbackEmail": "***@***.com.tr",
        "ReplyToAddress": "***@***.com.tr",
        "FeedbackOrganization": "mattermost",
        "EnableSMTPAuth": true,
        "SMTPUsername": "***@***.com.tr",
        "SMTPPassword": "***",
        "SMTPServer": "smtp.yandex.com.tr",
        "SMTPPort": "465",
        "ConnectionSecurity": "STARTTLS",
        "SendPushNotifications": true,
        "PushNotificationServer": "https://push-test.mattermost.com",
        "PushNotificationContents": "generic",
        "EnableEmailBatching": false,
        "EmailBatchingBufferSize": 256,
        "EmailBatchingInterval": 30,
        "EnablePreviewModeBanner": false,
        "SkipServerCertificateVerification": false,
        "EmailNotificationContentsType": "full",
        "LoginButtonColor": "#0000",
        "LoginButtonBorderColor": "#2389D7",
        "LoginButtonTextColor": "#2389D7"
    },
```

The problem is although `ConnectionSecurity` is set as TLS from the UI, config remains as `STARTTLS`. STARTTLS option probably works for gmail etc, but not for yandex. I could only connect when I set environment variable `MM_EMAILSETTINGS_CONNECTIONSECURITY=TLS`. With the env var set, everything works as expected since UI is out of equation (This setting has been set through an environment variable. It cannot be changed through the System Console.).

**Comment by amyblais** [comment] 2019-08-14 13:59
@developweekly It appears that this issue could be related to the ConnectionSecurity setting getting switched when set in the UI, which is fixed in v5.14: https://mattermost.atlassian.net/browse/MM-17393.

**Comment by amyblais** [comment] 2019-08-21 14:01
Closing as the above ticket is fixed. Please re-open this issue if upgrading to v5.14 doesn't resolve the problem.

**Closed by amyblais** 2019-08-21 14:01 UTC
Labels: Bug Report/Open

**Comment by aleqx** [comment] 2020-06-12 23:09
I find myself still having issues. Exact same installation type, from 1 hour ago, v5.23. Unlike the OP, I want to use my own localhost SMTP server which listens on port 25 and which works fine. The Docker bridge IP is 172.22.0.1.

Environment > SMTP > SMTP Server: 172.22.0.1
Environment > SMTP > SMTP Port: 25

All the others options are on their defaults (no auth required, no TLS).

When I click on "Test connection" I get "No errors were reported while sending an email. Please check your inbox to make sure." 

However, no connection attempt to the SMTP is made at all (I'm monitoring the Postfix logs).

What's even weirder is that if I change 172.22.0.1 to a bogus IP like 192.168.100.100 and I click on "Test connection" then it STILL says "No errors were reported while sending an email. Please check your inbox to make sure." 

Any clues?

**Comment by yewkay** [comment] 2022-06-08 02:45
Just to update. I'm on version 6.4.1 and I realised that emails have not been sending out recently when I'm trying to invite new member to my team. Changing the settings in UI didn't solve the connection errors, acme to this page when googling for answers.

 I went into config.json and found that it was set to STARTTLS strangely. Manually editing config.json and SMTP came back to live again.

**Comment by bergerkiller** [comment] 2024-01-25 10:31
Just in case other googlers land on this issue as well, I want to add some extra information that wasn't documented on my previous search.

Golang smtp does not allow plain authentication over an unencrypted channel. https://github.com/golang/go/issues/3609

If you are like me and have a local smtp relay and tried to connect to it within docker and got:
``` Failed to send password reset email successfully., err=authentication failed: unencrypted connection```

Its because of this. You will have to enable at least StartTLS on the smtp relay for this to work.

**Comment by safaroffagency** [comment] 2024-10-18 12:27
The same problem appears to me. I receive an error - Connection unsuccessful: Connection unsuccessful: unable to connect to the SMTP server through TLS: tls: first record does not look like a TLS handshake - version 9.0.1 I've checked the settings ConnectionSecurity is TLS. What's could be wrong?
