### ISSUE TITLE
No "Join Another Team" button in the user's menu

### ISSUE THREAD

**Issue by LilianCruanes** [mattermost/mattermost-server#13303] opened 2019-12-03 12:54 UTC
#### Summary
I don't find the "Join Another Team" button in the user's menu.

#### Steps to reproduce
I don't know.

#### Expected behavior
I've recently deployed a Mattermost instance for a new project, which run with Team Edition v5.17.1. I am used to work with Mattermost for other project and I am used to see a "Join Another Team" button in the user's menu, which redirect to "/select_team".

#### Observed behavior (that appears unintentional) 
But I can't find it in the new Mattermost instance. I have searched the solution during 3 hours, but I find nothing. Someone has an idea of what is going wrong ?

#### Possible fixes
None

**Comment by amyblais** [comment] 2019-12-03 13:05
@LilianCruanes Are there other teams to join on your instance? If yes, are those teams public or private?

**Comment by LilianCruanes** [comment] 2019-12-03 13:11
@amyblais Yes 2 others teams and both are public.

**Comment by amyblais** [comment] 2019-12-03 14:42
@LilianCruanes Are there any restrictions such as that the team is already full (https://docs.mattermost.com/administration/config-settings.html#max-users-per-team)?

Can you go to System Console and set “Authentication” > "SignUp" > “Enable Account Creation” to “True” and see if that changes anything?

**Comment by LilianCruanes** [comment] 2019-12-03 15:37
@amyblais The team are empty.
"Account Creation" was already on True. I've set it on False, then on True, no changes.

**Comment by LilianCruanes** [comment] 2019-12-03 17:04
@amyblais More, the "ExperimentalPrimaryTeam" parameter doesn't work : when a member signs up, he is redirected to "/select_team" and not to the primary team. Maybe it exists a link between both abnormal behaviors

**Comment by amyblais** [comment] 2019-12-03 17:22
@LilianCruanes Based on the documentation, your first issue is then expected: https://docs.mattermost.com/administration/config-settings.html#primary-team-experimental.

"When a primary team is set, the options to join other teams or leave the primary team are disabled."

I'll look into the second issue.

**Comment by LilianCruanes** [comment] 2019-12-03 17:37
@amyblais Oh I misread it, sorry...But how can I enforce users to be redirected in a team after registration ?

**Comment by amyblais** [comment] 2019-12-03 18:35
Opened a ticket for the second issue here: https://mattermost.atlassian.net/browse/MM-20915.

**Comment by LilianCruanes** [comment] 2019-12-03 18:57
> Opened a ticket for the second issue here: https://mattermost.atlassian.net/browse/MM-20915.

Thanks @amyblais !

**Comment by LilianCruanes** [comment] 2019-12-09 13:03
Any news ? @amyblais

**Comment by amyblais** [comment] 2019-12-16 16:44
An update:

Our developers have been taking a look at how ExperimentalPrimaryTeam option works and they think it's working as intended.

When you create a user, you can choose which team you want to join, even if you have the ExperimentalPrimaryTeam property set. However, this property doesn’t enforce the newly created user to join the team automatically.

Then after the account creation you have multiple options when you log in:

 - You are in a team which is not the primary one: You can join/leave teams without problem.
 - You are in the primary team: You can’t leave or join another team. You’re only allowed to create a new team as owner and every time you login, you’re redirected to the primary team.
 - You’re in a team which is not the primary one but then you join the primary one: The leave/join options are disabled and every time you join you are redirected to the primary team.

What we believe you are asking for is to add the user to the team automatically after the signup, without showing them the “select team” screen, but that is not possible with that experimental property.

The only way to enforce that is to let the user create a user, and have all the teams “Manual Invites”. Then after the account creation, invite the user to that “Primary team” first so that way they can’t join another team.

The PR where this option was introduced is this and it only affects the login not the sign up: https://github.com/mattermost/mattermost-webapp/pull/334.

**Comment by amyblais** [comment] 2019-12-18 21:46
Another update: We will evaluate this again later when we work on moving this feature out of experimental.

**Comment by LilianCruanes** [comment] 2019-12-19 15:34
@amyblais Thanks for all !

**Comment by amyblais** [comment] 2020-01-06 13:12
I'll close this issue for now,

**Closed by amyblais** 2020-01-06 13:12 UTC
Labels: Bug Report/Open
